---
title: "Q53 Cannabis Cost (Bask/Americann)"
author: "DJ"
date: "June 26, 2019"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
# Load libraries
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
# Read in raw data from the Bask survey. These are the files downloaded from survey monkey saved as a .csv
raw_data_bask <- read.csv("data/bask_text.csv", stringsAsFactors = FALSE)
```

```{r}
# Pull out all responses for Q53 (a single selection question) combine, then determine 'question n'
Q53 <- "On.average..how.much.do.you.spend..in.US.dollars..on.consumable.cannabis.products.per.week."

Q53_bask <- get_single_selection(data = raw_data_bask, q.name = Q53)

Q53_all <- rbind(Q53_bask)

number_of_people_who_submitted_response_to_Q53 <- length(unique(Q53_all$id))
```

```{r}
histogram_object <- hist(as.numeric(all_data$response))
histogram_object$breaks = c(0, 100, 200, 300, 400, 500, 600)
histogram_object$counts
plot(histogram_object)
```

```{r}
write.csv(Q53_all, 'bask_q53_cannabis_cost_18.34.csv', row.names = FALSE)
```