---
title: 'q16 covid survey: Do you use a regulated cannabis delivery service?'
author: "David Ritter"
date: "8/14/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q16 <- "Do.you.use.a.regulated.cannabis.delivery.service."
q16_t <- "Do you use a regulated cannabis delivery service?"
q16_data <- get_single_selection(data = raw_data, q.name = q16)
q16_n <- length(unique(q16_data$id))
q16_plot <- clean_single_select(q16_data)
r16 <- plot_single_select(q16_plot, q16_t, q16_n)
r16
```

```{r}
row3 <- colnames(q16_plot)
q16_plot2 <- rbind(row3, q16_plot)
names(q16_plot2) <- c("q16", q16_t, paste("n = ", q16_n))
```

```{r}
dir.create("output/q16_cannabis_delivery")
ggsave(filename = 'output/q16_cannabis_delivery/q16_cannabis_delivery.png', plot = r16, device = 'png')
write.csv(q16_plot2, paste0("output/q16_cannabis_delivery/q16_cannabis_delivery_", q16_n,".csv"), row.names=F)
```



