---
title: 'q39 covid survey: PRIOR to COVID-19, what were some barriers for you consuming cannabis? Please select all that apply.'
author: "David Ritter"
date: "8/139/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q39 <- "PRIOR.to.COVID.19..what.were.some.barriers.for.you.consuming.cannabis...Please.select.all.that.apply."
q39_final_response <- "X.205"
q39_t  <- "PRIOR to COVID-19, what were some barriers for you 
consuming cannabis? Please select all that apply."
q39_data <- get_choose_all(raw_data, q.name = q39, f.response = q39_final_response) %>%
  tidy_choose_all()
q39_n <- length(unique(q39_data$id))
q39_plot <- clean_choose_all(q39_data, q39_n)
r39 <- plot_choose_all(q39_plot, q39_t, q39_n)
r39
```

```{r}
row3 <- colnames(q39_plot)
q39_plot2 <- rbind(row3, q39_plot)
names(q39_plot2) <- c("q39", q39_t, paste("n = ", q39_n))
```

```{r}
dir.create("output/q39_barriers_prior_covid")
ggsave(filename = 'output/q39_barriers_prior_covid/q39_barriers_prior_covid.png', plot = r39, device = 'png')
write.csv(q39_plot2, paste0("output/q39_barriers_prior_covid/q39_barriers_prior_covid_", q39_n,".csv"), row.names=F)
write.csv(q39_data, 'output/q39_barriers_prior_covid/q39_barriers_prior_covid_ids.csv', row.names = FALSE)
```