---
title: 'q34 covid survey: After the start of COVID-19, what percent of your monthly cannabis purchases are through regulated sources (dispensaries, caregivers, etc.)?'
author: "David Ritter"
date: "8/34/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q34 <- "After.the.start.ofÂ.COVID.19..what.percent.of.your.monthly.cannabis.purchases.are.through.regulated.sources...dispensaries..caregivers..etc."
q34_t <- "After the start of COVID-19, what percent of your monthly cannabis purchases 
are through regulated sources (dispensaries, caregivers, etc.)?"
q34_data <- get_single_selection_0(data = raw_data, q.name = q34) %>%
  filter(response != "")
q34_n <- length(unique(q34_data$id))
q34_mean_data <- as.numeric(as.character(q34_data$response))
q34_mean <- mean(q34_mean_data) %>%
  round(3) %>%
  print()
q34_plot<- clean_single_select(q34_data)
r34 <- plot_single_select_0(q34_plot, q34_t, q34_n, q34_mean)
r34
```

```{r}
row3 <- colnames(q34_plot)
q34_plot2 <- rbind(row3, q34_plot)
names(q34_plot2) <- c("q34", q34_t, paste("n = ", q34_n, paste(" avg = ", q34_mean)))
```

```{r}
dir.create("output/q34_regulated_purchases_since_covid")
ggsave(filename = 'output/q34_regulated_purchases_since_covid/q34_regulated_purchases_since_covid.png', plot = r34, device = 'png')
write.csv(q34_plot2, paste0("output/q34_regulated_purchases_since_covid/q34_regulated_purchases_since_covid_", q34_n,".csv"), row.names=F)
write.csv(q34_data, 'output/q34_regulated_purchases_since_covid/q34_regulated_purchases_since_covid_ids.csv', row.names = FALSE)
```
