---
title: 'q11 covid survey: Are you actively trying to reduce your prescription medication intake using cannabis? Please select all that apply.'
author: "David Ritter"
date: "8/14/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q11 <- "Are.you.actively.trying.to.reduce.your.prescription.medication.intake.using.cannabis..Please.select.all.that.apply."
q11_final_response <- "X.98"
q11_t  <- "Are you actively trying to reduce your prescription 
medication intake using cannabis? 
Please select all that apply."
q11_data <- get_choose_all(raw_data, q.name = q11, f.response = q11_final_response) %>%
  tidy_choose_all()
q11_n <- length(unique(q11_data$id))
q11_plot <- clean_choose_all(q11_data, q11_n)
r11 <- plot_choose_all(q11_plot, q11_t, q11_n)
r11
```

```{r}
row3 <- colnames(q11_plot)
q11_plot2 <- rbind(row3, q11_plot)
names(q11_plot2) <- c("q11", q11_t, paste("n = ", q11_n))
```

```{r}
dir.create("output/q11_meds_reduced_cannabis")
ggsave(filename = 'output/q11_meds_reduced_cannabis/q11_meds_reduced_cannabis.png', plot = r11, device = 'png')
write.csv(q11_plot2, paste0("output/q11_meds_reduced_cannabis/q11_meds_reduced_cannabis_", q11_n,".csv"), row.names=F)
write.csv(q11_data, 'output/q11_meds_reduced_cannabis/q11_meds_reduced_cannabis_ids.csv', row.names = FALSE)
```