---
title: 'q21 covid survey: Are you concerned about your family members or loved ones knowing about your cannabis use?'
author: "David Ritter"
date: "8/14/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q21 <- "Are.you.concerned.about.your.family.members.or.loved.ones.knowing.about.your.cannabis.use."
q21_t <- "Are you concerned about your family members or 
loved ones knowing about your cannabis use?"
q21_data <- get_single_selection(data = raw_data, q.name = q21)
q21_n <- length(unique(q21_data$id))
q21_plot <- clean_single_select(q21_data)
r21 <- plot_single_select(q21_plot, q21_t, q21_n)
r21
```

```{r}
row3 <- colnames(q21_plot)
q21_plot2 <- rbind(row3, q21_plot)
names(q21_plot2) <- c("q21", q21_t, paste("n = ", q21_n))
```

```{r}
dir.create("output/q21_family_knowledge")
ggsave(filename = 'output/q21_family_knowledge/q21_family_knowledge.png', plot = r21, device = 'png')
write.csv(q21_plot2, paste0("output/q21_family_knowledge/q21_family_knowledge_", q21_n,".csv"), row.names=F)
```



