---
title: 'q34b covid survey: Has COVID-19 impacted any of the following for you personally? Please select all that apply.'
author: "David Ritter"
date: "8/14/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q34b <- "Has.COVID.19.impacted.any.of.the.following.for.you.personally...please.select.all.that.apply."
q34b_final_response <- "X.190"
q34b_t  <- "Has COVID-19 impacted any of the following 
for you personally? Please select all 
that apply."
q34b_data <- get_choose_all(raw_data, q.name = q34b, f.response = q34b_final_response) %>%
  tidy_choose_all()
q34b_n <- length(unique(q34b_data$id))
q34b_plot <- clean_choose_all(q34b_data, q34b_n)
r34b <- plot_choose_all(q34b_plot, q34b_t, q34b_n)
r34b
```

```{r}
row3 <- colnames(q34b_plot)
q34b_plot2 <- rbind(row3, q34b_plot)
names(q34b_plot2) <- c("q34b", q34b_t, paste("n = ", q34b_n))
```

```{r}
dir.create("output/q34b_covid_impact_personal")
ggsave(filename = 'output/q34b_covid_impact_personal/q34b_covid_impact_personal.png', plot = r34b, device = 'png')
write.csv(q34b_plot2, paste0("output/q34b_covid_impact_personal/q34b_covid_impact_personal_", q34b_n,".csv"), row.names=F)
write.csv(q34b_data, 'output/q34b_covid_impact_personal/q34b_covid_impact_personal_ids.csv', row.names = FALSE)
```
