---
title: 'q5 covid survey: Which of the following health conditions do you find cannabis to be helpful or most impactful? Please select all that apply.'
author: "David Ritter"
date: "8/15/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q5 <- "Which.of.the.following.health.conditions.do.you.find.cannabis.to.be.helpful.or.most.impactful..Please.select.all.that.apply."
q5_final_response <- "X.31"
q5_t  <- "Which of the following health conditions do
you find cannabis to be helpful or most
impactful? Please select all that apply."
q5_data <- get_choose_all(raw_data, q.name = q5, f.response = q5_final_response) %>%
  tidy_choose_all()
q5_n <- length(unique(q5_data$id))
q5_plot <- clean_choose_all(q5_data, q5_n)
r5 <- plot_choose_all(q5_plot, q5_t, q5_n)
r5
```

```{r}
row3 <- colnames(q5_plot)
q5_plot2 <- rbind(row3, q5_plot)
names(q5_plot2) <- c("q5", q5_t, paste("n = ", q5_n))
```

```{r}
dir.create("output/q5_conditions_cannabis")
ggsave(filename = 'output/q5_conditions_cannabis/q5_conditions_cannabis.png', plot = r5, device = 'png')
write.csv(q5_plot2, paste0("output/q5_conditions_cannabis/q5_conditions_cannabis_", q5_n,".csv"), row.names=F)
write.csv(q5_data, 'output/q5_conditions_cannabis/q5_conditions_cannabis_ids.csv', row.names = FALSE)
```