---
title: "q 'Master'"
author: "David Ritter"
date: "2/26/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
#Use if not filtering
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
#master <- read.csv("data/master.csv", stringsAsFactors = FALSE)
#headers <- master[c(1), ]
```

```{r}
#Filtering for choose all questions
#raw_data <- filter(master, master$X.183 == "Depression/mood")
#if filtering single select change assignment above from raw_data to filtered_data and run raw_data <- rbind(headers, filtered_data) after
```

```{r}
#Filtering for single select questions
#filtered_data <- filter(master, master$How.would.you.rate.your.quality.of.health.today. == "Fair")
#raw_data <- rbind(headers, filtered_data)
```

```{r}
q4 <- "How.would.you.rate.your.quality.of.health.today."
q4_t <- "How would you rate your quality of health today?"
q4_data <- get_single_selection(data = raw_data, q.name = q4)
q4_n <- length(unique(q4_data$id))
q4_plot<- clean_single_select(q4_data)
r4 <- plot_single_select(q4_plot, q4_t, q4_n)
r4
```

```{r}
q4_plot2 <- rbind(q4_plot, q4_t)
dir.create("output/q4_health_quality")
ggsave(filename = 'output/q4_health_quality/q4_health_quality.png', plot = r4, device = 'png')
write.csv(q4_plot2, paste0("output/q4_health_quality/q4_health_quality_", q4_n,".csv"), row.names=F)
```

```{r}
q5 <- 'Which.of.the.following.health.conditions.do.you.face.and.or.have.been.diagnosed.with...Please.select.all.that.apply.'
q5_final_response <- "X.25"
q5_t <- "Which of the following health conditions do you face and/or have been diagnosed with? (Please select all that apply)"
q5_data <- get_choose_all(raw_data, q.name = q5, f.response = q5_final_response) %>%
  tidy_choose_all()
q5_n <- length(unique(q5_data$id))
q5_plot <- clean_choose_all(q5_data, q5_n)
r5 <- plot_choose_all(q5_plot, q5_t, q5_n)
r5
```

```{r}
q5_plot2 <- rbind(q5_plot, q5_t)
dir.create("output/q5_conditions")
ggsave(filename = 'output/q5_conditions/q5_conditions.png', plot = r5, device = 'png')
write.csv(q5_plot2, paste0("output/q5_conditions/q5_conditions_", q5_n,".csv"), row.names=F)
write.csv(q5_data, 'output/q5_conditions/q5_conditions_ids.csv', row.names = FALSE)
```

```{r}
q6 <- "Which.is.the.primary.health.condition.that.causes.you.the.most.distress...Please.select.one."
q6_t <- "Which is the primary health condition that causes you the most distress? (Please select one)"
q6_data <- get_single_selection(data = raw_data, q.name = q6)
q6_n <- length(unique(q6_data$id))
q6_plot <- clean_single_select(q6_data)
r6 <- plot_single_select(q6_plot, q6_t, q6_n)
r6
```

```{r}
q6_plot2 <- rbind(q6_plot, q6_t)
dir.create("output/q6_top_condition")
ggsave(filename = 'output/q6_top_condition/q6_top_condition.png', plot = r6, device = 'png')
write.csv(q6_plot2, paste0("output/q6_top_condition/q6_top_condition_", q6_n,".csv"), row.names=F)
```

```{r}
q7 <- 'Which.of.the.following.symptoms.are.most.commonly.associated.with.your.primary.health.condition.or.underlying.health.conditions...Please.select.all.that.apply.'
q7_final_response <- "X.43"
q7_t <- "Which of the following symptoms are most commonly associated with your primary health condition or underlying health conditions? (Please select all that apply)"
q7_data <- get_choose_all(raw_data, q.name = q7, f.response = q7_final_response) %>%
  tidy_choose_all()
q7_n <- length(unique(q7_data$id))
q7_plot <- clean_choose_all(q7_data, q7_n)
r7 <- plot_choose_all(q7_plot, q7_t, q7_n)
r7
```

```{r}
q7_plot2 <- rbind(q7_plot, q7_t)
dir.create("output/q7_symptoms")
ggsave(filename = 'output/q7_symptoms/q7_symptoms.png', plot = r7, device = 'png')
write.csv(q7_plot2, paste0("output/q7_symptoms/q7_symptoms_", q7_n,".csv"), row.names=F)
write.csv(q7_data, 'output/q7_symptoms/q7_symptoms_ids.csv', row.names = FALSE)
```

```{r}
q8 <- "What.is.your.current.level.of.pain..where.0.is.no.pain.and.10.is.the.worst.pain.imaginable..what.is.your.current.level.of.pain."
q8_t <- "What is your current level of pain (where 0 is no pain and 10 is the worst pain imaginable) what is your current level of pain?"
q8_data <- get_single_selection_0(data = raw_data, q.name = q8) %>%
  filter(response != "")
q8_n <- length(unique(q8_data$id))
q8_mean_data <- as.numeric(as.character(q8_data$response))
q8_mean <- mean(q8_mean_data) %>%
  round(2) %>%
  print()
q8_plot<- clean_single_select(q8_data)
r8 <- plot_single_select_0(q8_plot, q8_t, q8_n, q8_mean)
r8
```

```{r}
q8_plot2 <- rbind(q8_plot, q8_t, paste("average", q8_mean, sep = " = "))
dir.create("output/q8_current_pain")
ggsave(filename = 'output/q8_current_pain/q8_current_pain.png', plot = r8, device = 'png')
write.csv(q8_plot2, paste0("output/q8_current_pain/q8_current_pain_", q8_n,".csv"), row.names=F)
write.csv(q8_data, 'output/q8_current_pain/q8_current_pain_ids.csv', row.names = FALSE)
```

```{r}
q9 <- "What.is.your.usual.level.of.pain..how.does.your.pain.feel.most.of.the.time.."
q9_t <- "What is your usual level of pain (how does your pain feel most of the time?"
q9_data <- get_single_selection_0(data = raw_data, q.name = q9) %>%
  filter(response != "")
q9_n <- length(unique(q9_data$id))
q9_mean_data <- as.numeric(as.character(q9_data$response))
q9_mean <- mean(q9_mean_data) %>%
  round(2) %>%
  print()
q9_plot<- clean_single_select(q9_data)
r9 <- plot_single_select_0(q9_plot, q9_t, q9_n, q9_mean)
r9
```

```{r}
q9_plot2 <- rbind(q9_plot, q9_t, paste("average", q9_mean, sep = " = "))
dir.create("output/q9_usual_pain")
ggsave(filename = 'output/q9_usual_pain/q9_usual_pain.png', plot = r9, device = 'png')
write.csv(q9_plot2, paste0("output/q9_usual_pain/q9_usual_pain_", q9_n,".csv"), row.names=F)
write.csv(q9_data, 'output/q9_usual_pain/q9_usual_pain_ids.csv', row.names = FALSE)
```

```{r}
q10 <- "What.is.your.least.level.of.pain..what.is.the.lowest.level.of.pain.you.feel.."
q10_t <- "What is your least level of pain (what is the lowest level of pain you feel?"
q10_data <- get_single_selection_0(data = raw_data, q.name = q10) %>%
  filter(response != "")
q10_n <- length(unique(q10_data$id))
q10_mean_data <- as.numeric(as.character(q10_data$response))
q10_mean <- mean(q10_mean_data) %>%
  round(3) %>%
  print()
q10_plot<- clean_single_select(q10_data)
r10 <- plot_single_select_0(q10_plot, q10_t, q10_n, q10_mean)
r10
```

```{r}
q10_plot2 <- rbind(q10_plot, q10_t, paste("average", q10_mean, sep = " = "))
dir.create("output/q10_least_pain")
ggsave(filename = 'output/q10_least_pain/q10_least_pain.png', plot = r10, device = 'png')
write.csv(q10_plot2, paste0("output/q10_least_pain/q10_least_pain_", q10_n,".csv"), row.names=F)
write.csv(q10_data, 'output/q10_least_pain/q10_least_pain_ids.csv', row.names = FALSE)
```

```{r}
q11 <- "What.is.yourÂ.highest.level.of.pain..what.is.the.highest.level.of.pain.you.feel.."
q11_t <- "What is your highest level of pain (what is the highest level of pain you feel?)"
q11_data <- get_single_selection_0(data = raw_data, q.name = q11) %>%
  filter(response != "")
q11_n <- length(unique(q11_data$id))
q11_mean_data <- as.numeric(as.character(q11_data$response))
q11_mean <- mean(q11_mean_data) %>%
  round(3) %>%
  print()
q11_plot<- clean_single_select(q11_data)
r11 <- plot_single_select_0(q11_plot, q11_t, q11_n, q11_mean)
r11
```

```{r}
q11_plot2 <- rbind(q11_plot, q11_t, paste("average", q11_mean, sep = " = "))
dir.create("output/q11_highest_pain")
ggsave(filename = 'output/q11_highest_pain/q11_highest_pain.png', plot = r11, device = 'png')
write.csv(q11_plot2, paste0("output/q11_highest_pain/q11_highest_pain_", q11_n,".csv"), row.names=F)
write.csv(q11_data, 'output/q11_highest_pain/q11_highest_pain_ids.csv', row.names = FALSE)
```

```{r}
q12 <- "If.you.had.to.live.with.some.pain..what.level.of.pain.would.be.acceptable."
q12_t <- "If you had to live with some pain, what level of pain would be acceptable?"
q12_data <- get_single_selection_0(data = raw_data, q.name = q12) %>%
  filter(response != "")
q12_n <- length(unique(q12_data$id))
q12_mean_data <- as.numeric(as.character(q12_data$response))
q12_mean <- mean(q12_mean_data) %>%
  round(3) %>%
  print()
q12_plot<- clean_single_select(q12_data)
r12 <- plot_single_select_0(q12_plot, q12_t, q12_n, q12_mean)
r12
```

```{r}
q12_plot2 <- rbind(q12_plot, q12_t, paste("average", q12_mean, sep = " = "))
dir.create("output/q12_acceptable_pain")
ggsave(filename = 'output/q12_acceptable_pain/q12_acceptable_pain.png', plot = r12, device = 'png')
write.csv(q12_plot2, paste0("output/q12_acceptable_pain/q12_acceptable_pain_", q12_n,".csv"), row.names=F)
write.csv(q12_data, 'output/q12_acceptable_pain/q12_acceptable_pain_ids.csv', row.names = FALSE)
```

```{r}
q13 <- 'Where.are.the.locations.of.your.pain..please.check.all.that.apply.'
q13_t <- "Where are the locations of your pain (please check all that apply)"
q13_final_response <- "X.66"
q13_data <- get_choose_all(raw_data, q.name = q13, f.response = q13_final_response) %>%
  tidy_choose_all()
q13_n <- length(unique(q13_data$id))
q13_plot <- clean_choose_all(q13_data, q13_n)
r13 <- plot_choose_all(q13_plot, q13_t, q13_n)
r13
```

```{r}
q13_plot2 <- rbind(q13_plot, q13_t)
dir.create("output/q13_pain_locations")
ggsave(filename = 'output/q13_pain_locations/q13_pain_locations.png', plot = r13, device = 'png')
write.csv(q13_plot2, paste0("output/q13_pain_locations/q13_pain_locations_", q13_n,".csv"), row.names=F)
write.csv(q13_data, 'output/q13_pain_locations/q13_pain_locations_ids.csv', row.names = FALSE)
```

```{r}
q14 <- 'What.are.the.effects.of.your.pain...Please.select.all.that.apply.'
q14_final_response <- "X.81"
q14_t <- "What are the effects of your pain? (Please select all that apply)"
q14_data <- get_choose_all(raw_data, q.name = q14, f.response = q14_final_response) %>%
  tidy_choose_all()
q14_n <- length(unique(q14_data$id))
q14_plot <- clean_choose_all(q14_data, q14_n)
r14 <- plot_choose_all(q14_plot, q14_t, q14_n)
r14
```

```{r}
q14_plot2 <- rbind(q14_plot, q14_t)
dir.create("output/q14_pain_effects")
ggsave(filename = 'output/q14_pain_effects/q14_pain_effects.png', plot = r14, device = 'png')
write.csv(q14_plot2, paste0("output/q14_pain_effects/q14_pain_effects_", q14_n,".csv"), row.names=F)
write.csv(q14_data, 'output/q14_pain_effects/q14_pain_effects_ids.csv', row.names = FALSE)
```

```{r}
q15 <- "Over.the.last.2.weeks..how.often.have.you.been.bothered.by.any.of.the.following.problems."
q15_final_response <- "X.91"
q15_t <- "Over the last 2 weeks, how often have you been bothered by any of the following problems?"
q15_data <- get_choose_all(raw_data, q.name = q15, f.response = q15_final_response)
dir.create("output/q15_anxiety")
```

```{r}
write.csv(q15_data, 'output/q15_anxiety/q15_anxiety_scales_data.csv', row.names = FALSE)
```

```{r}
q15_data1 <- get_single_selection_3(q15_data, "Feeling nervous, anxious, or on edge") %>%
  filter(response != "") %>%
  clean_single_select()
q15_n1 <- tally(q15_data1, count)
q15_t1 <- "Feeling nervous, anxious, or on edge"
q15_r1 <- plot_single_select(q15_data1, q15_t1, q15_n1)
q15_r1
```

```{r}
ggsave(filename = "output/q15_anxiety/q15_anxiety.png", plot = q15_r1, device = 'png')
write.csv(q15_data1, paste0("output/q15_anxiety/q15_anxiety_", q15_n1, ".csv"), row.names = FALSE)
```

```{r}
q15_data2 <- get_single_selection_3(q15_data, "Not being able to stop or control worrying") %>%
  filter(response != "") %>%
  clean_single_select()
q15_t2 <- "Not being able to stop or control worrying"
q15_n2 <- tally(q15_data2, count)
q15_r2 <- plot_single_select(q15_data2, q15_t2, q15_n2)
q15_r2
```

```{r}
ggsave(filename = "output/q15_anxiety/q15_control.png", plot = q15_r2, device = 'png')
write.csv(q15_data2, paste0("output/q15_anxiety/q15_control_", q15_n2, ".csv"), row.names = FALSE)
```

```{r}
q15_data3 <- get_single_selection_3(q15_data, "Worrying too much about different things") %>%
  filter(response != "") %>%
  clean_single_select()
q15_n3 <- tally(q15_data3, count)
q15_t3 <- "Worrying too much about different things"
q15_r3 <- plot_single_select(q15_data3, q15_t3, q15_n3)
q15_r3
```

```{r}
ggsave(filename = "output/q15_anxiety/q15_worry.png", plot = q15_r3, device = 'png')
write.csv(q15_data3, paste0("output/q15_anxiety/q15_worry_", q15_n3, ".csv"), row.names = FALSE)
```

```{r}
q15_data4 <- get_single_selection_3(q15_data, "Trouble relaxing") %>%
  filter(response != "") %>%
  clean_single_select()
q15_n4 <- tally(q15_data4, count)
q15_t4 <- "Trouble relaxing"
q15_r4 <- plot_single_select(q15_data4, q15_t4, q15_n4)
q15_r4
```

```{r}
ggsave(filename = "output/q15_anxiety/q15_relax.png", plot = q15_r4, device = 'png')
write.csv(q15_data4, paste0("output/q15_anxiety/q15_relax_", q15_n4, ".csv"), row.names = FALSE)
```

```{r}
q15_data5 <- get_single_selection_3(q15_data, "Being so restless that it is hard to sit still") %>%
  filter(response != "") %>%
  clean_single_select()
q15_n5 <- tally(q15_data5, count)
q15_t5 <- "Being so restless that it is hard to sit still"
q15_r5 <- plot_single_select(q15_data5, q15_t5, q15_n5)
q15_r5
```

```{r}
ggsave(filename = "output/q15_anxiety/q15_restless.png", plot = q15_r5, device = 'png')
write.csv(q15_data5, paste0("output/q15_anxiety/q15_restless_", q15_n5, ".csv"), row.names = FALSE)
```

```{r}
q15_data6 <- get_single_selection_3(q15_data, "Becoming easily annoyed or irritable") %>%
  filter(response != "") %>%
  clean_single_select()
q15_n6 <- tally(q15_data6, count)
q15_t6 <- "Becoming easily annoyed or irritable"
q15_r6 <- plot_single_select(q15_data6, q15_t6, q15_n6)
q15_r6
```

```{r}
ggsave(filename = "output/q15_anxiety/q15_annoyed.png", plot = q15_r6, device = 'png')
write.csv(q15_data6, paste0("output/q15_anxiety/q15_annoyed_", q15_n6, ".csv"), row.names = FALSE)
```

```{r}
q15_data7 <- get_single_selection_3(q15_data, "Feeling afraid as if something awful might happen") %>%
  filter(response != "") %>%
  clean_single_select()
q15_n7 <- tally(q15_data7, count)
q15_t7 <- "Feeling afraid as if something awful might happen"
q15_r7 <- plot_single_select(q15_data7, q15_t7, q15_n7)
q15_r7
```

```{r}
ggsave(filename = "output/q15_anxiety/q15_afraid.png", plot = q15_r7, device = 'png')
write.csv(q15_data7, paste0("output/q15_anxiety/q15_afraid_", q15_n7, ".csv"), row.names = FALSE)
```

```{r}
q16 <- "If.you.checked.offÂ.ï..anyï...problems..howÂ.difficult.have.these.problems.made.it.for.you.to.do.your.work..take.care.of.things.at.home..or.get.along.with.other.people."
q16_t <- "Difficulty of living with anxiety as top condition"
q16_data <- get_single_selection(data = raw_data, q.name = q16)
q16_n <- length(unique(q16_data$id))
q16_plot <- clean_single_select(q16_data)
r16 <- plot_single_select(q16_plot, q16_t, q16_n)
r16
```

```{r}
q16_plot2 <- rbind(q16_plot, q16_t)
dir.create("output/q16_anxiety_difficulty")
ggsave(filename = 'output/q16_anxiety_difficulty/q16_anxiety_difficulty.png', plot = r16, device = 'png')
write.csv(q16_plot2, paste0("output/q16_anxiety_difficulty/q16_anxiety_difficulty_", q16_n,".csv"), row.names=F)
```

```{r}
q17 <- "Over.the.last.2.weeks..how.often.have.you.been.bothered.by.any.of.the.following.problems..1"
q17_final_response <- "X.99"
q17_t <- "Over the last 2 weeks, how often have you been bothered by any of the following problems?"
q17_data <- get_choose_all(raw_data, q.name = q17, f.response = q17_final_response)
dir.create("output/q17_depression")
```

```{r}
write.csv(q17_data, 'output/q17_depression/q17_depression_scales_data.csv', row.names = FALSE)
```

```{r}
q17_data1 <- get_single_selection_3(q17_data, "Little interest or pleasure in doing things") %>%
  filter(response != "") %>%
  clean_single_select()
q17_n1 <- tally(q17_data1, count)
q17_t1 <- "Little interest or pleasure in doing things"
q17_r1 <- plot_single_select(q17_data1, q17_t1, q17_n1)
q17_r1
```

```{r}
ggsave(filename = "output/q17_depression/q17_interest.png", plot = q17_r1, device = 'png')
write.csv(q17_data1, paste0("output/q17_depression/q17_interest_", q17_n1, ".csv"), row.names = FALSE)
```

```{r}
q17_data2 <- get_single_selection_3(q17_data, "Feeling down, depressed, or hopeless") %>%
  filter(response != "") %>%
  clean_single_select()
q17_n2 <- tally(q17_data2, count)
q17_t2 <- "Feeling down, depressed, or hopeless"
q17_r2 <- plot_single_select(q17_data2, q17_t2, q17_n2)
q17_r2
```

```{r}
ggsave(filename = "output/q17_depression/q17_depressed.png", plot = q17_r2, device = 'png')
write.csv(q17_data2, paste0("output/q17_depression/q17_depressed_", q17_n2, ".csv"), row.names = FALSE)
```

```{r}
q17_data3 <- get_single_selection_3(q17_data, "Trouble falling or staying asleep, or sleeping too much") %>%
  filter(response != "") %>%
  clean_single_select()
q17_n3 <- tally(q17_data3, count)
q17_t3 <- "Trouble falling or staying asleep, or sleeping too much"
q17_r3 <- plot_single_select(q17_data3, q17_t3, q17_n3)
q17_r3
```

```{r}
ggsave(filename = "output/q17_depression/q17_sleep.png", plot = q17_r3, device = 'png')
write.csv(q17_data3, paste0("output/q17_depression/q17_sleep_", q17_n3, ".csv"), row.names = FALSE)
```

```{r}
q17_data4 <- get_single_selection_3(q17_data, "Feeling tired or having little energy") %>%
  filter(response != "") %>%
  clean_single_select()
q17_n4 <- tally(q17_data4, count)
q17_t4 <- "Feeling tired or having little energy"
q17_r4 <- plot_single_select(q17_data4, q17_t4, q17_n4)
q17_r4
```

```{r}
ggsave(filename = "output/q17_depression/q17_fatigue.png", plot = q17_r4, device = 'png')
write.csv(q17_data4, paste0("output/q17_depression/q17_fatigue_", q17_n4, ".csv"), row.names = FALSE)
```

```{r}
q17_data5 <- get_single_selection_3(q17_data, "Poor appetite or overeating") %>%
  filter(response != "") %>%
  clean_single_select()
q17_n5 <- tally(q17_data5, count)
q17_t5 <- "Poor appetite or overeating"
q17_r5 <- plot_single_select(q17_data5, q17_t5, q17_n5)
q17_r5
```

```{r}
ggsave(filename = "output/q17_depression/q17_appetite.png", plot = q17_r5, device = 'png')
write.csv(q17_data5, paste0("output/q17_depression/q17_appetite_", q17_n5, ".csv"), row.names = FALSE)
```

```{r}
q17_data6 <- get_single_selection_3(q17_data, "Feeling bad about yourself or that you are a failure or have let yourself or your family down") %>%
  filter(response != "") %>%
  clean_single_select()
q17_n6 <- tally(q17_data6, count)
q17_t6 <- "Feeling bad about yourself or that you are a failure or have let yourself or your family down"
q17_r6 <- plot_single_select(q17_data6, q17_t6, q17_n6)
q17_r6
```

```{r}
ggsave(filename = "output/q17_depression/q17_failure.png", plot = q17_r6, device = 'png')
write.csv(q17_data6, paste0("output/q17_depression/q17_failure_", q17_n6, ".csv"), row.names = FALSE)
```

```{r}
q17_data7 <- get_single_selection_3(q17_data, "Trouble concentrating on things such as reading the newspaper or watching television") %>%
  filter(response != "") %>%
  clean_single_select()
q17_n7 <- tally(q17_data7, count)
q17_t7 <- "Trouble concentrating on things such as reading the newspaper or watching television"
q17_r7 <- plot_single_select(q17_data7, q17_t7, q17_n7)
q17_r7
```

```{r}
ggsave(filename = "output/q17_depression/q17_concentration.png", plot = q17_r7, device = 'png')
write.csv(q17_data7, paste0("output/q17_depression/q17_concentration_", q17_n7, ".csv"), row.names = FALSE)
```

```{r}
q17_data8 <- get_single_selection_3(q17_data, "Moving or speaking so slowly that other people could have noticed, or the opposite: being so fidgety or restless that you have been moving around a lot more than usual") %>%
  filter(response != "") %>%
  clean_single_select()
q17_n8 <- tally(q17_data8, count)
q17_t8 <- "Moving or speaking so slowly that other people could have noticed, or the opposite: being so fidgety or restless that you have been moving around a lot more than usual"
q17_r8 <- plot_single_select(q17_data8, q17_t8, q17_n8)
q17_r8
```

```{r}
ggsave(filename = "output/q17_depression/q17_movement.png", plot = q17_r8, device = 'png')
write.csv(q17_data8, paste0("output/q17_depression/q17_movement_", q17_n8, ".csv"), row.names = FALSE)
```

```{r}
q17_data9 <- get_single_selection_3(q17_data, "Thoughts that you would be better off dead or of hurting yourself in some way") %>%
  filter(response != "") %>%
  clean_single_select()
q17_n9 <- tally(q17_data9, count)
q17_t9 <- "Thoughts that you would be better off dead or of hurting yourself in some way"
q17_r9 <- plot_single_select(q17_data9, q17_t9, q17_n9)
q17_r9
```

```{r}
ggsave(filename = "output/q17_depression/q17_self_harm.png", plot = q17_r9, device = 'png')
write.csv(q17_data9, paste0("output/q17_depression/q17_self_harm_", q17_n9, ".csv"), row.names = FALSE)
```

```{r}
q18 <- "If.you.checked.offÂ.ï..anyï...problems..howÂ.ï..difficultï...have.these.problems.made.it.for.you.to.do.your.work..take.care.of.things.at.home..or.get.along.with.other.people."
q18_t <- "Difficulty of living with depression as top condition"
q18_data <- get_single_selection(data = raw_data, q.name = q18)
q18_n <- length(unique(q18_data$id))
q18_plot<- clean_single_select(q18_data)
r18 <- plot_single_select(q18_plot, q18_t, q18_n)
r18
```

```{r}
q18_plot2 <- rbind(q18_plot, q18_t)
dir.create("output/q18_depression_difficulty")
ggsave(filename = 'output/q18_depression_difficulty/q18_depression_difficulty.png', plot = r18, device = 'png')
write.csv(q18_plot2, paste0("output/q18_depression_difficulty/q18_depression_difficulty_", q18_n,".csv"), row.names=F)
```

```{r}
q19 <- "Below.is.a.list.of.problems.and.complaints.that.veterans.sometimes.have.in.response.to.stressful.military.experiences..Please.read.each.one.carefully.and.indicate.how.much.you.have.beenÂ.ï..bothered.by.that.problem.in.the.last.month.ï.."
q19_final_response <- "X.115"
q19_t <- "PTSD Scales"
q19_data <- get_choose_all(raw_data, q.name = q19, f.response = q19_final_response)
dir.create("output/q19_ptsd")
```

```{r}
write.csv(q19_data, 'output/q19_ptsd/q19_ptsd_scales_data.csv', row.names = FALSE)
```

```{r}
q19_data1 <- get_single_selection_3(q19_data, "Repeated, disturbing memories, thoughts, or images of a stressful military experience?") %>%
  filter(response != "") %>%
  clean_single_select()
q19_n1 <- tally(q19_data1, count)
q19_t1 <- "Repeated, disturbing memories, thoughts, or images of a stressful military experience?"
q19_r1 <- plot_single_select(q19_data1, q19_t1, q19_n1)
q19_r1
```

```{r}
ggsave(filename = "output/q19_ptsd/q19_flashback.png", plot = q19_r1, device = 'png')
write.csv(q19_data1, paste0("output/q19_ptsd/q19_flashback_", q19_n1, ".csv"), row.names = FALSE)
```

```{r}
q19_data2 <- get_single_selection_3(q19_data, "Repeated, disturbing dreams of a stressful military experience?") %>%
  filter(response != "") %>%
  clean_single_select()
q19_n2 <- tally(q19_data2, count)
q19_t2 <- "Repeated, disturbing dreams of a stressful military experience?"
q19_r2 <- plot_single_select(q19_data2, q19_t2, q19_n2)
q19_r2
```

```{r}
ggsave(filename = "output/q19_ptsd/q19_dreams.png", plot = q19_r2, device = 'png')
write.csv(q19_data2, paste0("output/q19_ptsd/q19_dreams_", q19_n2, ".csv"), row.names = FALSE)
```

```{r}
q19_data3 <- get_single_selection_3(q19_data, "Suddenly acting or feeling as if a stressful military experience were happening again (as if you were reliving it)?") %>%
  filter(response != "") %>%
  clean_single_select()
q19_n3 <- tally(q19_data3, count)
q19_t3 <- "Suddenly acting or feeling as if a stressful military experience were happening again (as if you were reliving it)?"
q19_r3 <- plot_single_select(q19_data3, q19_t3, q19_n3)
q19_r3
```

```{r}
ggsave(filename = "output/q19_ptsd/q19_reliving.png", plot = q19_r3, device = 'png')
write.csv(q19_data3, paste0("output/q19_ptsd/q19_reliving_", q19_n3, ".csv"), row.names = FALSE)
```

```{r}
q19_data4 <- get_single_selection_3(q19_data, "Feeling very upset when something reminded you of a stressful military experience") %>%
  filter(response != "") %>%
  clean_single_select()
q19_n4 <- tally(q19_data4, count)
q19_t4 <- "Feeling very upset when something reminded you of a stressful military experience"
q19_r4 <- plot_single_select(q19_data4, q19_t4, q19_n4)
q19_r4
```

```{r}
ggsave(filename = "output/q19_ptsd/q19_trigger.png", plot = q19_r4, device = 'png')
write.csv(q19_data4, paste0("output/q19_ptsd/q19_trigger_", q19_n4, ".csv"), row.names = FALSE)
```

```{r}
q19_data5 <- get_single_selection_3(q19_data, "Having physical reactions (e.g., heart pounding, trouble breathing, or sweating) when something reminded you of a stressful military experience?") %>%
  filter(response != "") %>%
  clean_single_select()
q19_n5 <- tally(q19_data5, count)
q19_t5 <- "Having physical reactions (e.g., heart pounding, trouble breathing, or sweating) when something reminded you of a stressful military experience?" 
q19_r5 <- plot_single_select(q19_data5, q19_t5, q19_n5)
q19_r5
```

```{r}
ggsave(filename = "output/q19_ptsd/q19_physical.png", plot = q19_r5, device = 'png')
write.csv(q19_data5, paste0("output/q19_ptsd/q19_physical_", q19_n5, ".csv"), row.names = FALSE)
```

```{r}
q19_data6 <- get_single_selection_3(q19_data, "Avoid thinking about or talking about a stressful military experience or avoid having feelings related to it?") %>%
  filter(response != "") %>%
  clean_single_select()
q19_n6 <- tally(q19_data6, count)
q19_t6 <- "Avoid thinking about or talking about a stressful military experience or avoid having feelings related to it?"
q19_r6 <- plot_single_select(q19_data6, q19_t6, q19_n6)
q19_r6
```

```{r}
ggsave(filename = "output/q19_ptsd/q19_thinking.png", plot = q19_r6, device = 'png')
write.csv(q19_data6, paste0("output/q19_ptsd/q19_thinking_", q19_n6, ".csv"), row.names = FALSE)
```

```{r}
q19_data7 <- get_single_selection_3(q19_data, "Avoid activities or talking about a stressful military experience or avoid having feelings related to it?") %>%
  filter(response != "") %>%
  clean_single_select()
q19_n7 <- tally(q19_data7, count)
q19_t7 <- "Avoid activities or talking about a stressful military experience or avoid having feelings related to it?"
q19_r7 <- plot_single_select(q19_data7, q19_t7, q19_n7)
q19_r7
```

```{r}
ggsave(filename = "output/q19_ptsd/q19_activities.png", plot = q19_r7, device = 'png')
write.csv(q19_data7, paste0("output/q19_ptsd/q19_activities_", q19_n7, ".csv"), row.names = FALSE)
```

```{r}
q19_data8 <- get_single_selection_3(q19_data, "Trouble remembering important parts of a stressful military experience?") %>%
  filter(response != "") %>%
  clean_single_select()
q19_n8 <- tally(q19_data8, count)
q19_t8 <- "Trouble remembering important parts of a stressful military experience?"
q19_r8 <- plot_single_select(q19_data8, q19_t8, q19_n8)
q19_r8
```

```{r}
ggsave(filename = "output/q19_ptsd/q19_memory.png", plot = q19_r8, device = 'png')
write.csv(q19_data8, paste0("output/q19_ptsd/q19_memory_", q19_n8, ".csv"), row.names = FALSE)
```

```{r}
q19_data9 <- get_single_selection_3(q19_data, "Loss on interest in things that you used to enjoy?") %>%
  filter(response != "") %>%
  clean_single_select()
q19_n9 <- tally(q19_data9, count)
q19_t9 <- "Loss on interest in things that you used to enjoy?"
q19_r9 <- plot_single_select(q19_data9, q19_t9, q19_n9)
q19_r9
```

```{r}
ggsave(filename = "output/q19_ptsd/q19_interest.png", plot = q19_r9, device = 'png')
write.csv(q19_data9, paste0("output/q19_ptsd/q19_interest_", q19_n9, ".csv"), row.names = FALSE)
```

```{r}
q19_data10 <- get_single_selection_3(q19_data, "Feeling distant or cut off from other people") %>%
  filter(response != "") %>%
  clean_single_select()
q19_n10 <- tally(q19_data10, count)
q19_t10 <- "Feeling distant or cut off from other people"
q19_r10 <- plot_single_select(q19_data10, q19_t10, q19_n10)
q19_r10
```

```{r}
ggsave(filename = "output/q19_ptsd/q19_distant.png", plot = q19_r10, device = 'png')
write.csv(q19_data10, paste0("output/q19_ptsd/q19_distant_", q19_n10, ".csv"), row.names = FALSE)
```

```{r}
q19_data11 <- get_single_selection_3(q19_data, "Feeling emotionally numb or being unable to have loving feelings for those close to you?") %>%
  filter(response != "") %>%
  clean_single_select()
q19_n11 <- tally(q19_data11, count)
q19_t11 <- "Feeling emotionally numb or being unable to have loving feelings for those close to you?"
q19_r11 <- plot_single_select(q19_data11, q19_t11, q19_n11)
q19_r11
```

```{r}
ggsave(filename = "output/q19_ptsd/q19_numb.png", plot = q19_r11, device = 'png')
write.csv(q19_data11, paste0("output/q19_ptsd/q19_numb_", q19_n11, ".csv"), row.names = FALSE)
```

```{r}
q19_data12 <- get_single_selection_3(q19_data, "Feeling as if your future will somehow be cut short?") %>%
  filter(response != "") %>%
  clean_single_select()
q19_n12 <- tally(q19_data12, count)
q19_t12 <- "Feeling as if your future will somehow be cut short?"
q19_r12 <- plot_single_select(q19_data12, q19_t12, q19_n12)
q19_r12
```

```{r}
ggsave(filename = "output/q19_ptsd/q19_short_future.png", plot = q19_r12, device = 'png')
write.csv(q19_data12, paste0("output/q19_ptsd/q19_short_future_", q19_n12, ".csv"), row.names = FALSE)
```

```{r}
q19_data13 <- get_single_selection_3(q19_data, "Trouble falling or staying asleep?") %>%
  filter(response != "") %>%
  clean_single_select()
q19_n13 <- tally(q19_data13, count)
q19_t13 <- "Trouble falling or staying asleep?"
q19_r13 <- plot_single_select(q19_data13, q19_t13, q19_n13)
q19_r13
```

```{r}
ggsave(filename = "output/q19_ptsd/q19_sleep.png", plot = q19_r13, device = 'png')
write.csv(q19_data13, paste0("output/q19_ptsd/q19_sleep_", q19_n13, ".csv"), row.names = FALSE)
```

```{r}
q19_data14 <- get_single_selection_3(q19_data, "Feeling irritable or having angry outbursts?") %>%
  filter(response != "") %>%
  clean_single_select()
q19_n14 <- tally(q19_data14, count)
q19_t14 <- "Feeling irritable or having angry outbursts?"
q19_r14 <- plot_single_select(q19_data14, q19_t14, q19_n14)
q19_r14
```

```{r}
ggsave(filename = "output/q19_ptsd/q19_irritable.png", plot = q19_r14, device = 'png')
write.csv(q19_data14, paste0("output/q19_ptsd/q19_irritable_", q19_n14, ".csv"), row.names = FALSE)
```

```{r}
q19_data15 <- get_single_selection_3(q19_data, "Having difficulty concentrating?") %>%
  filter(response != "") %>%
  clean_single_select()
q19_n15 <- tally(q19_data15, count)
q19_t15 <- "Having difficulty concentrating?"
q19_r15 <- plot_single_select(q19_data15, q19_t15, q19_n15)
q19_r15
```

```{r}
ggsave(filename = "output/q19_ptsd/q19_concentration.png", plot = q19_r15, device = 'png')
write.csv(q19_data15, paste0("output/q19_ptsd/q19_concentration_", q19_n15, ".csv"), row.names = FALSE)
```

```{r}
q19_data16 <- get_single_selection_3(q19_data, 'Being "super alert" or watchful on guard?') %>%
  filter(response != "") %>%
  clean_single_select()
q19_n16 <- tally(q19_data16, count)
q19_t16 <- 'Being "super alert" or watchful on guard?'
q19_r16 <- plot_single_select(q19_data16, q19_t16, q19_n16)
q19_r16
```

```{r}
ggsave(filename = "output/q19_ptsd/q19_alert.png", plot = q19_r16, device = 'png')
write.csv(q19_data16, paste0("output/q19_ptsd/q19_alert_", q19_n16, ".csv"), row.names = FALSE)
```

```{r}
q19_data17 <- get_single_selection_3(q19_data, 'Feeling jumpy or easily startled?') %>%
  filter(response != "") %>%
  clean_single_select()
q19_n17 <- tally(q19_data17, count)
q19_t17 <- 'Feeling jumpy or easily startled?'
q19_r17 <- plot_single_select(q19_data17, q19_t17, q19_n17)
q19_r17
```

```{r}
ggsave(filename = "output/q19_ptsd/q19_jumpy.png", plot = q19_r17, device = 'png')
write.csv(q19_data17, paste0("output/q19_ptsd/q19_jumpy_", q19_n17, ".csv"), row.names = FALSE)
```

```{r}
q20 <- 'What.types.of.prescription.medications.are.you.currently.taking.for.the.health.conditions.and.symptoms.you.face...Please.select.all.that.apply.'
q20_final_response <- "X.136"
q20_t <- "What types of prescription medications are you currently taking for the health conditions and symptoms you face? (Please select all that apply)"
q20_data <- get_choose_all(raw_data, q.name = q20, f.response = q20_final_response) %>%
  tidy_choose_all()
q20_n <- length(unique(q20_data$id))
q20_plot <- clean_choose_all(q20_data, q20_n)
r20 <- plot_choose_all(q20_plot, q20_t, q20_n)
r20
```

```{r}
q20_plot2 <- rbind(q20_plot, q20_t)
dir.create("output/q20_prescriptions")
ggsave(filename = 'output/q20_prescriptions/q20_prescriptions.png', plot = r20, device = 'png')
write.csv(q20_plot2, paste0("output/q20_prescriptions/q20_prescriptions_", q20_n,".csv"), row.names=F)
write.csv(q20_data, 'output/q20_prescriptions/q20_prescriptions_ids.csv', row.names = FALSE)
```

```{r}
q21 <- "How.many.total.prescription.medications.are.you.currently.taking...Please.insert.number."
q21_t <- "How many total prescription medications are you currently taking? (Please insert number)"
q21_data <- get_single_selection_0(data = raw_data, q.name = q21) %>%
  filter(response != "")
q21_n <- length(unique(q21_data$id))
q21_mean_data <- as.numeric(as.character(q21_data$response))
q21_mean <- mean(q21_mean_data) %>%
  round(2) %>%
  print()
q21_plot <- clean_single_select(q21_data)
r21 <- plot_single_select_0(q21_plot, q21_t, q21_n, q21_mean)
r21
```

```{r}
q21_plot2 <- rbind(q21_plot, q21_t, paste("average", q21_mean, sep = " = "))
dir.create("output/q21_total_prescriptions")
ggsave(filename = 'output/q21_total_prescriptions/q21_total_prescriptions.png', plot = r21, device = 'png')
write.csv(q21_plot2, paste0("output/q21_total_prescriptions/q21_total_prescriptions_", q21_n,".csv"), row.names=F)
write.csv(q21_data, 'output/q21_total_prescriptions/q21_total_prescriptions_ids.csv', row.names = FALSE)
```

```{r}
q22 <- "Do.you.have.prescription.medications.in.your.house.that.you.don.t.want.to.use.and.currently.need.to.get.rid.of."
q22_t <- "Do you have prescription medications in your house that you don't want to use and currently need to get rid of?"
q22_data <- get_single_selection(data = raw_data, q.name = q22)
q22_n <- length(unique(q22_data$id))
q22_plot<- clean_single_select(q22_data)
r22 <- plot_single_select(q22_plot, q22_t, q22_n)
r22
```

```{r}
q22_plot2 <- rbind(q22_plot, q22_t)
dir.create("output/q22_unwanted_medication")
ggsave(filename = 'output/q22_unwanted_medication/q22_unwanted_medication.png', plot = r22, device = 'png')
write.csv(q22_plot2, paste0("output/q22_unwanted_medication/q22_unwanted_medication_", q22_n,".csv"), row.names=F)
```

```{r}
q23 <- "Have.you.ever.been.diagnosed.with.Opioid.Use.Disorder..OUD.."
q23_t <- "Have you ever been diagnosed with Opioid Use Disorder (OUD)?"
q23_data <- get_single_selection(data = raw_data, q.name = q23)
q23_n <- length(unique(q23_data$id))
q23_plot<- clean_single_select(q23_data)
r23 <- plot_single_select(q23_plot, q23_t, q23_n)
r23
```

```{r}
q23_plot2 <- rbind(q23_plot, q23_t)
dir.create("output/q23_opioid_use_disorder")
ggsave(filename = 'output/q23_opioid_use_disorder/q23_opioid_use_disorder.png', plot = r23, device = 'png')
write.csv(q23_plot2, paste0("output/q23_opioid_use_disorder/q23_opioid_use_disorder_", q23_n,".csv"), row.names=F)
```

```{r}
q24 <- "What.types.of.treatments.are.you.currently.receiving.for.your.OUD."
q24_t <- "What types of treatments are you currently receiving for your OUD?"
q24_data <- get_single_selection(data = raw_data, q.name = q24)
q24_n <- length(unique(q24_data$id))
q24_plot<- clean_single_select(q24_data)
r24 <- plot_single_select(q24_plot, q24_t, q24_n)
r24
```

```{r}
q24_plot2 <- rbind(q24_plot, q24_t)
dir.create("output/q24_oud_treatment")
ggsave(filename = 'output/q24_oud_treatment/q24_oud_treatment.png', plot = r24, device = 'png')
write.csv(q24_plot2, paste0("output/q24_oud_treatment/q24_oud_treatment_", q24_n,".csv"), row.names=F)
```

```{r}
q25 <- "Have.you.ever.been.tested.for.THC..marijuana..during.your.opioid.recovery.treatment."
q25_t <- "Have you ever been tested for THC (marijuana) during your opioid recovery treatment?"
q25_data <- get_single_selection(data = raw_data, q.name = q25)
q25_n <- length(unique(q25_data$id))
q25_plot<- clean_single_select(q25_data)
r25 <- plot_single_select(q25_plot, q25_t, q25_n)
r25
```

```{r}
q25_plot2 <- rbind(q25_plot, q25_t)
dir.create("output/q25_thc_test_oud")
ggsave(filename = 'output/q25_thc_test_oud/q25_thc_test_oud.png', plot = r25, device = 'png')
write.csv(q25_plot2, paste0("output/q25_thc_test_oud/q25_thc_test_oud_", q25_n,".csv"), row.names=F)
```

```{r}
q26 <- 'Have.you.ever.taken.any.of.the.following.opioids...Please.select.all.that.apply.'
q26_final_response <- "X.148"
q26_t <- "Have you ever taken any of the following opioids? (Please select all that apply)"
q26_data <- get_choose_all(raw_data, q.name = q26, f.response = q26_final_response) %>%
  tidy_choose_all()
q26_n <- length(unique(q26_data$id))
q26_plot <- clean_choose_all(q26_data, q26_n)
r26 <- plot_choose_all(q26_plot, q26_t, q26_n)
r26
```

```{r}
q26_plot2 <- rbind(q26_plot, q26_t)
dir.create("output/q26_opioids_taken")
ggsave(filename = 'output/q26_opioids_taken/q26_opioids_taken.png', plot = r26, device = 'png')
write.csv(q26_plot2, paste0("output/q26_opioids_taken/q26_opioids_taken_", q26_n,".csv"), row.names=F)
write.csv(q26_data, 'output/q26_opioids_taken/q26_opioids_taken_ids.csv', row.names = FALSE)
```

```{r}
q27 <- "Do.you.worry.about.your.use.of.opioids."
q27_t <- "Do you worry about your use of opioids?"
q27_data <- get_single_selection(data = raw_data, q.name = q27)
q27_n <- length(unique(q27_data$id))
q27_plot<- clean_single_select(q27_data)
r27 <- plot_single_select(q27_plot, q27_t, q27_n)
r27
```

```{r}
q27_plot2 <- rbind(q27_plot, q27_t)
dir.create("output/q27_opioid_use_worry")
ggsave(filename = 'output/q27_opioid_use_worry/q27_opioid_use_worry.png', plot = r27, device = 'png')
write.csv(q27_plot2, paste0("output/q27_opioid_use_worry/q27_opioid_use_worry_", q27_n,".csv"), row.names=F)
```

```{r}
q28 <- "Do.you.find.it.difficult.to.stop.or.not.use.opioids."
q28_t <- "Do you find it difficult to stop or not use opioids?"
q28_data <- get_single_selection(data = raw_data, q.name = q28)
q28_n <- length(unique(q28_data$id))
q28_plot<- clean_single_select(q28_data)
r28 <- plot_single_select(q28_plot, q28_t, q28_n)
r28
```

```{r}
q28_plot2 <- rbind(q28_plot, q28_t)
dir.create("output/q28_opioid_cessation")
ggsave(filename = 'output/q28_opioid_cessation/q28_opioid_cessation.png', plot = r28, device = 'png')
write.csv(q28_plot2, paste0("output/q28_opioid_cessation/q28_opioid_cessation_", q28_n,".csv"), row.names=F)
```

```{r}
q29 <- "What.percentage.of.disability.are.you.rated..as.is.indicated.by.the.Veteran.s.Affairs..VA.."
q29_t <- "What percentage of disability are you rated, as indicated by the Veteran's Affairs (VA)?"
q29_data <- get_single_selection_0(data = raw_data, q.name = q29) %>%
  filter(response != "")
q29_n <- length(unique(q29_data$id))
q29_mean_data <- as.numeric(as.character(q29_data$response))
q29_mean <- mean(q29_mean_data) %>%
  round(2) %>%
  print()
q29_plot<- clean_single_select(q29_data)
r29 <- plot_single_select_0(q29_plot, q29_t, q29_n, q29_mean)
r29
```

```{r}
q29_plot2 <- rbind(q29_plot, q29_t, paste("average", q29_mean, sep = " = "))
dir.create("output/q29_disability")
ggsave(filename = 'output/q29_disability/q29_disability.png', plot = r29, device = 'png')
write.csv(q29_plot2, paste0("output/q29_disability/q29_disability_", q29_n,".csv"), row.names=F)
write.csv(q29_data, 'output/q29_disability/q29_disability_ids.csv', row.names = FALSE)
```

```{r}
q30 <- "Do.you.currently.have.health.insurance...Please.select.one."
q30_t <- "Do you currently have health insurance? (Please select one)"
q30_data <- get_single_selection(data = raw_data, q.name = q30)
q30_n <- length(unique(q30_data$id))
q30_plot<- clean_single_select(q30_data)
r30 <- plot_single_select(q30_plot, q30_t, q30_n)
r30
```

```{r}
q30_plot2 <- rbind(q30_plot, q30_t)
dir.create("output/q30_health_insurance")
ggsave(filename = 'output/q30_health_insurance/q30_health_insurance.png', plot = r30, device = 'png')
write.csv(q30_plot2, paste0("output/q30_health_insurance/q30_health_insurance_", q30_n,".csv"), row.names=F)
```

```{r}
q31 <- "Do.you.have.prescription.drug.coverage."
q31_t <- "Do you have prescription drug coverage?"
q31_data <- get_single_selection(data = raw_data, q.name = q31)
q31_n <- length(unique(q31_data$id))
q31_plot<- clean_single_select(q31_data)
r31 <- plot_single_select(q31_plot, q31_t, q31_n)
r31
```

```{r}
q31_plot2 <- rbind(q31_plot, q31_t)
dir.create("output/q31_drug_coverage")
ggsave(filename = 'output/q31_drug_coverage/q31_drug_coverage.png', plot = r31, device = 'png')
write.csv(q31_plot2, paste0("output/q31_drug_coverage/q31_drug_coverage_", q31_n,".csv"), row.names=F)
```

```{r}
q32 <- "Where.how.do.you.get.your.medications."
q32_t <- "Where/how do you get your medications?"
q32_data <- get_single_selection(data = raw_data, q.name = q32)
q32_n <- length(unique(q32_data$id))
q32_plot<- clean_single_select(q32_data)
r32 <- plot_single_select(q32_plot, q32_t, q32_n)
r32
```

```{r}
q32_plot2 <- rbind(q32_plot, q32_t)
dir.create("output/q32_medication_sourcing")
ggsave(filename = 'output/q32_medication_sourcing/q32_medication_sourcing.png', plot = r32, device = 'png')
write.csv(q32_plot2, paste0("output/q32_medication_sourcing/q32_medication_sourcing_", q32_n,".csv"), row.names=F)
```

```{r}
q33 <- "On.average..how.much.do.you.pay..in.US.dollars..for.your.medications.on.a.monthly.basis.out.of.pocket."
q33_t <- "On average, how much do you pay (in US dollars) for your medications on a monthly basis out of pocket?"
q33_data <- get_single_selection_0(data = raw_data, q.name = q33) %>%
  filter(response != "")
q33_n <- length(unique(q33_data$id))
q33_mean_data <- as.numeric(as.character(q33_data$response))
q33_mean <- mean(q33_mean_data) %>%
  round(3) %>%
  print()
q33_plot <- clean_single_select(q33_data)
r33 <- plot_single_select_0(q33_plot, q33_t, q33_n, q33_mean)
r33
```

```{r}
q33_plot2 <- rbind(q33_plot, q33_t, paste("average", q33_mean, sep = " = "))
dir.create("output/q33_med_cost_monthly")
ggsave(filename = 'output/q33_med_cost_monthly/q33_med_cost_monthly.png', plot = r33, device = 'png')
write.csv(q33_plot2, paste0("output/q33_med_cost_monthly/q33_med_cost_monthly_", q33_n,".csv"), row.names=F)
write.csv(q33_data, 'output/q33_med_cost_monthly/q33_med_cost_monthly_ids.csv', row.names = FALSE)
```

```{r}
q34 <- "Do.you.seek.supportive.mental.health.services..counseling..or.other.therapy.within.or.outside.of.the.VA."
q34_t <- "Do you seek supportive mental health services, counseling, or other therapy within or outside of the VA?"
q34_data <- get_single_selection(data = raw_data, q.name = q34)
q34_n <- length(unique(q34_data$id))
q34_plot<- clean_single_select(q34_data)
r34 <- plot_single_select(q34_plot, q34_t, q34_n)
r34
```

```{r}
q34_plot2 <- rbind(q34_plot, q34_t)
dir.create("output/q34_mental_health_services")
ggsave(filename = 'output/q34_mental_health_services/q34_mental_health_services.png', plot = r34, device = 'png')
write.csv(q34_plot2, paste0("output/q34_mental_health_services/q34_mental_health_services_", q34_n,".csv"), row.names=F)
```

```{r}
q35 <- "Do.you.use.cannabis.for.medical.purposes."
q35_t <- "Do you use cannabis for medical purposes?"
q35_data <- get_single_selection(data = raw_data, q.name = q35)
q35_n <- length(unique(q35_data$id))
q35_plot<- clean_single_select(q35_data)
r35 <- plot_single_select(q35_plot, q35_t, q35_n)
r35
```

```{r}
q35_plot2 <- rbind(q35_plot, q35_t)
dir.create("output/q35_medical_cannabis")
ggsave(filename = 'output/q35_medical_cannabis/q35_medical_cannabis.png', plot = r35, device = 'png')
write.csv(q35_plot2, paste0("output/q35_medical_cannabis/q35_medical_cannabis_", q35_n,".csv"), row.names=F)
```

```{r}
q36 <- "Do.you.use.cannabis.for.recreational.purposes."
q36_t <- "Do you use cannabis for recreational purposes?"
q36_data <- get_single_selection(data = raw_data, q.name = q36)
q36_n <- length(unique(q36_data$id))
q36_plot<- clean_single_select(q36_data)
r36 <- plot_single_select(q36_plot, q36_t, q36_n)
r36
```

```{r}
q36_plot2 <- rbind(q36_plot, q36_t)
dir.create("output/q36_rec_cannabis")
ggsave(filename = 'output/q36_rec_cannabis/q36_rec_cannabis.png', plot = r36, device = 'png')
write.csv(q36_plot2, paste0("output/q36_rec_cannabis/q36_rec_cannabis_", q36_n,".csv"), row.names=F)
```

```{r}
q37 <- 'Under.what.circumstances.do.you.use.cannabis...Please.select.all.that.apply.'
q37_final_response <- "X.153"
q37_t <- "Under what circumstances do you use cannabis? (Please select all that apply)"
q37_data <- get_choose_all(raw_data, q.name = q37, f.response = q37_final_response) %>%
  tidy_choose_all()
q37_n <- length(unique(q37_data$id))
q37_plot <- clean_choose_all(q37_data, q37_n)
r37 <- plot_choose_all(q37_plot, q37_t, q37_n)
r37
```

```{r}
q37_plot2 <- rbind(q37_plot, q37_t)
dir.create("output/q37_cannabis_uses")
ggsave(filename = 'output/q37_cannabis_uses/q37_cannabis_uses.png', plot = r37, device = 'png')
write.csv(q37_plot2, paste0("output/q37_cannabis_uses/q37_cannabis_uses_", q37_n,".csv"), row.names=F)
write.csv(q37_data, 'output/q37_cannabis_uses/q37_cannabis_uses_ids.csv', row.names = FALSE)
```

```{r}
q38 <- 'Which.health.conditions.do.you.find.cannabis.to.be.helpful.in.treating...Please.select.all.that.apply.'
q38_final_response <- "X.179"
q38_t <- "Which health conditions do you find cannabis to be helpful in treating? (Please select all that apply)"
q38_data <- get_choose_all(raw_data, q.name = q38, f.response = q38_final_response) %>%
  tidy_choose_all()
q38_n <- length(unique(q38_data$id))
q38_plot <- clean_choose_all(q38_data, q38_n)
r38 <- plot_choose_all(q38_plot, q38_t, q38_n)
r38
```

```{r}
q38_plot2 <- rbind(q38_plot, q38_t)
dir.create("output/q38_conditions_cannabis")
ggsave(filename = 'output/q38_conditions_cannabis/q38_conditions_cannabis.png', plot = r38, device = 'png')
write.csv(q38_plot2, paste0("output/q38_conditions_cannabis/q38_conditions_cannabis_", q38_n,".csv"), row.names=F)
write.csv(q38_data, 'output/q38_conditions_cannabis/q38_conditions_cannabis_ids.csv', row.names = FALSE)
```

```{r}
q39 <- "What.is.the.primary.health.condition.for.which.you.find.cannabis.to.be.helpful...Please.select.one."
q39_t <- "What is the primary health condition for which you find cannabis to be helpful? (Please select one)"
q39_data <- get_single_selection(data = raw_data, q.name = q39)
q39_n <- length(unique(q39_data$id))
q39_plot<- clean_single_select(q39_data)
r39 <- plot_single_select(q39_plot, q39_t, q39_n)
r39
```

```{r}
q39_plot2 <- rbind(q39_plot, q39_t)
dir.create("output/q39_top_condition_cannabis")
ggsave(filename = 'output/q39_top_condition_cannabis/q39_top_condition_cannabis.png', plot = r39, device = 'png')
write.csv(q39_plot2, paste0("output/q39_top_condition_cannabis/q39_top_condition_cannabis_", q39_n,".csv"), row.names=F)
```

```{r}
q40 <- 'What.symptoms.do.you.find.medical.cannabis.is.most.helpful.in.treating.alleviating...Please.select.all.that.apply.'
q40_final_response <- "X.197"
q40_t <- "What symptoms do you find medical cannabis is most helpful in treating/alleviating? (Please select all that apply)"
q40_data <- get_choose_all(raw_data, q.name = q40, f.response = q40_final_response) %>%
  tidy_choose_all()
q40_n <- length(unique(q40_data$id))
q40_plot <- clean_choose_all(q40_data, q40_n)
r40 <- plot_choose_all(q40_plot, q40_t, q40_n)
r40
```

```{r}
q40_plot2 <- rbind(q40_plot, q40_t)
dir.create("output/q40_symptoms_treated")
ggsave(filename = 'output/q40_symptoms_treated/q40_symptoms_treated.png', plot = r40, device = 'png')
write.csv(q40_plot2, paste0("output/q40_symptoms_treated/q40_symptoms_treated_", q40_n,".csv"), row.names=F)
write.csv(q40_data, 'output/q40_symptoms_treated/q40_symptoms_treated_ids.csv', row.names = FALSE)
```

```{r}
q41 <- "How.long.have.you.been.using.cannabis.for.medical.purposes."
q41_t <- "How long have you been using cannabis for medical purposes?"
q41_data <- get_single_selection(data = raw_data, q.name = q41)
q41_n <- length(unique(q41_data$id))
q41_plot<- clean_single_select(q41_data)
r41 <- plot_single_select(q41_plot, q41_t, q41_n)
r41
```

```{r}
q41_plot2 <- rbind(q41_plot, q41_t)
dir.create("output/q41_med_cannabis_duration")
ggsave(filename = 'output/q41_med_cannabis_duration/q41_med_cannabis_duration.png', plot = r41, device = 'png')
write.csv(q41_plot2, paste0("output/q41_med_cannabis_duration/q41_med_cannabis_duration_", q41_n,".csv"), row.names=F)
```

```{r}
q42 <- "How.long.have.you.been.using.cannabis.for.recreational.purposes."
q42_t <- "How long have you been using cannabis for recreational purposes?"
q42_data <- get_single_selection(data = raw_data, q.name = q42)
q42_n <- length(unique(q42_data$id))
q42_plot<- clean_single_select(q42_data)
r42 <- plot_single_select(q42_plot, q42_t, q42_n)
r42
```

```{r}
q42_plot2 <- rbind(q42_plot, q42_t)
dir.create("output/q42_rec_cannabis_duration")
ggsave(filename = 'output/q42_rec_cannabis_duration/q42_rec_cannabis_duration.png', plot = r42, device = 'png')
write.csv(q42_plot2, paste0("output/q42_rec_cannabis_duration/q42_rec_cannabis_duration_", q42_n,".csv"), row.names=F)
```

```{r}
q43 <- 'How.do.you.feel.cannabis.has.helped.your.daily.life.Thinking.about.how.you.feelÂ.TODAYÂ.compared.to.theÂ.BEGINNINGÂ.of.your.use.of.cannabis.to.treat.your.primary.medical.condition...'
q43_final_response <- "X.204"
q43_t <- "How do you feel cannabis has helped your daily life?"
q43_data <- get_choose_all(raw_data, q.name = q43, f.response = q43_final_response)
dir.create("output/q43_qol")
```

```{r}
write.csv(q43_data, 'output/q43_qol/q43_daily_qol_data.csv', row.names = FALSE)
```

```{r}
q43_data1 <- get_single_selection_3(q43_data, "I experience a greater quality of life") %>%
  filter(response != "N/A") %>%
  filter(response != "") %>%
  clean_single_select()
q43_n1 <- tally(q43_data1, count)
q43_t1 <- "I experience a greater quality of life"
q43_r1 <- plot_single_select(q43_data1, q43_t1, q43_n1)
q43_r1
```

```{r}
ggsave(filename = "output/q43_qol/q43_greater_qol.png", plot = q43_r1, device = 'png')
write.csv(q43_data1, paste0("output/q43_qol/q43_greater_qol_", q43_n1, ".csv"), row.names = FALSE)
```

```{r}
q43_data2 <- get_single_selection_3(q43_data, "I experience physical symptoms (body pains, function, sensation)") %>%
  filter(response != "N/A") %>%
  filter(response != "") %>%
  clean_single_select()
q43_n2 <- tally(q43_data2, count)
q43_t2 <- "I experience physical symptoms (body pains, function, sensation)"
q43_r2 <- plot_single_select(q43_data2, q43_t2, q43_n2)
q43_r2
```

```{r}
ggsave(filename = "output/q43_qol/q43_physical.png", plot = q43_r2, device = 'png')
write.csv(q43_data2, paste0("output/q43_qol/q43_physical_", q43_n2, ".csv"), row.names = FALSE)
```

```{r}
q43_data3 <- get_single_selection_3(q43_data, "I experience psychological symptoms (anxiety, stress, sadness)") %>%
  filter(response != "N/A") %>%
  filter(response != "") %>%
  clean_single_select()
q43_n3 <- tally(q43_data3, count)
q43_t3 <- "I experience psychological symptoms (anxiety, stress, sadness)"
q43_r3 <- plot_single_select(q43_data3, q43_t3, q43_n3)
q43_r3
```

```{r}
ggsave(filename = "output/q43_qol/q43_psychological.png", plot = q43_r3, device = 'png')
write.csv(q43_data3, paste0("output/q43_qol/q43_psychological_", q43_n3, ".csv"), row.names = FALSE)
```

```{r}
q43_data4 <- get_single_selection_3(q43_data, "I use opioids") %>%
  filter(response != "N/A") %>%
  filter(response != "") %>%
  clean_single_select()
q43_n4 <- tally(q43_data4, count)
q43_t4 <- "I use opioids"
q43_r4 <- plot_single_select(q43_data4, q43_t4, q43_n4)
q43_r4
```

```{r}
ggsave(filename = "output/q43_qol/q43_opioid_use.png", plot = q43_r4, device = 'png')
write.csv(q43_data4, paste0("output/q43_qol/q43_opioid_use_", q43_n4, ".csv"), row.names = FALSE)
```

```{r}
q43_data5 <- get_single_selection_3(q43_data, "I use my prior medications (non-opioid)") %>%
  filter(response != "N/A") %>%
  filter(response != "") %>%
  clean_single_select()
q43_n5 <- tally(q43_data5, count)
q43_t5 <- "I use my prior medications (non-opioid)"
q43_r5 <- plot_single_select(q43_data5, q43_t5, q43_n5)
q43_r5
```

```{r}
ggsave(filename = "output/q43_qol/q43_prior_med_use.png", plot = q43_r5, device = 'png')
write.csv(q43_data5, paste0("output/q43_qol/q43_prior_med_use_", q43_n5, ".csv"), row.names = FALSE)
```

```{r}
q43_data6 <- get_single_selection_3(q43_data, "I use alcohol") %>%
  filter(response != "N/A") %>%
  filter(response != "") %>%
  clean_single_select()
q43_n6 <- tally(q43_data6, count)
q43_t6 <- "I use alcohol"
q43_r6 <- plot_single_select(q43_data6, q43_t6, q43_n6)
q43_r6
```

```{r}
ggsave(filename = "output/q43_qol/q43_alcohol.png", plot = q43_r6, device = 'png')
write.csv(q43_data6, paste0("output/q43_qol/q43_alcohol_", q43_n6, ".csv"), row.names = FALSE)
```

```{r}
q43_data7 <- get_single_selection_3(q43_data, "I use tobacco") %>%
  filter(response != "N/A") %>%
  filter(response != "") %>%
  clean_single_select()
q43_n7 <- tally(q43_data7, count)
q43_t7 <- "I use tobacco"
q43_r7 <- plot_single_select(q43_data7, q43_t7, q43_n7)
q43_r7
```

```{r}
ggsave(filename = "output/q43_qol/q43_tobacco.png", plot = q43_r7, device = 'png')
write.csv(q43_data7, paste0("output/q43_qol/q43_tobacco_", q43_n7, ".csv"), row.names = FALSE)
```

```{r}
q43_data8 <- get_single_selection_3(q43_data, "I feel the quality of my daily life is") %>%
  filter(response != "N/A") %>%
  filter(response != "") %>%
  clean_single_select()
q43_n8 <- tally(q43_data8, count)
q43_t8 <- "I feel the quality of my daily life is"
q43_r8 <- plot_single_select(q43_data8, q43_t8, q43_n8)
q43_r8
```

```{r}
ggsave(filename = "output/q43_qol/q43_daily_qol.png", plot = q43_r8, device = 'png')
write.csv(q43_data8, paste0("output/q43_qol/q43_daily_qol_", q43_n8, ".csv"), row.names = FALSE)
```

```{r}
q44 <- 'Have.you.experienced.any.side.effects.from.using.cannabis...Please.select.all.that.apply.'
q44_final_response <- "X.226"
q44_t <- "Have you experienced any side effects from using cannabis? (Please select all that apply)"
q44_data <- get_choose_all(raw_data, q.name = q44, f.response = q44_final_response) %>%
  tidy_choose_all()
q44_n <- length(unique(q44_data$id))
q44_plot <- clean_choose_all(q44_data, q44_n)
r44 <- plot_choose_all(q44_plot, q44_t, q44_n)
r44
```

```{r}
q44_plot2 <- rbind(q44_plot, q44_t)
dir.create("output/q44_cannabis_side_effects")
ggsave(filename = 'output/q44_cannabis_side_effects/q44_cannabis_side_effects.png', plot = r44, device = 'png')
write.csv(q44_plot2, paste0("output/q44_cannabis_side_effects/q44_cannabis_side_effects_", q44_n,".csv"), row.names=F)
write.csv(q44_data, 'output/q44_cannabis_side_effects/q44_cannabis_side_effects_ids.csv', row.names = FALSE)
```

```{r}
q45 <- 'What.prescription.medications.are.you.currently.taking.for.the.health.conditions.and.symptoms.you.face.that.you.are.actively.trying.to.reduce.the.use.of.by.using.cannabis...Please.select.all.that.apply.'
q45_final_response <- "X.249"
q45_t <- "What prescription medications are you currently taking for the health conditions and symptoms you face that you are actively trying to reduce the use of by using cannabis? (Please select all that apply)"
q45_data <- get_choose_all(raw_data, q.name = q45, f.response = q45_final_response) %>%
  tidy_choose_all()
q45_n <- length(unique(q45_data$id))
q45_plot <- clean_choose_all(q45_data, q45_n)
r45 <- plot_choose_all(q45_plot, q45_t, q45_n)
r45
```

```{r}
q45_plot2 <- rbind(q45_plot, q45_t)
dir.create("output/q45_meds_reduced_cannabis")
ggsave(filename = 'output/q45_meds_reduced_cannabis/q45_meds_reduced_cannabis.png', plot = r45, device = 'png')
write.csv(q45_plot2, paste0("output/q45_meds_reduced_cannabis/q45_meds_reduced_cannabis_", q45_n,".csv"), row.names=F)
write.csv(q45_data, 'output/q45_meds_reduced_cannabis/q45_meds_reduced_cannabis_ids.csv', row.names = FALSE)
```

```{r}
q46 <- "Please.rate.the.severity.of.the.side.effects.you.have.faced.with.prescription.medications.compared.to.cannabis.treatments."
q46_t <- "Please rate the severity of the side effects you have faced with prescription medications compared to cannabis treatments:"
q46_data <- get_single_selection_0(data = raw_data, q.name = q46)
q46_n <- length(unique(q46_data$id))
q46_mean_data <- as.numeric(as.character(q46_data$response))
q46_mean <- mean(q46_mean_data) %>%
  round(3) %>%
  print()
q46_plot<- clean_single_select(q46_data)
r46 <- plot_single_select_0(q46_plot, q46_t, q46_n, q46_mean)
r46
```

```{r}
q46_plot2 <- rbind(q46_plot, q46_t, paste("average", q46_mean, sep = " = "))
dir.create("output/q46_side_effects_cannabis_v_med")
ggsave(filename = 'output/q46_side_effects_cannabis_v_med/q46_side_effects_cannabis_v_med.png', plot = r46, device = 'png')
write.csv(q46_plot2, paste0("output/q46_side_effects_cannabis_v_med/q46_side_effects_cannabis_v_med_", q46_n,".csv"), row.names=F)
write.csv(q46_data, 'output/q46_side_effects_cannabis_v_med/q46_side_effects_cannabis_v_med_ids.csv', row.names = FALSE)
```

```{r}
q47 <- 'How.do.you.prefer.to.use.cannabis...Please.select.all.that.apply.'
q47_final_response <- "X.259"
q47_t <- "How do you prefer to use cannabis? (Please select all that apply)"
q47_data <- get_choose_all(raw_data, q.name = q47, f.response = q47_final_response) %>%
  tidy_choose_all()
q47_n <- length(unique(q47_data$id))
q47_plot <- clean_choose_all(q47_data, q47_n)
r47 <- plot_choose_all(q47_plot, q47_t, q47_n)
r47
```

```{r}
q47_plot2 <- rbind(q47_plot, q47_t)
dir.create("output/q47_cannabis_methods")
ggsave(filename = 'output/q47_cannabis_methods/q47_cannabis_methods.png', plot = r47, device = 'png')
write.csv(q47_plot2, paste0("output/q47_cannabis_methods/q47_cannabis_methods_", q47_n,".csv"), row.names=F)
write.csv(q47_data, 'output/q47_cannabis_methods/q47_cannabis_methods_ids.csv', row.names = FALSE)
```

```{r}
q48 <- "What.is.your.top.preferred.method..that.is..favorite.method..of.using.cannabis...Please.select.one."
q48_t <- "What is your top preferred method (that is, favorite method) of using cannabis? (Please select one)"
q48_data <- get_single_selection(data = raw_data, q.name = q48)
q48_n <- length(unique(q48_data$id))
q48_plot<- clean_single_select(q48_data)
r48 <- plot_single_select(q48_plot, q48_t, q48_n)
r48
```

```{r}
q48_plot2 <- rbind(q48_plot, q48_t)
dir.create("output/q48_top_cannabis_method")
ggsave(filename = 'output/q48_top_cannabis_method/q48_top_cannabis_method.png', plot = r48, device = 'png')
write.csv(q48_plot2, paste0("output/q48_top_cannabis_method/q48_top_cannabis_method_", q48_n,".csv"), row.names=F)
```

```{r}
q49 <- "Please.rate.the.importance.of.the.following.aspects.ofÂ.cannabis.products.to.you."
q49_final_response <- "X.267"
q49_t <- "Please rate the importance of the following aspects of cannabis products to you"
q49_data <- get_choose_all(raw_data, q.name = q49, f.response = q49_final_response)
dir.create("output/q49_cannabis_aspect_importance")
```

```{r}
write.csv(q49_data, 'output/q49_cannabis_aspect_importance/q49_cannabis_aspect_importance_data.csv', row.names = FALSE)
```

```{r}
q49_data1 <- get_single_selection_3(q49_data, "THC content - Importance") %>%
  filter(response != "") %>%
  clean_single_select()
q49_n1 <- tally(q49_data1, count)
q49_t1 <- "THC content"
q49_r1 <- plot_single_select(q49_data1, q49_t1, q49_n1)
q49_r1
```

```{r}
ggsave(filename = "output/q49_cannabis_aspect_importance/q49_thc.png", plot = q49_r1, device = 'png')
write.csv(q49_data1, paste0("output/q49_cannabis_aspect_importance/q49_thc_", q49_n1, ".csv"), row.names = FALSE)
```

```{r}
q49_data2 <- get_single_selection_3(q49_data, "CBD content - Importance") %>%
  filter(response != "") %>%
  clean_single_select()
q49_n2 <- tally(q49_data2, count)
q49_t2 <- "CBD content - Importance"
q49_r2 <- plot_single_select(q49_data2, q49_t2, q49_n2)
q49_r2
```

```{r}
ggsave(filename = "output/q49_cannabis_aspect_importance/q49_cbd.png", plot = q49_r2, device = 'png')
write.csv(q49_data2, paste0("output/q49_cannabis_aspect_importance/q49_cbd_", q49_n2, ".csv"), row.names = FALSE)
```

```{r}
q49_data3 <- get_single_selection_3(q49_data, "Other cannabinoids and terpenes - Importance") %>%
  filter(response != "") %>%
  clean_single_select()
q49_n3 <- tally(q49_data3, count)
q49_t3 <- "Other cannabinoids and terpenes"
q49_r3 <- plot_single_select(q49_data3, q49_t3, q49_n3)
q49_r3
```

```{r}
ggsave(filename = "output/q49_cannabis_aspect_importance/q49_other_cbd.png", plot = q49_r3, device = 'png')
write.csv(q49_data3, paste0("output/q49_cannabis_aspect_importance/q49_other_cbd_", q49_n3, ".csv"), row.names = FALSE)
```

```{r}
q49_data4 <- get_single_selection_3(q49_data, "Cost/price - Importance") %>%
  filter(response != "") %>%
  clean_single_select()
q49_n4 <- tally(q49_data4, count)
q49_t4 <- "Cost/price - Importance"
q49_r4 <- plot_single_select(q49_data4, q49_t4, q49_n4)
q49_r4
```

```{r}
ggsave(filename = "output/q49_cannabis_aspect_importance/q49_cost.png", plot = q49_r4, device = 'png')
write.csv(q49_data4, paste0("output/q49_cannabis_aspect_importance/q49_cost_", q49_n4, ".csv"), row.names = FALSE)
```

```{r}
q49_data5 <- get_single_selection_3(q49_data, "Quality - Importance") %>%
  filter(response != "") %>%
  clean_single_select()
q49_n5 <- tally(q49_data5, count)
q49_t5 <- "Quality - Importance"
q49_r5 <- plot_single_select(q49_data5, q49_t5, q49_n5)
q49_r5
```

```{r}
ggsave(filename = "output/q49_cannabis_aspect_importance/q49_quality.png", plot = q49_r5, device = 'png')
write.csv(q49_data5, paste0("output/q49_cannabis_aspect_importance/q49_quality_", q49_n5, ".csv"), row.names = FALSE)
```

```{r}
q49_data6 <- get_single_selection_3(q49_data, "Product type (flower, vape cartridge, edibles, etc.) - Importance") %>%
  filter(response != "") %>%
  clean_single_select()
q49_n6 <- tally(q49_data6, count)
q49_t6 <- "Product type (flower, vape cartridge, edibles, etc.) - Importance"
q49_r6 <- plot_single_select(q49_data6, q49_t6, q49_n6)
q49_r6
```

```{r}
ggsave(filename = "output/q49_cannabis_aspect_importance/q49_product_type.png", plot = q49_r6, device = 'png')
write.csv(q49_data6, paste0("output/q49_cannabis_aspect_importance/q49_product_type_", q49_n6, ".csv"), row.names = FALSE)
```

```{r}
q49_data7 <- get_single_selection_3(q49_data, "Favorite strain - Importance") %>%
  filter(response != "") %>%
  clean_single_select()
q49_n7 <- tally(q49_data7, count)
q49_t7 <- "Favorite strain - Importance"
q49_r7 <- plot_single_select(q49_data7, q49_t7, q49_n7)
q49_r7
```

```{r}
ggsave(filename = "output/q49_cannabis_aspect_importance/q49_favorite_strain.png", plot = q49_r7, device = 'png')
write.csv(q49_data7, paste0("output/q49_cannabis_aspect_importance/q49_favorite_strain_", q49_n7, ".csv"), row.names = FALSE)
```

```{r}
q49_data8 <- get_single_selection_3(q49_data, "Other - Importance") %>%
  filter(response != "") %>%
  clean_single_select()
q49_n8 <- tally(q49_data8, count)
q49_t8 <- "Other - Importance"
q49_r8 <- plot_single_select(q49_data8, q49_t8, q49_n8)
q49_r8
```

```{r}
ggsave(filename = "output/q49_cannabis_aspect_importance/q49_other.png", plot = q49_r8, device = 'png')
write.csv(q49_data8, paste0("output/q49_cannabis_aspect_importance/q49_other_", q49_n8, ".csv"), row.names = FALSE)
```

```{r}
q50 <- "How.many.days.do.you.use.cannabis.per.week...Please.select.one."
q50_t <- "How many days do you use cannabis per week? (Please select one)"
q50_data <- get_single_selection(data = raw_data, q.name = q50)
q50_n <- length(unique(q50_data$id))
q50_plot<- clean_single_select(q50_data)
r50 <- plot_single_select(q50_plot, q50_t, q50_n)
r50
```

```{r}
q50_plot2 <- rbind(q50_plot, q50_t)
dir.create("output/q50_cannabis_days_per_wk")
ggsave(filename = 'output/q50_cannabis_days_per_wk/q50_cannabis_days_per_wk.png', plot = r50, device = 'png')
write.csv(q50_plot2, paste0("output/q50_cannabis_days_per_wk/q50_cannabis_days_per_wk_", q50_n,".csv"), row.names=F)
```

```{r}
q51 <- "What.isÂ.ï..your.preferred.time.of.day.to.use.cannabis...Please.select.one."
q51_t <- "What is your preferred time of day to use cannabis? (Please select one)"
q51_data <- get_single_selection(data = raw_data, q.name = q51)
q51_n <- length(unique(q51_data$id))
q51_plot<- clean_single_select(q51_data)
r51 <- plot_single_select(q51_plot, q51_t, q51_n)
r51
```

```{r}
q51_plot2 <- rbind(q51_plot, q51_t)
dir.create("output/q51_preferred_use_time")
ggsave(filename = 'output/q51_preferred_use_time/q51_preferred_use_time.png', plot = r51, device = 'png')
write.csv(q51_plot2, paste0("output/q51_preferred_use_time/q51_preferred_use_time_", q51_n,".csv"), row.names=F)
```

```{r}
q52 <- "On.days.you.regularly.use.cannabis..how.many.times.per.day.do.you.use.cannabis."
q52_t <- "On days you regularly use cannabis, how many times per day do you use cannabis?"
q52_data <- get_single_selection(data = raw_data, q.name = q52)
q52_n <- length(unique(q52_data$id))
q52_plot<- clean_single_select(q52_data)
r52 <- plot_single_select(q52_plot, q52_t, q52_n)
r52
```

```{r}
q52_plot2 <- rbind(q52_plot, q52_t)
dir.create("output/q52_use_times_per_day")
ggsave(filename = 'output/q52_use_times_per_day/q52_use_times_per_day.png', plot = r52, device = 'png')
write.csv(q52_plot2, paste0("output/q52_use_times_per_day/q52_use_times_per_day_", q52_n,".csv"), row.names=F)
```

```{r}
q53 <- "On.average..how.much.do.you.spend..in.US.dollars..on.consumable.cannabis.products.per.week."
q53_t <- "On average, how much do you spend (in US dollars) on consumable cannabis products per week?"
q53_data <- get_single_selection_0(data = raw_data, q.name = q53) %>%
  filter(response != "")
q53_n <- length(unique(q53_data$id))
q53_mean_data <- as.numeric(as.character(q53_data$response))
q53_mean <- mean(q53_mean_data) %>%
  round(3) %>%
  print()
q53_plot<- clean_single_select(q53_data)
r53 <- plot_single_select_0(q53_plot, q53_t, q53_n, q53_mean)
r53
```

```{r}
q53_plot2 <- rbind(q53_plot, q53_t, paste("average", q53_mean, sep = " = "))
dir.create("output/q53_cannabis_cost_wkly")
ggsave(filename = 'output/q53_cannabis_cost_wkly/q53_cannabis_cost_wkly.png', plot = r53, device = 'png')
write.csv(q53_plot2, paste0("output/q53_cannabis_cost_wkly/q53_cannabis_cost_wkly_", q53_n,".csv"), row.names=F)
write.csv(q53_data, 'output/q53_cannabis_cost_wkly/q53_cannabis_cost_wkly_ids.csv', row.names = FALSE)
```

```{r}
q54 <- "What.percent.of.your.monthly.purchases.are.through.regulated.sources..dispensary..retail.establishment..caregiver.authorized.private.cultivator.."
q54_t <- "What percent of your monthly purchases are through regulated sources (dispensary, retail establishment, caregiver/authorized private cultivator)?"
q_data <- get_single_selection_0(data = raw_data, q.name = q54) %>%
  filter(response != "")
q54_n <- length(unique(q_data$id))
q54_mean_data <- as.numeric(as.character(q_data$response))
q54_mean <- mean(q54_mean_data) %>%
  round(3) %>%
  print()
q54_plot<- clean_single_select(q_data)
r54 <- plot_single_select_0(q54_plot, q54_t, q54_n, q54_mean)
r54
```

```{r}
q54_plot2 <- rbind(q54_plot, q54_t, paste("average", q54_mean, sep = " = "))
dir.create("output/q54_purchase_sources")
ggsave(filename = 'output/q54_purchase_sources/q54_purchase_sources.png', plot = r54, device = 'png')
write.csv(q54_plot2, paste0("output/q54_purchase_sources/q54_purchase_sources_", q54_n,".csv"), row.names=F)
write.csv(q_data, 'output/q54_purchase_sources/q54_purchase_sources_ids.csv', row.names = FALSE)
```

```{r}
q55 <- "Do.you.grow.your.own.cannabis.at.home."
q55_t <- "Do you grow your own cannabis at home?"
q55_data <- get_single_selection(data = raw_data, q.name = q55)
q55_n <- length(unique(q55_data$id))
q55_plot<- clean_single_select(q55_data)
r55 <- plot_single_select(q55_plot, q55_t, q55_n)
r55
```

```{r}
q55_plot2 <- rbind(q55_plot, q55_t)
dir.create("output/q55_home_grow")
ggsave(filename = 'output/q55_home_grow/q55_home_grow.png', plot = r55, device = 'png')
write.csv(q55_plot2, paste0("output/q55_home_grow/q55_home_grow_", q55_n,".csv"), row.names=F)
```

```{r}
q56 <- "What.is.your.favorite.cannabis.strain."
q56_t <- "What is your favorite cannabis strain?"
q56_data <- get_single_selection(data = raw_data, q.name = q56)
q56_n <- length(unique(q_data$id))
q56_plot <- clean_single_select(q56_data)
```

```{r}
q56_plot2 <- rbind(q56_plot, q56_t)
dir.create("output/q56_favorite_strain")
write.csv(q56_plot2, paste0("output/q56_favorite_strain/q56_favorite_strain_", q56_n,".csv"), row.names=F)
```

```{r}
q57 <- "What.product.s..and.or.strain.s..do.you.want.that.are.not.currently.available.in.your.local.dispensaries."
q57_t <- "What product(s) and/or strain(s) do you want that are not currently available in your local dispensaries?"
q57_data <- get_single_selection_0(data = raw_data, q.name = q57)
q57_n <- length(unique(q57_data$id))
q57_plot<- clean_single_select(q57_data)
```

```{r}
q57_plot2 <- rbind(q57_plot, q57_t)
dir.create("output/q57_products_desired")
write.csv(q57_plot2, paste0("output/q57_products_desired/q57_products_desired_", q57_n,".csv"), row.names=F)
```

```{r}
q58 <- "Are.you.concerned.about.your.family.members.or.loved.ones.knowing.about.your.cannabis.use."
q58_t <- "Are you concerned about your family members or loved ones knowing about your cannabis use?"
q58_data <- get_single_selection(data = raw_data, q.name = q58)
q58_n <- length(unique(q58_data$id))
q58_plot<- clean_single_select(q58_data)
r58 <- plot_single_select(q58_plot, q58_t, q58_n)
r58
```

```{r}
q58_plot2 <- rbind(q58_plot, q58_t)
dir.create("output/q58_family_cannabis_acceptence")
ggsave(filename = 'output/q58_family_cannabis_acceptence/q58_family_cannabis_acceptence.png', plot = r58, device = 'png')
write.csv(q58_plot2, paste0("output/q58_family_cannabis_acceptence/q58_family_cannabis_acceptence_", q58_n,".csv"), row.names=F)
```

```{r}
q59 <- "Are.you.concerned.about.your.workplace.knowing.about.your.cannabis.use."
q59_t <- "Are you concerned about your workplace knowing about your cannabis use?"
q59_data <- get_single_selection(data = raw_data, q.name = q59)
q59_n <- length(unique(q59_data$id))
q59_plot<- clean_single_select(q59_data)
r59 <- plot_single_select(q59_plot, q59_t, q59_n)
r59
```

```{r}
q59_plot2 <- rbind(q59_plot, q59_t)
dir.create("output/q59_workplace_cannabis_knowledge")
ggsave(filename = 'output/q59_workplace_cannabis_knowledge/q59_workplace_cannabis_knowledge.png', plot = r59, device = 'png')
write.csv(q59_plot2, paste0("output/q59_workplace_cannabis_knowledge/q59_workplace_cannabis_knowledge_", q59_n,".csv"), row.names=F)
```

```{r}
q60 <- "Are.you.concerned.that.your.workplace.or.other.agency.will.test.you.for.your.cannabis.use."
q60_t <- "Are you concerned that your workplace or other agency will test you for your cannabis use?"
q60_data <- get_single_selection(data = raw_data, q.name = q60)
q60_n <- length(unique(q60_data$id))
q60_plot<- clean_single_select(q60_data)
r60 <- plot_single_select(q60_plot, q60_t, q60_n)
r60
```

```{r}
q60_plot2 <- rbind(q60_plot, q60_t)
dir.create("output/q60_workplace_cannabis_testing")
ggsave(filename = 'output/q60_workplace_cannabis_testing/q60_workplace_cannabis_testing.png', plot = r60, device = 'png')
write.csv(q60_plot2, paste0("output/q60_workplace_cannabis_testing/q60_workplace_cannabis_testing_", q60_n,".csv"), row.names=F)
```

```{r}
q61 <- 'Do.you.face.any.of.the.following.barriers.for.you.to.consume.cannabis...Please.select.all.that.apply.'
q61_final_response <- "X.279"
q61_t <- "Do you face any of the following barriers for you to consume cannabis (Please select all that apply)"
q61_data <- get_choose_all(raw_data, q.name = q61, f.response = q61_final_response) %>%
  tidy_choose_all()
q61_n <- length(unique(q61_data$id))
q61_plot <- clean_choose_all(q61_data, q61_n)
r61 <- plot_choose_all(q61_plot, q61_t, q61_n)
r61
```

```{r}
q61_plot2 <- rbind(q61_plot, q61_t)
dir.create("output/q61_barriers")
ggsave(filename = 'output/q61_barriers/q61_barriers.png', plot = r61, device = 'png')
write.csv(q61_plot2, paste0("output/q61_barriers/q61_barriers_", q61_n,".csv"), row.names=F)
write.csv(q61_data, 'output/q61_barriers/q61_barriers_ids.csv', row.names = FALSE)
```

```{r}
q62 <- 'How.much.cannabis.flower.are.you.smoking.or.vaping.per.week...i.e..grams..ounces..etc..'
q62_final_response <- "X.283"
q62_t <- "How much cannabis flower are you smoking or vaping per week (ie. grams, ounces, etc)?"
q62_data <- get_choose_all(raw_data, q.name = q62, f.response = q62_final_response)
dir.create("output/q62_smoke_vape_wkly")
```

```{r}
write.csv(q62_data, 'output/q62_smoke_vape_wkly/q62_smoke_vape_wkly_data.csv', row.names = FALSE)
```

```{r}
q62_data1 <- get_single_selection_3(q62_data, "Smoke flower") %>%
  filter(response != "") %>%
  clean_single_select()
q62_n1 <- tally(q62_data1, count)
q62_t1 <- "Flower weekly"
q62_r1 <- plot_single_select(q62_data1, q62_t1, q62_n1)
q62_r1
```

```{r}
ggsave(filename = "output/q62_smoke_vape_wkly/smoke_flower.png", plot = q62_r1, device = 'png')
write.csv(q62_data1, paste0("output/q62_smoke_vape_wkly/smoke_flower_", q62_n1, ".csv"), row.names = FALSE)
```

```{r}
q62_data2 <- get_single_selection_3(q62_data, "Vape flower") %>%
  filter(response != "") %>%
  clean_single_select()
q62_n2 <- tally(q62_data2, count)
q62_t2 <- "Vape weekly"
q62_r2 <- plot_single_select(q62_data2, q62_t2, q62_n2)
q62_r2
```

```{r}
ggsave(filename = "output/q62_smoke_vape_wkly/vape_flower.png", plot = q62_r2, device = 'png')
write.csv(q62_data2, paste0("output/q62_smoke_vape_wkly/vape_flower_", q62_n2, ".csv"), row.names = FALSE)
```

```{r}
q62_data3 <- get_single_selection_3(q62_data, "Concentrates (e.g. rosin, shatter, wax, hash, kief)") %>%
  filter(response != "") %>%
  clean_single_select()
q62_n3 <- tally(q62_data3, count)
q62_t3 <- "Concentrates weekly"
q62_r3 <- plot_single_select(q62_data3, q62_t3, q62_n3)
q62_r3
```

```{r}
ggsave(filename = "output/q62_smoke_vape_wkly/concentrates.png", plot = q62_r3, device = 'png')
write.csv(q62_data3, paste0("output/q62_smoke_vape_wkly/concentrates_", q62_n3, ".csv"), row.names = FALSE)
```

```{r}
q63 <- 'How.many.milligrams.of.cannabis.do.you.use.per.week.'
q63_final_response <- "X.297"
q63_t <- "How many milligrams of cannabis do you use per week?"
q63_data <- get_choose_all(raw_data, q.name = q63, f.response = q63_final_response)
dir.create("output/q63_mg_edibles_etc")
```

```{r}
write.csv(q63_data, 'output/q63_mg_edibles_etc/q63_mg_edibles_etc_data.csv', row.names = FALSE)
```

```{r}
q63_data1 <- get_single_selection_3(q63_data, "Edibles (e.g. gummies, chocolate, lozenges, beverages, cooking oils, etc.)") %>%
  filter(response != "") %>%
  clean_single_select()
q63_n1 <- tally(q63_data1, count)
q63_t1 <- "Edibles (e.g. gummies, chocolate, lozenges, beverages, cooking oils, etc.)"
q63_r1 <- plot_single_select(q63_data1, q63_t1, q63_n1)
q63_r1
```

```{r}
ggsave(filename = "output/q63_mg_edibles_etc/q63_edibles.png", plot = q63_r1, device = 'png')
write.csv(q63_data1, paste0("output/q63_mg_edibles_etc/q63_edibles_", q63_n1, ".csv"), row.names = FALSE)
```

```{r}
q63_data2 <- get_single_selection_3(q63_data, "Transdermal patches") %>%
  filter(response != "") %>%
  clean_single_select()
q63_n2 <- tally(q63_data2, count)
q63_t2 <- "Transdermal patches"
q63_r2 <- plot_single_select(q63_data2, q63_t2, q63_n2)
q63_r2
```

```{r}
ggsave(filename = "output/q63_mg_edibles_etc/q63_patches.png", plot = q63_r2, device = 'png')
write.csv(q63_data2, paste0("output/q63_mg_edibles_etc/q63_patches_", q63_n2, ".csv"), row.names = FALSE)
```

```{r}
q63_data3 <- get_single_selection_3(q63_data, "Suppositories") %>%
  filter(response != "") %>%
  clean_single_select()
q63_n3 <- tally(q63_data3, count)
q63_t3 <- "Suppositories"
q63_r3 <- plot_single_select(q63_data3, q63_t3, q63_n3)
q63_r3
```

```{r}
ggsave(filename = "output/q63_mg_edibles_etc/q63_suppositories.png", plot = q63_r3, device = 'png')
write.csv(q63_data3, paste0("output/q63_mg_edibles_etc/q63_suppositories_", q63_n3, ".csv"), row.names = FALSE)
```

```{r}
q63_data4 <- get_single_selection_3(q63_data, "Capsules") %>%
  filter(response != "") %>%
  clean_single_select()
q63_n4 <- tally(q63_data4, count)
q63_t4 <- "Capsules"
q63_r4 <- plot_single_select(q63_data4, q63_t4, q63_n4)
q63_r4
```

```{r}
ggsave(filename = "output/q63_mg_edibles_etc/q63_capsules.png", plot = q63_r4, device = 'png')
write.csv(q63_data4, paste0("output/q63_mg_edibles_etc/q63_capsules_", q63_n4, ".csv"), row.names = FALSE)
```

```{r}
q64 <- 'In.an.average.week..how.often.do.you.use.salves.topicals..e.g..creams..lotions..sprays..etc...'
q64_final_response <- "X.303"
q64_t <- "In an average week, how often do you use salves/topicals (e.g. creams, lotions, sprays, etc.)"
q64_data <- get_choose_all(raw_data, q.name = q64, f.response = q64_final_response)
dir.create("output/q64_salves_topicals_wkly")
```

```{r}
q64_data1 <- get_single_selection_3(q64_data, "Salves/topicals") %>%
  filter(response != "") %>%
  clean_single_select()
q64_n1 <- tally(q64_data1, count)
q64_t1 <- "Salves/topicals"
q64_r1 <- plot_single_select(q64_data1, q64_t1, q64_n1)
q64_r1
```

```{r}
ggsave(filename = "output/q64_salves_topicals_wkly/q64_salves_topicals_wkly.png", plot = q64_r1, device = 'png')
write.csv(q64_data1, paste0("output/q64_salves_topicals_wkly/q64_salves_topicals_wkly_", q64_n1, ".csv"), row.names = FALSE)
```

```{r}
q65 <- 'How.many.milliliters..mL..of.tincture.are.you.using.per.week..Note..30mL...1oz'
q65_final_response <- "X.311"
q65_t <- "q65 'How many milliliters (mL) of tincture are you using per week? Note (30mL) = 1oz"
q65_data <- get_choose_all(raw_data, q.name = q65, f.response = q65_final_response)
dir.create("output/q65_tinctures_wkly")
```

```{r}
q65_data1 <- get_single_selection_3(q65_data, "Tinctures") %>%
  filter(response != "") %>%
  clean_single_select()
q65_n1 <- tally(q65_data1, count)
q65_t1 <- "Tinctures"
r1 <- plot_single_select(q65_data1, q65_t1, q65_n1)
r1
```

```{r}
ggsave(filename = "output/q65_tinctures_wkly/q65_tinctures_wkly.png", plot = r1, device = 'png')
write.csv(q65_data1, paste0("output/q65_tinctures_wkly/q65_tinctures_wkly_", q65_n1, ".csv"), row.names = FALSE)
```

```{r}
q66 <- "Does.yourÂ.VA.doctor.or.clinical.care.provider.know.about.your.medical.cannabis.use."
q66_t <- "Does your VA doctor or clinical care provider know about your medical cannabis use?"
q66_data <- get_single_selection(data = raw_data, q.name = q66)
q66_n <- length(unique(q66_data$id))
q66_plot<- clean_single_select(q66_data)
r66 <- plot_single_select(q66_plot, q66_t, q66_n)
r66
```

```{r}
q66_plot2 <- rbind(q66_plot, q66_t)
dir.create("output/q66_va_use_knowledge")
ggsave(filename = 'output/q66_va_use_knowledge/q66_va_use_knowledge.png', plot = r66, device = 'png')
write.csv(q66_plot2, paste0("output/q66_va_use_knowledge/q66_va_use_knowledge_", q66_n,".csv"), row.names=F)
```

```{r}
q67 <- "Which.VA.do.you.go.to."
q67_t <- "Which VA do you go to?"
q67_data <- get_single_selection_0(data = raw_data, q.name = q67) %>%
  filter(response != "")
q67_n <- length(unique(q67_data$id))
q67_plot<- clean_single_select(q67_data)
```

```{r}
q67_plot2 <- rbind(q67_plot, q67_t)
dir.create("output/q67_va_location")
write.csv(q67_plot2, paste0("output/q67_va_location/q67_va_location_", q67_n,".csv"), row.names=F)
```

```{r}
q68 <- "Does.your.VA.doctor.or.clinician.supportÂ.yourÂ.cannabis.use."
q68_t <- "Does your VA doctor or clinician support your cannabis use?"
q68_data <- get_single_selection(data = raw_data, q.name = q68)
q68_n <- length(unique(q68_data$id))
q68_plot<- clean_single_select(q68_data)
r68 <- plot_single_select(q68_plot, q68_t, q68_n)
r68
```

```{r}
q68_plot2 <- rbind(q68_plot, q68_t)
dir.create("output/q68_va_cannabis_use_support")
ggsave(filename = 'output/q68_va_cannabis_use_support/q68_va_cannabis_use_support.png', plot = r68, device = 'png')
write.csv(q68_plot2, paste0("output/q68_va_cannabis_use_support/q68_va_cannabis_use_support_", q68_n,".csv"), row.names=F)
```

```{r}
q69 <- "How.satisfied.are.you.with.the.VA.in.managing.your.health.condition."
q69_t <- "How satisfied are you with the VA in managing your health condition?"
q69_data <- get_single_selection(data = raw_data, q.name = q69)
q69_n <- length(unique(q69_data$id))
q69_plot<- clean_single_select(q69_data)
r69 <- plot_single_select(q69_plot, q69_t, q69_n)
r69
```

```{r}
q69_plot2 <- rbind(q69_plot, q69_t)
dir.create("output/q69_va_satisfaction")
ggsave(filename = 'output/q69_va_satisfaction/q69_va_satisfaction.png', plot = r69, device = 'png')
write.csv(q69_plot2, paste0("output/q69_va_satisfaction/q69_va_satisfaction_", q69_n,".csv"), row.names=F)
```

```{r}
q70 <- 'Where.do.you.get.your.information.to.make.informed.decisions.about.cannabis.products...Please.select.all.that.apply.'
q70_final_response <- "X.322"
q70_t <- "Where do you get your information to make informed decisions about cannabis products? (Please select all that apply)"
q70_data <- get_choose_all(raw_data, q.name = q70, f.response = q70_final_response) %>%
  tidy_choose_all()
q70_n <- length(unique(q70_data$id))
q70_plot <- clean_choose_all(q70_data, q70_n)
r70 <- plot_choose_all(q70_plot, q70_t, q70_n)
r70
```

```{r}
q70_plot2 <- rbind(q70_plot, q70_t)
dir.create("output/q70_cannabis_info")
ggsave(filename = 'output/q70_cannabis_info/q70_cannabis_info.png', plot = r70, device = 'png')
write.csv(q70_plot2, paste0("output/q70_cannabis_info/q70_cannabis_info_", q70_n,".csv"), row.names=F)
write.csv(q70_data, 'output/q70_cannabis_info/q70_cannabis_info_ids.csv', row.names = FALSE)
```

```{r}
q71 <- 'Which.apps.websites.do.you.use...Please.select.all.that.apply.'
q71_final_response <- "X.332"
q71_t <- "Which apps/websites do you use? (Please select all that apply)"
q71_data <- get_choose_all(raw_data, q.name = q71, f.response = q71_final_response) %>%
  tidy_choose_all()
q71_n <- length(unique(q71_data$id))
q71_plot <- clean_choose_all(q71_data, q71_n)
r71 <- plot_choose_all(q71_plot, q71_t, q71_n)
r71
```

```{r}
q71_plot2 <- rbind(q71_plot, q71_t)
dir.create("output/q71_websites_apps_used")
ggsave(filename = 'output/q71_websites_apps_used/q71_websites_apps_used.png', plot = r71, device = 'png')
write.csv(q71_plot2, paste0("output/q71_websites_apps_used/q71_websites_apps_used_", q71_n,".csv"), row.names=F)
write.csv(q71_data, 'output/q71_websites_apps_used/q71_websites_apps_used_ids.csv', row.names = FALSE)
```

```{r}
q72 <- "Which.of.the.websites.apps.is.your.primary.source.of.information...Please.select.one."
q72_t <- "Which of the websites/apps is your primary source of information? (Please select one)"
q72_data <- get_single_selection(data = raw_data, q.name = q72)
q72_n <- length(unique(q72_data$id))
q72_plot<- clean_single_select(q72_data)
r72 <- plot_single_select(q72_plot, q72_t, q72_n)
r72
```

```{r}
q72_plot2 <- rbind(q72_plot, q72_t)
dir.create("output/q72_top_website_app")
ggsave(filename = 'output/q72_top_website_app/q72_top_website_app.png', plot = r72, device = 'png')
write.csv(q72_plot2, paste0("output/q72_top_website_app/q72_top_website_app_", q72_n,".csv"), row.names=F)
```

```{r}
q73 <- "In.the.last.30.days..how.often.have.you.seen.or.heard.advertising.for.cannabis.products.or.stores.in.your.community..including.TV..radio..signs..billboards..newspapers..pamphlets..or.street.side.marketing.."
q73_t <- "In the last 30 days, how often have you seen or heard advertising for cannabis products or stores in your community (including TV, radio, signs, billboards, newspapers, pamphlets, or street-side marketing)?"
q73_data <- get_single_selection(data = raw_data, q.name = q73)
q73_n <- length(unique(q73_data$id))
q73_plot<- clean_single_select(q73_data)
r73 <- plot_single_select(q73_plot, q73_t, q73_n)
r73
```

```{r}
q73_plot2 <- rbind(q73_plot, q73_t)
dir.create("output/q73_advertising")
ggsave(filename = 'output/q73_advertising/q73_advertising.png', plot = r73, device = 'png')
write.csv(q73_plot2, paste0("output/q73_advertising/q73_advertising_", q73_n,".csv"), row.names=F)
```

```{r}
q74 <- "What.was.the.highest.pay.grade.rank.achieved.at.the.time.of.formal.discharge."
q74_t <- "What was the highest pay grade/rank achieved at the time of formal discharge?"
q74_data <- get_single_selection(data = raw_data, q.name = q74)
q74_n <- length(unique(q74_data$id))
q74_plot<- clean_single_select(q74_data)
r74 <- plot_single_select(q74_plot, q74_t, q74_n)
```

```{r}
q74_plot2 <- rbind(q74_plot, q74_t)
dir.create("output/q74_top_military_rank")
write.csv(q74_plot2, paste0("output/q74_top_military_rank/q74_top_military_rank_", q74_n,".csv"), row.names=F)
```

```{r}
q75 <- 'Which.branch.of.the.armed.services.did.you.serve.in...Please.select.all.that.apply.'
q75_final_response <- "X.339"
q75_t <- "Which branch of the armed services did you serve in? (Please select all that apply)"
q75_data <- get_choose_all(raw_data, q.name = q75, f.response = q75_final_response) %>%
  tidy_choose_all()
q75_n <- length(unique(q75_data$id))
q75_plot <- clean_choose_all(q75_data, q75_n)
r75 <- plot_choose_all(q75_plot, q75_t, q75_n)
r75
```

```{r}
q75_plot2 <- rbind(q75_plot, q75_t)
dir.create("output/q75_service_branch")
ggsave(filename = 'output/q75_service_branch/q75_service_branch.png', plot = r75, device = 'png')
write.csv(q75_plot2, paste0("output/q75_service_branch/q75_service_branch_", q75_n,".csv"), row.names=F)
write.csv(q75_data, 'output/q75_service_branch/q75_service_branch_ids.csv', row.names = FALSE)
```

```{r}
q76 <- 'Where.were.you.deployed.stationed...Please.select.all.that.apply.'
q76_final_response <- "X.365"
q76_t <- "Where were you deployed/stationed? (Please select all that apply)"
q76_data <- get_choose_all(raw_data, q.name = q76, f.response = q76_final_response) %>%
  tidy_choose_all()
q76_n <- length(unique(q76_data$id))
q76_plot <- clean_choose_all(q76_data, q76_n)
r76 <- plot_choose_all(q76_plot, q76_t, q76_n)
r76
```

```{r}
q76_plot2 <- rbind(q76_plot, q76_t)
dir.create("output/q76_deployment_locations")
ggsave(filename = 'output/q76_deployment_locations/q76_deployment_locations.png', plot = r76, device = 'png')
write.csv(q76_plot2, paste0("output/q76_deployment_locations/q76_deployment_locations_", q76_n,".csv"), row.names=F)
write.csv(q76_data, 'output/q76_deployment_locations/q76_deployment_locations_ids.csv', row.names = FALSE)
```

```{r}
q77 <- 'What.war.s..did.you.serve.in...Please.select.all.that.apply.'
q77_final_response <- "X.373"
q77_t <- "What war(s) did you serve in? (Please select all that apply)"
q77_data <- get_choose_all(raw_data, q.name = q77, f.response = q77_final_response) %>%
  tidy_choose_all()
q77_n <- length(unique(q77_data$id))
q77_plot <- clean_choose_all(q77_data, q77_n)
r77 <- plot_choose_all(q77_plot, q77_t, q77_n)
r77
```

```{r}
q77_plot2 <- rbind(q77_plot, q77_t)
dir.create("output/q77_wars_served")
ggsave(filename = 'output/q77_wars_served/q77_wars_served.png', plot = r77, device = 'png')
write.csv(q77_plot2, paste0("output/q77_wars_served/q77_wars_served_", q77_n,".csv"), row.names=F)
write.csv(q77_data, 'output/q77_wars_served/q77_wars_served_ids.csv', row.names = FALSE)
```

```{r}
q78 <- "Were.you.exposed.to.workplace.hazards.including.loud.noises.from.firearms.factories.etc..chemicals..exposed.to.burn.pits.during.war..or.working.hazardous.environments.that.could.impair.any.of.your.five.senses.and.clinical.health."
q78_t <- "Were you exposed to workplace hazards including loud noises from firearms/factories/etc, chemicals, exposed to burn pits during war, or working hazardous environments that could impair any of your five senses and clinical health?"
q78_data <- get_single_selection(data = raw_data, q.name = q78)
q78_n <- length(unique(q78_data$id))
q78_plot<- clean_single_select(q78_data)
r78 <- plot_single_select(q78_plot, q78_t, q78_n)
r78
```

```{r}
q78_plot2 <- rbind(q78_plot, q78_t)
dir.create("output/q78_workplace_hazards")
ggsave(filename = 'output/q78_workplace_hazards/q78_workplace_hazards.png', plot = r78, device = 'png')
write.csv(q78_plot2, paste0("output/q78_workplace_hazards/q78_workplace_hazards_", q78_n,".csv"), row.names=F)
```

```{r}
q79 <- 'Were.you.exposed.to.any.of.the.following.during.your.service...Please.select.all.that.apply.'
q79_final_response <- "X.385"
q79_t <- "Were you exposed to any of the following during your service? (Please select all that apply)"
q79_data <- get_choose_all(raw_data, q.name = q79, f.response = q79_final_response) %>%
  tidy_choose_all()
q79_n <- length(unique(q79_data$id))
q79_plot <- clean_choose_all(q79_data, q79_n)
r79 <- plot_choose_all(q79_plot, q79_t, q79_n)
r79
```

```{r}
q79_plot2 <- rbind(q79_plot, q79_t)
dir.create("output/q79_service_exposure")
ggsave(filename = 'output/q79_service_exposure/q79_service_exposure.png', plot = r79, device = 'png')
write.csv(q79_plot2, paste0("output/q79_service_exposure/q79_service_exposure_", q79_n,".csv"), row.names=F)
write.csv(q79_data, 'output/q79_service_exposure/q79_service_exposure_ids.csv', row.names = FALSE)
```

```{r}
q80 <- "Did.you.serve.and.or.live.in.an.active.combat.zone."
q80_t <- "Did you serve and/or live in an active combat zone?"
q80_data <- get_single_selection(data = raw_data, q.name = q80)
q80_n <- length(unique(q80_data$id))
q80_plot <- clean_single_select(q80_data)
r80 <- plot_single_select(q80_plot, q80_t, q80_n)
r80
```

```{r}
q80_plot2 <- rbind(q80_plot, q80_t)
dir.create("output/q80_active_combat_zones")
ggsave(filename = 'output/q80_active_combat_zones/q80_active_combat_zones.png', plot = r80, device = 'png')
write.csv(q80_plot2, paste0("output/q80_active_combat_zones/q80_active_combat_zones_", q80_n,".csv"), row.names=F)
```

```{r}
q81 <- "Did.you.ever.go.on.combat.patrols.or.have.other.dangerous.duty."
q81_t <- "Did you ever go on combat patrols or have other dangerous duty?"
q81_data <- get_single_selection(data = raw_data, q.name = q81)
q81_n <- length(unique(q81_data$id))
q81_plot<- clean_single_select(q81_data)
r81 <- plot_single_select(q81_plot, q81_t, q81_n)
r81
```

```{r}
q81_plot2 <- rbind(q81_plot, q81_t)
dir.create("output/q81_dangerous_duties")
ggsave(filename = 'output/q81_dangerous_duties/q81_dangerous_duties.png', plot = r81, device = 'png')
write.csv(q81_plot2, paste0("output/q81_dangerous_duties/q81_dangerous_duties_", q81_n,".csv"), row.names=F)
```

```{r}
q82 <- "Were.you.ever.under.enemy.fire."
q82_t <- "Were you ever under enemy fire?"
q82_data <- get_single_selection(data = raw_data, q.name = q82)
q82_n <- length(unique(q82_data$id))
q82_plot<- clean_single_select(q82_data)
r82 <- plot_single_select(q82_plot, q82_t, q82_n)
r82
```

```{r}
q82_plot2 <- rbind(q82_plot, q82_t)
dir.create("output/q82_enemy_fire")
ggsave(filename = 'output/q82_enemy_fire/q82_enemy_fire.png', plot = r82, device = 'png')
write.csv(q82_plot2, paste0("output/q82_enemy_fire/q82_enemy_fire_", q82_n,".csv"), row.names=F)
```

```{r}
q83 <- "Were.you.ever.surrounded.by.the.enemy."
q83_t <- "Were you ever surrounded by the enemy?"
q83_data <- get_single_selection(data = raw_data, q.name = q83)
q83_n <- length(unique(q83_data$id))
q83_plot<- clean_single_select(q83_data)
r83 <- plot_single_select(q83_plot, q83_t, q83_n)
r83
```

```{r}
q83_plot2 <- rbind(q83_plot, q83_t)
dir.create("output/q83_surrounded_by_enemy")
ggsave(filename = 'output/q83_surrounded_by_enemy/q83_surrounded_by_enemy.png', plot = r83, device = 'png')
write.csv(q83_plot2, paste0("output/q83_surrounded_by_enemy/q83_surrounded_by_enemy_", q83_n,".csv"), row.names=F)
```

```{r}
q84 <- "What.percentage.of.the.soldiers.in.your.unit.were.killed..KIA...wounded.or.missing.in.action..MIA.."
q84_t <- "What percentage of the soldiers in your unit were killed (KIA), wounded or missing in action (MIA)?"
q84_data <- get_single_selection(data = raw_data, q.name = q84)
q84_n <- length(unique(q84_data$id))
q84_plot<- clean_single_select(q84_data)
r84 <- plot_single_select(q84_plot, q84_t, q84_n)
r84
```

```{r}
q84_plot2 <- rbind(q84_plot, q84_t)
dir.create("output/q84_soldiers_kia_mia")
ggsave(filename = 'output/q84_soldiers_kia_mia/q84_soldiers_kia_mia.png', plot = r84, device = 'png')
write.csv(q84_plot2, paste0("output/q84_soldiers_kia_mia/q84_soldiers_kia_mia_", q84_n,".csv"), row.names=F)
```

```{r}
q85 <- "How.often.did.you.fire.rounds.at.the.enemy."
q85_t <- "How often did you fire rounds at the enemy?"
q85_data <- get_single_selection(data = raw_data, q.name = q85)
q85_n <- length(unique(q85_data$id))
q85_plot<- clean_single_select(q85_data)
r85 <- plot_single_select(q85_plot, q85_t, q85_n)
r85
```

```{r}
q85_plot2 <- rbind(q85_plot, q85_t)
dir.create("output/q85_fire_rounds_enemy")
ggsave(filename = 'output/q85_fire_rounds_enemy/q85_fire_rounds_enemy.png', plot = r85, device = 'png')
write.csv(q85_plot2, paste0("output/q85_fire_rounds_enemy/q85_fire_rounds_enemy_", q85_n,".csv"), row.names=F)
```

```{r}
q86 <- "How.often.did.you.see.someone.hit.by.incoming.or.outgoing.rounds."
q86_t <- "How often did you see someone hit by incoming or outgoing rounds?"
q86_data <- get_single_selection(data = raw_data, q.name = q86)
q86_n <- length(unique(q86_data$id))
q86_plot<- clean_single_select(q86_data)
r86 <- plot_single_select(q86_plot, q86_t, q86_n)
r86
```

```{r}
q86_plot2 <- rbind(q86_plot, q86_t)
dir.create("output/q86_witness_hit_rounds")
ggsave(filename = 'output/q86_witness_hit_rounds/q86_witness_hit_rounds.png', plot = r86, device = 'png')
write.csv(q86_plot2, paste0("output/q86_witness_hit_rounds/q86_witness_hit_rounds_", q86_n,".csv"), row.names=F)
```

```{r}
q87 <- "How.often.were.you.in.danger.of.being.injured.or.killed..i.e...being.pinned.down..overrun..ambushed..near.miss..etc..."
q87_t <- "How often were you in danger of being injured or killed (i.e. being pinned down, overrun, ambushed, near miss, etc.)?"
q87_data <- get_single_selection(data = raw_data, q.name = q87)
q87_n <- length(unique(q87_data$id))
q87_plot<- clean_single_select(q87_data)
r87 <- plot_single_select(q87_plot, q87_t, q87_n)
r87
```

```{r}
q87_plot2 <- rbind(q87_plot, q87_t)
dir.create("output/q87_danger_frequency")
ggsave(filename = 'output/q87_danger_frequency/q87_danger_frequency.png', plot = r87, device = 'png')
write.csv(q87_plot2, paste0("output/q87_danger_frequency/q87_danger_frequency_", q87_n,".csv"), row.names=F)
```

```{r}
q88 <- "What.is.your.age..in.years.."
q88_t <- "What is your age (in years)?"
q88_data <- get_single_selection(data = raw_data, q.name = q88)
q88_n <- length(unique(q88_data$id))
q88_plot<- clean_single_select(q88_data)
r88 <- plot_single_select(q88_plot, q88_t, q88_n)
r88
```

```{r}
q88_plot2 <- rbind(q88_plot, q88_t)
dir.create("output/q88_age")
ggsave(filename = 'output/q88_age/q88_age.png', plot = r88, device = 'png')
write.csv(q88_plot2, paste0("output/q88_age/q88_age_", q88_n,".csv"), row.names=F)
```

```{r}
q89 <- "To.which.gender.do.you.most.identify."
q89_t <- "To which gender do you most identify?"
q89_data <- get_single_selection(data = raw_data, q.name = q89)
q89_n <- length(unique(q89_data$id))
q89_plot<- clean_single_select(q89_data)
r89 <- plot_single_select(q89_plot, q89_t, q89_n)
r89
```

```{r}
q89_plot2 <- rbind(q89_plot, q89_t)
dir.create("output/q89_gender")
ggsave(filename = 'output/q89_gender/q89_gender.png', plot = r89, device = 'png')
write.csv(q89_plot2, paste0("output/q89_gender/q89_gender_", q89_n,".csv"), row.names=F)
```

```{r}
q90 <- "What.is.your.annual.household.income..in.US.dollars."
q90_t <- "What is your annual household income (in US dollars)"
q90_data <- get_single_selection_0(data = raw_data, q.name = q90) %>%
  filter(response != "")
q90_n <- length(unique(q90_data$id))
q90_plot<- clean_single_select(q90_data)
r90 <- plot_single_select(q90_plot, q90_t, q90_n)
r90
```

```{r}
q90_plot2 <- rbind(q90_plot, q90_t)
dir.create("output/q90_income")
ggsave(filename = 'output/q90_income/q90_income.png', plot = r90, device = 'png')
write.csv(q90_plot2, paste0("output/q90_income/q90_income_", q90_n,".csv"), row.names=F)
```

```{r}
q91 <- "What.is.the.highest.degree.or.level.of.school.you.have.completed...If.you.re.currently.enrolled.in.school..please.indicate.the.highest.degree.you.haveÂ.received..Â."
q91_t <- "What is the highest degree or level of school you have completed? (If you're currently enrolled in school, please indicate the highest degree you have received.)"
q91_data <- get_single_selection(data = raw_data, q.name = q91)
q91_n <- length(unique(q91_data$id))
q91_plot<- clean_single_select(q91_data)
r91 <- plot_single_select(q91_plot, q91_t, q91_n)
r91
```

```{r}
q91_plot2 <- rbind(q91_plot, q91_t)
dir.create("output/q91_highest_degree")
ggsave(filename = 'output/q91_highest_degree/q91_highest_degree.png', plot = r91, device = 'png')
write.csv(q91_plot2, paste0("output/q91_highest_degree/q91_highest_degree_", q91_n,".csv"), row.names=F)
```

```{r}
q92 <- "What.is.your.marital.status."
q92_t <- "What is your marital status?"
q92_data <- get_single_selection(data = raw_data, q.name = q92)
q92_n <- length(unique(q92_data$id))
q92_plot<- clean_single_select(q92_data)
r92 <- plot_single_select(q92_plot, q92_t, q92_n)
r92
```

```{r}
q92_plot2 <- rbind(q92_plot, q92_t)
dir.create("output/q92_marital_status")
ggsave(filename = 'output/q92_marital_status/q92_marital_status.png', plot = r92, device = 'png')
write.csv(q92_plot2, paste0("output/q92_marital_status/q92_marital_status_", q92_n,".csv"), row.names=F)
```

```{r}
q93 <- "What.is.your.current.employment.status."
q93_t <- "What is your current employment status?"
q93_data <- get_single_selection(data = raw_data, q.name = q93)
q93_n <- length(unique(q93_data$id))
q93_plot<- clean_single_select(q93_data)
r93 <- plot_single_select(q93_plot, q93_t, q93_n)
r93
```

```{r}
q93_plot2 <- rbind(q93_plot, q93_t)
dir.create("output/q93_employment_status")
ggsave(filename = 'output/q93_employment_status/q93_employment_status.png', plot = r93, device = 'png')
write.csv(q93_plot2, paste0("output/q93_employment_status/q93_employment_status_", q93_n,".csv"), row.names=F)
```

```{r}
q94 <- "Have.you.ever.been.homeless."
q94_t <- "Have you ever been homeless?"
q94_data <- get_single_selection(data = raw_data, q.name = q94)
q94_n <- length(unique(q94_data$id))
q94_plot<- clean_single_select(q94_data)
r94 <- plot_single_select(q94_plot, q94_t, q94_n)
r94
```

```{r}
q94_plot2 <- rbind(q94_plot, q94_t)
dir.create("output/q94_homeless")
ggsave(filename = 'output/q94_homeless/q94_homeless.png', plot = r94, device = 'png')
write.csv(q94_plot2, paste0("output/q94_homeless/q94_homeless_", q94_n,".csv"), row.names=F)
```

```{r}
q95 <- "Do.you.own.a.firearm."
q95_t <- "Do you own a firearm?"
q95_data <- get_single_selection(data = raw_data, q.name = q95)
q95_n <- length(unique(q95_data$id))
q95_plot<- clean_single_select(q95_data)
r95 <- plot_single_select(q95_plot, q95_t, q95_n)
r95
```

```{r}
q95_plot2 <- rbind(q95_plot, q95_t)
dir.create("output/q95_firearms")
ggsave(filename = 'output/q95_firearms/q95_firearms.png', plot = r95, device = 'png')
write.csv(q95_plot2, paste0("output/q95_firearms/q95_firearms_", q95_n,".csv"), row.names=F)
```

```{r}
q96 <- "Which.of.the.following.best.represents.your.ethnic.heritage."
q96_t <- "Which of the following best represents your ethnic heritage?"
q96_data <- get_single_selection(data = raw_data, q.name = q96)
q96_n <- length(unique(q96_data$id))
q96_plot<- clean_single_select(q96_data)
r96 <- plot_single_select(q96_plot, q96_t, q96_n)
r96
```

```{r}
q96_plot2 <- rbind(q96_plot, q96_t)
dir.create("output/q96_race")
ggsave(filename = 'output/q96_race/q96_race.png', plot = r96, device = 'png')
write.csv(q96_plot2, paste0("output/q96_race/q96_race_", q96_n,".csv"), row.names=F)
```

```{r}
q97 <- 'Do.you.consider.yourself.to.be.any.of.the.following.'
q97_t <- "Do you consider yourself to be any of the following?"
q97_data <- get_single_selection(data = raw_data, q.name = q97)
q97_n <- length(unique(q97_data$id))
q97_plot<- clean_single_select(q97_data)
r97 <- plot_single_select(q97_plot, q97_t, q97_n)
r97
```

```{r}
q97_plot2 <- rbind(q97_plot, q97_t)
dir.create("output/q97_sexuality")
ggsave(filename = 'output/q97_sexuality/q97_sexuality.png', plot = r97, device = 'png')
write.csv(q97_plot2, paste0("output/q97_sexuality/q97_sexuality_", q97_n,".csv"), row.names=F)
```

```{r}
q98 <- "What.state.in.the.US.do.you.currently.live.in."
q98_t <- "What state in the US do you currently live in?"
q98_data <- get_single_selection(data = raw_data, q.name = q98)
q98_n <- length(unique(q98_data$id))
q98_plot<- clean_single_select(q98_data)
r98 <- plot_single_select(q98_plot, q98_t, q98_n)
r98
```

```{r}
q98_plot2 <- rbind(q98_plot, q98_t)
dir.create("output/q98_state")
ggsave(filename = 'output/q98_state/q98_state.png', plot = r98, device = 'png')
write.csv(q98_plot2, paste0("output/q98_state/q98_state_", q98_n,".csv"), row.names=F)
```

```{r}
q99 <- "I.would.choose.medical.cannabis.if.it.was.a.federally.legal.treatment.option."
q99_t <- "I would choose medical cannabis if it was a federally-legal treatment option."
q99_data <- get_single_selection(data = raw_data, q.name = q99)
q99_n <- length(unique(q99_data$id))
q99_plot<- clean_single_select(q99_data)
r99 <- plot_single_select(q99_plot, q99_t, q99_n)
r99
```

```{r}
q99_plot2 <- rbind(q99_plot, q99_t)
dir.create("output/q99_cannabis_if_legal")
ggsave(filename = 'output/q99_cannabis_if_legal/q99_cannabis_if_legal.png', plot = r99, device = 'png')
write.csv(q99_plot2, paste0("output/q99_cannabis_if_legal/q99_cannabis_if_legal_", q99_n,".csv"), row.names=F)
```

```{r}
q100 <- "Do.you.think.the.VA.should.be.trained.in.medical.cannabis.and.allowed.to.recommend.it.for.veterans."
q100_t <- "Do you think the VA should be trained in medical cannabis and allowed to recommend it for veterans?"
q100_data <- get_single_selection(data = raw_data, q.name = q100)
q100_n <- length(unique(q100_data$id))
q100_plot<- clean_single_select(q100_data)
r100 <- plot_single_select(q100_plot, q100_t, q100_n)
r100
```

```{r}
q100_plot2 <- rbind(q100_plot, q100_t)
dir.create("output/q100_va_offer_cannabis")
ggsave(filename = 'output/q100_va_offer_cannabis/q100_va_offer_cannabis.png', plot = r100, device = 'png')
write.csv(q100_plot2, paste0("output/q100_va_offer_cannabis/q100_va_offer_cannabis_", q100_n,".csv"), row.names=F)
```

```{r}
q101 <- "Do.you.support.conducting.more.research.for.medical.cannabis.in.veteran.populations."
q101_t <- "Do you support conducting more research for medical cannabis in veteran populations?"
q101_data <- get_single_selection(data = raw_data, q.name = q101)
q101_n <- length(unique(q101_data$id))
q101_plot<- clean_single_select(q101_data)
r101 <- plot_single_select(q101_plot, q101_t, q101_n)
r101
```

```{r}
q101_plot2 <- rbind(q101_plot, q101_t)
dir.create("output/q101_support_med_cannabis_research")
ggsave(filename = 'output/q101_support_med_cannabis_research/q101_support_med_cannabis_research.png', plot = r101, device = 'png')
write.csv(q101_plot2, paste0("output/q101_support_med_cannabis_research/q101_support_med_cannabis_research_", q101_n,".csv"), row.names=F)
```

```{r}
q102 <- "Do.you.believe.the.VA.should.offerÂ.free..or.discounted..medical.cannabis.to.veterans.who.qualify.for.its.use."
q102_t <- "Do you believe the VA should offer free (or discounted) medical cannabis to veterans who qualify for its use?"
q102_data <- get_single_selection(data = raw_data, q.name = q102)
q102_n <- length(unique(q102_data$id))
q102_plot<- clean_single_select(q102_data)
r102 <- plot_single_select(q102_plot, q102_t, q102_n)
r102
```

```{r}
q102_plot2 <- rbind(q102_plot, q102_t)
dir.create("output/q102_cannabis_discount")
ggsave(filename = 'output/q102_cannabis_discount/q102_cannabis_discount.png', plot = r102, device = 'png')
write.csv(q102_plot2, paste0("output/q102_cannabis_discount/q102_cannabis_discount_", q102_n,".csv"), row.names=F)
```

```{r}
q103 <- 'Do.you.belong.to.any.of.the.following.veterans.support.organizations...Please.select.all.that.apply.'
q103_final_response <- "X.395"
q103_t <- "Do you belong to any of the following veterans support organizations? (Please select all that apply)"
q103_data <- get_choose_all(raw_data, q.name = q103, f.response = q103_final_response) %>%
  tidy_choose_all()
q103_n <- length(unique(q103_data$id))
q103_plot <- clean_choose_all(q103_data, q103_n)
r103 <- plot_choose_all(q103_plot, q103_t, q103_n)
r103
```

```{r}
q103_plot2 <- rbind(q103_plot, q103_t)
dir.create("output/q103_support_groups")
ggsave(filename = 'output/q103_support_groups/q103_support_groups.png', plot = r103, device = 'png')
write.csv(q103_plot2, paste0("output/q103_support_groups/q103_support_groups_", q103_n,".csv"), row.names=F)
write.csv(q103_data, 'output/q103_support_groups/q103_support_groups_ids.csv', row.names = FALSE)
```

```{r}
q104 <- "Would.you.be.willing.to.let.your.anonymous.results.be.re.shared.with.other.researchers.to.use.in.future.data.analysis.and.publications."
q104_t <- "Would you be willing to let your anonymous results be re-shared with other researchers to use in future data analysis and publications?"
q104_data <- get_single_selection(data = raw_data, q.name = q104)
q104_n <- length(unique(q104_data$id))
q104_plot <- clean_single_select(q104_data)
r104 <- plot_single_select(q104_plot, q104_t, q104_n)
r104
```

```{r}
q104_plot2 <- rbind(q104_plot, q104_t)
dir.create("output/q104_share_results")
ggsave(filename = 'output/q104_share_results/q104_share_results.png', plot = r104, device = 'png')
write.csv(q104_plot2, paste0("output/q104_share_results/q104_share_results_", q104_n,".csv"), row.names=F)
```

```{r}
print(paste("current pain avg =", q8_mean))
print(paste("usual pain avg =", q9_mean))
print(paste("least pain avg =", q10_mean))
print(paste("highest pain avg =", q11_mean))
print(paste("acceptable pain avg =", q12_mean))
print(paste("# prescriptions avg =", q21_mean))
print(paste("med $ monthly avg =", q33_mean))
print(paste("side effects cannabis v med avg =", q46_mean))
print(paste("cannabis $ wkly avg =", q53_mean))
print(paste("% purchased regulated avg =", q54_mean))
```