---
title: "q32 'Do you currently work in the cannabis industry?"
author: "David Ritter"
date: "11/7/2020"
output: html_document
runtime: shiny
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/njsurvey.csv", stringsAsFactors = FALSE)
```

```{r}
q32 <- "Do.you.currently.work.in.the.cannabis.industry."
q32_t <- "Do you currently work in the cannabis industry?"
q32_data <- get_single_selection(data = raw_data, q.name = q32)
q32_n <- length(unique(q32_data$id))
q32_plot <- clean_single_select(q32_data)
r32 <- plot_single_select(q32_plot, q32_t, q32_n)
r32
```

```{r}
row3 <- colnames(q32_plot)
q32_plot2 <- rbind(row3, q32_plot)
names(q32_plot2) <- c("q32", q32_t, paste("n = ", q32_n))
```

```{r}
dir.create("output/q32_work_cannabis_industry")
ggsave(filename = 'output/q32_work_cannabis_industry/q32_work_cannabis_industry.png', plot = r32, device = 'png')
write.csv(q32_plot2, paste0("output/q32_work_cannabis_industry/q32_work_cannabis_industry_", q32_n,".csv"), row.names=F)
```
