---
title: "q7 'Are you registered to vote in New Jersey?'"
author: "David Ritter"
date: "11/7/2020"
output: html_document
runtime: shiny
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/njsurvey.csv", stringsAsFactors = FALSE)
```

```{r}
q7 <- "Are.you.registered.to.vote.in.New.Jersey."
q7_t <- "Are you registered to vote in New Jersey?"
q7_data <- get_single_selection(data = raw_data, q.name = q7)
q7_n <- length(unique(q7_data$id))
q7_plot <- clean_single_select(q7_data)
r7 <- plot_single_select(q7_plot, q7_t, q7_n)
r7
```

```{r}
row3 <- colnames(q7_plot)
q7_plot2 <- rbind(row3, q7_plot)
names(q7_plot2) <- c("q7", q7_t, paste("n = ", q7_n))
```

```{r}
dir.create("output/q7_registered_voter")
ggsave(filename = 'output/q7_registered_voter/q7_registered_voter.png', plot = r7, device = 'png')
write.csv(q7_plot2, paste0("output/q7_registered_voter/q7_registered_voter_", q7_n,".csv"), row.names=F)
```
