---
title: "q31 'Do you face any of the following barriers for you to consume cannabis? Please select all that apply."
author: "David Ritter"
date: "11/7/2020"
output: html_document
runtime: shiny
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/njsurvey.csv", stringsAsFactors = FALSE)
```

```{r}
q31 <- "Do.you.face.any.of.the.following.barriers.for.you.to.consume.cannabis..Please.select.all.that.apply."
q31_final_response <- "X.105"
q31_t  <- "Do you face any of the following barriers
for you to consume cannabis? Please
select all that apply."
q31_data <- get_choose_all(raw_data, q.name = q31, f.response = q31_final_response) %>%
  tidy_choose_all()
q31_n <- length(unique(q31_data$id))
q31_plot <- clean_choose_all(q31_data, q31_n)
r31 <- plot_choose_all(q31_plot, q31_t, q31_n)
r31
```

```{r}
row3 <- colnames(q31_plot)
q31_plot2 <- rbind(row3, q31_plot)
names(q31_plot2) <- c("q31", q31_t, paste("n = ", q31_n))
```

```{r}
dir.create("output/q31_consumption_barriers")
ggsave(filename = 'output/q31_consumption_barriers/q31_consumption_barriers.png', plot = r31, device = 'png')
write.csv(q31_plot2, paste0("output/q31_consumption_barriers/q31_consumption_barriers_", q31_n,".csv"), row.names=F)
write.csv(q31_data, 'output/q31_consumption_barriers/q31_consumption_barriers_ids.csv', row.names = FALSE)
```
