---
title: "Q4 NJ Survey: 'In your opinion, do you think cannabis should be legal for adult (21+ years) recreational use in New Jersey?' "
author: "David Ritter"
date: "10/22/2020"
output: html_document
runtime: shiny
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/njsurvey.csv", stringsAsFactors = FALSE)
```

```{r}
q4 <- "In.your.opinion..do.you.think.cannabis.should.be.legal.for.adult..21..years..recreational.use.in.New.Jersey."
q4_t <- "In your opinion, do you think cannabis should be legal for 
adult (21+ years) recreational use in New Jersey?"
q4_data <- get_single_selection(data = raw_data, q.name = q4)
q4_n <- length(unique(q4_data$id))
q4_plot <- clean_single_select(q4_data)
r4 <- plot_single_select(q4_plot, q4_t, q4_n)
r4
```

```{r}
row3 <- colnames(q4_plot)
q4_plot2 <- rbind(row3, q4_plot)
names(q4_plot2) <- c("q4", q4_t, paste("n = ", q4_n))
```

```{r}
dir.create("output/q4_rec_cannabis_legalization")
ggsave(filename = 'output/q4_rec_cannabis_legalization/q4_rec_cannabis_legalization.png', plot = r4, device = 'png')
write.csv(q4_plot2, paste0("output/q4_rec_cannabis_legalization/q4_rec_cannabis_legalization_", q4_n,".csv"), row.names=F)
```
