---
title: "q11 'I am familiar with the history of the War on Drugs'"
author: "David Ritter"
date: "11/7/2020"
output: html_document
runtime: shiny
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/njsurvey.csv", stringsAsFactors = FALSE)
```

```{r}
q11 <- "I.am.familiar.with.the.history.of.the.War.on.Drugs."
q11_t <- "I am familiar with the history of the War on Drugs"
q11_data <- get_single_selection(data = raw_data, q.name = q11)
q11_n <- length(unique(q11_data$id))
q11_plot <- clean_single_select(q11_data)
r11 <- plot_single_select(q11_plot, q11_t, q11_n)
r11
```

```{r}
row3 <- colnames(q11_plot)
q11_plot2 <- rbind(row3, q11_plot)
names(q11_plot2) <- c("q11", q11_t, paste("n = ", q11_n))
```

```{r}
dir.create("output/q11_familiarity_war_on_drugs")
ggsave(filename = 'output/q11_familiarity_war_on_drugs/q11_familiarity_war_on_drugs.png', plot = r11, device = 'png')
write.csv(q11_plot2, paste0("output/q11_familiarity_war_on_drugs/q11_familiarity_war_on_drugs_", q11_n,".csv"), row.names=F)
```
