---
title: "q25 'Under what circumstances do you primarily use cannabis? Please select one.'"
author: "David Ritter"
date: "11/7/2020"
output: html_document
runtime: shiny
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/njsurvey.csv", stringsAsFactors = FALSE)
```

```{r}
q25 <- "Under.what.circumstances.do.you.primarily.use.cannabis..Please.select.one."
q25_t <- "Under what 
circumstances do 
you primarily 
use cannabis? 
Please select one."
q25_data <- get_single_selection(data = raw_data, q.name = q25)
q25_n <- length(unique(q25_data$id))
q25_plot <- clean_single_select(q25_data)
r25 <- plot_single_select(q25_plot, q25_t, q25_n)
r25
```

```{r}
row3 <- colnames(q25_plot)
q25_plot2 <- rbind(row3, q25_plot)
names(q25_plot2) <- c("q25", q25_t, paste("n = ", q25_n))
```

```{r}
dir.create("output/q25_consumption_circumstance")
ggsave(filename = 'output/q25_consumption_circumstance/q25_consumption_circumstance.png', plot = r25, device = 'png')
write.csv(q25_plot2, paste0("output/q25_consumption_circumstance/q25_consumption_circumstance_", q25_n,".csv"), row.names=F)
```
