---
title: "q42 'Has an immediate family member or spouse been arrested for a non-violent cannabis charge in the past?'"
author: "David Ritter"
date: "11/7/2020"
output: html_document
runtime: shiny
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/njsurvey.csv", stringsAsFactors = FALSE)
```

```{r}
q42 <- "Has.an.immediate.family.member.or.spouse.been.arrested.for.a.non.violent.cannabis.charge.in.the.past."
q42_t <- "Has an immediate family member or spouse been arrested 
for a non-violent cannabis charge in the past?"
q42_data <- get_single_selection(data = raw_data, q.name = q42)
q42_n <- length(unique(q42_data$id))
q42_plot <- clean_single_select(q42_data)
r42 <- plot_single_select(q42_plot, q42_t, q42_n)
r42
```

```{r}
row3 <- colnames(q42_plot)
q42_plot2 <- rbind(row3, q42_plot)
names(q42_plot2) <- c("q42", q42_t, paste("n = ", q42_n))
```

```{r}
dir.create("output/q42_previous_cannabis_arrest")
ggsave(filename = 'output/q42_previous_cannabis_arrest/q42_previous_cannabis_arrest.png', plot = r42, device = 'png')
write.csv(q42_plot2, paste0("output/q42_previous_cannabis_arrest/q42_previous_cannabis_arrest_", q42_n,".csv"), row.names=F)
```
