---
title: "q23 'In your own words, how do you think about social equity and restorative justice will be affected if adult use cannabis is legalized in New Jersey.'"
author: "David Ritter"
date: "11/7/2020"
output: html_document
runtime: shiny
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/njsurvey.csv", stringsAsFactors = FALSE)
```

```{r}
q23 <- "In.your.own.words..how.do.you.think.about.social.equity.and.restorative.justice.will.be.affected.if.adult.use.cannabis.is.legalized.in.New.Jersey."
q23_t <- "In your own words, how do you think social equity and restorative justice will be affected if adult use cannabis is legalized in New Jersey."
q23_data <- get_single_selection(data = raw_data, q.name = q23)
q23_n <- length(unique(q23_data$id))
q23_plot <- clean_single_select(q23_data)
r23 <- plot_single_select(q23_plot, q23_t, q23_n)
r23
```

```{r}
row3 <- colnames(q23_plot)
q23_plot2 <- rbind(row3, q23_plot)
names(q23_plot2) <- c("q23", q23_t, paste("n = ", q23_n))
```

```{r}
dir.create("output/q23_legalization_affect_equity_justice")
write.csv(q23_plot2, paste0("output/q23_legalization_affect_equity_justice/q23_legalization_affect_equity_justice_", q23_n,".csv"), row.names=F)
```
