---
title: "q39 'What is your current employment status?'"
author: "David Ritter"
date: "11/7/2020"
output: html_document
runtime: shiny
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/njsurvey.csv", stringsAsFactors = FALSE)
```

```{r}
q39 <- "What.is.your.current.employment.status."
q39_t <- "What is your current
employment status?"
q39_data <- get_single_selection(data = raw_data, q.name = q39)
q39_n <- length(unique(q39_data$id))
q39_plot <- clean_single_select(q39_data)
r39 <- plot_single_select(q39_plot, q39_t, q39_n)
r39
```

```{r}
row3 <- colnames(q39_plot)
q39_plot2 <- rbind(row3, q39_plot)
names(q39_plot2) <- c("q39", q39_t, paste("n = ", q39_n))
```

```{r}
dir.create("output/q39_employment")
ggsave(filename = 'output/q39_employment/q39_employment.png', plot = r39, device = 'png')
write.csv(q39_plot2, paste0("output/q39_employment/q39_employment_", q39_n,".csv"), row.names=F)
```
