---
title: "q14 q14 'How many milliliters (mL) of tincture/oil/alcohol/glycerine etc. are you using per week? Note (30mL) = 1oz"
author: "David Ritter"
date: "6/24/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q14 <- 'How.manyÂ.mL.ofÂ.cannabisÂ.tincture..oil..alcohol..glycerine..etc..do.you.consume.a.week.'
q14_final_response <- "X.98"
q14_t <- "q14 'How many milliliters (mL) of tincture/oil/alcohol/glycerine etc. are you using per week? Note (30mL) = 1oz"
q14_data <- get_choose_all(raw_data, q.name = q14, f.response = q14_final_response)
dir.create("output/q14_tinctures_wkly")
```

```{r}
q14_data1 <- get_single_selection_3(q14_data, "Tinctures") %>%
  filter(response != "") %>%
  clean_single_select()
q14_n1 <- tally(q14_data1, count)
q14_t1 <- "Tinctures"
r1 <- plot_single_select(q14_data1, q14_t1, q14_n1)
r1
```

```{r}
ggsave(filename = "output/q14_tinctures_wkly/q14_tinctures_wkly.png", plot = r1, device = 'png')
write.csv(q14_data1, paste0("output/q14_tinctures_wkly/q14_tinctures_wkly_", q14_n1, ".csv"), row.names = FALSE)
```

