---
title: "q44 How important to you are consumer reviews in determining which retail establishments or dispensary to use?"
author: "David Ritter"
date: "6/24/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data_occp <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q44 <- "How.important.to.you.are.consumer.reviews.in.determining.which.retail.establishment.or.dispensary.to.use."
q44_t <- "How important to you are consumer reviews in determining which retail establishments or dispensary to use?"
q44_data <- get_single_selection(data = raw_data_occp, q.name = q44)
q44_n <- length(unique(q44_data$id))
q44_plot <- clean_single_select(q44_data)
r44 <- plot_single_select(q44_plot, q44_t, q44_n)
r44
```

```{r}
row3 <- colnames(q44_plot)
q44_plot2 <- rbind(row3, q44_plot)
names(q44_plot2) <- c("q44", q44_t, paste("n = ", q44_n))
```

```{r}
dir.create("output/q44_consumer_review_importance")
ggsave(filename = 'output/q44_consumer_review_importance/q44_consumer_review_importance.png', plot = r44, device = 'png')
write.csv(q44_plot2, paste0("output/q44_consumer_review_importance/q44_consumer_review_importance_", q44_n,".csv"), row.names=F)
```
