---
title: "Q5 Top Condition Cannabis (OCCP)"
author: "DJ"
date: "June 26, 2019"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
# Load libraries
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
# Read in raw data from the OCCP survey. These are the files downloaded from survey monkey saved as a .csv
raw_data_occp <- read.csv("data/occp_ma_text.csv", stringsAsFactors = FALSE)
```

```{r}
# Pull out all responses for Q5 (a single selection question) combine, then determine 'question n'
Q5 <- "WhatÂ.is.the.primary.health.condition.for.which.you.find.cannabis.to.be.helpful.or.most.impactful..Please.select.one."

Q5_all <- get_single_selection(data = raw_data_occp, q.name = Q5)

number_of_people <- length(unique(Q5_all$id))
```

```{r}
# Manipulate data into a graphable format
Q5_plot <- 
  Q5_all %>%
  group_by(response) %>%
  summarize(count = n()) %>%
  mutate(percent_all = count / sum(count)) %>%
  mutate(percent_responded = count / number_of_people)
```

```{r}
# Plot with percents and response counts
r <- 
  ggplot(Q5_plot, aes(x = reorder(response, count), y = percent_responded)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  geom_text(aes(label= paste(round(percent_responded, 2), count, sep = "***")))

r
```

```{r}
# Save graph as PNG, plot data as csv, and all question data including response IDs as csv (save question n and N at end of plot file as "_x.x")
ggsave(filename = 'bask_q5_top_condition_cannabis.png', plot = r, device = 'png')

write.csv(Q5_plot, 'bask_q5_top_condition_cannabis_900.900.csv', row.names = FALSE)

write.csv(Q5_all, 'bask_q5_top_condition_cannabis_ids.csv', row.names = FALSE)
```

```{r}
#OPTIONAL Filter for specific responses and create a file to use for a different question
Q5_Chronic_Pain <- Q5_all %>% 
  filter(response %in% c("Chronic pain"))
```

```{r}
Q5_Anxiety <- Q5_all %>% 
  filter(response %in% c("Anxiety"))
```

```{r}
Q5_Depression <- Q5_all %>% 
  filter(response %in% c("Depression/mood"))
```