---
title: "q50 In the last 30 days, how often have you seen or heard advertising for cannabis products or stores in your community, including TV, radio, signs, billboards, newspapers, pamphlets, or street side marketing?"
author: "David Ritter"
date: "6/24/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data_occp <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q50 <- "In.the.last.30.days..how.often.have.you.seen.or.heard.advertising.for.cannabis.products.or.stores.in.your.community..include.TV..radio..signs..billboards..newspapers..pamphlets..or.street.side.marketing.."
q50_t <- "In the last 30 days, how often have you seen or heard advertising for cannabis products or stores in your community, including TV, radio, signs, billboards, newspapers, pamphlets, or street side marketing?"
q50_data <- get_single_selection(data = raw_data_occp, q.name = q50)
q50_n <- length(unique(q50_data$id))
q50_plot <- clean_single_select(q50_data)
r50 <- plot_single_select(q50_plot, q50_t, q50_n)
r50
```

```{r}
row3 <- colnames(q50_plot)
q50_plot2 <- rbind(row3, q50_plot)
names(q50_plot2) <- c("q50", q50_t, paste("n = ", q50_n))
```

```{r}
dir.create("output/q50_advertising_last_30days")
ggsave(filename = 'output/q50_advertising_last_30days/q50_advertising_last_30days.png', plot = r50, device = 'png')
write.csv(q50_plot2, paste0("output/q50_advertising_last_30days/q50_advertising_last_30days_", q50_n,".csv"), row.names=F)
```


