---
title: "q19 What.percent.of.your.monthly.cannabis.purchases.are.through.regulated.sources...dispensaries..caregivers..etc."
author: "David Ritter"
date: "6/24/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q19 <- "What.percent.of.your.monthly.cannabis.purchases.are.through.regulated.sources...dispensaries..caregivers..etc."
q19_t <- "What percent of your monthly cannabis purchases are through regulated sources (dispensaries, caregivers, etc.)"
q19_data <- get_single_selection_0(data = raw_data, q.name = q19) %>%
  filter(response != "")
q19_n <- length(unique(q19_data$id))
q19_mean_data <- as.numeric(as.character(q19_data$response))
q19_mean <- mean(q19_mean_data) %>%
  round(3) %>%
  print()
q19_plot<- clean_single_select(q19_data)
r19 <- plot_single_select_0(q19_plot, q19_t, q19_n, q19_mean)
r19
```

```{r}
row3 <- colnames(q19_plot)
q19_plot2 <- rbind(row3, q19_plot)
names(q19_plot2) <- c("q19", q19_t, paste("n = ", q19_n, paste(" avg = ", q19_mean)))
```

```{r}
dir.create("output/q19_regulated_purchases")
ggsave(filename = 'output/q19_regulated_purchases/q19_regulated_purchases.png', plot = r19, device = 'png')
write.csv(q19_plot2, paste0("output/q19_regulated_purchases/q19_regulated_purchases_", q19_n,".csv"), row.names=F)
write.csv(q19_data, 'output/q19_regulated_purchases/q19_regulated_purchases_ids.csv', row.names = FALSE)
```
