---
title: "q30 'What are some barriers for you consuming cannabis? Please select all that apply.' (OCCP)"
author: "DJ"
date: "November 19, 2019"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
# Load libraries
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
# Read in raw data from the OCCP survey. These are the files downloaded from survey monkey saved as a .csv
raw_data_occp <- read.csv("data/occp.csv", stringsAsFactors = FALSE)
```

```{r}
# Pull out all responses for q30 (a choose all question), combine, turn into a tidy data format for further processing then determine 'question n'
q30 <- 'What.are.some.barriers.for.you.consuming.cannabis..Please.select.all.that.apply.'
q30_final_response <- "X.151"

q30_all <- get_choose_all(raw_data_occp, q.name = q30, f.response = q30_final_response)
q30_clean <- tidy_choose_all(q30_all)

number_of_people <- length(unique(q30_all$id))
```

```{r}
# Manipulate data into a graphable format
q30_plot <-
  q30_clean %>%
  group_by(chosen) %>%
  summarize(count = n()) %>%
  mutate(percent_all = count / sum(count)) %>%
  mutate(percent_responded = count / number_of_people)
```

```{r}
# Plot with percents and response counts
r <- 
  ggplot(q30_plot, aes(x = reorder(chosen, count), y = percent_responded)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  geom_text(aes(label= paste(round(percent_responded,2), count, sep = "***")))

r
```

```{r}
# Save graph as PNG, plot data as csv, and all question data including response IDs as csv (save question n and N at end of plot file as "_x.x")
ggsave(filename = 'q30_barriers.png', plot = r, device = 'png')

write.csv(q30_plot, 'q30_barriers_900.csv', row.names = FALSE)

write.csv(q30_clean, 'q30_barriers_ids.csv', row.names = FALSE)
```