---
title: "q4 'How do you use cannabis? Please select all that apply.' (OCCP)"
author: "DJ"
date: "October 21, 2019"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
# Load libraries
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
# Read in raw data from the OCCP survey. These are the files downloaded from survey monkey saved as a .csv
raw_data_occp <- read.csv("data/occp.csv", stringsAsFactors = FALSE)
```

```{r}
# Pull out all responses for q4 (a choose all question), combine, turn into a tidy data format for further processing then determine 'question n'
q4 <- "How.do.you.use.cannabis..Please.select.all.that.apply."
q4_final_response <- "X.3"

q4_all <- get_choose_all(raw_data_occp, q.name = q4, f.response = q4_final_response) %>%
  tidy_choose_all()

q4_n <- length(unique(q4_all$id))
```


```{r}
rec_ids <- q4_all %>% 
  filter(chosen %in% c("Recreational user"))

#q4_rec <- q4_all %>%
  #inner_join(rec_ids, by = "id")

#rec_user <- length(unique(rec_ids$id))

```

```{r}
med_ids <- q4_all %>% 
  filter(chosen %in% c("Medically indicated, recommended by a licensed clinical provider"))
  
#"Medically indicated, self-prescribed""

  #inner_join(med_ids, by = "id")

med_user <- length(unique(med_ids$id))
```

```{r}
# Manipulate data into a graphable format
q4_plot <-
  q4_all %>%
  group_by(chosen) %>%
  summarize(count = n()) %>%
  mutate(percent_all = count / sum(count)) %>%
  mutate(percent_responded = count / q4_n)
```

```{r}
# Plot with percents and response counts
r <- 
  ggplot(q4_plot, aes(x = reorder(chosen, count), y = percent_responded)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  geom_text(aes(label= paste(round(percent_responded,2), count, sep = "***")))

r
```

```{r}
# Save graph as PNG, plot data as csv, and all question data including response IDs as csv (save question n and N at end of plot file as "_x.x")
ggsave(filename = 'q4_cannabis_use_type.png', plot = r, device = 'png')

write.csv(q4_plot, 'q4_cannabis_use_type_906.csv', row.names = FALSE)

write.csv(q4_all, 'q4_cannabis_use_type_ids.csv', row.names = FALSE)
```