---
title: "q18 'On average, how much do you spend (in US dollar) on consumable cannabis products each week?' (OCCP)"
author: "David Ritter"
date: "November 19, 2019"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
# Load libraries
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
# Read in raw data from the OCCP survey. These are the files downloaded from survey monkey saved as a .csv
raw_data_occp <- read.csv("data/occp.csv", stringsAsFactors = FALSE)
```

```{r}
# Pull out all responses for q18 (a single selection question) combine, then determine 'question n'
q18 <- "On.average..how.much.do.you.spend..in.US.dollar..on.consumable.cannabis.products.each.week."

q18_all <- get_single_selection(data = raw_data_occp, q.name = q18)

q18_respondents <- length(unique(q18_all$id))
```

```{r}
# Manipulate data into a graphable format (SKIP IF FILTERING)
q18_plot <- 
  q18_all %>%
  group_by(response) %>%
  summarize(count = n()) %>%
  mutate(percent_all = count / sum(count)) %>%
  mutate(percent_responded = count / q18_respondents)
```

```{r}
# Plot with percents and response counts (SKIP IF FILTERING)
r <- 
  ggplot(q18_plot, aes(x = reorder(response, count), y = percent_responded)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  geom_text(aes(label= paste(round(percent_responded, 2), count, sep = "***")))

r
```

```{r}
# Save graph as PNG, plot data as csv, and all question data including response IDs as csv (save question n and N at end of plot file as "_x.x") (SKIP IF)
ggsave(filename = 'q18_cannabis_cost.png', plot = r, device = 'png')

write.csv(q18_plot, 'q18_cannabis_cost_852.csv', row.names = FALSE)

write.csv(q18_all, 'q18_cannabis_cost_ids.csv', row.names = FALSE)
```


```{r}
# PATH P OPTIONAL FILTERING STEP. Determine Cannabis spending of those with "Chronic pain" and determine question 'n'
q18_q5_P <- 
  q18_all %>%
  inner_join(q5_Chronic_Pain, by = "id")

q18_q5_P_R <- length(unique(q18_q5_P$id))
```

```{r}
# PATH P OPTIONAL FILTERING STEP Manipulate data into a graphable format for "Chronic pain"
q18_q5_P_G <- 
  q18_q5_P %>%
  group_by(response.y) %>%
  summarize(count = n()) %>%
  mutate(percent_all = count / sum(count)) %>%
  mutate(percent_responded = count / number_of_people)
```

```{r}
# PATH P OPTIONAL FILTERING STEP Plot with percents and response counts for "Chronic pain"
p <- 
  ggplot(q18_q5_P, aes(x = reorder(response.y, count), y = percent_responded)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  geom_text(aes(label= paste(round(percent_responded, 2), count, sep = "***")))

p
```

```{r}
# PATH P OPTIONAL FILTERING PATH Savegraph as PNG, plot data as csv, and all question data including response IDs as csv (save question n and N at end of plot file as "_x.x") for "Chronic Pain"
ggsave(filename = 'q18_q5_Chronic_Pain.png', plot = p, device = 'png')

write.csv(q18_q5_P, 'q18_q5_Chronic_Pain_293.csv', row.names = FALSE)

write.csv(q18_q5_P_G, 'q18_q5_Chronic_Pain_IDS.csv', row.names = FALSE)
```

```{r}
# PATH A OPTIONAL FILTERING STEP. Determine Cannabis spending of those with "Anxiety" and determine question 'n'
q18_q5_A <- 
  q18_all %>%
  inner_join(q5_Anxiety, by = "id")

q18_q5_A_R <- length(unique(q18_q5_A$id))
```

```{r}
# PATH A OPTIONAL FILTERING STEP Manipulate data into a graphable format for "Anxiety"
q18_q5_A_G <- 
  q18_q5_A %>%
  group_by(response) %>%
  summarize(count = n()) %>%
  mutate(percent_all = count / sum(count)) %>%
  mutate(percent_responded = count / number_of_people)
```

```{r}
# PATH A OPTIONAL FILTERING STEP Plot with percents and response counts for "Anxiety"
a <- 
  ggplot(q18_q5_A_G, aes(x = reorder(response, count), y = percent_responded)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  geom_text(aes(label= paste(round(percent_responded, 2), count, sep = "***")))

a
```

```{r}
# PATH A OPTIONAL FILTERING PATH A Save graph as PNG, plot data as csv, and all question data including response IDs as csv (save question n and N at end of plot file as "_x.x") for "Anxiety"
ggsave(filename = 'q18_q5_Anxiety.png', plot = a, device = 'png')

write.csv(q18_q5_A, 'q18_q5_Anxiety_206.csv', row.names = FALSE)

write.csv(q18_q5_A_G, 'q18_q5_Anxiety_IDS.csv', row.names = FALSE)
```

```{r}
# PATH D OPTIONAL FILTERING STEP. Determine Cannabis spending of those with "Depression/mood" and determine question 'n'
q18_q5_D <- 
  q18_all %>%
  inner_join(q5_Depression, by = "id")

q18_q5_D_R <- length(unique(q18_q5_D$id))
```

```{r}
# PATH D OPTIONAL FILTERING STEP Manipulate data into a graphable format for "Depression/mood
q18_q5_D_G <- 
  q18_q5_D %>%
  group_by(response) %>%
  summarize(count = n()) %>%
  mutate(percent_all = count / sum(count)) %>%
  mutate(percent_responded = count / number_of_people)
```

```{r}
# PATH D OPTIONAL FILTERING STEP Plot with percents and response counts for "Depression/mood"
d <- 
  ggplot(q18_q5_D_G, aes(x = reorder(response, count), y = percent_responded)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  geom_text(aes(label= paste(round(percent_responded, 2), count, sep = "***")))

d
```

```{r}
# PATH D OPTIONAL FILTERING PATH D Save graph as PNG, plot data as csv, and all question data including response IDs as csv (save question n and N at end of plot file as "_x.x") for "Anxiety"
ggsave(filename = 'q18_q5_Depression.png', plot = d, device = 'png')

write.csv(q18_q5_D, 'q18_q5_Depression_111.csv', row.names = FALSE)

write.csv(q18_q5_D_G, 'q18_q5_Depression_IDS.csv', row.names = FALSE)
```




