---
title: "q6 'What symptoms for the primary condition do you use cannabis to treat? Please select all that apply.' (OCCP)"
author: "David Ritter"
date: "June 23, 2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data_occp <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q6 <- 'What.symptoms.for.the.primary.condition.do.you.use.cannabis.to.treat..Please.select.all.that.apply.'
q6_final_response <- "X.22"
q6_t <- "What symptoms for the primary condition do you use cannabis to treat? Please select all that apply."
q6_data <- get_choose_all(raw_data_occp, q.name = q6, f.response = q6_final_response) %>%
  tidy_choose_all()
q6_n <- length(unique(q6_data$id))
q6_plot <- clean_choose_all(q6_data, q6_n)
r6 <- plot_choose_all(q6_plot, q6_t, q6_n)
r6
```

```{r}
row3 <- colnames(q6_plot)
q6_plot2 <- rbind(row3, q6_plot)
names(q6_plot2) <- c("q6", q6_t, paste("n = ", q6_n))
```

```{r}
dir.create("output/q6_symptoms_cannabis_helps")
ggsave(filename = 'output/q6_symptoms_cannabis_helps/q6_symptoms_cannabis_helps.png', plot = r6, device = 'png')
write.csv(q6_plot2, paste0("output/q6_symptoms_cannabis_helps/q6_symptoms_cannabis_helps_", q6_n,".csv"), row.names=F)
write.csv(q6_data, 'output/q6_symptoms_cannabis_helps/q6_symptoms_cannabis_helps_ids.csv', row.names = FALSE)
```

