---
title: "q55 'What is your age in years?' OCCP"
author: "David Ritter"
date: "June 24, 2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data_occp <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q55 <- "What.is.your.age..in.years..Â."
q55_t <- "What is your age in years?"
q55_data <- get_single_selection_0(data = raw_data_occp, q.name = q55) %>%
  filter(response != "")
q55_n <- length(unique(q55_data$id))
q55_mean_data <- as.numeric(as.character(q55_data$response))
q55_mean <- mean(q55_mean_data) %>%
  round(3) %>%
  print()
q55_plot <- clean_single_select(q55_data)
r55 <- plot_single_select_0(q55_plot, q55_t, q55_n, q55_mean)
r55
```

```{r}
row3 <- colnames(q55_plot)
q55_plot2 <- rbind(row3, q55_plot)
names(q55_plot2) <- c("q55", q55_t, paste("n = ", q55_n, paste(" avg = ", q55_mean)))
```

```{r}
dir.create("output/q55_age")
ggsave(filename = 'output/q55_age/q55_age.png', plot = r55, device = 'png')
write.csv(q55_plot2, paste0("output/q55_age/q55_age_", q55_n,".csv"), row.names=F)
write.csv(q55_data, 'output/q55_age/q55_age_ids.csv', row.names = FALSE)
```

