---
title: q50 'What is your top preferred method (that is, favorite) of using cannabis?
  (Please select one)' occp
author: "DJ"
date: "October 30, 2019"
output: html_document
runtime: shiny
---


```{r, message = FALSE}
# Load libraries
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
# Read in raw data from the OCCP survey. These are the files downloaded from survey monkey saved as a .csv
raw_data_occp <- read.csv("data/occp.csv", stringsAsFactors = FALSE)
```

```{r}
# Pull out all responses for q50 (a choose all question), combine, turn into a tidy data format for further processing then determine 'question n'
q50 <- "What.are.you.looking.for.in.cannabis.products..Please.select.all.that.apply."

q50_final_response <- "X.139"

q50_all <- get_choose_all(raw_data_occp, q.name = q50, f.response = q50_final_response) %>%
  tidy_choose_all()
  
q50_n <- length(unique(q50_all$id))
```

```{r}
# Manipulate data into a graphable format
q50_plot <-
  q50_all %>%
  group_by(chosen) %>%
  summarize(count = n()) %>%
  mutate(percent_all = count / sum(count)) %>%
  mutate(percent_responded = count / q50_n)
```

```{r}
# Plot with percents and response counts
r <- 
  ggplot(q50_plot, aes(x = reorder(chosen, count), y = percent_responded)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  geom_text(aes(label= paste(round(percent_responded,2), count, sep = "***")))

r
```

```{r}
# Save graph as PNG, plot data as csv, and all question data including response IDs as csv (save question n and N at end of plot file as "_x.x")
ggsave(filename = 'q22_seek_cannabis_quality.png', plot = r, device = 'png')

write.csv(q50_plot, 'q22_seek_cannabis_quality_1283.csv', row.names = FALSE)

write.csv(q50_all, 'q22_seek_cannabis_quality_ids.csv', row.names = FALSE)
```
