---
title: "q34 How.important.is.your.relationship.with.your.budtender.patient.advocate.in.determining.which.product.retail.establishment.or.dispensary.to.use."
author: "David Ritter"
date: "6/24/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data_occp <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q34 <- "How.important.is.your.relationship.with.your.budtender.patient.advocate.in.determining.which.product.retail.establishment.or.dispensary.to.use."
q34_t <- "How important is your relationship with your budtender/patient advocate in determining which product, retail establishment or dispensary to use?"
q34_data <- get_single_selection(data = raw_data_occp, q.name = q34)
q34_n <- length(unique(q34_data$id))
q34_plot <- clean_single_select(q34_data)
r34 <- plot_single_select(q34_plot, q34_t, q34_n)
r34
```

```{r}
row3 <- colnames(q34_plot)
q34_plot2 <- rbind(row3, q34_plot)
names(q34_plot2) <- c("q34", q34_t, paste("n = ", q34_n))
```

```{r}
dir.create("output/q34_budtender_relation_importance")
ggsave(filename = 'output/q34_budtender_relation_importance/q34_budtender_relation_importance.png', plot = r34, device = 'png')
write.csv(q34_plot2, paste0("output/q34_budtender_relation_importance/q34_budtender_relation_importance_", q34_n,".csv"), row.names=F)
```
