---
title: "q36 What.is.your.level.of.confidence.in.the.accuracy.of.strain.information..strain.genetics..across.retail.establishments.Â."
author: "David Ritter"
date: "6/24/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data_occp <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q36 <- "What.is.your.level.of.confidence.in.the.accuracy.of.strain.information..strain.genetics..across.retail.establishments.Â."
q36_t <- "What is your level of confidence in the accuracy of strain information (strain genetics) across retail establishments?"
q36_data <- get_single_selection(data = raw_data_occp, q.name = q36)
q36_n <- length(unique(q36_data$id))
q36_plot <- clean_single_select(q36_data)
r36 <- plot_single_select(q36_plot, q36_t, q36_n)
r36
```

```{r}
row3 <- colnames(q36_plot)
q36_plot2 <- rbind(row3, q36_plot)
names(q36_plot2) <- c("q36", q36_t, paste("n = ", q36_n))
```

```{r}
dir.create("output/q36_info_confidence")
ggsave(filename = 'output/q36_info_confidence/q36_info_confidence.png', plot = r36, device = 'png')
write.csv(q36_plot2, paste0("output/q36_info_confidence/q36_info_confidence_", q36_n,".csv"), row.names=F)
```

