---
title: "q101 'Do you support conducting more research for medical cannabis in veteran populations?'"
author: "David Ritter"
date: "2/28/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q101 <- "Do.you.support.conducting.more.research.for.medical.cannabis.in.veteran.populations."
q101_t <- "Do you support conducting more research for medical cannabis in veteran populations?"
q101_data <- get_single_selection(data = raw_data, q.name = q101)
q101_n <- length(unique(q101_data$id))
q101_plot<- clean_single_select(q101_data)
r101 <- plot_single_select(q101_plot, q101_t, q101_n)
r101
```

```{r}
row3 <- colnames(q101_plot)
q101_plot2 <- rbind(row3, q101_plot)
names(q101_plot2) <- c("q101", q101_t, paste("n = ", q101_n))
```

```{r}
dir.create("output/q101_support_med_cannabis_research")
ggsave(filename = 'output/q101_support_med_cannabis_research/q101_support_med_cannabis_research.png', plot = r101, device = 'png')
write.csv(q101_plot2, paste0("output/q101_support_med_cannabis_research/q101_support_med_cannabis_research_", q101_n,".csv"), row.names=F)
```







```{r}
qf_data <- q_data %>%
  filter(response == "Response text")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")
qf_n <- length(unique(qf_all_data$id))
q_plot <- clean_single_select_y(qf_all_data)
r <- plot_single_select_y(q_plot)
r
```

```{r}
q_plot2 <- rbind(q_plot, t)
dir.create("output/q101_support_med_cannabis_research")
ggsave(filename = 'output/q101_support_med_cannabis_research/q101_support_med_cannabis_research.png', plot = r, device = 'png')
write.csv(q_plot2, paste0("output/q101_support_med_cannabis_research/q101_support_med_cannabis_research_", qf_n,".csv"), row.names=F)
```
