---
title: "q102 'Do you believe the VA should offer free (or discounted) medical cannabis to veterans who qualify for its use?'"
author: "David Ritter"
date: "2/28/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q102 <- "Do.you.believe.the.VA.should.offerÂ.free..or.discounted..medical.cannabis.to.veterans.who.qualify.for.its.use."
q102_t <- "Do you believe the VA should offer free (or discounted) medical cannabis to veterans who qualify for its use?"
q102_data <- get_single_selection(data = raw_data, q.name = q102)
q102_n <- length(unique(q102_data$id))
q102_plot<- clean_single_select(q102_data)
r102 <- plot_single_select(q102_plot, q102_t, q102_n)
r102
```

```{r}
row3 <- colnames(q102_plot)
q102_plot2 <- rbind(row3, q102_plot)
names(q102_plot2) <- c("q102", q102_t, paste("n = ", q102_n))
```

```{r}
dir.create("output/q102_cannabis_discount")
ggsave(filename = 'output/q102_cannabis_discount/q102_cannabis_discount.png', plot = r102, device = 'png')
write.csv(q102_plot2, paste0("output/q102_cannabis_discount/q102_cannabis_discount_", q102_n,".csv"), row.names=F)
```







```{r}
qf_data <- q_data %>%
  filter(response == "Response text")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")
qf_n <- length(unique(qf_all_data$id))
q_plot <- clean_single_select_y(qf_all_data)
r <- plot_single_select_y(q_plot)
r
```

```{r}
q_plot2 <- rbind(q_plot, t)
dir.create("output/q102_cannabis_discount")
ggsave(filename = 'output/q102_cannabis_discount/q102_cannabis_discount.png', plot = r, device = 'png')
write.csv(q_plot2, paste0("output/q102_cannabis_discount/q102_cannabis_discount_", qf_n,".csv"), row.names=F)
```

