---
title: "q103 'Do you belong to any of the following veterans support organizations? (Please select all that apply)'"
author: "David Ritter"
date: "2/28/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q103 <- 'Do.you.belong.to.any.of.the.following.veterans.support.organizations...Please.select.all.that.apply.'
q103_final_response <- "X.395"
q103_t <- "Do you belong to any of the following veterans support organizations? (Please select all that apply)"
q103_data <- get_choose_all(raw_data, q.name = q103, f.response = q103_final_response) %>%
  tidy_choose_all()
q103_n <- length(unique(q103_data$id))
q103_plot <- clean_choose_all(q103_data, q103_n)
r103 <- plot_choose_all(q103_plot, q103_t, q103_n)
r103
```

```{r}
row3 <- colnames(q103_plot)
q103_plot2 <- rbind(row3, q103_plot)
names(q103_plot2) <- c("q103", q103_t, paste("n = ", q103_n))
```

```{r}
dir.create("output/q103_support_groups")
ggsave(filename = 'output/q103_support_groups/q103_support_groups.png', plot = r103, device = 'png')
write.csv(q103_plot2, paste0("output/q103_support_groups/q103_support_groups_", q103_n,".csv"), row.names=F)
write.csv(q103_data, 'output/q103_support_groups/q103_support_groups_ids.csv', row.names = FALSE)
```







```{r}
qf_data <- q_data %>%
  filter(chosen == "Response text")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")

qf_n <- length(unique(qf_all_data$id))
```

```{r}
q_plot <- clean_choose_all_f(qf_all_data)
r <- plot_choose_all_f(q_plot)
r
```

```{r}
q_plot2 <- rbind(q_plot, t)
dir.create("output/q103_support_groups")
ggsave(filename = 'output/q103_support_groups/q103_support_groups.png', plot = r, device = 'png')
write.csv(q_plot2, paste0("output/q103_support_groups/q103_support_groups_", qf_n,".csv"), row.names=F)
write.csv(qf_all_data, 'output/q103_support_groups/q103_support_groups_ids.csv', row.names = FALSE)
```
