---
title: "q104 'Would you be willing to let your anonymous results be re-shared with other researchers to use in future data analysis and publications?'"
author: "David Ritter"
date: "2/25/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q104 <- "Would.you.be.willing.to.let.your.anonymous.results.be.re.shared.with.other.researchers.to.use.in.future.data.analysis.and.publications."
q104_t <- "Would you be willing to let your anonymous results be re-shared with other researchers to use in future data analysis and publications?"
q104_data <- get_single_selection(data = raw_data, q.name = q104)
q104_n <- length(unique(q104_data$id))
q104_plot <- clean_single_select(q104_data)
r104 <- plot_single_select(q104_plot, q104_t, q104_n)
r104
```

```{r}
q104_plot2 <- rbind(q104_plot, q104_t)
dir.create("output/q104_share_results")
ggsave(filename = 'output/q104_share_results/q104_share_results.png', plot = r104, device = 'png')
write.csv(q104_plot2, paste0("output/q104_share_results/q104_share_results_", q104_n,".csv"), row.names=F)
```




```{r}
qf_data <- q_data %>%
  filter(response == "Response text")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")
qf_n <- length(unique(qf_all_data$id))
q_plot <- clean_single_select_f(qf_all_data)
r <- plot_single_select_f(q_plot)
r
```

```{r}
q_plot2 <- rbind(q_plot, t)
dir.create("output/q104_share_results")
ggsave(filename = 'output/q104_share_results/q104_share_results.png', plot = r, device = 'png')
write.csv(q_plot2, paste0("output/q104_share_results/q104_share_results_", qf_n,".csv"), row.names=F)
```