---
title: "Q14 Pain Effects"
author: "DJ"
date: "May 23, 2019"
output: html_document
runtime: shiny
---
---
title: "Q14 Pain Locations"
author: "DJ"
date: "May 23, 2019"
output: html_document
runtime: shiny
---

---
title: "Q5_Common_Conditions_X"
author: "DJ"
date: "April 24, 2019"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
# Read in raw data. These are the files downloaded from survey monkey saved as a .csv

raw_data_general <- read.csv("data/general_text.csv", stringsAsFactors = FALSE)
raw_data_botanist <- read.csv("data/botanist_text.csv", stringsAsFactors = FALSE)
raw_data_bask <- read.csv("data/bask_text.csv", stringsAsFactors = FALSE)
raw_data_healing_rose <- read.csv("data/healing_rose_text.csv", stringsAsFactors = FALSE)
```

```{r}
# Pull out all responses for Q5 (a choose all question), combine, and turn
# into a tidy data format for further processing

Q5 <- 'What.are.the.effects.of.your.pain...Please.select.all.that.apply.'
Q5_final_response <- "X.85"

Q5_general <- get_choose_all(raw_data_general, q.name = Q5, f.response = Q5_final_response)
Q5_bask <- get_choose_all(raw_data_bask, q.name = Q5, f.response = Q5_final_response)
Q5_botanist <- get_choose_all(raw_data_botanist, q.name = Q5, f.response = Q5_final_response)
Q5_healing_rose <- get_choose_all(raw_data_healing_rose, q.name = Q5, f.response = Q5_final_response)

Q5_all <- 
  rbind(Q5_general, Q5_bask, Q5_botanist) %>%
  tidy_choose_all()


number_of_people <- length(unique(Q5_all$id))

```

```{r}

for_plot <-
  Q5_all %>%
  group_by(chosen) %>%
  summarize(count = n()) %>%
  mutate(percent_all = count / sum(count)) %>%
  mutate(percent_responded = count / number_of_people)

r <- 
  ggplot(for_plot, aes(x = reorder(chosen, count), y = percent_responded)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  geom_text(aes(label= paste(round(percent_responded,2), count, sep = "***")))

r

```

```{r}

ggsave(filename = 'Q14_Pain_Effects.png', plot = r, device = 'png')

write.csv(for_plot, 'Q14_Pain_Effects_74.167.csv', row.names = FALSE)

write.csv(Q5_all, 'Q14_Responses_ID.csv', row.names = FALSE)

```
