---
title: "q15 Over the last 2 weeks, how often have you been bothered by any of the following problems? (anxiety scales)"
author: "David Ritter"
date: "2/25/2020"
output: html_document
runtime: shiny
---
 
```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q15 <- "Over.the.last.2.weeks..how.often.have.you.been.bothered.by.any.of.the.following.problems."
q15_final_response <- "X.91"
q15_t <- "Over the last 2 weeks, how often have you been bothered by any of the following problems?"
q15_data <- get_choose_all(raw_data, q.name = q15, f.response = q15_final_response)
dir.create("output/q15_anxiety")
```

```{r}
write.csv(q15_data, 'output/q15_anxiety/q15_anxiety_scales_data.csv', row.names = FALSE)
```

```{r}
q15_data1 <- get_single_selection_3(q15_data, "Feeling nervous, anxious, or on edge") %>%
  filter(response != "") %>%
  clean_single_select()
q15_n1 <- tally(q15_data1, count)
q15_t1 <- "Feeling nervous, anxious, or on edge"
q15_r1 <- plot_single_select(q15_data1, q15_t1, q15_n1)
q15_r1
```

```{r}
ggsave(filename = "output/q15_anxiety/q15_anxiety.png", plot = q15_r1, device = 'png')
write.csv(q15_data1, paste0("output/q15_anxiety/q15_anxiety_", q15_n1, ".csv"), row.names = FALSE)
```

```{r}
q15_data2 <- get_single_selection_3(q15_data, "Not being able to stop or control worrying") %>%
  filter(response != "") %>%
  clean_single_select()
q15_t2 <- "Not being able to stop or control worrying"
q15_n2 <- tally(q15_data2, count)
q15_r2 <- plot_single_select(q15_data2, q15_t2, q15_n2)
q15_r2
```

```{r}
ggsave(filename = "output/q15_anxiety/q15_control.png", plot = q15_r2, device = 'png')
write.csv(q15_data2, paste0("output/q15_anxiety/q15_control_", q15_n2, ".csv"), row.names = FALSE)
```

```{r}
q15_data3 <- get_single_selection_3(q15_data, "Worrying too much about different things") %>%
  filter(response != "") %>%
  clean_single_select()
q15_n3 <- tally(q15_data3, count)
q15_t3 <- "Worrying too much about different things"
q15_r3 <- plot_single_select(q15_data3, q15_t3, q15_n3)
q15_r3
```

```{r}
ggsave(filename = "output/q15_anxiety/q15_worry.png", plot = q15_r3, device = 'png')
write.csv(q15_data3, paste0("output/q15_anxiety/q15_worry_", q15_n3, ".csv"), row.names = FALSE)
```

```{r}
q15_data4 <- get_single_selection_3(q15_data, "Trouble relaxing") %>%
  filter(response != "") %>%
  clean_single_select()
q15_n4 <- tally(q15_data4, count)
q15_t4 <- "Trouble relaxing"
q15_r4 <- plot_single_select(q15_data4, q15_t4, q15_n4)
q15_r4
```

```{r}
ggsave(filename = "output/q15_anxiety/q15_relax.png", plot = q15_r4, device = 'png')
write.csv(q15_data4, paste0("output/q15_anxiety/q15_relax_", q15_n4, ".csv"), row.names = FALSE)
```

```{r}
q15_data5 <- get_single_selection_3(q15_data, "Being so restless that it is hard to sit still") %>%
  filter(response != "") %>%
  clean_single_select()
q15_n5 <- tally(q15_data5, count)
q15_t5 <- "Being so restless that it is hard to sit still"
q15_r5 <- plot_single_select(q15_data5, q15_t5, q15_n5)
q15_r5
```

```{r}
ggsave(filename = "output/q15_anxiety/q15_restless.png", plot = q15_r5, device = 'png')
write.csv(q15_data5, paste0("output/q15_anxiety/q15_restless_", q15_n5, ".csv"), row.names = FALSE)
```

```{r}
q15_data6 <- get_single_selection_3(q15_data, "Becoming easily annoyed or irritable") %>%
  filter(response != "") %>%
  clean_single_select()
q15_n6 <- tally(q15_data6, count)
q15_t6 <- "Becoming easily annoyed or irritable"
q15_r6 <- plot_single_select(q15_data6, q15_t6, q15_n6)
q15_r6
```

```{r}
ggsave(filename = "output/q15_anxiety/q15_annoyed.png", plot = q15_r6, device = 'png')
write.csv(q15_data6, paste0("output/q15_anxiety/q15_annoyed_", q15_n6, ".csv"), row.names = FALSE)
```

```{r}
q15_data7 <- get_single_selection_3(q15_data, "Feeling afraid as if something awful might happen") %>%
  filter(response != "") %>%
  clean_single_select()
q15_n7 <- tally(q15_data7, count)
q15_t7 <- "Feeling afraid as if something awful might happen"
q15_r7 <- plot_single_select(q15_data7, q15_t7, q15_n7)
q15_r7
```

```{r}
ggsave(filename = "output/q15_anxiety/q15_afraid.png", plot = q15_r7, device = 'png')
write.csv(q15_data7, paste0("output/q15_anxiety/q15_afraid_", q15_n7, ".csv"), row.names = FALSE)
```
