---
title: "q17 Over the last 2 weeks, how often have you been bothered by any of the following problems? (depression scale)"
author: "David Ritter"
date: "2/25/2020"
output: html_document
runtime: shiny
---
 
```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q17 <- "Over.the.last.2.weeks..how.often.have.you.been.bothered.by.any.of.the.following.problems..1"
q17_final_response <- "X.99"
q17_t <- "Over the last 2 weeks, how often have you been bothered by any of the following problems?"
q17_data <- get_choose_all(raw_data, q.name = q17, f.response = q17_final_response)
dir.create("output/q17_depression")
```

```{r}
write.csv(q17_data, 'output/q17_depression/q17_depression_scales_data.csv', row.names = FALSE)
```

```{r}
q17_data1 <- get_single_selection_3(q17_data, "Little interest or pleasure in doing things") %>%
  filter(response != "") %>%
  clean_single_select()
q17_n1 <- tally(q17_data1, count)
q17_t1 <- "Little interest or pleasure in doing things"
q17_r1 <- plot_single_select(q17_data1, q17_t1, q17_n1)
q17_r1
```

```{r}
ggsave(filename = "output/q17_depression/q17_interest.png", plot = q17_r1, device = 'png')
write.csv(q17_data1, paste0("output/q17_depression/q17_interest_", q17_n1, ".csv"), row.names = FALSE)
```

```{r}
q17_data2 <- get_single_selection_3(q17_data, "Feeling down, depressed, or hopeless") %>%
  filter(response != "") %>%
  clean_single_select()
q17_n2 <- tally(q17_data2, count)
q17_t2 <- "Feeling down, depressed, or hopeless"
q17_r2 <- plot_single_select(q17_data2, q17_t2, q17_n2)
q17_r2
```

```{r}
ggsave(filename = "output/q17_depression/q17_depressed.png", plot = q17_r2, device = 'png')
write.csv(q17_data2, paste0("output/q17_depression/q17_depressed_", q17_n2, ".csv"), row.names = FALSE)
```

```{r}
q17_data3 <- get_single_selection_3(q17_data, "Trouble falling or staying asleep, or sleeping too much") %>%
  filter(response != "") %>%
  clean_single_select()
q17_n3 <- tally(q17_data3, count)
q17_t3 <- "Trouble falling or staying asleep, or sleeping too much"
q17_r3 <- plot_single_select(q17_data3, q17_t3, q17_n3)
q17_r3
```

```{r}
ggsave(filename = "output/q17_depression/q17_sleep.png", plot = q17_r3, device = 'png')
write.csv(q17_data3, paste0("output/q17_depression/q17_sleep_", q17_n3, ".csv"), row.names = FALSE)
```

```{r}
q17_data4 <- get_single_selection_3(q17_data, "Feeling tired or having little energy") %>%
  filter(response != "") %>%
  clean_single_select()
q17_n4 <- tally(q17_data4, count)
q17_t4 <- "Feeling tired or having little energy"
q17_r4 <- plot_single_select(q17_data4, q17_t4, q17_n4)
q17_r4
```

```{r}
ggsave(filename = "output/q17_depression/q17_fatigue.png", plot = q17_r4, device = 'png')
write.csv(q17_data4, paste0("output/q17_depression/q17_fatigue_", q17_n4, ".csv"), row.names = FALSE)
```

```{r}
q17_data5 <- get_single_selection_3(q17_data, "Poor appetite or overeating") %>%
  filter(response != "") %>%
  clean_single_select()
q17_n5 <- tally(q17_data5, count)
q17_t5 <- "Poor appetite or overeating"
q17_r5 <- plot_single_select(q17_data5, q17_t5, q17_n5)
q17_r5
```

```{r}
ggsave(filename = "output/q17_depression/q17_appetite.png", plot = q17_r5, device = 'png')
write.csv(q17_data5, paste0("output/q17_depression/q17_appetite_", q17_n5, ".csv"), row.names = FALSE)
```

```{r}
q17_data6 <- get_single_selection_3(q17_data, "Feeling bad about yourself or that you are a failure or have let yourself or your family down") %>%
  filter(response != "") %>%
  clean_single_select()
q17_n6 <- tally(q17_data6, count)
q17_t6 <- "Feeling bad about yourself or that you are a failure or have let yourself or your family down"
q17_r6 <- plot_single_select(q17_data6, q17_t6, q17_n6)
q17_r6
```

```{r}
ggsave(filename = "output/q17_depression/q17_failure.png", plot = q17_r6, device = 'png')
write.csv(q17_data6, paste0("output/q17_depression/q17_failure_", q17_n6, ".csv"), row.names = FALSE)
```

```{r}
q17_data7 <- get_single_selection_3(q17_data, "Trouble concentrating on things such as reading the newspaper or watching television") %>%
  filter(response != "") %>%
  clean_single_select()
q17_n7 <- tally(q17_data7, count)
q17_t7 <- "Trouble concentrating on things such as reading the newspaper or watching television"
q17_r7 <- plot_single_select(q17_data7, q17_t7, q17_n7)
q17_r7
```

```{r}
ggsave(filename = "output/q17_depression/q17_concentration.png", plot = q17_r7, device = 'png')
write.csv(q17_data7, paste0("output/q17_depression/q17_concentration_", q17_n7, ".csv"), row.names = FALSE)
```

```{r}
q17_data8 <- get_single_selection_3(q17_data, "Moving or speaking so slowly that other people could have noticed, or the opposite: being so fidgety or restless that you have been moving around a lot more than usual") %>%
  filter(response != "") %>%
  clean_single_select()
q17_n8 <- tally(q17_data8, count)
q17_t8 <- "Moving or speaking so slowly that other people could have noticed, or the opposite: being so fidgety or restless that you have been moving around a lot more than usual"
q17_r8 <- plot_single_select(q17_data8, q17_t8, q17_n8)
q17_r8
```

```{r}
ggsave(filename = "output/q17_depression/q17_movement.png", plot = q17_r8, device = 'png')
write.csv(q17_data8, paste0("output/q17_depression/q17_movement_", q17_n8, ".csv"), row.names = FALSE)
```

```{r}
q17_data9 <- get_single_selection_3(q17_data, "Thoughts that you would be better off dead or of hurting yourself in some way") %>%
  filter(response != "") %>%
  clean_single_select()
q17_n9 <- tally(q17_data9, count)
q17_t9 <- "Thoughts that you would be better off dead or of hurting yourself in some way"
q17_r9 <- plot_single_select(q17_data9, q17_t9, q17_n9)
q17_r9
```

```{r}
ggsave(filename = "output/q17_depression/q17_self_harm.png", plot = q17_r9, device = 'png')
write.csv(q17_data9, paste0("output/q17_depression/q17_self_harm_", q17_n9, ".csv"), row.names = FALSE)
```
