---
title: "q19 Over the last 2 weeks, how often have you been bothered by any of the following problems? (PTSD scale)" 
author: "David Ritter"
date: "2/25/2020"
output: html_document
runtime: shiny
---
 
```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q19 <- "Below.is.a.list.of.problems.and.complaints.that.veterans.sometimes.have.in.response.to.stressful.military.experiences..Please.read.each.one.carefully.and.indicate.how.much.you.have.beenÂ.ï..bothered.by.that.problem.in.the.last.month.ï.."
q19_final_response <- "X.115"
q19_t <- "PTSD Scales"
q19_data <- get_choose_all(raw_data, q.name = q19, f.response = q19_final_response)
dir.create("output/q19_ptsd")
```

```{r}
write.csv(q19_data, 'output/q19_ptsd/q19_ptsd_scales_data.csv', row.names = FALSE)
```

```{r}
q19_data1 <- get_single_selection_2(q19_data, "Repeated, disturbing memories, thoughts, or images of a stressful military experience?") %>%
  filter(response != "N/A") %>%
  clean_single_select()
q19_n1 <- tally(q19_data1, count)
q19_t1 <- "Repeated, disturbing memories, thoughts, or images of a stressful military experience?"
q19_r1 <- plot_single_select(q19_data1, q19_t1, q19_n1)
q19_r1
```

```{r}
ggsave(filename = "output/q19_ptsd/q19_flashback.png", plot = q19_r1, device = 'png')
write.csv(q19_data1, paste0("output/q19_ptsd/q19_flashback_", q19_n1, ".csv"), row.names = FALSE)
```

```{r}
q19_data2 <- get_single_selection_2(q19_data, "Repeated, disturbing dreams of a stressful military experience?") %>%
  filter(response != "N/A") %>%
  clean_single_select()
q19_n2 <- tally(q19_data2, count)
q19_t2 <- "Repeated, disturbing dreams of a stressful military experience?"
q19_r2 <- plot_single_select(q19_data2, q19_t2, q19_n2)
q19_r2
```

```{r}
ggsave(filename = "output/q19_ptsd/q19_dreams.png", plot = q19_r2, device = 'png')
write.csv(q19_data2, paste0("output/q19_ptsd/q19_dreams_", q19_n2, ".csv"), row.names = FALSE)
```

```{r}
q19_data3 <- get_single_selection_2(q19_data, "Suddenly acting or feeling as if a stressful military experience were happening again (as if you were reliving it)?") %>%
  filter(response != "N/A") %>%
  clean_single_select()
q19_n3 <- tally(q19_data3, count)
q19_t3 <- "Suddenly acting or feeling as if a stressful military experience were happening again (as if you were reliving it)?"
q19_r3 <- plot_single_select(q19_data3, q19_t3, q19_n3)
q19_r3
```

```{r}
ggsave(filename = "output/q19_ptsd/q19_reliving.png", plot = q19_r3, device = 'png')
write.csv(q19_data3, paste0("output/q19_ptsd/q19_reliving_", q19_n3, ".csv"), row.names = FALSE)
```

```{r}
q19_data4 <- get_single_selection_2(q19_data, "Feeling very upset when something reminded you of a stressful military experience") %>%
  filter(response != "N/A") %>%
  clean_single_select()
q19_n4 <- tally(q19_data4, count)
q19_t4 <- "Feeling very upset when something reminded you of a stressful military experience"
q19_r4 <- plot_single_select(q19_data4, q19_t4, q19_n4)
q19_r4
```

```{r}
ggsave(filename = "output/q19_ptsd/q19_trigger.png", plot = q19_r4, device = 'png')
write.csv(q19_data4, paste0("output/q19_ptsd/q19_trigger_", q19_n4, ".csv"), row.names = FALSE)
```

```{r}
q19_data5 <- get_single_selection_2(q19_data, "Having physical reactions (e.g., heart pounding, trouble breathing, or sweating) when something reminded you of a stressful military experience?") %>%
  filter(response != "N/A") %>%
  clean_single_select()
q19_n5 <- tally(q19_data5, count)
q19_t5 <- "Having physical reactions (e.g., heart pounding, trouble breathing, or sweating) when something reminded you of a stressful military experience?" 
q19_r5 <- plot_single_select(q19_data5, q19_t5, q19_n5)
q19_r5
```

```{r}
ggsave(filename = "output/q19_ptsd/q19_physical.png", plot = q19_r5, device = 'png')
write.csv(q19_data5, paste0("output/q19_ptsd/q19_physical_", q19_n5, ".csv"), row.names = FALSE)
```

```{r}
q19_data6 <- get_single_selection_2(q19_data, "Avoid thinking about or talking about a stressful military experience or avoid having feelings related to it?") %>%
  filter(response != "N/A") %>%
  clean_single_select()
q19_n6 <- tally(q19_data6, count)
q19_t6 <- "Avoid thinking about or talking about a stressful military experience or avoid having feelings related to it?"
q19_r6 <- plot_single_select(q19_data6, q19_t6, q19_n6)
q19_r6
```

```{r}
ggsave(filename = "output/q19_ptsd/q19_thinking.png", plot = q19_r6, device = 'png')
write.csv(q19_data6, paste0("output/q19_ptsd/q19_thinking_", q19_n6, ".csv"), row.names = FALSE)
```

```{r}
q19_data7 <- get_single_selection_2(q19_data, "Avoid activities or talking about a stressful military experience or avoid having feelings related to it?") %>%
  filter(response != "N/A") %>%
  clean_single_select()
q19_n7 <- tally(q19_data7, count)
q19_t7 <- "Avoid activities or talking about a stressful military experience or avoid having feelings related to it?"
q19_r7 <- plot_single_select(q19_data7, q19_t7, q19_n7)
q19_r7
```

```{r}
ggsave(filename = "output/q19_ptsd/q19_activities.png", plot = q19_r7, device = 'png')
write.csv(q19_data7, paste0("output/q19_ptsd/q19_activities_", q19_n7, ".csv"), row.names = FALSE)
```

```{r}
q19_data8 <- get_single_selection_2(q19_data, "Trouble remembering important parts of a stressful military experience?") %>%
  filter(response != "N/A") %>%
  clean_single_select()
q19_n8 <- tally(q19_data8, count)
q19_t8 <- "Trouble remembering important parts of a stressful military experience?"
q19_r8 <- plot_single_select(q19_data8, q19_t8, q19_n8)
q19_r8
```

```{r}
ggsave(filename = "output/q19_ptsd/q19_memory.png", plot = q19_r8, device = 'png')
write.csv(q19_data8, paste0("output/q19_ptsd/q19_memory_", q19_n8, ".csv"), row.names = FALSE)
```

```{r}
q19_data9 <- get_single_selection_2(q19_data, "Loss on interest in things that you used to enjoy?") %>%
  filter(response != "N/A") %>%
  clean_single_select()
q19_n9 <- tally(q19_data9, count)
q19_t9 <- "Loss on interest in things that you used to enjoy?"
q19_r9 <- plot_single_select(q19_data9, q19_t9, q19_n9)
q19_r9
```

```{r}
ggsave(filename = "output/q19_ptsd/q19_interest.png", plot = q19_r9, device = 'png')
write.csv(q19_data9, paste0("output/q19_ptsd/q19_interest_", q19_n9, ".csv"), row.names = FALSE)
```

```{r}
q19_data10 <- get_single_selection_2(q19_data, "Feeling distant or cut off from other people") %>%
  filter(response != "N/A") %>%
  clean_single_select()
q19_n10 <- tally(q19_data10, count)
q19_t10 <- "Feeling distant or cut off from other people"
q19_r10 <- plot_single_select(q19_data10, q19_t10, q19_n10)
q19_r10
```

```{r}
ggsave(filename = "output/q19_ptsd/q19_distant.png", plot = q19_r10, device = 'png')
write.csv(q19_data10, paste0("output/q19_ptsd/q19_distant_", q19_n10, ".csv"), row.names = FALSE)
```

```{r}
q19_data11 <- get_single_selection_2(q19_data, "Feeling emotionally numb or being unable to have loving feelings for those close to you?") %>%
  filter(response != "N/A") %>%
  clean_single_select()
q19_n11 <- tally(q19_data11, count)
q19_t11 <- "Feeling emotionally numb or being unable to have loving feelings for those close to you?"
q19_r11 <- plot_single_select(q19_data11, q19_t11, q19_n11)
q19_r11
```

```{r}
ggsave(filename = "output/q19_ptsd/q19_numb.png", plot = q19_r11, device = 'png')
write.csv(q19_data11, paste0("output/q19_ptsd/q19_numb_", q19_n11, ".csv"), row.names = FALSE)
```

```{r}
q19_data12 <- get_single_selection_2(q19_data, "Feeling as if your future will somehow be cut short?") %>%
  filter(response != "N/A") %>%
  clean_single_select()
q19_n12 <- tally(q19_data12, count)
q19_t12 <- "Feeling as if your future will somehow be cut short?"
q19_r12 <- plot_single_select(q19_data12, q19_t12, q19_n12)
q19_r12
```

```{r}
ggsave(filename = "output/q19_ptsd/q19_short_future.png", plot = q19_r12, device = 'png')
write.csv(q19_data12, paste0("output/q19_ptsd/q19_short_future_", q19_n12, ".csv"), row.names = FALSE)
```

```{r}
q19_data13 <- get_single_selection_2(q19_data, "Trouble falling or staying asleep?") %>%
  filter(response != "N/A") %>%
  clean_single_select()
q19_n13 <- tally(q19_data13, count)
q19_t13 <- "Trouble falling or staying asleep?"
q19_r13 <- plot_single_select(q19_data13, q19_t13, q19_n13)
q19_r13
```

```{r}
ggsave(filename = "output/q19_ptsd/q19_sleep.png", plot = q19_r13, device = 'png')
write.csv(q19_data13, paste0("output/q19_ptsd/q19_sleep_", q19_n13, ".csv"), row.names = FALSE)
```

```{r}
q19_data14 <- get_single_selection_2(q19_data, "Feeling irritable or having angry outbursts?") %>%
  filter(response != "N/A") %>%
  clean_single_select()
q19_n14 <- tally(q19_data14, count)
q19_t14 <- "Feeling irritable or having angry outbursts?"
q19_r14 <- plot_single_select(q19_data14, q19_t14, q19_n14)
q19_r14
```

```{r}
ggsave(filename = "output/q19_ptsd/q19_irritable.png", plot = q19_r14, device = 'png')
write.csv(q19_data14, paste0("output/q19_ptsd/q19_irritable_", q19_n14, ".csv"), row.names = FALSE)
```

```{r}
q19_data15 <- get_single_selection_2(q19_data, "Having difficulty concentrating?") %>%
  filter(response != "N/A") %>%
  clean_single_select()
q19_n15 <- tally(q19_data15, count)
q19_t15 <- "Having difficulty concentrating?"
q19_r15 <- plot_single_select(q19_data15, q19_t15, q19_n15)
q19_r15
```

```{r}
ggsave(filename = "output/q19_ptsd/q19_concentration.png", plot = q19_r15, device = 'png')
write.csv(q19_data15, paste0("output/q19_ptsd/q19_concentration_", q19_n15, ".csv"), row.names = FALSE)
```

```{r}
q19_data16 <- get_single_selection_2(q19_data, 'Being "super alert" or watchful on guard?') %>%
  filter(response != "N/A") %>%
  clean_single_select()
q19_n16 <- tally(q19_data16, count)
q19_t16 <- 'Being "super alert" or watchful on guard?'
q19_r16 <- plot_single_select(q19_data16, q19_t16, q19_n16)
q19_r16
```

```{r}
ggsave(filename = "output/q19_ptsd/q19_alert.png", plot = q19_r16, device = 'png')
write.csv(q19_data16, paste0("output/q19_ptsd/q19_alert_", q19_n16, ".csv"), row.names = FALSE)
```

```{r}
q19_data17 <- get_single_selection_2(q19_data, 'Feeling jumpy or easily startled?') %>%
  filter(response != "N/A") %>%
  clean_single_select()
q19_n17 <- tally(q19_data17, count)
q19_t17 <- 'Feeling jumpy or easily startled?'
q19_r17 <- plot_single_select(q19_data17, q19_t17, q19_n17)
q19_r17
```

```{r}
ggsave(filename = "output/q19_ptsd/q19_jumpy.png", plot = q19_r17, device = 'png')
write.csv(q19_data17, paste0("output/q19_ptsd/q19_jumpy_", q19_n17, ".csv"), row.names = FALSE)
```

