---
title: "q20 'What types of prescription medications are you currently taking for the health conditions and symptoms you face? (Please select all that apply)'"
author: "David Ritter"
date: "2/28/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q20 <- 'What.types.of.prescription.medications.are.you.currently.taking.for.the.health.conditions.and.symptoms.you.face...Please.select.all.that.apply.'
q20_final_response <- "X.136"
q20_t <- "What types of prescription medications are you currently taking for the health conditions and symptoms you face? (Please select all that apply)"
q20_data <- get_choose_all(raw_data, q.name = q20, f.response = q20_final_response) %>%
  tidy_choose_all()
q20_n <- length(unique(q20_data$id))
q20_plot <- clean_choose_all(q20_data, q20_n)
r20 <- plot_choose_all(q20_plot, q20_t, q20_n)
r20
```

```{r}
row3 <- colnames(q20_plot)
q20_plot2 <- rbind(row3, q20_plot)
names(q20_plot2) <- c("q20", q20_t, paste("n = ", q20_n))
```

```{r}
dir.create("output/q20_prescriptions")
ggsave(filename = 'output/q20_prescriptions/q20_prescriptions.png', plot = r20, device = 'png')
write.csv(q20_plot2, paste0("output/q20_prescriptions/q20_prescriptions_", q20_n,".csv"), row.names=F)
write.csv(q20_data, 'output/q20_prescriptions/q20_prescriptions_ids.csv', row.names = FALSE)
```







```{r}
qf_data <- q_data %>%
  filter(chosen == "Response text")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")
qf_n <- length(unique(qf_all_data$id))
qf_data <- qf_all_data[3] %>%
  group_by(chosen) %>%
  summarize(count=n()) %>%
  mutate(percent_responded = round(100*(count / qf_n), 2)) %>%
  arrange(desc(count))
```

```{r}
q_plot <- clean_choose_all_f2(qf_data)
r <- plot_choose_all_f2(q_plot)
r
```

```{r}
q_plot2 <- rbind(q_plot, t)
dir.create("output/q20_prescriptions")
ggsave(filename = 'output/q20_prescriptions/q20_prescriptions.png', plot = r, device = 'png')
write.csv(q_plot2, paste0("output/q20_prescriptions/q20_prescriptions_", qf_n,".csv"), row.names=F)
write.csv(qf_all_data, 'output/q20_prescriptions/q20_prescriptions_ids.csv', row.names = FALSE)
```

