---
title: "q22 'Do you have prescription medications in your house that you don't want to use and currently need to get rid of?'"
author: "David Ritter"
date: "2/25/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q22 <- "Do.you.have.prescription.medications.in.your.house.that.you.don.t.want.to.use.and.currently.need.to.get.rid.of."
q22_t <- "Do you have prescription medications in your house that you don't want to use and currently need to get rid of?"
q22_data <- get_single_selection(data = raw_data, q.name = q22)
q22_n <- length(unique(q22_data$id))
q22_plot<- clean_single_select(q22_data)
r22 <- plot_single_select(q22_plot, q22_t, q22_n)
r22
```

```{r}
q22_plot2 <- rbind(q22_plot, q22_t)
dir.create("output/q22_unwanted_medication")
ggsave(filename = 'output/q22_unwanted_medication/q22_unwanted_medication.png', plot = r22, device = 'png')
write.csv(q22_plot2, paste0("output/q22_unwanted_medication/q22_unwanted_medication_", q22_n,".csv"), row.names=F)
```




```{r}
qf_data <- q_data %>%
  filter(response == "Response text")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")
qf_n <- length(unique(qf_all_data$id))
q_plot <- clean_single_select_y(qf_all_data)
r <- plot_single_select_y(q_plot)
r
```

```{r}
q_plot2 <- rbind(q_plot, t)
dir.create("output/q22_unwanted_medication")
ggsave(filename = 'output/q22_unwanted_medication/q22_unwanted_medication.png', plot = r, device = 'png')
write.csv(q_plot2, paste0("output/q22_unwanted_medication/q22_unwanted_medication_", qf_n,".csv"), row.names=F)
```
