---
title: "Q22 Unwanted Medications"
runtime: shiny
output: html_document
---


```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```


```{r}
# Read in raw data. These are the files downloaded from survey monkey saved as a .csv

raw_data_general <- read.csv("data/general_text.csv", stringsAsFactors = FALSE)
raw_data_botanist <- read.csv("data/botanist_text.csv", stringsAsFactors = FALSE)
raw_data_bask <- read.csv("data/bask_text.csv", stringsAsFactors = FALSE)

```


```{r}
# Pull out all responses for Q22 (a single selection question) and combine

Q22 <- "Do.you.have.prescription.medications.in.your.house.that.you.don.t.want.to.use.and.currently.need.to.get.rid.of."

Q22_general <- get_single_selection(data = raw_data_general, q.name = Q22)
Q22_bask <- get_single_selection(data = raw_data_bask, q.name = Q22)
Q22_botanist <- get_single_selection(data = raw_data_botanist, q.name = Q22)

Q22_all <- rbind(Q22_general, Q22_bask, Q22_botanist)

## Determine Question N

number_of_people_who_submitted_response_to_Q22 <- length(unique(Q22_all$id))

```

```{r}

Q22_plot <- 
  Q22_all %>%
  group_by(response) %>%
  summarize(count = n()) %>%
  mutate(percent_all = count / sum(count)) %>%
  mutate(percent_responded = count / number_of_people_who_submitted_response_to_Q22)

p <- 
  ggplot(Q22_plot, aes(x = reorder(response, count), y = count)) +
  geom_bar(stat = 'identity') + 
  coord_flip()

p

```

```{r}
# Add percents and response counts

q <- 
  ggplot(Q22_plot, aes(x = reorder(response, count), y = percent_all)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  geom_text(aes(label= round(percent_all,2)))

q


r <- 
  ggplot(Q22_plot, aes(x = reorder(response, count), y = percent_responded)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  geom_text(aes(label= paste(round(percent_responded, 2), count, sep = "***")))


r



```


```{r}

ggsave(filename = 'Q22_Unwanted_Medications_PNG.png', plot = r, device = 'png')

```

```{r}

write.csv(Q22_plot, 'Q22_Unwanted_Medications.csv', row.names = FALSE)

```




