

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
# Read in raw data. These are the files downloaded from survey monkey saved as a .csv

raw_data_general <- read.csv("data/general_text.csv", stringsAsFactors = FALSE)
raw_data_botanist <- read.csv("data/botanist_text.csv", stringsAsFactors = FALSE)
raw_data_bask <- read.csv("data/bask_text.csv", stringsAsFactors = FALSE)
raw_data_healing_rose <- read.csv("data/healing_rose_text.csv", stringsAsFactors = FALSE)

```

```{r}
# Pull out all responses for Q23 (a single selection question) and combine

Q23 <- "Have.you.ever.been.diagnosed.with.Opioid.Use.Disorder..OUD.."

Q23_general <- get_single_selection(data = raw_data_general, q.name = Q23)
Q23_bask <- get_single_selection(data = raw_data_bask, q.name = Q23)
Q23_botanist <- get_single_selection(data = raw_data_botanist, q.name = Q23)
Q23_healing_rose <- get_single_selection(data = raw_data_healing_rose, q.name = Q23)

Q23_all <- rbind(Q23_general, Q23_bask, Q23_botanist, Q23_healing_rose)

## Determine Question N

number_of_people <- length(unique(Q23_all$id))

```


```{r}

ids_we_want <- Q23_all %>% 
  filter(response %in% c("Yes, currently", "Yes, in the past but not currently"))

```


```{r}

Q45_responses_we_want <- Q45_all %>%
  right_join(ids_we_want)

```

```{r}

number_of_people <- length(unique(Q45_responses_we_want$id))
  
for_plot <-
  Q45_responses_we_want %>%
  group_by(chosen) %>%
  summarize(count = n()) %>%
  mutate(percent_all = count / sum(count)) %>%
  mutate(percent_responded = count / number_of_people)

r <- 
  ggplot(for_plot, aes(x = reorder(chosen, count), y = percent_responded)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  geom_text(aes(label= paste(round(percent_responded,2), count, sep = "***")))


r

```
```{r}

ggsave(filename = 'Q45_Filtered_Q23.png', plot = r, device = 'png')

write.csv(for_plot, 'Q45_Filtered_Q23_9.csv', row.names = FALSE)


```