---
title: "q23 'Have you ever been diagnosed with Opioid Use Disorder (OUD)?'"
author: "David Ritter"
date: "2/28/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q23 <- "Have.you.ever.been.diagnosed.with.Opioid.Use.Disorder..OUD.."
q23_t <- "Have you ever been diagnosed with Opioid Use Disorder (OUD)?"
q23_data <- get_single_selection(data = raw_data, q.name = q23)
q23_n <- length(unique(q23_data$id))
q23_plot<- clean_single_select(q23_data)
r23 <- plot_single_select(q23_plot, q23_t, q23_n)
r23
```

```{r}
row3 <- colnames(q23_plot)
q23_plot2 <- rbind(row3, q23_plot)
names(q23_plot2) <- c("q23", q23_t, paste("n = ", q23_n))
```

```{r}
dir.create("output/q23_opioid_use_disorder")
ggsave(filename = 'output/q23_opioid_use_disorder/q23_opioid_use_disorder.png', plot = r23, device = 'png')
write.csv(q23_plot2, paste0("output/q23_opioid_use_disorder/q23_opioid_use_disorder_", q23_n,".csv"), row.names=F)
```







```{r}
qf_data <- q_data %>%
  filter(response == "Response text")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")
qf_n <- length(unique(qf_all_data$id))
q_plot <- clean_single_select_y(qf_all_data)
r <- plot_single_select_y(q_plot)
r
```

```{r}
q_plot2 <- rbind(q_plot, t)
dir.create("output/q23_opioid_use_disorder")
ggsave(filename = 'output/q23_opioid_use_disorder/q23_opioid_use_disorder.png', plot = r, device = 'png')
write.csv(q_plot2, paste0("output/q23_opioid_use_disorder/q23_opioid_use_disorder_", qf_n,".csv"), row.names=F)
```
