---
title: "q29 'What percentage of disability are you rated, as indicated by the Veteran's Affairs (VA)?'"
author: "David Ritter"
date: "2/28/2020"
output: html_document
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q29 <- "What.percentage.of.disability.are.you.rated..as.is.indicated.by.the.Veteran.s.Affairs..VA.."
q29_t <- "What percentage of disability are you rated, as indicated by the Veteran's Affairs (VA)?"
q29_data <- get_single_selection_0(data = raw_data, q.name = q29) %>%
  filter(response != "")
q29_n <- length(unique(q29_data$id))
q29_mean_data <- as.numeric(as.character(q29_data$response))
q29_mean <- mean(q29_mean_data) %>%
  round(2) %>%
  print()
q29_plot<- clean_single_select(q29_data)
r29 <- plot_single_select_0(q29_plot, q29_t, q29_n, q29_mean)
r29
```

```{r}
row3 <- colnames(q29_plot)
q29_plot2 <- rbind(row3, q29_plot)
names(q29_plot2) <- c("q29", q29_t, paste("n = ", q29_n, paste(" avg = ", q29_mean)))
```

```{r}
dir.create("output/q29_disability")
ggsave(filename = 'output/q29_disability/q29_disability.png', plot = r29, device = 'png')
write.csv(q29_plot2, paste0("output/q29_disability/q29_disability_", q29_n,".csv"), row.names=F)
write.csv(q29_data, 'output/q29_disability/q29_disability_ids.csv', row.names = FALSE)
```

```{r}
histogram_object <- hist(as.numeric(q29_data$response))
histogram_object$breaks
histogram_object$counts
plot(histogram_object)
```







```{r}
qf_data <- q_data %>%
  filter(response == "Response text")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")
qf_mean_data <- as.numeric(as.character(qf_all_data$response.y))
q29f_mean <- mean(qf_mean_data) %>%
  round(3) %>%
  print()
qf_n <- length(unique(qf_all_data$id))
```

```{r}
q_plot <- clean_single_select_y(qf_all_data)
r <- plot_single_select_y(q_plot)
r
```

```{r}
q_plot2 <- rbind(q_plot, t, paste("average", q29f_mean, sep = " = "))
dir.create("output/q29_disability/q29_disability")
ggsave(filename = 'output/q29_disability/q29_disability.png', plot = r, device = 'png')
write.csv(q_plot2, paste0("output/q29_disability/q29_disability_", qf_n,".csv"), row.names=F)
write.csv(qf_all_data, 'output/q29_disability/q29_disability_ids.csv', row.names = FALSE)
```

