---
title: "Q29_Percentage_Disability"
author: "Neil Ritter"
date: "4/10/2019"
output: html_document
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```


```{r}
# Read in raw data. These are the files downloaded from survey monkey saved as a .csv

raw_data_general <- read.csv("data/general_text.csv", stringsAsFactors = FALSE)
raw_data_botanist <- read.csv("data/botanist_text.csv", stringsAsFactors = FALSE)
raw_data_bask <- read.csv("data/bask_text.csv", stringsAsFactors = FALSE)

```

```{r}
Q29 <- "What.percentage.of.disability.are.you.rated..as.is.indicated.by.the.Veteran.s.Affairs..VA.."

# Pull out all responses for Q29 (a single selection question) and combine

Q29_general <- get_single_selection(data = raw_data_general, q.name = Q29)
Q29_bask <- get_single_selection(data = raw_data_bask, q.name = Q29)
Q29_botanist <- get_single_selection(data = raw_data_botanist, q.name = Q29)

Q29_all <- rbind(Q29_general, Q29_bask, Q29_botanist)


```


```{r}

histogram_object <- hist(as.numeric(Q29_all$response))

histogram_object$breaks
histogram_object$counts
plot(histogram_object)

```






