---
title: "q30 'Do you currently have health insurance? (Please select one)'"
author: "David Ritter"
date: "2/25/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q30 <- "Do.you.currently.have.health.insurance...Please.select.one."
q30_t <- "Do you currently have health insurance? (Please select one)"
q30_data <- get_single_selection(data = raw_data, q.name = q30)
q30_n <- length(unique(q30_data$id))
q30_plot<- clean_single_select(q30_data)
r30 <- plot_single_select(q30_plot, q30_t, q30_n)
r30
```

```{r}
q30_plot2 <- rbind(q30_plot, q30_t)
dir.create("output/q30_health_insurance")
ggsave(filename = 'output/q30_health_insurance/q30_health_insurance.png', plot = r30, device = 'png')
write.csv(q30_plot2, paste0("output/q30_health_insurance/q30_health_insurance_", q30_n,".csv"), row.names=F)
```




```{r}
qf_data <- q_data %>%
  filter(response == "Response text")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")
qf_n <- length(unique(qf_all_data$id))
q_plot <- clean_single_select_y(qf_all_data)
r <- plot_single_select_y(q_plot)
r
```

```{r}
q_plot2 <- rbind(q_plot, t)
dir.create("output/q30_health_insurance")
ggsave(filename = 'output/q30_health_insurance/q30_health_insurance.png', plot = r, device = 'png')
write.csv(q_plot2, paste0("output/q30_health_insurance/q30_health_insurance_", qf_n,".csv"), row.names=F)
```
