---
title: "q31 'Do you have prescription drug coverage?'"
author: "David Ritter"
date: "2/25/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q31 <- "Do.you.have.prescription.drug.coverage."
q31_t <- "Do you have prescription drug coverage?"
q31_data <- get_single_selection(data = raw_data, q.name = q31)
q31_n <- length(unique(q31_data$id))
q31_plot<- clean_single_select(q31_data)
r31 <- plot_single_select(q31_plot, q31_t, q31_n)
r31
```

```{r}
q31_plot2 <- rbind(q31_plot, q31_t)
dir.create("output/q31_drug_coverage")
ggsave(filename = 'output/q31_drug_coverage/q31_drug_coverage.png', plot = r31, device = 'png')
write.csv(q31_plot2, paste0("output/q31_drug_coverage/q31_drug_coverage_", q31_n,".csv"), row.names=F)
```




```{r}
qf_data <- q_data %>%
  filter(response == "Response text")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")
qf_n <- length(unique(qf_all_data$id))
q_plot <- clean_single_select_y(qf_all_data)
r <- plot_single_select_y(q_plot)
r
```

```{r}
q_plot2 <- rbind(q_plot, t)
dir.create("output/q31_drug_coverage")
ggsave(filename = 'output/q31_drug_coverage/q31_drug_coverage.png', plot = r, device = 'png')
write.csv(q_plot2, paste0("output/q31_drug_coverage/q31_drug_coverage_", qf_n,".csv"), row.names=F)
```