---
title: "q37 'Under what circumstances do you use cannabis? (Please select all that apply)'"
author: "David Ritter"
date: "2/28/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q37 <- 'Under.what.circumstances.do.you.use.cannabis...Please.select.all.that.apply.'
q37_final_response <- "X.153"
q37_t <- "Under what circumstances do you use cannabis? (Please select all that apply)"
q37_data <- get_choose_all(raw_data, q.name = q37, f.response = q37_final_response) %>%
  tidy_choose_all()
q37_n <- length(unique(q37_data$id))
q37_plot <- clean_choose_all(q37_data, q37_n)
r37 <- plot_choose_all(q37_plot, q37_t, q37_n)
r37
```

```{r}
row3 <- colnames(q37_plot)
q37_plot2 <- rbind(row3, q37_plot)
names(q37_plot2) <- c("q37", q37_t, paste("n = ", q37_n))
```

```{r}
dir.create("output/q37_cannabis_uses")
ggsave(filename = 'output/q37_cannabis_uses/q37_cannabis_uses.png', plot = r37, device = 'png')
write.csv(q37_plot2, paste0("output/q37_cannabis_uses/q37_cannabis_uses_", q37_n,".csv"), row.names=F)
write.csv(q37_data, 'output/q37_cannabis_uses/q37_cannabis_uses_ids.csv', row.names = FALSE)
```







```{r}
qf_data <- q_data %>%
  filter(chosen == "Response text")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")
qf_n <- length(unique(qf_all_data$id))
qf_data <- qf_all_data[3] %>%
  group_by(chosen) %>%
  summarize(count=n()) %>%
  mutate(percent_responded = round(100*(count / qf_n), 2)) %>%
  arrange(desc(count))
```

```{r}
q_plot <- clean_choose_all_f2(qf_data)
r <- plot_choose_all_f2(q_plot)
r
```

```{r}
q_plot2 <- rbind(q_plot, t)
dir.create("output/q37_cannabis_uses")
ggsave(filename = 'output/q37_cannabis_uses/q37_cannabis_uses.png', plot = r, device = 'png')
write.csv(q_plot2, paste0("output/q37_cannabis_uses/q37_cannabis_uses_", qf_n,".csv"), row.names=F)
write.csv(qf_all_data, 'output/q37_cannabis_uses/q37_cannabis_uses_ids.csv', row.names = FALSE)
```


