---
title: "q39 'What is the primary health condition for which you find cannabis to be helpful? (Please select one)'"
author: "David Ritter"
date: "2/25/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q39 <- "What.is.the.primary.health.condition.for.which.you.find.cannabis.to.be.helpful...Please.select.one."
q39_t <- "What is the primary health condition for which you find cannabis to be helpful? (Please select one)"
q39_data <- get_single_selection(data = raw_data, q.name = q39)
q39_n <- length(unique(q39_data$id))
q39_plot<- clean_single_select(q39_data)
r39 <- plot_single_select(q39_plot, q39_t, q39_n)
r39
```

```{r}
q39_plot2 <- rbind(q39_plot, q39_t)
dir.create("output/q39_top_condition_cannabis")
ggsave(filename = 'output/q39_top_condition_cannabis/q39_top_condition_cannabis.png', plot = r39, device = 'png')
write.csv(q39_plot2, paste0("output/q39_top_condition_cannabis/q39_top_condition_cannabis_", q39_n,".csv"), row.names=F)
```




```{r}
qf_data <- q_data %>%
  filter(response == "Response text")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")
qf_n <- length(unique(qf_all_data$id))
q_plot <- clean_single_select_y(qf_all_data)
r <- plot_single_select_y(q_plot)
r
```

```{r}
q_plot2 <- rbind(q_plot, t)
dir.create("output/q39_top_condition_cannabis")
ggsave(filename = 'output/q39_top_condition_cannabis/q39_top_condition_cannabis.png', plot = r, device = 'png')
write.csv(q_plot2, paste0("output/q39_top_condition_cannabis/q39_top_condition_cannabis_", qf_n,".csv"), row.names=F)
```
