---
title: "Q39_Primary_Condition_Cannabis_Helpful"
runtime: shiny
output: html_document
---


```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```


```{r}
# Read in raw data. These are the files downloaded from survey monkey saved as a .csv

raw_data_general <- read.csv("data/general_text.csv", stringsAsFactors = FALSE)
raw_data_botanist <- read.csv("data/botanist_text.csv", stringsAsFactors = FALSE)
raw_data_bask <- read.csv("data/bask_text.csv", stringsAsFactors = FALSE)

```


```{r}
# Pull out all responses for Q39 (a single selection question) and combine

Q39 <- "What.is.the.primary.health.condition.for.which.you.find.cannabis.to.be.helpful...Please.select.one."

Q39_general <- get_single_selection(data = raw_data_general, q.name = Q39)
Q39_bask <- get_single_selection(data = raw_data_bask, q.name = Q39)
Q39_botanist <- get_single_selection(data = raw_data_botanist, q.name = Q39)

Q39_all <- rbind(Q39_general, Q39_bask, Q39_botanist)

number_of_people_who_submitted_response_to_Q39 <- length(unique(Q39_all$id))

```

```{r}

for_plot <- 
  Q39_all %>%
  group_by(response) %>%
  summarize(count = n()) %>%
  mutate(percent_all = count / sum(count)) %>%
  mutate(percent_responded = count / number_of_people_who_submitted_response_to_Q39)

p <- 
  ggplot(for_plot, aes(x = reorder(response, count), y = count)) +
  geom_bar(stat = 'identity') + 
  coord_flip()

p

```
```{r}

# Add percentages

q <- 
  ggplot(for_plot, aes(x = reorder(response, count), y = percent_all)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  geom_text(aes(label= round(percent_all,2)))

q


r <- 
  ggplot(for_plot, aes(x = reorder(response, count), y = percent_responded)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  geom_text(aes(label= paste(round(percent_responded, 2), count, sep = "***")))



r


```

```{r}

ggsave(filename = 'Q39_Primary_Condition_Cannabis_Helpful_PNG.png', plot = r, device = 'png')

```
```{r}

write.csv(for_plot, 'Q39_Primary_Condition_Cannabis_Helpful.csv', row.names = FALSE)

```


