---
title: "q40 'What symptoms do you find medical cannabis is most helpful in treating/alleviating? (Please select all that apply)'"
author: "David Ritter"
date: "2/28/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q40 <- 'What.symptoms.do.you.find.medical.cannabis.is.most.helpful.in.treating.alleviating...Please.select.all.that.apply.'
q40_final_response <- "X.197"
q40_t <- "What symptoms do you find medical cannabis is most helpful in treating/alleviating? (Please select all that apply)"
q40_data <- get_choose_all(raw_data, q.name = q40, f.response = q40_final_response) %>%
  tidy_choose_all()
q40_n <- length(unique(q40_data$id))
q40_plot <- clean_choose_all(q40_data, q40_n)
r40 <- plot_choose_all(q40_plot, q40_t, q40_n)
r40
```

```{r}
row3 <- colnames(q40_plot)
q40_plot2 <- rbind(row3, q40_plot)
names(q40_plot2) <- c("q40", q40_t, paste("n = ", q40_n))
```

```{r}
dir.create("output/q40_symptoms_treated")
ggsave(filename = 'output/q40_symptoms_treated/q40_symptoms_treated.png', plot = r40, device = 'png')
write.csv(q40_plot2, paste0("output/q40_symptoms_treated/q40_symptoms_treated_", q40_n,".csv"), row.names=F)
write.csv(q40_data, 'output/q40_symptoms_treated/q40_symptoms_treated_ids.csv', row.names = FALSE)
```







```{r}
qf_data <- q_data %>%
  filter(chosen == "Response text")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")
qf_n <- length(unique(qf_all_data$id))
qf_data <- qf_all_data[3] %>%
  group_by(chosen) %>%
  summarize(count=n()) %>%
  mutate(percent_responded = round(100*(count / qf_n), 2)) %>%
  arrange(desc(count))
```

```{r}
q_plot <- clean_choose_all_f2(qf_data)
r <- plot_choose_all_f2(q_plot)
r
```

```{r}
q_plot2 <- rbind(q_plot, t)
dir.create("output/q40_symptoms_treated")
ggsave(filename = 'output/q40_symptoms_treated/5_conditions.png', plot = r, device = 'png')
write.csv(q_plot2, paste0("output/q40_symptoms_treated/q40_symptoms_treated_", qf_n,".csv"), row.names=F)
write.csv(qf_all_data, 'output/q40_symptoms_treated/q5_condition_ids.csv', row.names = FALSE)
```

