---
title: "q41 'How long have you been using cannabis for medical purposes?'"
author: "David Ritter"
date: "2/28/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q41 <- "How.long.have.you.been.using.cannabis.for.medical.purposes."
q41_t <- "How long have you been using cannabis for medical purposes?"
q41_data <- get_single_selection(data = raw_data, q.name = q41)
q41_n <- length(unique(q41_data$id))
q41_plot<- clean_single_select(q41_data)
r41 <- plot_single_select(q41_plot, q41_t, q41_n)
r41
```

```{r}
row3 <- colnames(q41_plot)
q41_plot2 <- rbind(row3, q41_plot)
names(q41_plot2) <- c("q41", q41_t, paste("n = ", q41_n))
```

```{r}
dir.create("output/q41_med_cannabis_duration")
ggsave(filename = 'output/q41_med_cannabis_duration/q41_med_cannabis_duration.png', plot = r41, device = 'png')
write.csv(q41_plot2, paste0("output/q41_med_cannabis_duration/q41_med_cannabis_duration_", q41_n,".csv"), row.names=F)
```







```{r}
qf_data <- q_data %>%
  filter(response == "Response text")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")
qf_n <- length(unique(qf_all_data$id))
q_plot <- clean_single_select_y(qf_all_data)
r <- plot_single_select_y(q_plot)
r
```

```{r}
q_plot2 <- rbind(q_plot, t)
dir.create("output/q41_med_cannabis_duration")
ggsave(filename = 'output/q41_med_cannabis_duration/q41_med_cannabis_duration.png', plot = r, device = 'png')
write.csv(q_plot2, paste0("output/q41_med_cannabis_duration/q41_med_cannabis_duration_", qf_n,".csv"), row.names=F)
```
