---
title: "q43 'How do you feel cannabis has helped your daily life?'"
author: "David Ritter"
date: "2/25/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q43 <- 'How.do.you.feel.cannabis.has.helped.your.daily.life.Thinking.about.how.you.feelÂ.TODAYÂ.compared.to.theÂ.BEGINNINGÂ.of.your.use.of.cannabis.to.treat.your.primary.medical.condition...'
q43_final_response <- "X.204"
q43_t <- "How do you feel cannabis has helped your daily life?"
q43_data <- get_choose_all(raw_data, q.name = q43, f.response = q43_final_response)
dir.create("output/q43_qol")
```

```{r}
write.csv(q43_data, 'output/q43_qol/q43_daily_qol_data.csv', row.names = FALSE)
```

```{r}
q43_data1 <- get_single_selection_3(q43_data, "I experience a greater quality of life") %>%
  filter(response != "N/A") %>%
  filter(response != "") %>%
  clean_single_select()
q43_n1 <- tally(q43_data1, count)
q43_t1 <- "I experience a greater quality of life"
q43_r1 <- plot_single_select(q43_data1, q43_t1, q43_n1)
q43_r1
```

```{r}
ggsave(filename = "output/q43_qol/q43_greater_qol.png", plot = q43_r1, device = 'png')
write.csv(q43_data1, paste0("output/q43_qol/q43_greater_qol_", q43_n1, ".csv"), row.names = FALSE)
```

```{r}
q43_data2 <- get_single_selection_3(q43_data, "I experience physical symptoms (body pains, function, sensation)") %>%
  filter(response != "N/A") %>%
  filter(response != "") %>%
  clean_single_select()
q43_n2 <- tally(q43_data2, count)
q43_t2 <- "I experience physical symptoms (body pains, function, sensation)"
q43_r2 <- plot_single_select(q43_data2, q43_t2, q43_n2)
q43_r2
```

```{r}
ggsave(filename = "output/q43_qol/q43_physical.png", plot = q43_r2, device = 'png')
write.csv(q43_data2, paste0("output/q43_qol/q43_physical_", q43_n2, ".csv"), row.names = FALSE)
```

```{r}
q43_data3 <- get_single_selection_3(q43_data, "I experience psychological symptoms (anxiety, stress, sadness)") %>%
  filter(response != "N/A") %>%
  filter(response != "") %>%
  clean_single_select()
q43_n3 <- tally(q43_data3, count)
q43_t3 <- "I experience psychological symptoms (anxiety, stress, sadness)"
q43_r3 <- plot_single_select(q43_data3, q43_t3, q43_n3)
q43_r3
```

```{r}
ggsave(filename = "output/q43_qol/q43_psychological.png", plot = q43_r3, device = 'png')
write.csv(q43_data3, paste0("output/q43_qol/q43_psychological_", q43_n3, ".csv"), row.names = FALSE)
```

```{r}
q43_data4 <- get_single_selection_3(q43_data, "I use opioids") %>%
  filter(response != "N/A") %>%
  filter(response != "") %>%
  clean_single_select()
q43_n4 <- tally(q43_data4, count)
q43_t4 <- "I use opioids"
q43_r4 <- plot_single_select(q43_data4, q43_t4, q43_n4)
q43_r4
```

```{r}
ggsave(filename = "output/q43_qol/q43_opioid_use.png", plot = q43_r4, device = 'png')
write.csv(q43_data4, paste0("output/q43_qol/q43_opioid_use_", q43_n4, ".csv"), row.names = FALSE)
```

```{r}
q43_data5 <- get_single_selection_3(q43_data, "I use my prior medications (non-opioid)") %>%
  filter(response != "N/A") %>%
  filter(response != "") %>%
  clean_single_select()
q43_n5 <- tally(q43_data5, count)
q43_t5 <- "I use my prior medications (non-opioid)"
q43_r5 <- plot_single_select(q43_data5, q43_t5, q43_n5)
q43_r5
```

```{r}
ggsave(filename = "output/q43_qol/q43_prior_med_use.png", plot = q43_r5, device = 'png')
write.csv(q43_data5, paste0("output/q43_qol/q43_prior_med_use_", q43_n5, ".csv"), row.names = FALSE)
```

```{r}
q43_data6 <- get_single_selection_3(q43_data, "I use alcohol") %>%
  filter(response != "N/A") %>%
  filter(response != "") %>%
  clean_single_select()
q43_n6 <- tally(q43_data6, count)
q43_t6 <- "I use alcohol"
q43_r6 <- plot_single_select(q43_data6, q43_t6, q43_n6)
q43_r6
```

```{r}
ggsave(filename = "output/q43_qol/q43_alcohol.png", plot = q43_r6, device = 'png')
write.csv(q43_data6, paste0("output/q43_qol/q43_alcohol_", q43_n6, ".csv"), row.names = FALSE)
```

```{r}
q43_data7 <- get_single_selection_3(q43_data, "I use tobacco") %>%
  filter(response != "N/A") %>%
  filter(response != "") %>%
  clean_single_select()
q43_n7 <- tally(q43_data7, count)
q43_t7 <- "I use tobacco"
q43_r7 <- plot_single_select(q43_data7, q43_t7, q43_n7)
q43_r7
```

```{r}
ggsave(filename = "output/q43_qol/q43_tobacco.png", plot = q43_r7, device = 'png')
write.csv(q43_data7, paste0("output/q43_qol/q43_tobacco_", q43_n7, ".csv"), row.names = FALSE)
```

```{r}
q43_data8 <- get_single_selection_3(q43_data, "I feel the quality of my daily life is") %>%
  filter(response != "N/A") %>%
  filter(response != "") %>%
  clean_single_select()
q43_n8 <- tally(q43_data8, count)
q43_t8 <- "I feel the quality of my daily life is"
q43_r8 <- plot_single_select(q43_data8, q43_t8, q43_n8)
q43_r8
```

```{r}
ggsave(filename = "output/q43_qol/q43_daily_qol.png", plot = q43_r8, device = 'png')
write.csv(q43_data8, paste0("output/q43_qol/q43_daily_qol_", q43_n8, ".csv"), row.names = FALSE)
```