---
title: "Q45_Prescriptions"
author: "Neil Ritter"
date: "4/10/2019"
output: html_document
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```


```{r}
# Read in raw data. These are the files downloaded from survey monkey saved as a .csv

raw_data_general <- read.csv("data/general_text.csv", stringsAsFactors = FALSE)
raw_data_botanist <- read.csv("data/botanist_text.csv", stringsAsFactors = FALSE)
raw_data_bask <- read.csv("data/bask_text.csv", stringsAsFactors = FALSE)

```


```{r}
# Pull out all responses for Q45 (a choose all question), combine, and turn
# into a tidy data format for further processing


# Notes
# - Not including X.249 (Other) and X.248 (Have reduced use in past)

Q45 <- 'What.prescription.medications.are.you.currently.taking.for.the.health.conditions.and.symptoms.you.face.that.you.are.actively.trying.to.reduce.the.use.of.by.using.cannabis...Please.select.all.that.apply.'
Q45_final_response <- "X.249"

Q45_general <- get_choose_all(raw_data_general, q.name = Q45, f.response = Q45_final_response)
Q45_bask <- get_choose_all(raw_data_bask, q.name = Q45, f.response = Q45_final_response)
Q45_botanist <- get_choose_all(raw_data_botanist, q.name = Q45, f.response = Q45_final_response)

Q45_all <- 
  rbind(Q45_general, Q45_bask, Q45_botanist) %>%
  tidy_choose_all()

number_of_people_who_submitted_response_to_Q45 <- length(unique(Q45_all$id))

# Filter undesirable responses

Q45_all_reduce <-
   Q45_all %>%
   filter(chosen != "I'm not trying to reduce any medication use") %>%
   filter(chosen != "I have reduced my prescription medication use in the past")

number_of_people_who_use_cannabis_to_reduce_prescription_use <- length(unique(Q45_all_reduce$id))



```


```{r}

for_plot <-
  Q45_all_reduce %>%
  group_by(chosen) %>%
  summarize(count = n()) %>%
  mutate(percent_all = count / sum(count)) %>%
  mutate(percent_responded = count / number_of_people_who_use_cannabis_to_reduce_prescription_use)

p <- 
  ggplot(for_plot, aes(x = reorder(chosen, count), y = count)) +
  geom_bar(stat = 'identity') +
  coord_flip()

p


q <- 
  ggplot(for_plot, aes(x = reorder(chosen, count), y = percent_all)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  geom_text(aes(label= round(percent_all,2)))

q


r <- 
  ggplot(for_plot, aes(x = reorder(chosen, count), y = percent_responded)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  geom_text(aes(label= round(percent_responded,2)))


r


```


```{r}

# Save PNG with % and Count

ggsave(filename = 'Q45_Unwanted_Medications_PNG.png', plot = r, device = 'png')

```

```{r}

# Save CSV with % 

write.csv(for_plot, 'Q45_Unwanted_Medications.csv', row.names = FALSE)

```







