---
title: "q45 'What prescription medications are you currently taking for the health conditions and symptoms you face that you are actively trying to reduce the use of by using cannabis? (Please select all that apply)'"
author: "David Ritter"
date: "2/25/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q45 <- 'What.prescription.medications.are.you.currently.taking.for.the.health.conditions.and.symptoms.you.face.that.you.are.actively.trying.to.reduce.the.use.of.by.using.cannabis...Please.select.all.that.apply.'
q45_final_response <- "X.249"
q45_t <- "What prescription medications are you currently taking for the health conditions and symptoms you face that you are actively trying to reduce the use of by using cannabis? (Please select all that apply)"
q45_data <- get_choose_all(raw_data, q.name = q45, f.response = q45_final_response) %>%
  tidy_choose_all()
q45_n <- length(unique(q45_data$id))
q45_plot <- clean_choose_all(q45_data, q45_n)
r45 <- plot_choose_all(q45_plot, q45_t, q45_n)
r45
```

```{r}
q45_plot2 <- rbind(q45_plot, q45_t)
dir.create("output/q45_meds_reduced_cannabis")
ggsave(filename = 'output/q45_meds_reduced_cannabis/q45_meds_reduced_cannabis.png', plot = r45, device = 'png')
write.csv(q45_plot2, paste0("output/q45_meds_reduced_cannabis/q45_meds_reduced_cannabis_", q45_n,".csv"), row.names=F)
write.csv(q45_data, 'output/q45_meds_reduced_cannabis/q45_meds_reduced_cannabis_ids.csv', row.names = FALSE)
```




```{r}
qf_data <- q_data %>%
  filter(chosen == "Response text")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")

qf_n <- length(unique(qf_all_data$id))

qf_data <- qf_all_data[3] %>%
  group_by(chosen) %>%
  summarize(count=n()) %>%
  mutate(percent_responded = round(100*(count / qf_n), 2)) %>%
  arrange(desc(count))
```

```{r}
q_plot <- clean_choose_all_f2(qf_data)
r <- plot_choose_all_f2(q_plot)
r
```

```{r}
q_plot2 <- rbind(q_plot, t)
dir.create("output/q45_meds_reduced_cannabis")
ggsave(filename = 'output/q45_meds_reduced_cannabis/q45_meds_reduced_cannabis.png', plot = r, device = 'png')
write.csv(q_plot2, paste0("output/q45_meds_reduced_cannabis/q45_meds_reduced_cannabis_", qf_n,".csv"), row.names=F)
write.csv(qf_all_data, 'output/q45_meds_reduced_cannabis/q45_meds_reduced_cannabis_ids.csv', row.names = FALSE)
```