---
title: "q46 'Please rate the severity of the side effects you have faced with prescription medications compared to cannabis treatments:'"
author: "David Ritter"
date: "2/25/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q46 <- "Please.rate.the.severity.of.the.side.effects.you.have.faced.with.prescription.medications.compared.to.cannabis.treatments."
q46_t <- "Please rate the severity of the side effects you have faced with prescription medications compared to cannabis treatments:"
q46_data <- get_single_selection_0(data = raw_data, q.name = q46)
q46_n <- length(unique(q46_data$id))
q46_mean_data <- as.numeric(as.character(q46_data$response))
q46_mean <- mean(q46_mean_data) %>%
  round(3) %>%
  print()
q46_plot<- clean_single_select(q46_data)
r46 <- plot_single_select_0(q46_plot, q46_t, q46_n, q46_mean)
r46
```

```{r}
q46_plot2 <- rbind(q46_plot, q46_t, paste("average", q46_mean, sep = " = "))
dir.create("output/q46_side_effects_cannabis_v_med")
ggsave(filename = 'output/q46_side_effects_cannabis_v_med/q46_side_effects_cannabis_v_med.png', plot = r46, device = 'png')
write.csv(q46_plot2, paste0("output/q46_side_effects_cannabis_v_med/q46_side_effects_cannabis_v_med_", q46_n,".csv"), row.names=F)
write.csv(q46_data, 'output/q46_side_effects_cannabis_v_med/q46_side_effects_cannabis_v_med_ids.csv', row.names = FALSE)
```




```{r}
qf_data <- q_data %>%
  filter(response == "Response text")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")
qf_mean_data <- as.numeric(as.character(qf_all_data$response.y))
q46f_mean <- mean(qf_mean_data) %>%
  round(3) %>%
  print()
qf_n <- length(unique(qf_all_data$id))
```

```{r}
q_plot <- clean_single_select_y(qf_all_data)
r <- plot_single_select_y(q_plot)
r
```

```{r}
q_plot2 <- rbind(q_plot, t, paste("average", q46f_mean, sep = " = "))
dir.create("output/q46_side_effects_cannabis_v_med")
ggsave(filename = 'output/q46_side_effects_cannabis_v_med/q46_side_effects_cannabis_v_med.png', plot = r, device = 'png')
write.csv(q_plot2, paste0("output/q46_side_effects_cannabis_v_med/q46_side_effects_cannabis_v_med_", qf_n,".csv"), row.names=F)
write.csv(qf_all_data, 'output/q46_side_effects_cannabis_v_med/q46_side_effects_cannabis_v_med_ids.csv', row.names = FALSE)
```


