---
title: "Q48 Top Preferred Method"
author: "DJ"
date: "May 22, 2019"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
# Read in raw data. These are the files downloaded from survey monkey saved as a .csv

raw_data_general <- read.csv("data/general_text.csv", stringsAsFactors = FALSE)
raw_data_botanist <- read.csv("data/botanist_text.csv", stringsAsFactors = FALSE)
raw_data_bask <- read.csv("data/bask_text.csv", stringsAsFactors = FALSE)
raw_data_healing_rose <- read.csv("data/healing_rose_text.csv", stringsAsFactors = FALSE)
```

```{r}
# Pull out all responses for Q48 (a single selection question) and combine

Q48 <- "What.is.your.top.preferred.method..that.is..favorite.method..of.using.cannabis...Please.select.one."

Q48_general <- get_single_selection(data = raw_data_general, q.name = Q48)
Q48_bask <- get_single_selection(data = raw_data_bask, q.name = Q48)
Q48_botanist <- get_single_selection(data = raw_data_botanist, q.name = Q48)
Q48_healing_rose <- get_single_selection(data = raw_data_healing_rose, q.name = Q48)

Q48_all <- rbind(Q48_general, Q48_bask, Q48_botanist, Q48_healing_rose)
  
## Determine Question N

number_of_people <- length(unique(Q48_all$id))

```

```{r}

for_plot <- 
  Q48_all %>%
  group_by(response) %>%
  summarize(count = n()) %>%
  mutate(percent_all = count / sum(count)) %>%
  mutate(percent_responded = count / number_of_people)

```

```{r}
# Plot with percents and response counts

r <- 
  ggplot(for_plot, aes(x = reorder(response, count), y = percent_responded)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  geom_text(aes(label= paste(round(percent_responded, 2), count, sep = "***")))

r

```

```{r}

ggsave(filename = 'Q48_Top_Preferred_Method.png', plot = r, device = 'png')

write.csv(for_plot, 'Q48_Top_Preferred_Method_155.277.csv', row.names = FALSE)

write.csv(Q48_all, 'Q48_Responses_ID.csv', row.names = FALSE)

```
