---
title: "q49 Please rate the importance of the following aspects of cannabis products to you" 
author: "David Ritter"
date: "2/22/2020"
output: html_document
runtime: shiny
---
 
```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q <- "Please.rate.the.importance.of.the.following.aspects.ofÂ.cannabis.products.to.you."
q_final_response <- "X.267"
t <- "Please rate the importance of the following aspects of cannabis products to you"
q_data <- get_choose_all(raw_data, q.name = q, f.response = q_final_response)
dir.create("output/q49_cannabis_aspect_importance")
```

```{r}
write.csv(q_data, 'output/q49_cannabis_aspect_importance/q49_cannabis_aspect_importance_data.csv', row.names = FALSE)
```

```{r}
table_1 <- get_single_selection_2(q_data, "THC content - Importance") %>%
  filter(response != "N/A") %>%
  clean_single_select_2()
q_n <- tally(table_1, count)
r1 <- plot_single_select(table_1) +
  labs(title = "THC content", subtitle = q_n)
r1
```

```{r}
ggsave(filename = "output/q49_cannabis_aspect_importance/q49_thc.png", plot = r1, device = 'png')
write.csv(table_1, paste0("output/q49_cannabis_aspect_importance/q49_thc_", q_n, ".csv"), row.names = FALSE)
```

```{r}
table_2 <- get_single_selection_2(q_data, "CBD content - Importance") %>%
  filter(response != "N/A") %>%
  clean_single_select_2()
q_n <- tally(table_2, count)
r2 <- plot_single_select(table_2) +
  labs(title = "CBD content", subtitle = q_n)
r2
```

```{r}
ggsave(filename = "output/q49_cannabis_aspect_importance/q49_cbd.png", plot = r2, device = 'png')
write.csv(table_2, paste0("output/q49_cannabis_aspect_importance/q49_cbd_", q_n, ".csv"), row.names = FALSE)
```

```{r}
table_3 <- get_single_selection_2(q_data, "Other cannabinoids and terpenes - Importance") %>%
  filter(response != "N/A") %>%
  clean_single_select_2()
q_n <- tally(table_3, count)
r3 <- plot_single_select(table_3) +
  labs(title = "Other cannabinoids and terpenes", subtitle = q_n)
r3
```

```{r}
ggsave(filename = "output/q49_cannabis_aspect_importance/q49_other_cbd.png", plot = r3, device = 'png')
write.csv(table_3, paste0("output/q49_cannabis_aspect_importance/q49_other_cbd_", q_n, ".csv"), row.names = FALSE)
```

```{r}
table_4 <- get_single_selection_2(q_data, "Cost/price - Importance") %>%
  filter(response != "N/A") %>%
  clean_single_select_2()
q_n <- tally(table_4, count)
r4 <- plot_single_select(table_4) +
  labs(title = "Cost/price - Importance", subtitle = q_n)
r4
```

```{r}
ggsave(filename = "output/q49_cannabis_aspect_importance/q49_cost.png", plot = r4, device = 'png')
write.csv(table_4, paste0("output/q49_cannabis_aspect_importance/q49_cost_", q_n, ".csv"), row.names = FALSE)
```

```{r}
table_5 <- get_single_selection_2(q_data, "Quality - Importance") %>%
  filter(response != "N/A") %>%
  clean_single_select_2()
q_n <- tally(table_5, count)
r5 <- plot_single_select(table_5) +
  labs(title = "Quality - Importance", subtitle = q_n)
r5
```

```{r}
ggsave(filename = "output/q49_cannabis_aspect_importance/q49_quality.png", plot = r5, device = 'png')
write.csv(table_5, paste0("output/q49_cannabis_aspect_importance/q49_quality_", q_n, ".csv"), row.names = FALSE)
```

```{r}
table_6 <- get_single_selection_2(q_data, "Product type (flower, vape cartridge, edibles, etc.) - Importance") %>%
  filter(response != "N/A") %>%
  clean_single_select_2()
q_n <- tally(table_6, count)
r6 <- plot_single_select(table_6) +
  labs(title = "Product type (flower, vape cartridge, edibles, etc.)", subtitle = q_n)
r6
```

```{r}
ggsave(filename = "output/q49_cannabis_aspect_importance/q49_product_type.png", plot = r6, device = 'png')
write.csv(table_6, paste0("output/q49_cannabis_aspect_importance/q49_product_type_", q_n, ".csv"), row.names = FALSE)
```

```{r}
table_7 <- get_single_selection_2(q_data, "Favorite strain - Importance") %>%
  filter(response != "N/A") %>%
  clean_single_select_2()

q_n <- tally(table_7, count)

r7 <- plot_single_select(table_7) +
  labs(title = "Favorite strain - Importance", subtitle = q_n)
r7
```

```{r}
ggsave(filename = "output/q49_cannabis_aspect_importance/q49_favorite_strain.png", plot = r7, device = 'png')
write.csv(table_7, paste0("output/q49_cannabis_aspect_importance/q49_favorite_strain_", q_n, ".csv"), row.names = FALSE)
```

```{r}
table_8 <- get_single_selection_2(q_data, "Other - Importance") %>%
  filter(response != "N/A") %>%
  clean_single_select_2()

q_n <- tally(table_8, count)

r8 <- plot_single_select(table_8) +
  labs(title = "Other - Importance", subtitle = q_n)
r8
```

```{r}
ggsave(filename = "output/q49_cannabis_aspect_importance/q49_other.png", plot = r8, device = 'png')
write.csv(table_8, paste0("output/q49_cannabis_aspect_importance/q49_other_", q_n, ".csv"), row.names = FALSE)
```