---
title: "q4 'How would you rate your quality of health today?'"
author: "David Ritter"
date: "2/28/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q4 <- "How.would.you.rate.your.quality.of.health.today."
q4_t <- "How would you rate your quality of health today?"
q4_data <- get_single_selection(data = raw_data, q.name = q4)
q4_n <- length(unique(q4_data$id))
q4_plot <- clean_single_select(q4_data)
r4 <- plot_single_select(q4_plot, q4_t, q4_n)
r4
```

```{r}
row3 <- colnames(q4_plot)
q4_plot2 <- rbind(row3, q4_plot)
names(q4_plot2) <- c("q4", q4_t, paste("n = ", q4_n))
```

```{r}
dir.create("output/q4_health_quality")
ggsave(filename = 'output/q4_health_quality/q4_health_quality.png', plot = r4, device = 'png')
write.csv(q4_plot2, paste0("output/q4_health_quality/q4_health_quality_", q4_n,".csv"), row.names=F)
```







```{r}
qf_data <- q_data %>%
  filter(response == "Fair")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")
qf_n <- length(unique(qf_all_data$id))
q_plot <- clean_single_select_y(qf_all_data)
r <- plot_single_select_y(q_plot)
r
```

```{r}
q_plot2 <- rbind(q_plot, t)
dir.create("output/q4_health_quality")
ggsave(filename = 'output/q4_health_quality/q4_health_quality.png', plot = r, device = 'png')
write.csv(q_plot2, paste0("output/q4_health_quality/q4_health_quality_", qf_n,".csv"), row.names=F)
```
