---
title: "q50 'How many days do you use cannabis per week? (Please select one)'"
author: "David Ritter"
date: "2/28/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q50 <- "How.many.days.do.you.use.cannabis.per.week...Please.select.one."
q50_t <- "How many days do you use cannabis per week? (Please select one)"
q50_data <- get_single_selection(data = raw_data, q.name = q50)
q50_n <- length(unique(q50_data$id))
q50_plot<- clean_single_select(q50_data)
r50 <- plot_single_select(q50_plot, q50_t, q50_n)
r50
```

```{r}
row3 <- colnames(q50_plot)
q50_plot2 <- rbind(row3, q50_plot)
names(q50_plot2) <- c("q50", q50_t, paste("n = ", q50_n))
```

```{r}
dir.create("output/q50_cannabis_days_per_wk")
ggsave(filename = 'output/q50_cannabis_days_per_wk/q50_cannabis_days_per_wk.png', plot = r50, device = 'png')
write.csv(q50_plot2, paste0("output/q50_cannabis_days_per_wk/q50_cannabis_days_per_wk_", q50_n,".csv"), row.names=F)
```







```{r}
qf_data <- q_data %>%
  filter(response == "Multiple times every day")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")
qf_n <- length(unique(qf_all_data$id))
q_plot <- clean_single_select_y(qf_all_data)
r <- plot_single_select_y(q_plot)
r
```

```{r}
q_plot2 <- rbind(q_plot, t)
dir.create("output/q50_cannabis_days_per_wk")
ggsave(filename = 'output/q50_cannabis_days_per_wk/q50_cannabis_days_per_wk.png', plot = r, device = 'png')
write.csv(q_plot2, paste0("output/q50_cannabis_days_per_wk/q50_cannabis_days_per_wk_", qf_n,".csv"), row.names=F)
```
