---
title: "q52 'On days you regularly use cannabis, how many times per day do you use cannabis?'"
author: "David Ritter"
date: "2/28/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q52 <- "On.days.you.regularly.use.cannabis..how.many.times.per.day.do.you.use.cannabis."
q52_t <- "On days you regularly use cannabis, how many times per day do you use cannabis?"
q52_data <- get_single_selection(data = raw_data, q.name = q52)
q52_n <- length(unique(q52_data$id))
q52_plot<- clean_single_select(q52_data)
r52 <- plot_single_select(q52_plot, q52_t, q52_n)
r52
```

```{r}
row3 <- colnames(q52_plot)
q52_plot2 <- rbind(row3, q52_plot)
names(q52_plot2) <- c("q52", q52_t, paste("n = ", q52_n))
```

```{r}
dir.create("output/q52_use_times_per_day")
ggsave(filename = 'output/q52_use_times_per_day/q52_use_times_per_day.png', plot = r52, device = 'png')
write.csv(q52_plot2, paste0("output/q52_use_times_per_day/q52_use_times_per_day_", q52_n,".csv"), row.names=F)
```







```{r}
qf_data <- q_data %>%
  filter(response == "1 time")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")
qf_n <- length(unique(qf_all_data$id))
q_plot <- clean_single_select_y(qf_all_data)
r <- plot_single_select_y(q_plot)
r
```

```{r}
q_plot2 <- rbind(q_plot, t)
dir.create("output/q52_use_times_per_day")
ggsave(filename = 'output/q52_use_times_per_day/q52_use_times_per_day.png', plot = r, device = 'png')
write.csv(q_plot2, paste0("output/q52_use_times_per_day/q52_use_times_per_day_", qf_n,".csv"), row.names=F)
```
