---
title: "q53 'On average, how much do you spend (in US dollars) on consumable cannabis products per week?'"
author: "David Ritter"
date: "2/25/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q53 <- "On.average..how.much.do.you.spend..in.US.dollars..on.consumable.cannabis.products.per.week."
q53_t <- "On average, how much do you spend (in US dollars) on consumable cannabis products per week?"
q53_data <- get_single_selection_0(data = raw_data, q.name = q53) %>%
  filter(response != "")
q53_n <- length(unique(q53_data$id))
q53_mean_data <- as.numeric(as.character(q53_data$response))
q53_mean <- mean(q53_mean_data) %>%
  round(3) %>%
  print()
q53_plot<- clean_single_select(q53_data)
r53 <- plot_single_select_0(q53_plot, q53_t, q53_n, q53_mean)
r53
```

```{r}
q53_plot2 <- rbind(q53_plot, q53_t, paste("average", q53_mean, sep = " = "))
dir.create("output/q53_cannabis_cost_wkly")
ggsave(filename = 'output/q53_cannabis_cost_wkly/q53_cannabis_cost_wkly.png', plot = r53, device = 'png')
write.csv(q53_plot2, paste0("output/q53_cannabis_cost_wkly/q53_cannabis_cost_wkly_", q53_n,".csv"), row.names=F)
write.csv(q53_data, 'output/q53_cannabis_cost_wkly/q53_cannabis_cost_wkly_ids.csv', row.names = FALSE)
```




```{r}
qf_data <- q_data %>%
  filter(response == "Response")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")
qf_mean_data <- as.numeric(as.character(qf_all_data$response.y))
q53f_mean <- mean(qf_mean_data) %>%
  round(3) %>%
  print()
qf_n <- length(unique(qf_all_data$id))
```

```{r}
q_plot <- clean_single_select_y(qf_all_data)
r <- plot_single_select_y(q_plot)
r
```

```{r}
q_plot2 <- rbind(q_plot, t, paste("average", q53f_mean, sep = " = "))
dir.create("output/q53_cannabis_cost_wkly")
ggsave(filename = 'output/q53_cannabis_cost_wkly/q53_cannabis_cost_wkly.png', plot = r, device = 'png')
write.csv(q_plot2, paste0("output/q53_cannabis_cost_wkly/q53_cannabis_cost_wkly_", qf_n,".csv"), row.names=F)
write.csv(qf_all_data, 'output/q53_cannabis_cost_wkly/q53_cannabis_cost_wkly_ids.csv', row.names = FALSE)
```