---
title: "q54 'What percent of your monthly purchases are through regulated sources (dispensary, retail establishment, caregiver/authorized private cultivator)?'"
author: "David Ritter"
date: "2/28/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q54 <- "What.percent.of.your.monthly.purchases.are.through.regulated.sources..dispensary..retail.establishment..caregiver.authorized.private.cultivator.."
q54_t <- "What percent of your monthly purchases are through regulated sources (dispensary, retail establishment, caregiver/authorized private cultivator)?"
q_data <- get_single_selection_0(data = raw_data, q.name = q54) %>%
  filter(response != "")
q54_n <- length(unique(q_data$id))
q54_mean_data <- as.numeric(as.character(q_data$response))
q54_mean <- mean(q54_mean_data) %>%
  round(3) %>%
  print()
q54_plot<- clean_single_select(q_data)
r54 <- plot_single_select_0(q54_plot, q54_t, q54_n, q54_mean)
r54
```

```{r}
row3 <- colnames(q54_plot)
q54_plot2 <- rbind(row3, q54_plot)
names(q54_plot2) <- c("q54", q54_t, paste("n = ", q54_n, paste(" avg = ", q54_mean)))
```

```{r}
dir.create("output/q54_purchase_sources")
ggsave(filename = 'output/q54_purchase_sources/q54_purchase_sources.png', plot = r54, device = 'png')
write.csv(q54_plot2, paste0("output/q54_purchase_sources/q54_purchase_sources_", q54_n,".csv"), row.names=F)
write.csv(q_data, 'output/q54_purchase_sources/q54_purchase_sources_ids.csv', row.names = FALSE)
```







```{r}
qf_data <- q_data %>%
  filter(response == "Response text")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")
qf_mean_data <- as.numeric(as.character(qf_all_data$response.y))
q54f_mean <- mean(qf_mean_data) %>%
  round(3) %>%
  print()
qf_n <- length(unique(qf_all_data$id))
```

```{r}
q_plot <- clean_single_select_y(qf_all_data)
r <- plot_single_select_y(q_plot)
r
```

```{r}
q_plot2 <- rbind(q_plot, t, paste("average", q54f_mean, sep = " = "))
dir.create("output/q54_purchase_sources")
ggsave(filename = 'output/q54_purchase_sources/q54_purchase_sources.png', plot = r, device = 'png')
write.csv(q_plot2, paste0("output/q54_purchase_sources/q54_purchase_sources_", qf_n,".csv"), row.names=F)
write.csv(qf_all_data, 'output/q54_purchase_sources/q54_purchase_sources_ids.csv', row.names = FALSE)
```
