---
title: "q55 'Do you grow your own cannabis at home?'"
author: "David Ritter"
date: "2/18/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q <- "Do.you.grow.your.own.cannabis.at.home."
t <- "Do you grow your own cannabis at home?"
q_data <- get_single_selection(data = raw_data, q.name = q)
q_n <- length(unique(q_data$id))
```

```{r}
q_plot<- clean_single_select(q_data)
r <- plot_single_select(q_plot)
r
```

```{r}
# Save graph as PNG, plot data as csv, and all question data including response IDs as csv (save question n and N at end of plot file as "_x.x")
ggsave(filename = 'q55_home_grow.png', plot = r, device = 'png')

write.csv(q_plot, 'q55_home_grow_144.csv', row.names = FALSE)

write.csv(q_data, 'q55_home_grow_ids.csv', row.names = FALSE)
```

```{r}
qf_data <- q_data %>%
  filter(response == "No")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")

qf_n <- length(unique(qf_all_data$id))
```

```{r}
q_plot <- clean_single_select_f(qf_all_data)
r <- plot_single_select_f(q_plot)
r
```

```{r}
ggsave(filename = 'q55_home_grow.png', plot = r, device = 'png')
write.csv(q_plot, 'q55_home_grow_n#.csv', row.names = FALSE)
```