---
title: "q57 'What product(s) and/or strain(s) do you want that are not currently available in your local dispensaries?'"
author: "David Ritter"
date: "2/22/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q <- "What.product.s..and.or.strain.s..do.you.want.that.are.not.currently.available.in.your.local.dispensaries."
t <- "What product(s) and/or strain(s) do you want that are not currently available in your local dispensaries?"
q_data <- get_single_selection_0(data = raw_data, q.name = q)
q_n <- length(unique(q_data$id))
q_plot<- clean_single_select(q_data)
```

```{r}
q_plot2 <- rbind(q_plot, t)
dir.create("output/q57_products_desired")
ggsave(filename = 'output/q57_products_desired/q57_products_desired.png', plot = r, device = 'png')
write.csv(q_plot2, paste0("output/q57_products_desired/q57_products_desired_", q_n,".csv"), row.names=F)
```