---
title: "q58 'Are you concerned about your family members or loved ones knowing about your cannabis use?'"
author: "David Ritter"
date: "2/28/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q58 <- "Are.you.concerned.about.your.family.members.or.loved.ones.knowing.about.your.cannabis.use."
q58_t <- "Are you concerned about your family members or loved ones knowing about your cannabis use?"
q58_data <- get_single_selection(data = raw_data, q.name = q58)
q58_n <- length(unique(q58_data$id))
q58_plot<- clean_single_select(q58_data)
r58 <- plot_single_select(q58_plot, q58_t, q58_n)
r58
```

```{r}
row3 <- colnames(q58_plot)
q58_plot2 <- rbind(row3, q58_plot)
names(q58_plot2) <- c("q58", q58_t, paste("n = ", q58_n))
```

```{r}
dir.create("output/q58_family_cannabis_acceptence")
ggsave(filename = 'output/q58_family_cannabis_acceptence/q58_family_cannabis_acceptence.png', plot = r58, device = 'png')
write.csv(q58_plot2, paste0("output/q58_family_cannabis_acceptence/q58_family_cannabis_acceptence_", q58_n,".csv"), row.names=F)
```







```{r}
qf_data <- q_data %>%
  filter(response == "No")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")
qf_n <- length(unique(qf_all_data$id))
q_plot <- clean_single_select_y(qf_all_data)
r <- plot_single_select_y(q_plot)
r
```

```{r}
q_plot2 <- rbind(q_plot, t)
dir.create("output/q58_family_cannabis_acceptence")
ggsave(filename = 'output/q58_family_cannabis_acceptence/q58_family_cannabis_acceptence.png', plot = r, device = 'png')
write.csv(q_plot2, paste0("output/q58_family_cannabis_acceptence/q58_family_cannabis_acceptence_", qf_n,".csv"), row.names=F)
```


