---
title: "q61 'Do you face any of the following barriers for you to consume cannabis (Please select all that apply)'"
author: "David Ritter"
date: "2/15/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
# Load libraries
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
# Read in raw data from the Veterans surveys. These are the files downloaded from survey monkey saved as a .csv
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
# Pull out all responses for q5 (a choose all question), combine, turn into a tidy data format for further processing then d <- tidy_choose_all(q)etermine 'question n'
q <- 'Do.you.face.any.of.the.following.barriers.for.you.to.consume.cannabis...Please.select.all.that.apply.'
q_final_response <- "X.279"

q_data <- get_choose_all(raw_data, q.name = q, f.response = q_final_response) %>%
  tidy_choose_all()

q_n <- length(unique(q_data$id))
```

```{r}
#Pass q_data to clean_data to create q_plot. Then pass q_plot through clean_plot to produce plot.
q_plot<- clean_choose_all(q_data)

plot_choose_all(q_plot) +
  labs(title = "Do you face any of the following barriers for you to consume cannabis (Please select all that apply)", subtitle = q_n)
```

```{r}
# Save data with N
ggsave(filename = 'q61_barriers.png', plot = r, device = 'png')

write.csv(q_plot, 'q61_barriers_217.csv', row.names = FALSE)

write.csv(q_data, 'q61_barrers_ids.csv', row.names = FALSE)
```
