---
title: "How much cannabis flower are you smoking or vaping per week (ie. grams, ounces, etc)?"
author: "David Ritter"
date: "2/16/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
# Load libraries
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q <- 'How.much.cannabis.flower.are.you.smoking.or.vaping.per.week...i.e..grams..ounces..etc..'
q_final_response <- "X.283"

q_data <- get_choose_all(raw_data, q.name = q, f.response = q_final_response)
```

```{r}
table_1 <- get_single_selection_2(q_data, "Smoke flower") %>%
  filter(response != "N/A") %>%
  clean_single_select_2()

table_1_n <- tally(table_1, count)

r1 <- plot_single_select(table_1) +
  labs(title = "Flower weekly", subtitle = table_1_n)
r1
```

```{r}
table_2 <- get_single_selection_2(q_data, "Vape flower") %>%
  filter(response != "N/A") %>%
  clean_single_select_2()

table_2_n <- tally(table_2, count)

r2 <- plot_single_select(table_2) +
  labs(title = "Vape weekly", subtitle = table_2_n)
r2
```

```{r}
table_3 <- get_single_selection_2(q_data, "Concentrates (e.g. rosin, shatter, wax, hash, kief)") %>%
  filter(response != "N/A") %>%
  clean_single_select_2()

table_3_n <- tally(table_3, count)

r3 <- plot_single_select(table_3) +
  labs(title = "Concentrates weekly", subtitle = table_2_n)
r3
```

```{r}
# Save graph as PNG, plot data as csv, and all question data including response IDs as csv (save question n and N at end of plot file as "_x.x")
ggsave(filename = 'q62_flower_wkly.png', plot = r1, device = 'png')
write.csv(table_1, 'q62_flower_wkly_xx.csv', row.names = FALSE)

ggsave(filename = 'q62_vape_wkly.png', plot = r2, device = 'png')
write.csv(table_2, 'q62_vape_wkly_xx.csv', row.names = FALSE)

ggsave(filename = 'q62_concentrates_wkly.png', plot = r3, device = 'png')
write.csv(table_3, 'q62_concentrates_wkly_xx.csv', row.names = FALSE)
```










```{r}
# Save graph as PNG, plot data as csv, and all question data including response IDs as csv (save question n and N at end of plot file as "_x.x")
ggsave(filename = 'q62_smoke_vape_wkly.png', plot = r, device = 'png')

write.csv(q_plot, 'q62_smoke_vape_wkly_144.csv', row.names = FALSE)

write.csv(q_data, 'q62_smoke_vape_wkly_ids.csv', row.names = FALSE)
```


```{r}
#OPTIONAL Filter one response, then move to process qf_data in the code of the other question being analyzed
qf_data <- filter(q_data, chosen == "Response")
```

```{r}
#OPTIONAL FILTERING!!!  Filter out responses from non-selected IDs. Run after step that generates q_data.
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")

q_n <- length(unique(qf_all_data$id))
```

```{r}
#OPTIONAL FILTERING!!!
q_plot<- clean_choose_all(qf_all_data)

r <- plot_choose_all(q_plot) +
  labs(title = "Which health conditions do you find cannabis to be helpful in treating? (Please select all that apply)", subtitle = q_n)
r
```

```{r}
# Save graph as PNG, plot data as csv, and all question data including response IDs as csv (save question n and N at end of plot file as "_x.x")
ggsave(filename = 'q#_qtext.png', plot = r, device = 'png')

write.csv(q_plot, 'q#_qtext_XX.csv', row.names = FALSE)

write.csv(qf_all_data, 'q#_qtext_ids.csv', row.names = FALSE)
```
