---
title: "How much cannabis flower are you smoking or vaping per week (ie. grams, ounces, etc)?"
author: "David Ritter"
date: "2/22/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q <- 'How.much.cannabis.flower.are.you.smoking.or.vaping.per.week...i.e..grams..ounces..etc..'
q_final_response <- "X.283"
q_data <- get_choose_all(raw_data, q.name = q, f.response = q_final_response)
dir.create("output/q62_smoke_vape_wkly")
```

```{r}
write.csv(q_data, 'output/q62_smoke_vape_wkly/q62_smoke_vape_wkly_data.csv', row.names = FALSE)
```

```{r}
table_1 <- get_single_selection_2(q_data, "Smoke flower") %>%
  filter(response != "N/A") %>%
  clean_single_select_2()
q_n <- tally(table_1, count)
r1 <- plot_single_select(table_1) +
  labs(title = "Flower weekly", subtitle = q_n)
r1
```

```{r}
ggsave(filename = "output/q62_smoke_vape_wkly/smoke_flower.png", plot = r1, device = 'png')
write.csv(table_1, paste0("output/q62_smoke_vape_wkly/smoke_flower_", q_n, ".csv"), row.names = FALSE)
```

```{r}
table_2 <- get_single_selection_2(q_data, "Vape flower") %>%
  filter(response != "N/A") %>%
  clean_single_select_2()
q_n <- tally(table_2, count)
r2 <- plot_single_select(table_2) +
  labs(title = "Vape weekly", subtitle = q_n)
r2
```

```{r}
ggsave(filename = "output/q62_smoke_vape_wkly/vape_flower.png", plot = r2, device = 'png')
write.csv(table_2, paste0("output/q62_smoke_vape_wkly/vape_flower_", q_n, ".csv"), row.names = FALSE)
```

```{r}
table_3 <- get_single_selection_2(q_data, "Concentrates (e.g. rosin, shatter, wax, hash, kief)") %>%
  filter(response != "N/A") %>%
  clean_single_select_2()
q_n <- tally(table_3, count)
r3 <- plot_single_select(table_3) +
  labs(title = "Concentrates weekly", subtitle = q_n)
r3
```

```{r}
ggsave(filename = "output/q62_smoke_vape_wkly/concentrates.png", plot = r3, device = 'png')
write.csv(table_3, paste0("output/q62_smoke_vape_wkly/concentrates_", q_n, ".csv"), row.names = FALSE)
```

