---
title: "How many milligrams of cannabis do you use per week?"
author: "David Ritter"
date: "2/25/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q63 <- 'How.many.milligrams.of.cannabis.do.you.use.per.week.'
q63_final_response <- "X.297"
q63_t <- "How many milligrams of cannabis do you use per week?"
q63_data <- get_choose_all(raw_data, q.name = q63, f.response = q63_final_response)
dir.create("output/q63_mg_edibles_etc")
```

```{r}
write.csv(q63_data, 'output/q63_mg_edibles_etc/q63_mg_edibles_etc_data.csv', row.names = FALSE)
```

```{r}
q63_data1 <- get_single_selection_3(q63_data, "Edibles (e.g. gummies, chocolate, lozenges, beverages, cooking oils, etc.)") %>%
  filter(response != "") %>%
  clean_single_select()
q63_n1 <- tally(q63_data1, count)
q63_t1 <- "Edibles (e.g. gummies, chocolate, lozenges, beverages, cooking oils, etc.)"
q63_r1 <- plot_single_select(q63_data1, q63_t1, q63_n1)
q63_r1
```

```{r}
ggsave(filename = "output/q63_mg_edibles_etc/q63_edibles.png", plot = q63_r1, device = 'png')
write.csv(q63_data1, paste0("output/q63_mg_edibles_etc/q63_edibles_", q63_n1, ".csv"), row.names = FALSE)
```

```{r}
q63_data2 <- get_single_selection_3(q63_data, "Transdermal patches") %>%
  filter(response != "") %>%
  clean_single_select()
q63_n2 <- tally(q63_data2, count)
q63_t2 <- "Transdermal patches"
q63_r2 <- plot_single_select(q63_data2, q63_t2, q63_n2)
q63_r2
```

```{r}
ggsave(filename = "output/q63_mg_edibles_etc/q63_patches.png", plot = q63_r2, device = 'png')
write.csv(q63_data2, paste0("output/q63_mg_edibles_etc/q63_patches_", q63_n2, ".csv"), row.names = FALSE)
```

```{r}
q63_data3 <- get_single_selection_3(q63_data, "Suppositories") %>%
  filter(response != "") %>%
  clean_single_select()
q63_n3 <- tally(q63_data3, count)
q63_t3 <- "Suppositories"
q63_r3 <- plot_single_select(q63_data3, q63_t3, q63_n3)
q63_r3
```

```{r}
ggsave(filename = "output/q63_mg_edibles_etc/q63_suppositories.png", plot = q63_r3, device = 'png')
write.csv(q63_data3, paste0("output/q63_mg_edibles_etc/q63_suppositories_", q63_n3, ".csv"), row.names = FALSE)
```

```{r}
q63_data4 <- get_single_selection_3(q63_data, "Capsules") %>%
  filter(response != "") %>%
  clean_single_select()
q63_n4 <- tally(q63_data4, count)
q63_t4 <- "Capsules"
q63_r4 <- plot_single_select(q63_data4, q63_t4, q63_n4)
q63_r4
```

```{r}
ggsave(filename = "output/q63_mg_edibles_etc/q63_capsules.png", plot = q63_r4, device = 'png')
write.csv(q63_data4, paste0("output/q63_mg_edibles_etc/q63_capsules_", q63_n4, ".csv"), row.names = FALSE)
```