---
title: "Q66_VA_Cannabis_Use_Knowledge"
runtime: shiny
output: html_document
---


```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
source("helper.R")
```


```{r}
# Read in raw data. These are the files downloaded from survey monkey saved as a .csv

raw_data_general <- read.csv("data/general_text.csv", stringsAsFactors = FALSE)
raw_data_botanist <- read.csv("data/botanist_text.csv", stringsAsFactors = FALSE)
raw_data_bask <- read.csv("data/bask_text.csv", stringsAsFactors = FALSE)

```


```{r}
# Pull out all responses for Q66 (a single selection question) and combine

Q66 <- "Does.yourÂ.VA.doctor.or.clinical.care.provider.know.about.your.medical.cannabis.use."

Q66_general <- get_single_selection(data = raw_data_general, q.name = Q66)
Q66_bask <- get_single_selection(data = raw_data_bask, q.name = Q66)
Q66_botanist <- get_single_selection(data = raw_data_botanist, q.name = Q66)

Q66_all <- rbind(Q66_general, Q66_bask, Q66_botanist)

```

```{r}

Q66_plot <- 
  Q66_all %>%
  group_by(response) %>%
  summarize(count = n())

p <- 
  ggplot(Q66_plot, aes(x = reorder(response, count), y = count)) +
  geom_bar(stat = 'identity') + 
  coord_flip()

p

```

```{r}

ggsave(filename = 'Q66_VA_Cannabis_Use_Knowledge_PNG', plot = p, device = 'png')

```



