---
title: "q68 'Does your VA doctor or clinician support your cannabis use?'"
author: "David Ritter"
date: "2/15/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
# Load libraries
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q <- "Does.your.VA.doctor.or.clinician.supportÂ.yourÂ.cannabis.use."

q_data <- get_single_selection(data = raw_data, q.name = q)

q_n <- length(unique(q_data$id))
```

```{r}
#OPTIONAL: Filter one response, then move to process qf_data in the code of the other question being analyzed
qf_data <- filter(q_data, response != "Yes")

# Paste this into doc you are analyzing
#OPTIONAL FILTERING!!!
#qf_all_data <- 
  #qf_data %>%
  #inner_join(q_data, by = "id")

#q_n <- length(unique(qf_all_data$id))

```

```{r}
# Manipulate data into a graphable format
q_plot <-
  q_data %>%
  group_by(response) %>%
  summarize(count = n()) %>%
  mutate(percent_responded = round(100*(count / q_n), 2)) %>%
  arrange(desc(count))
```

```{r}
# Plot with percents and response counts
r <- 
  ggplot(q_plot, aes(x = reorder(response, count), y = percent_responded)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  geom_text(aes(label= paste(round(percent_responded, 0), count, sep = "%:"))) +
  xlab("Response") +
  ylab("% Responded, Count") +
  labs(title = "Does your VA doctor or clinician support your cannabis use?", subtitle = q_n)
r
```


```{r}
# Save graph as PNG, plot data as csv, and all question data including response IDs as csv (save question n and N at end of plot file as "_x.x")
ggsave(filename = 'q68_va_cannabis_use_support.png', plot = r, device = 'png')

write.csv(q_plot, 'q68_va_cannabis_use_support_202.csv', row.names = FALSE)

write.csv(q_data, 'q68_va_cannabis_use_support_info.csv', row.names = FALSE)
```