---
title: "q69 'How satisfied are you with the VA in managing your health condition?'"
author: "David Ritter"
date: "2/25/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q69 <- "How.satisfied.are.you.with.the.VA.in.managing.your.health.condition."
q69_t <- "How satisfied are you with the VA in managing your health condition?"
q69_data <- get_single_selection(data = raw_data, q.name = q69)
q69_n <- length(unique(q69_data$id))
q69_plot<- clean_single_select(q69_data)
r69 <- plot_single_select(q69_plot, q69_t, q69_n)
r69
```

```{r}
q69_plot2 <- rbind(q69_plot, q69_t)
dir.create("output/q69_va_satisfaction")
ggsave(filename = 'output/q69_va_satisfaction/q69_va_satisfaction.png', plot = r69, device = 'png')
write.csv(q69_plot2, paste0("output/q69_va_satisfaction/q69_va_satisfaction_", q69_n,".csv"), row.names=F)
```




```{r}
qf_data <- q_data %>%
  filter(response == "Response text")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")
qf_n <- length(unique(qf_all_data$id))
q_plot <- clean_single_select_y(qf_all_data)
r <- plot_single_select_y(q_plot)
r
```

```{r}
q_plot2 <- rbind(q_plot, t)
dir.create("output/q69_va_satisfaction")
ggsave(filename = 'output/q69_va_satisfaction/q69_va_satisfaction.png', plot = r, device = 'png')
write.csv(q_plot2, paste0("output/q69_va_satisfaction/q69_va_satisfaction_", qf_n,".csv"), row.names=F)
```

