---
title: "Q6xQ88_Top_Condition_by_Age"
author: "Neil Ritter"
date: "3/23/2019"
output: html_document
---




```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
```


```{r}
# Read in raw data. These are the files downloaded from survey monkey saved as a .csv
raw_data_general <- read.csv("data/general_text.csv", stringsAsFactors = FALSE)
raw_data_botanist <- read.csv("data/botanist_text.csv", stringsAsFactors = FALSE)
raw_data_bask <- read.csv("data/bask_text.csv", stringsAsFactors = FALSE)
```


```{r}

single_selection <- function(data, q.name)
  {
  responses <- 
    data %>%
    select(id = Respondent.ID, question = q.name) %>%
    slice(2:nrow(.)) %>%
    filter(question > 0)
  
  return(responses)
  }

```

```{r}

test <- single_selection(
  data = raw_data_general,
  q.name = "Which.is.the.primary.health.condition.that.causes.you.the.most.distress...Please.select.one.")


```

```{r}

  ## General
general <-
  single_selection(
    data = raw_data_general,
    q.name = "Which.is.the.primary.health.condition.that.causes.you.the.most.distress...Please.select.one.") %>%
  rename(condition = question) %>%
  inner_join(
    single_selection(
      data = raw_data_general,
      q.name = "What.is.your.age..in.years.."
    )
  )

  ## Bask
bask <-
  single_selection(
    data = raw_data_bask,
    q.name = "Which.is.the.primary.health.condition.that.causes.you.the.most.distress...Please.select.one.") %>%
  rename(condition = question) %>%
  inner_join(
    single_selection(
      data = raw_data_bask,
      q.name = "What.is.your.age..in.years.."
    )
  )


    ## Botanist
botanist <-
  single_selection(
    data = raw_data_botanist,
    q.name = "Which.is.the.primary.health.condition.that.causes.you.the.most.distress...Please.select.one.") %>%
  rename(condition = question) %>%
  inner_join(
    single_selection(
      data = raw_data_botanist,
      q.name = "What.is.your.age..in.years.."
    )
  )


```


```{r}

all <-
  rbind(general, bask, botanist)

```


```{r}

for_plot <-
  all %>%
  group_by(condition, question) %>%
  summarize(count = n())

```



```{r}

p <- 
  ggplot(for_plot, aes(x = condition, y = count)) +
  geom_bar(stat = "identity") +
  facet_wrap(~question) +
  coord_flip()

p

```








