---
title: "q70 'Where do you get your information to make informed decisions about cannabis products? (Please select all that apply)'"
author: "David Ritter"
date: "2/25/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q70 <- 'Where.do.you.get.your.information.to.make.informed.decisions.about.cannabis.products...Please.select.all.that.apply.'
q70_final_response <- "X.322"
q70_t <- "Where do you get your information to make informed decisions about cannabis products? (Please select all that apply)"
q70_data <- get_choose_all(raw_data, q.name = q70, f.response = q70_final_response) %>%
  tidy_choose_all()
q70_n <- length(unique(q70_data$id))
q70_plot <- clean_choose_all(q70_data, q70_n)
r70 <- plot_choose_all(q70_plot, q70_t, q70_n)
r70
```

```{r}
q70_plot2 <- rbind(q70_plot, q70_t)
dir.create("output/q70_cannabis_info")
ggsave(filename = 'output/q70_cannabis_info/q70_cannabis_info.png', plot = r70, device = 'png')
write.csv(q70_plot2, paste0("output/q70_cannabis_info/q70_cannabis_info_", q70_n,".csv"), row.names=F)
write.csv(q70_data, 'output/q70_cannabis_info/q70_cannabis_info_ids.csv', row.names = FALSE)
```




```{r}
qf_data <- q_data %>%
  filter(chosen == "Scientific literature")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")

qf_n <- length(unique(qf_all_data$id))

qf_data <- qf_all_data[3] %>%
  group_by(chosen) %>%
  summarize(count=n()) %>%
  mutate(percent_responded = round(100*(count / qf_n), 2)) %>%
  arrange(desc(count))
```

```{r}
q_plot <- clean_choose_all_f2(qf_data)
r <- plot_choose_all_f2(q_plot)
r
```

```{r}
q_plot2 <- rbind(q_plot, t)
dir.create("output/q70_cannabis_info")
ggsave(filename = 'output/q70_cannabis_info/q70_cannabis_info.png', plot = r, device = 'png')
write.csv(q_plot2, paste0("output/q70_cannabis_info/q70_cannabis_info_", qf_n,".csv"), row.names=F)
write.csv(qf_all_data, 'output/q70_cannabis_info/q70_cannabis_info_ids.csv', row.names = FALSE)
```
