---
title: "q72 'Which of the websites/apps is your primary source of information? (Please select one)'"
author: "David Ritter"
date: "2/28/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q72 <- "Which.of.the.websites.apps.is.your.primary.source.of.information...Please.select.one."
q72_t <- "Which of the websites/apps is your primary source of information? (Please select one)"
q72_data <- get_single_selection(data = raw_data, q.name = q72)
q72_n <- length(unique(q72_data$id))
q72_plot<- clean_single_select(q72_data)
r72 <- plot_single_select(q72_plot, q72_t, q72_n)
r72
```

```{r}
row3 <- colnames(q72_plot)
q72_plot2 <- rbind(row3, q72_plot)
names(q72_plot2) <- c("q72", q72_t, paste("n = ", q72_n))
```

```{r}
dir.create("output/q72_top_website_app")
ggsave(filename = 'output/q72_top_website_app/q72_top_website_app.png', plot = r72, device = 'png')
write.csv(q72_plot2, paste0("output/q72_top_website_app/q72_top_website_app_", q72_n,".csv"), row.names=F)
```







```{r}
qf_data <- q_data %>%
  filter(response == "Leafly")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")
qf_n <- length(unique(qf_all_data$id))
q_plot <- clean_single_select_y(qf_all_data)
r <- plot_single_select_y(q_plot)
r
```

```{r}
q_plot2 <- rbind(q_plot, t)
dir.create("output/q72_top_website_app")
ggsave(filename = 'output/q72_top_website_app/q72_top_website_app.png', plot = r, device = 'png')
write.csv(q_plot2, paste0("output/q72_top_website_app/q72_top_website_app_", qf_n,".csv"), row.names=F)
```

