---
title: "q79 'Were you exposed to any of the following during your service? (Please select all that apply)'"
author: "David Ritter"
date: "2/25/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q79 <- 'Were.you.exposed.to.any.of.the.following.during.your.service...Please.select.all.that.apply.'
q79_final_response <- "X.385"
q79_t <- "Were you exposed to any of the following during your service? (Please select all that apply)"
q79_data <- get_choose_all(raw_data, q.name = q79, f.response = q79_final_response) %>%
  tidy_choose_all()
q79_n <- length(unique(q79_data$id))
q79_plot <- clean_choose_all(q79_data, q79_n)
r79 <- plot_choose_all(q79_plot, q79_t, q79_n)
r79
```

```{r}
q79_plot2 <- rbind(q79_plot, q79_t)
dir.create("output/q79_service_exposure")
ggsave(filename = 'output/q79_service_exposure/q79_service_exposure.png', plot = r79, device = 'png')
write.csv(q79_plot2, paste0("output/q79_service_exposure/q79_service_exposure_", q79_n,".csv"), row.names=F)
write.csv(q79_data, 'output/q79_service_exposure/q79_service_exposure_ids.csv', row.names = FALSE)
```




```{r}
qf_data <- q_data %>%
  filter(chosen == "Response text")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")
qf_n <- length(unique(qf_all_data$id))
qf_data <- qf_all_data[3] %>%
  group_by(chosen) %>%
  summarize(count=n()) %>%
  mutate(percent_responded = round(100*(count / qf_n), 2)) %>%
  arrange(desc(count))
```

```{r}
q_plot <- clean_choose_all_f2(qf_data)
r <- plot_choose_all_f2(q_plot)
r
```

```{r}
q_plot2 <- rbind(q_plot, t)
dir.create("output/q79_service_exposure")
ggsave(filename = 'output/q79_service_exposure/q79_service_exposure.png', plot = r, device = 'png')
write.csv(q_plot2, paste0("output/q79_service_exposure/q79_service_exposure_", qf_n,".csv"), row.names=F)
write.csv(qf_all_data, 'output/q79_service_exposure/q79_service_exposure_ids.csv', row.names = FALSE)
```
