---
title: "q80 'Did you serve and/or live in an active combat zone?'"
author: "David Ritter"
date: "2/25/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q80 <- "Did.you.serve.and.or.live.in.an.active.combat.zone."
q80_t <- "Did you serve and/or live in an active combat zone?"
q80_data <- get_single_selection(data = raw_data, q.name = q80)
q80_n <- length(unique(q80_data$id))
q80_plot <- clean_single_select(q80_data)
r80 <- plot_single_select(q80_plot, q80_t, q80_n)
r80
```

```{r}
q80_plot2 <- rbind(q80_plot, q80_t)
dir.create("output/q80_active_combat_zones")
ggsave(filename = 'output/q80_active_combat_zones/q80_active_combat_zones.png', plot = r80, device = 'png')
write.csv(q80_plot2, paste0("output/q80_active_combat_zones/q80_active_combat_zones_", q80_n,".csv"), row.names=F)
```



```{r}
qf_data <- q_data %>%
  filter(response == "Response text")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")
qf_n <- length(unique(qf_all_data$id))
q_plot <- clean_single_select_y(qf_all_data)
r <- plot_single_select_y(q_plot)
r
```

```{r}
q_plot2 <- rbind(q_plot, t)
dir.create("output/q80_active_combat_zones")
ggsave(filename = 'output/q80_active_combat_zones/q80_active_combat_zones.png', plot = r, device = 'png')
write.csv(q_plot2, paste0("output/q80_active_combat_zones/q80_active_combat_zones_", qf_n,".csv"), row.names=F)
```