---
title: "q81 'Did you ever go on combat patrols or have other dangerous duty?'"
author: "David Ritter"
date: "2/28/20"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q81 <- "Did.you.ever.go.on.combat.patrols.or.have.other.dangerous.duty."
q81_t <- "Did you ever go on combat patrols or have other dangerous duty?"
q81_data <- get_single_selection(data = raw_data, q.name = q81)
q81_n <- length(unique(q81_data$id))
q81_plot<- clean_single_select(q81_data)
r81 <- plot_single_select(q81_plot, q81_t, q81_n)
r81
```

```{r}
row3 <- colnames(q81_plot)
q81_plot2 <- rbind(row3, q81_plot)
names(q81_plot2) <- c("q81", q81_t, paste("n = ", q81_n))
```

```{r}
dir.create("output/q81_dangerous_duties")
ggsave(filename = 'output/q81_dangerous_duties/q81_dangerous_duties.png', plot = r81, device = 'png')
write.csv(q81_plot2, paste0("output/q81_dangerous_duties/q81_dangerous_duties_", q81_n,".csv"), row.names=F)
```








```{r}
qf_data <- q_data %>%
  filter(response == "Response text")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")
qf_n <- length(unique(qf_all_data$id))
q_plot <- clean_single_select_y(qf_all_data)
r <- plot_single_select_y(q_plot)
r
```

```{r}
q_plot2 <- rbind(q_plot, t)
dir.create("output/q81_dangerous_duties")
ggsave(filename = 'output/q81_dangerous_duties/q81_dangerous_duties.png', plot = r, device = 'png')
write.csv(q_plot2, paste0("output/q81_dangerous_duties/q81_dangerous_duties_", qf_n,".csv"), row.names=F)
```

