---
title: "q82 'Were you ever under enemy fire?'"
author: "David Ritter"
date: "2/28/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q82 <- "Were.you.ever.under.enemy.fire."
q82_t <- "Were you ever under enemy fire?"
q82_data <- get_single_selection(data = raw_data, q.name = q82)
q82_n <- length(unique(q82_data$id))
q82_plot<- clean_single_select(q82_data)
r82 <- plot_single_select(q82_plot, q82_t, q82_n)
r82
```

```{r}
row3 <- colnames(q82_plot)
q82_plot2 <- rbind(row3, q82_plot)
names(q82_plot2) <- c("q82", q82_t, paste("n = ", q82_n))
```

```{r}
dir.create("output/q82_enemy_fire")
ggsave(filename = 'output/q82_enemy_fire/q82_enemy_fire.png', plot = r82, device = 'png')
write.csv(q82_plot2, paste0("output/q82_enemy_fire/q82_enemy_fire_", q82_n,".csv"), row.names=F)
```







```{r}
qf_data <- q_data %>%
  filter(response == "Response text")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")
qf_n <- length(unique(qf_all_data$id))
q_plot <- clean_single_select_y(qf_all_data)
r <- plot_single_select_y(q_plot)
r
```

```{r}
q_plot2 <- rbind(q_plot, t)
dir.create("output/q82_enemy_fire")
ggsave(filename = 'output/q82_enemy_fire/q82_enemy_fire.png', plot = r, device = 'png')
write.csv(q_plot2, paste0("output/q82_enemy_fire/q82_enemy_fire_", qf_n,".csv"), row.names=F)
```