---
title: "q83 'Were you ever surrounded by the enemy?'"
author: "David Ritter"
date: "2/25/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q83 <- "Were.you.ever.surrounded.by.the.enemy."
q83_t <- "Were you ever surrounded by the enemy?"
q83_data <- get_single_selection(data = raw_data, q.name = q83)
q83_n <- length(unique(q83_data$id))
q83_plot<- clean_single_select(q83_data)
r83 <- plot_single_select(q83_plot, q83_t, q83_n)
r83
```

```{r}
q83_plot2 <- rbind(q83_plot, q83_t)
dir.create("output/q83_surrounded_by_enemy")
ggsave(filename = 'output/q83_surrounded_by_enemy/q83_surrounded_by_enemy.png', plot = r83, device = 'png')
write.csv(q83_plot2, paste0("output/q83_surrounded_by_enemy/q83_surrounded_by_enemy_", q83_n,".csv"), row.names=F)
```



```{r}
qf_data <- q_data %>%
  filter(response == "Response text")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")
qf_n <- length(unique(qf_all_data$id))
q_plot <- clean_single_select_y(qf_all_data)
r <- plot_single_select_y(q_plot)
r
```

```{r}
q_plot2 <- rbind(q_plot, t)
dir.create("output/q83_surrounded_by_enemy")
ggsave(filename = 'output/q83_surrounded_by_enemy/q83_surrounded_by_enemy.png', plot = r, device = 'png')
write.csv(q_plot2, paste0("output/q83_surrounded_by_enemy/q83_surrounded_by_enemy_", qf_n,".csv"), row.names=F)
```
