---
title: "q85 'How often did you fire rounds at the enemy?'"
author: "David Ritter"
date: "2/28/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q85 <- "How.often.did.you.fire.rounds.at.the.enemy."
q85_t <- "How often did you fire rounds at the enemy?"
q85_data <- get_single_selection(data = raw_data, q.name = q85)
q85_n <- length(unique(q85_data$id))
q85_plot<- clean_single_select(q85_data)
r85 <- plot_single_select(q85_plot, q85_t, q85_n)
r85
```

```{r}
row3 <- colnames(q85_plot)
q85_plot2 <- rbind(row3, q85_plot)
names(q85_plot2) <- c("q85", q85_t, paste("n = ", q85_n))
```

```{r}
dir.create("output/q85_fire_rounds_enemy")
ggsave(filename = 'output/q85_fire_rounds_enemy/q85_fire_rounds_enemy.png', plot = r85, device = 'png')
write.csv(q85_plot2, paste0("output/q85_fire_rounds_enemy/q85_fire_rounds_enemy_", q85_n,".csv"), row.names=F)
```







```{r}
qf_data <- q_data %>%
  filter(response == "Response text")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")
qf_n <- length(unique(qf_all_data$id))
q_plot <- clean_single_select_y(qf_all_data)
r <- plot_single_select_y(q_plot)
r
```

```{r}
q_plot2 <- rbind(q_plot, t)
dir.create("output/q85_fire_rounds_enemy")
ggsave(filename = 'output/q85_fire_rounds_enemy/q85_fire_rounds_enemy.png', plot = r, device = 'png')
write.csv(q_plot2, paste0("output/q85_fire_rounds_enemy/q85_fire_rounds_enemy_", qf_n,".csv"), row.names=F)
```

