---
title: "q86 'How often did you see someone hit by incoming or outgoing rounds?'"
author: "David Ritter"
date: "2/25/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q86 <- "How.often.did.you.see.someone.hit.by.incoming.or.outgoing.rounds."
q86_t <- "How often did you see someone hit by incoming or outgoing rounds?"
q86_data <- get_single_selection(data = raw_data, q.name = q86)
q86_n <- length(unique(q86_data$id))
q86_plot<- clean_single_select(q86_data)
r86 <- plot_single_select(q86_plot, q86_t, q86_n)
r86
```

```{r}
q86_plot2 <- rbind(q86_plot, q86_t)
dir.create("output/q86_witness_hit_rounds")
ggsave(filename = 'output/q86_witness_hit_rounds/q86_witness_hit_rounds.png', plot = r86, device = 'png')
write.csv(q86_plot2, paste0("output/q86_witness_hit_rounds/q86_witness_hit_rounds_", q86_n,".csv"), row.names=F)
```



```{r}
qf_data <- q_data %>%
  filter(response == "Response text")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")
qf_n <- length(unique(qf_all_data$id))
q_plot <- clean_single_select_f(qf_all_data)
r <- plot_single_select_f(q_plot)
r
```

```{r}
q_plot2 <- rbind(q_plot, t)
dir.create("output/q86_witness_hit_rounds")
ggsave(filename = 'output/q86_witness_hit_rounds/q86_witness_hit_rounds.png', plot = r, device = 'png')
write.csv(q_plot2, paste0("output/q86_witness_hit_rounds/q86_witness_hit_rounds_", qf_n,".csv"), row.names=F)
```

