---
title: "Q88_Age_Range"
author: "David Ritter"
date: "4/17/2019"
output: html_document
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```



```{r}

# Read in raw data. These are the files downloaded from survey monkey saved as a .csv
raw_data_general <- read.csv("data/general.csv", stringsAsFactors = FALSE)
raw_data_botanist <- read.csv("data/botanist.csv", stringsAsFactors = FALSE)
raw_data_bask <- read.csv("data/bask.csv", stringsAsFactors = FALSE)

```

```{r}
# Pull information for only this question out of each survey
# - Rename columns
# - Drop first row (first row contained column names)
# - Add survey source as a variable

    ## General

general <- 
  raw_data_general %>%
  select(question = "What.is.your.age..in.years..") %>%
  slice(2:nrow(.))


  ## Bask
bask <- 
  raw_data_bask %>%
  select(question = "What.is.your.age..in.years..") %>%
  slice(2:nrow(.))


  ## Botanist
botanist <- 
  raw_data_botanist %>%
  select(question = "What.is.your.age..in.years..") %>%
  slice(2:nrow(.))

```


```{r}
# Combine General, Botanist, and Bask data frames into 1 and remove blank responses

all_data <- 
  rbind(general, bask, botanist) %>%
  filter(question > 0) %>%
  mutate(question = as.numeric(question)) %>%
  mutate(range = case_when(
    question == 1 ~ "21 - 29",
    question == 2 ~ "30 - 39",
    question == 3 ~ "40 - 49",
    question == 4 ~ "50 - 59",
    question == 5 ~ "60 - 69",
    question == 6 ~ "70+"))

## Add # Responses

number_of_people_who_submitted_response_to_Q88 <- length(unique(all_data$id))


```


```{r}

for_plot <-
  all_data %>%
  group_by(range, ) %>%
  summarize(count = n()) %>%
  ungroup() %>%
  mutate(percent_all = count / sum(count))
  
  
```


```{r}

p <-
  ggplot(for_plot, aes(x = range, y = count)) +
  geom_bar(stat = 'identity')
  geom_text(aes(label= paste(round(percent_responded, 2), count, sep = "***")))
p

```

```{r}

q <- 
  ggplot(for_plot, aes(x = range, y = count)) +
  geom_bar(stat = 'identity') +
  geom_text(aes(label= round(percent_all,2)))

q

```

```{r}

ggsave(filename = 'Q88_Age_Responses.png', plot = q, device = 'png')

write.csv(for_plot, 'Q88_Age_Responses.csv', row.names = FALSE)

```
