---
title: "Q88_Age_Range"
author: "Neil Ritter"
date: "3/22/2019"
output: html_document
---

```{r, message = FALSE}

library(tidyverse)
library(ggplot2)
source("helper.R")

```



```{r}

# Read in raw data. These are the files downloaded from survey monkey saved as a .csv
raw_data_general <- read.csv("data/general.csv", stringsAsFactors = FALSE)
raw_data_botanist <- read.csv("data/botanist.csv", stringsAsFactors = FALSE)
raw_data_bask <- read.csv("data/bask.csv", stringsAsFactors = FALSE)

```


```{r}
# Pull information for only this question out of the general survey
# - Rename columns
# - Drop first row (first row contained column names)
# - Add survey source as a variable

    ## General
general <- 
  raw_data_general %>%
  select(question = "What.is.your.age..in.years..") %>%
  slice(2:nrow(.)) %>%
  mutate(source = 'general')

```


```{r}
# rbind General, and remove blank responses

all_data <- 
  rbind(general) %>%
  filter(question > 0) %>%
  mutate(question = as.numeric(question)) %>%
  mutate(range = case_when(
    question == 1 ~ "21 - 29",
    question == 2 ~ "30 - 39",
    question == 3 ~ "40 - 49",
    question == 4 ~ "50 - 59",
    question == 5 ~ "60 - 69",
    question == 6 ~ "70+"))

```


```{r}

for_plot <-
  all_data %>%
  group_by(range, ) %>%
  summarize(count = n()) %>%
  ungroup()
  
```


```{r}

p <-
  ggplot(for_plot, aes(x = range, y = count)) +
  geom_histogram(stat = 'identity')

p

```

```{r}
# Save Plot as PNG
ggsave(filename = 'Q88_Age_Range_General.png', plot = p, device = 'png')

```

```{r}
# Save data as CSV
write.csv(for_plot, 'Q88_Age_Range_General.csv', row.names = FALSE)

```













