---
title: "Q88 Age Range (Veterans)"
author: "David Ritter"
date: "June 13, 2019"
output: html_document
---

```{r, message = FALSE}
# Load libraries
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
# Read in raw data from the Veterans surveys. These are the files downloaded from survey monkey saved as a .csv
raw_data_general <- read.csv("data/general_text.csv", stringsAsFactors = FALSE)
raw_data_botanist <- read.csv("data/botanist_text.csv", stringsAsFactors = FALSE)
raw_data_bask <- read.csv("data/bask_text.csv", stringsAsFactors = FALSE)
raw_data_healing_rose <- read.csv("data/healing_rose_text.csv", stringsAsFactors = FALSE)
```

```{r}
# Pull information for only this question out of each survey
# - Rename columns
# - Drop first row (first row contained column names)
# - Add survey source as a variable

Q88 <- "What.is.your.age..in.years.."

general <- get_single_selection(data = raw_data_general, q.name = Q88)
bask <- get_single_selection(data = raw_data_bask, q.name = Q88)
botanist <- get_single_selection(data = raw_data_botanist, q.name = Q88)
healing_rose <- get_single_selection(data = raw_data_healing_rose, q.name = Q88)

Q88_data <- rbind(general, bask, botanist, healing_rose)
```

```{r}
# Manipulate data into a graphable format
Q88_plot <-
  Q88_data %>%
  group_by(response, ) %>%
  summarize(count = n()) %>%
  ungroup() %>%
  mutate(percent_all = count / sum(count))
```

```{r}
# Plot with percents and response counts
r <- 
  ggplot(Q88_plot, aes(x = response, y = count)) +
  geom_bar(stat = 'identity') +
  geom_text(aes(label= paste(round(percent_all,2), count, sep = "***")))

r
```

```{r}
# Save graph as PNG, plot data as csv, and all question data including response IDs as csv (save question n and N at end of plot file as "_x.x")
ggsave(filename = 'Q88_Age.png', plot = r, device = 'png')

write.csv(Q88_plot, 'Q88_Age_152.277.csv', row.names = FALSE)

write.csv(Q88_data, 'Q88_Responses_ID.csv', row.names = FALSE)
```
