---
title: "q90 'What is your annual household income (in US dollars)'"
author: "David Ritter"
date: "2/25/2020"
output: html_document
runtime: shiny
---

```{r message=FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q90 <- "What.is.your.annual.household.income..in.US.dollars."
q90_t <- "What is your annual household income (in US dollars)"
q90_data <- get_single_selection_0(data = raw_data, q.name = q90) %>%
  filter(response != "")
q90_n <- length(unique(q90_data$id))
q90_plot<- clean_single_select(q90_data)
r90 <- plot_single_select(q90_plot, q90_t, q90_n)
r90
```

```{r}
q90_plot2 <- rbind(q90_plot, q90_t)
dir.create("output/q90_income")
ggsave(filename = 'output/q90_income/q90_income.png', plot = r90, device = 'png')
write.csv(q90_plot2, paste0("output/q90_income/q90_income_", q90_n,".csv"), row.names=F)
```



```{r}
qf_data <- q_data %>%
  filter(response == "Less than $10,000" | response == "$10,000-$19,999" | response == "$20,000-$29,999" | response == "$30,000-$39,999" | response == "$40,000-$49,999" | response == "$50,000-$59,999")
```

```{r}
qf_data <- q_data %>%
  filter(response != "Less than $10,000" & response != "$10,000-$19,999" & response != "$20,000-$29,999" & response != "$30,000-$39,999" & response != "$40,000-$49,999" & response != "$50,000-$59,999")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")
qf_n <- length(unique(qf_all_data$id))
```

```{r}
q_plot <- clean_single_select_f(qf_all_data)
r <- plot_single_select_f(q_plot)
r
```

```{r}
q_plot2 <- rbind(q_plot, t)
dir.create("output/q90_income")
ggsave(filename = 'output/q90_income/q90_income.png', plot = r, device = 'png')
write.csv(q_plot2, paste0("output/q90_income/q90_income_", qf_n,".csv"), row.names=F)
```