---
title: "q91 'What is the highest degree or level of school you have completed? (If you're currently enrolled in school, please indicate the highest degree you have received.)'"
author: "David Ritter"
date: "2/28/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q91 <- "What.is.the.highest.degree.or.level.of.school.you.have.completed...If.you.re.currently.enrolled.in.school..please.indicate.the.highest.degree.you.haveÂ.received..Â."
q91_t <- "What is the highest degree or level of school you have completed? (If you're currently enrolled in school, please indicate the highest degree you have received.)"
q91_data <- get_single_selection(data = raw_data, q.name = q91)
q91_n <- length(unique(q91_data$id))
q91_plot<- clean_single_select(q91_data)
r91 <- plot_single_select(q91_plot, q91_t, q91_n)
r91
```

```{r}
row3 <- colnames(q91_plot)
q91_plot2 <- rbind(row3, q91_plot)
names(q91_plot2) <- c("q91", q91_t, paste("n = ", q91_n))
```

```{r}
dir.create("output/q91_highest_degree")
ggsave(filename = 'output/q91_highest_degree/q91_highest_degree.png', plot = r91, device = 'png')
write.csv(q91_plot2, paste0("output/q91_highest_degree/q91_highest_degree_", q91_n,".csv"), row.names=F)
```







```{r}
qf_data <- q_data %>%
  filter(response == "Response text")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")
qf_n <- length(unique(qf_all_data$id))
q_plot <- clean_single_select_y(qf_all_data)
r <- plot_single_select_y(q_plot)
r
```

```{r}
q_plot2 <- rbind(q_plot, t)
dir.create("output/q91_highest_degree")
ggsave(filename = 'output/q91_highest_degree/q91_highest_degree.png', plot = r, device = 'png')
write.csv(q_plot2, paste0("output/q91_highest_degree/q91_highest_degree_", qf_n,".csv"), row.names=F)
```