---
title: "Q98 State"
runtime: shiny
output: html_document
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
source("helper.R")
```


```{r}
# Read in raw data. These are the files downloaded from survey monkey saved as a .csv

raw_data_general <- read.csv("data/general_text.csv", stringsAsFactors = FALSE)
raw_data_botanist <- read.csv("data/botanist_text.csv", stringsAsFactors = FALSE)
raw_data_bask <- read.csv("data/bask_text.csv", stringsAsFactors = FALSE)

```



```{r}
# Pull out all responses for Q98 (a single selection question) and combine

Q98 <- "What.state.in.the.US.do.you.currently.live.in."

Q98_general <- get_single_selection(data = raw_data_general, q.name = Q98)

Q98_all <- rbind(Q98_general)

```

```{r}

Q98_plot <- 
  Q98_all %>%
  group_by(response) %>%
  summarize(count = n())

p <- 
  ggplot(Q98_plot, aes(x = reorder(response, count), y = count)) +
  geom_bar(stat = 'identity') + 
  coord_flip()

p

```

```{r}
# Save Plot as PNG
ggsave(filename = 'Q98_State.png', plot = p, device = 'png')

```

```{r}
# Save data as CSV
write.csv(Q98_plot, 'Q98_State.csv', row.names = FALSE)

```






