---
title: "q98 'What state in the US do you currently live in?'"
author: "David Ritter"
date: "2/28/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q98 <- "What.state.in.the.US.do.you.currently.live.in."
q98_t <- "What state in the US do you currently live in?"
q98_data <- get_single_selection(data = raw_data, q.name = q98)
q98_n <- length(unique(q98_data$id))
q98_plot<- clean_single_select(q98_data)
r98 <- plot_single_select(q98_plot, q98_t, q98_n)
r98
```

```{r}
row3 <- colnames(q98_plot)
q98_plot2 <- rbind(row3, q98_plot)
names(q98_plot2) <- c("q98", q98_t, paste("n = ", q98_n))
```

```{r}
dir.create("output/q98_state")
ggsave(filename = 'output/q98_state/q98_state.png', plot = r98, device = 'png')
write.csv(q98_plot2, paste0("output/q98_state/q98_state_", q98_n,".csv"), row.names=F)
```







```{r}
qf_data <- q_data %>%
  filter(response == "Response text")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")
qf_n <- length(unique(qf_all_data$id))
q_plot <- clean_single_select_y(qf_all_data)
r <- plot_single_select_y(q_plot)
r
```

```{r}
q_plot2 <- rbind(q_plot, t)
dir.create("output/q98_state")
ggsave(filename = 'output/q98_state/q98_state.png', plot = r, device = 'png')
write.csv(q_plot2, paste0("output/q98_state/q98_state_", qf_n,".csv"), row.names=F)
```




