---
title: "q99 'I would choose medical cannabis if it was a federally-legal treatment option.'"
author: "David Ritter"
date: "2/25/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q99 <- "I.would.choose.medical.cannabis.if.it.was.a.federally.legal.treatment.option."
q99_t <- "I would choose medical cannabis if it was a federally-legal treatment option."
q99_data <- get_single_selection(data = raw_data, q.name = q99)
q99_n <- length(unique(q99_data$id))
q99_plot<- clean_single_select(q99_data)
r99 <- plot_single_select(q99_plot, q99_t, q99_n)
r99
```

```{r}
q99_plot2 <- rbind(q99_plot, q99_t)
dir.create("output/q99_cannabis_if_legal")
ggsave(filename = 'output/q99_cannabis_if_legal/q99_cannabis_if_legal.png', plot = r99, device = 'png')
write.csv(q99_plot2, paste0("output/q99_cannabis_if_legal/q99_cannabis_if_legal_", q99_n,".csv"), row.names=F)
```



```{r}
qf_data <- q_data %>%
  filter(response == "Response text")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")
qf_n <- length(unique(qf_all_data$id))
q_plot <- clean_single_select_y(qf_all_data)
r <- plot_single_select_y(q_plot)
r
```

```{r}
q_plot2 <- rbind(q_plot, t)
dir.create("output/q99_cannabis_if_legal")
ggsave(filename = 'output/q99_cannabis_if_legal/q99_cannabis_if_legal.png', plot = r, device = 'png')
write.csv(q_plot2, paste0("output/q99_cannabis_if_legal/q99_cannabis_if_legal_", qf_n,".csv"), row.names=F)
```
