---
title: "Q20 by Q88 Prescriptions by Age (Veterans)"
author: "DJ"
date: "June 13, 2019"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
# Read in raw data from the Veterans surveys. These are the files downloaded from survey monkey saved as a .csv
raw_data_general <- read.csv("data/general_text.csv", stringsAsFactors = FALSE)
raw_data_botanist <- read.csv("data/botanist_text.csv", stringsAsFactors = FALSE)
raw_data_bask <- read.csv("data/bask_text.csv", stringsAsFactors = FALSE)
raw_data_healing_rose <- read.csv("data/healing_rose_text.csv", stringsAsFactors = FALSE)
```

```{r}
# Pull out all responses for Q5 (a choose all question), combine, turn into a tidy data format for further processing then determine 'question n'
Q20 <- 'What.types.of.prescription.medications.are.you.currently.taking.for.the.health.conditions.and.symptoms.you.face...Please.select.all.that.apply.'
Q20_final_response <- "X.136"

Q20_general <- get_choose_all(raw_data_general, q.name = Q20, f.response = Q20_final_response)
Q20_bask <- get_choose_all(raw_data_bask, q.name = Q20, f.response = Q20_final_response)
Q20_botanist <- get_choose_all(raw_data_botanist, q.name = Q20, f.response = Q20_final_response)
Q20_healing_rose <- get_choose_all(raw_data_healing_rose, q.name = Q20, f.response = Q20_final_response)

Q20_all <- rbind(Q20_general, Q20_bask, Q20_botanist, Q20_healing_rose)

number_of_people <- length(unique(Q20_all$id))
```

```{r}
# Combine Q6_all and Q20_all into one dataframe To Combine Age 
Q20_Q88_all <-
  Q20_all %>%
  inner_join(all_data, by = "id")
```

```{r}
Q20_Q88_plot <- 
  Q20_Q88_all %>%
  group_by(response, condition) %>%
  summarize(count = n())
```


```{r}

p <- ggplot(data = Q20_Q88_plot, aes(x = condition, y = count)) +
  geom_bar(stat = 'identity') + 
  coord_flip() +
  facet_wrap(~range)

p
```

```{r}
# Save plot file as csv (save question n and N at end of plot file as "_x.x")

write.csv(Q20_Q88_all, 'Q20_Condition_Prescriptions_By_Age_152.305.csv', row.names = FALSE)
```
