---
title: "Q53 Spend Cannabis"
author: "DJ"
date: "May 23, 2019"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
# Load libraries
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
# Read in raw data from the Veterans surveys. These are the files downloaded from survey monkey saved as a .csv
raw_data_general <- read.csv("data/general_text.csv", stringsAsFactors = FALSE)
raw_data_botanist <- read.csv("data/botanist_text.csv", stringsAsFactors = FALSE)
raw_data_bask <- read.csv("data/bask_text.csv", stringsAsFactors = FALSE)
raw_data_healing_rose <- read.csv("data/healing_rose_text.csv", stringsAsFactors = FALSE)
```

```{r}
# Pull out all responses for Q53 (a single selection question) combine, then determine 'question n'
Q53 <- "On.average..how.much.do.you.spend..in.US.dollars..on.consumable.cannabis.products.per.week."

Q53_general <- get_single_selection(data = raw_data_general, q.name = Q53)
Q53_bask <- get_single_selection(data = raw_data_bask, q.name = Q53)
Q53_botanist <- get_single_selection(data = raw_data_botanist, q.name = Q53)
Q53_healing_rose <- get_single_selection(data = raw_data_healing_rose, q.name = Q53)
  
all_data <- rbind(Q53_general, Q53_bask, Q53_botanist, Q53_healing_rose)

number_of_people_who_submitted_response_to_Q53 <- length(unique(all_data$id))
```

```{r}
# Generate Chronic Pain IDs we want from Q6 file
Q53_Q6_Chronic_Pain <- 
  all_data %>%
  inner_join(Q6_Chronic_Pain_ids_we_want, by = "id")

Chronic_Pain_Q53_Respondents <- length(unique(Q53_Q6_Chronic_Pain$id))
```

```{r}
# Generate PTSD IDs we want from Q6 file
Q53_Q6_PTSD <-
  all_data %>%
  inner_join(Q6_PTSD_ids_we_want, by = "id")

PTSD_Respondents <- length(unique(Q53_Q6_PTSD$id))
```

```{r}

histogram_object <- hist(as.numeric(all_data$response))
histogram_object$breaks = c(0, 100, 200, 300, 400, 500, 600)
histogram_object$counts
plot(histogram_object)
```

```{r}
# Save graph as PNG, plot data as csv, and all question data including response IDs as csv (save question n and N at end of plot file as "_x.x")
write.csv(all_data, 'Q53_Cannabis_Spending_144.277.csv', row.names = FALSE)
write.csv(Q53_Q6_Chronic_Pain, 'Q53xQ6_Chronic_Pain_Cannabis_Spending_52.144.csv', row.names = FALSE)
write.csv(Q53_Q6_PTSD, 'Q53xQ6_PTSD_Cannabis_Spending_31.144.csv', row.names = FALSE)
```