---
title: "Q6 Chronic Pain Top Condition x Pain Scales"
author: "DJ"
date: "May 22, 2019"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
# Read in raw data. These are the files downloaded from survey monkey saved as a .csv

raw_data_general <- read.csv("data/general_text.csv", stringsAsFactors = FALSE)
raw_data_botanist <- read.csv("data/botanist_text.csv", stringsAsFactors = FALSE)
raw_data_bask <- read.csv("data/bask_text.csv", stringsAsFactors = FALSE)
raw_data_healing_rose <- read.csv("data/healing_rose_text.csv", stringsAsFactors = FALSE)

```

```{r}
# Pull out all responses for Q6 (a single selection question) and combine

Q6 <- "Which.is.the.primary.health.condition.that.causes.you.the.most.distress...Please.select.one."

Q6_general <- get_single_selection(data = raw_data_general, q.name = Q6)
Q6_bask <- get_single_selection(data = raw_data_bask, q.name = Q6)
Q6_botanist <- get_single_selection(data = raw_data_botanist, q.name = Q6)
Q6_healing_rose <- get_single_selection(data = raw_data_healing_rose, q.name = Q6)

Q6_all <- rbind(Q6_general, Q6_bask, Q6_botanist, Q6_healing_rose)
  
## Determine Question N

number_of_people <- length(unique(Q6_all$id))

```

```{r}


Q6_Chronic_Pain_ids_we_want <- Q6_all %>% 
  filter(response %in% c("Chronic pain"))

Q6_PTSD_ids_we_want <- Q6_all %>% 
  filter(response %in% c("Posttraumatic stress disorder (PTSD)"))

```

