---
title: "q52 'On days you regularly use cannabis, how many times per day do you use cannabis?' National Veterans"
author: "DJ"
date: "1/6/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
# Load libraries
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
# Read in raw data from the Veterans surveys. These are the files downloaded from survey monkey saved as a .csv
raw_data_general <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
# Pull out all responses for q52 (a single selection question) combine, then determine 'question n'
q52 <- "On.days.you.regularly.use.cannabis..how.many.times.per.day.do.you.use.cannabis."

q52_all <- get_single_selection(data = raw_data_general, q.name = q52)

q52_n <- length(unique(q52_all$id))
```

```{r}
# Manipulate data into a graphable format
q52_plot <- 
  q52_all %>%
  group_by(response) %>%
  summarize(count = n()) %>%
  mutate(percent_all = count / sum(count)) %>%
  mutate(percent_responded = count / q52_n)
```

```{r}
# Plot with percents and response counts
r <- 
  ggplot(q52_plot, aes(x = reorder(response, count), y = percent_responded)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  geom_text(aes(label= paste(round(percent_responded, 2), count, sep = "***")))
r
```

```{r}
# Save graph as PNG, plot data as csv, and all question data including response IDs as csv (save question n and N at end of plot file as "_x.x")
ggsave(filename = 'q52_use_times_per_day.png', plot = r, device = 'png')

write.csv(q52_plot, 'q52_use_times_per_day_217.csv', row.names = FALSE)

write.csv(q52_all, 'q52_use_times_per_day_ids.csv', row.names = FALSE)
```
