---
title: "q20 'What types of prescription medications are you currently taking for the health conditions and symptoms you face? (Please select all that apply)' (MA Veterans)"
author: "DJ"
date: "October 21, 2019"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
# Load libraries
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
# Read in raw data from the Veterans surveys. These are the files downloaded from survey monkey saved as a .csv
raw_data_general <- read.csv("data/general.csv", stringsAsFactors = FALSE)
raw_data_botanist <- read.csv("data/botanist.csv", stringsAsFactors = FALSE)
raw_data_bask <- read.csv("data/bask.csv", stringsAsFactors = FALSE)
raw_data_hr <- read.csv("data/hr.csv", stringsAsFactors = FALSE)
```

```{r}
# Pull out all responses for q98 (a single selection question) combine, then determine 'question n' (subsequent q are labeled for convenience, do not respond to survey q#)

q98 <- "What.state.in.the.US.do.you.currently.live.in."
q99 <- "What.US.State.do.you.currently.live.in."
q100 <- "Which.US.state.do.you.currently.live.in."
q101 <- "What.US.state.do.you.currently.live.in."

q98_general <- get_single_selection(data = raw_data_general, q.name = q98)
q98_bask <- get_single_selection(data = raw_data_bask, q.name = q99)
q98_botanist <- get_single_selection(data = raw_data_botanist, q.name = q100)
q98_hr <- get_single_selection(data = raw_data_hr, q.name = q101)

q98_all <- rbind(q98_general, q98_bask, q98_botanist, q98_hr)

ma_ids <- q98_all %>% 
  filter(response %in% c("Massachusetts"))

state_ma <- length(unique(ma_ids$id))
```

```{r}
# Pull out all responses for q20 (a choose all question), combine, turn into a tidy data format for further processing then determine 'question n'
q20 <- 'What.types.of.prescription.medications.are.you.currently.taking.for.the.health.conditions.and.symptoms.you.face...Please.select.all.that.apply.'
q20_final_response <- "X.136"

q20_general <- get_choose_all(raw_data_general, q.name = q20, f.response = q20_final_response)
q20_bask <- get_choose_all(raw_data_bask, q.name = q20, f.response = q20_final_response)
q20_botanist <- get_choose_all(raw_data_botanist, q.name = q20, f.response = q20_final_response)
q20_hr <- get_choose_all(raw_data_hr, q.name = q20, f.response = q20_final_response)

names(q20_hr) <- names(q20_general)
names(q20_bask) <- names(q20_general)
names(q20_botanist) <- names(q20_general)

q20_all <-
  rbind(q20_general, q20_bask, q20_botanist, q20_hr) %>%
  tidy_choose_all() %>%
  inner_join(ma_ids, by = "id")
 
q20_ma_n <- length(unique(q20_all$id))
```

```{r}
# Manipulate data into a graphable format
q20_plot <-
  q20_all %>%
  group_by(chosen) %>%
  summarize(count = n()) %>%
  mutate(percent_all = count / sum(count)) %>%
  mutate(percent_responded = count / q20_ma_n)
```

```{r}
# Plot with percents and response counts
r <- 
  ggplot(q20_plot, aes(x = reorder(chosen, count), y = percent_responded)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  geom_text(aes(label= paste(round(percent_responded,2), count, sep = "***")))

r
```

```{r}
# Save graph as PNG, plot data as csv, and all question data including response IDs as csv (save question n and N at end of plot file as "_x.x")
ggsave(filename = 'q20_prescriptions_taken.png', plot = r, device = 'png')

write.csv(q20_plot, 'q20_prescriptions_taken_161.csv', row.names = FALSE)

write.csv(q20_all, 'q20_prescriptions_taken_ids.csv', row.names = FALSE)
```
