---
title: "Q29 'What percentage of disability are you rated, as indicated by the Veteran's Affairs (VA)?' (National Veterans)"
author: "DJ"
date: "October, 2019"
output: html_document
---
```{r, message = FALSE}
# Load libraries
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
# Read in raw data from the Veterans surveys. These are the files downloaded from survey monkey saved as a .csv
raw_data_general <- read.csv("data/general.csv", stringsAsFactors = FALSE)
raw_data_botanist <- read.csv("data/botanist.csv", stringsAsFactors = FALSE)
raw_data_bask <- read.csv("data/bask.csv", stringsAsFactors = FALSE)
raw_data_hr <- read.csv("data/hr.csv", stringsAsFactors = FALSE)
```

```{r}
# Pull out all responses for Q29 (a single selection question) combine, then determine 'question n'
Q29 <- "What.percentage.of.disability.are.you.rated..as.is.indicated.by.the.Veteran.s.Affairs..VA.."

Q29_general <- get_single_selection(data = raw_data_general, q.name = Q29)
Q29_bask <- get_single_selection(data = raw_data_bask, q.name = Q29)
Q29_botanist <- get_single_selection(data = raw_data_botanist, q.name = Q29)
Q29_hr <- get_single_selection(data = raw_data_hr, q.name = Q29)

Q29_all <- rbind(Q29_general, Q29_bask, Q29_botanist, Q29_hr)

q29_n <- length(unique(Q29_all$id))
```


```{r}
histogram_object <- hist(as.numeric(Q29_all$response))
histogram_object$breaks
histogram_object$counts
plot(histogram_object)
```

```{r}
ggsave(plot(histogram_object), file = "Q29_Percentage_Disability.png")
```

```{r}
write.csv(Q29_all, 'Q29_Percentage_Disability_346.csv', row.names = FALSE)
```



