---
title: q102 'Do you believe the VA should offer free (or discounted) medical cannabis
  to veterans who qualify for its use?' Veterans
author: "DJ"
date: "October 25, 2019"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
# Load libraries
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
# Read in raw data from the Veterans surveys. These are the files downloaded from survey monkey saved as a .csv
raw_data_general <- read.csv("data/general.csv", stringsAsFactors = FALSE)
raw_data_botanist <- read.csv("data/botanist.csv", stringsAsFactors = FALSE)
raw_data_bask <- read.csv("data/bask.csv", stringsAsFactors = FALSE)
raw_data_hr <- read.csv("data/hr.csv", stringsAsFactors = FALSE)
```

```{r}
# Pull out all responses for q102 (a single selection question) combine, then determine 'question n'
q102 <- "Do.you.believe.the.VA.should.offer.free..or.discounted..medical.cannabis.to.veterans.who.qualify.for.its.use."
q103 <- "Do.you.believe.the.VA.should.offerÂ.free..or.discounted..medical.cannabis.to.veterans.who.qualify.for.its.use."

q102_general <- get_single_selection(data = raw_data_general, q.name = q102)
q102_bask <- get_single_selection(data = raw_data_bask, q.name = q102)
q102_botanist <- get_single_selection(data = raw_data_botanist, q.name = q102)
q102_hr <- get_single_selection(data = raw_data_hr, q.name = q103)

q102_all <- rbind(q102_general, q102_bask, q102_botanist, q102_hr)

q102_n <- length(unique(q102_all$id))
```


```{r}
# Manipulate data into a graphable format
q102_plot <- 
  q102_all %>%
  group_by(response) %>%
  summarize(count = n()) %>%
  mutate(percent_all = count / sum(count)) %>%
  mutate(percent_responded = count / q102_n)
```

```{r}
# Plot with percents and response counts
r <- 
  ggplot(q102_plot, aes(x = reorder(response, count), y = percent_responded)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  geom_text(aes(label= paste(round(percent_responded, 2), count, sep = "***")))
r
```

```{r}
# Save graph as PNG, plot data as csv, and all question data including response IDs as csv (save question n and N at end of plot file as "_x.x")
ggsave(filename = 'q102_vet_cannabis_discount.png', plot = r, device = 'png')

write.csv(q102_plot, 'q102_vet_cannabis_discount_431.csv', row.names = FALSE)

write.csv(q102_all, 'q102_vet_cannabis_discount_ids.csv', row.names = FALSE)
```