---
title: "q61 'Do you face any of the following barriers for you to consume cannabis (Please select all that apply)' (Veterans)"
author: "David Ritter"
date: "November 19, 2019"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
# Load libraries
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
# Read in raw data from the Veterans surveys. These are the files downloaded from survey monkey saved as a .csv
raw_data_general <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
# Pull out all responses for q61 (a choose all question), combine, turn into a tidy data format for further processing then determine 'question n'
q61 <- "Do.you.face.any.of.the.following.barriers.for.you.to.consume.cannabis...Please.select.all.that.apply."
q61_final_response <- "X.279"


q61_general <- get_choose_all(raw_data_general, q.name = q61, f.response = q61_final_response)

q61_all <- tidy_choose_all(q61_general)

q61_n <- length(unique(q61_all$id))
```

```{r}
# Manipulate data into a graphable format
q61_plot <-
  q61_all %>%
  group_by(chosen) %>%
  summarize(count = n()) %>%
  mutate(percent_all = count / sum(count)) %>%
  mutate(percent_responded = count / q61_n)
```

```{r}
# Plot with percents and response counts
r <- 
  ggplot(q61_plot, aes(x = reorder(chosen, count), y = percent_responded)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  geom_text(aes(label= paste(round(percent_responded,2), count, sep = "***")))

r
```

```{r}
# Save graph as PNG, plot data as csv, and all question data including response IDs as csv (save question n and N at end of plot file as "_x.x")
ggsave(filename = 'q61_barriers.png', plot = r, device = 'png')

write.csv(q61_plot, 'q61_barriers_144.csv', row.names = FALSE)

write.csv(q61_all, 'q61_barrers_ids.csv', row.names = FALSE)
```
