---
title: "q74 'What was the highest pay grade/rank achieved at the time of formal discharge?' National Veterans "
author: "DJ"
date: "1/74/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
# Load libraries
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
# Read in raw data from the Veterans surveys. These are the files downloaded from survey monkey saved as a .csv
raw_data_general <- read.csv("data/general.csv", stringsAsFactors = FALSE)
raw_data_botanist <- read.csv("data/botanist.csv", stringsAsFactors = FALSE)
raw_data_bask <- read.csv("data/bask.csv", stringsAsFactors = FALSE)
raw_data_hr <- read.csv("data/hr.csv", stringsAsFactors = FALSE)
```

```{r}
# Pull out all responses for q74 (a single selection question) combine, then determine 'question n'
q74 <- "What.was.the.highest.pay.grade.rank.achieved.at.the.time.of.formal.discharge."

q74_general <- get_single_selection(data = raw_data_general, q.name = q74)
q74_bask <- get_single_selection(data = raw_data_bask, q.name = q74)
q74_botanist <- get_single_selection(data = raw_data_botanist, q.name = q74)
q74_hr <- get_single_selection(data = raw_data_hr, q.name = q74)

q74_all <- rbind(q74_general, q74_bask, q74_botanist, q74_hr)

q74_n <- length(unique(q74_all$id))
```

```{r}
# Manipulate data into a graphable format
q74_plot <- 
  q74_all %>%
  group_by(response) %>%
  summarize(count = n()) %>%
  mutate(percent_all = count / sum(count)) %>%
  mutate(percent_responded = count / q74_n)
```

```{r}
# Plot with percents and response counts
r <- 
  ggplot(q74_plot, aes(x = reorder(response, count), y = percent_responded)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  geom_text(aes(label= paste(round(percent_responded, 2), count, sep = "***")))
r
```

```{r}
# Save graph as PNG, plot data as csv, and all question data including response IDs as csv (save question n and N at end of plot file as "_x.x")
ggsave(filename = 'q74_top_military_rank.png', plot = r, device = 'png')

write.csv(q74_plot, 'q74_top_military_rank_565.csv', row.names = FALSE)

write.csv(q74_all, 'q74_top_military_rank_ids.csv', row.names = FALSE)
```

