---
title: "q6 'Which is the primary health condition that causes you the most distress? (Please select one)' (MA Veterans)"
author: "David Ritter"
date: "November 19, 2019"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
# Load libraries
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
# Read in raw data from the Veterans surveys. These are the files downloaded from survey monkey saved as a .csv
raw_data_general <- read.csv("data/general.csv", stringsAsFactors = FALSE)
raw_data_botanist <- read.csv("data/botanist.csv", stringsAsFactors = FALSE)
raw_data_bask <- read.csv("data/bask.csv", stringsAsFactors = FALSE)
raw_data_hr <- read.csv("data/hr.csv", stringsAsFactors = FALSE)
```

```{r}
# Pull out all responses for q6 (a single selection question) combine, then determine 'question n'
q6 <- "Which.is.the.primary.health.condition.that.causes.you.the.most.distress...Please.select.one."

q6_general <- get_single_selection(data = raw_data_general, q.name = q6)
q6_bask <- get_single_selection(data = raw_data_bask, q.name = q6)
q6_botanist <- get_single_selection(data = raw_data_botanist, q.name = q6)
q6_hr <- get_single_selection(data = raw_data_hr, q.name = q6)

q6_all <- rbind(q6_general, q6_bask, q6_botanist, q6_hr)

q6_n <- length(unique(q6_all$id))
```

```{r}
# Optional Filtering by MA: Filter by ma_ids generated in seperate code (vet_q9_state)
q6_ma <-
  q6_all %>%
  inner_join(ma_ids, by = "id")

q6_ma_n <- length(unique(q6_ma$id))
```

```{r}
# Manipulate data into a graphable format
q6_plot <- 
  q6_ma %>%
  group_by(response.x) %>%
  summarize(count = n()) %>%
  mutate(percent_all = count / sum(count)) %>%
  mutate(percent_responded = count / q6_n)
```

```{r}
# Plot with percents and response counts
r <- 
  ggplot(q6_plot, aes(x = reorder(response.x, count), y = percent_responded)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  geom_text(aes(label= paste(round(percent_responded, 2), count, sep = "***")))
r
```

```{r}
# Save graph as PNG, plot data as csv, and all question data including response IDs as csv (save question n and N at end of plot file as "_x.x")
ggsave(filename = 'q6_top_condition.png', plot = r, device = 'png')

write.csv(q6_plot, 'q6_top_condition_161.csv', row.names = FALSE)

write.csv(q6_ma, 'q6_top_condition_ids.csv', row.names = FALSE)
```
