---
title: "Q98 State (Veterans)"
author: "DJ"
date: "June 26, 2019"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
# Load libraries
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
# Read in raw data from the Veterans surveys. These are the files downloaded from survey monkey saved as a .csv
raw_data_general <- read.csv("data/general_nat.csv", stringsAsFactors = FALSE)
raw_data_botanist <- read.csv("data/botanist_nat.csv", stringsAsFactors = FALSE)
raw_data_bask <- read.csv("data/bask_nat.csv", stringsAsFactors = FALSE)
raw_data_healing_rose <- read.csv("data/healing_rose_nat.csv", stringsAsFactors = FALSE)
```

```{r}
# Pull out all responses for Q98 (a single selection question) combine, then determine 'question n'

Q98 <- "What.state.in.the.US.do.you.currently.live.in."
Q99 <- "What.US.State.do.you.currently.live.in."
Q100 <- "Which.US.state.do.you.currently.live.in."
Q101 <- "What.US.state.do.you.currently.live.in."

Q98_general <- get_single_selection(data = raw_data_general, q.name = Q98)
Q98_bask <- get_single_selection(data = raw_data_bask, q.name = Q99)
Q98_botanist <- get_single_selection(data = raw_data_botanist, q.name = Q100)
Q98_healing_rose <- get_single_selection(data = raw_data_healing_rose, q.name = Q101)
Q98_all <- rbind(Q98_general, Q98_bask, Q98_botanist, Q98_healing_rose)

number_of_people <- length(unique(Q98_all$id))
```


```{r}
ma_ids <- Q98_all %>% 
  filter(response %in% c("Massachusetts"))
ma_people <- length(unique(ma_ids$id))
```

```{r}
# Manipulate data into a graphable format
Q98_plot <- 
  Q98_all %>%
  group_by(response) %>%
  summarize(count = n()) %>%
  mutate(percent_all = count / sum(count)) %>%
  mutate(percent_responded = count / number_of_people)
```

```{r}
# Plot with percents and response counts
r <- 
  ggplot(Q98_plot, aes(x = reorder(response, count), y = percent_responded)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  geom_text(aes(label= paste(round(percent_responded, 2), count, sep = "***")))

r
```

```{r}
# Save graph as PNG, plot data as csv, and all question data including response IDs as csv (save question n and N at end of plot file as "_x.x")
ggsave(filename = 'vet_q98_state.png', plot = r, device = 'png')

write.csv(Q98_plot, 'vet_q98_state_103.305.csv', row.names = FALSE)

write.csv(Q98_all, 'vet_q98_state_ids.csv', row.names = FALSE)
```






