---
title: "q7 'Which of the following symptoms are most commonly associated with your primary health condition or underlying health conditions? (Please select all that apply)' (Veterans)"
author: "David Ritter"
date: "November 19, 2019"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
# Load libraries
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
# Read in raw data from the Veterans surveys. These are the files downloaded from survey monkey saved as a .csv
raw_data_general <- read.csv("data/general.csv", stringsAsFactors = FALSE)
raw_data_botanist <- read.csv("data/botanist.csv", stringsAsFactors = FALSE)
raw_data_bask <- read.csv("data/bask.csv", stringsAsFactors = FALSE)
raw_data_hr <- read.csv("data/hr.csv", stringsAsFactors = FALSE)
```

```{r}
# Pull out all responses for q7 (a choose all question), combine, turn into a tidy data format for further processing then determine 'question n'
q7 <- 'Which.of.the.following.symptoms.are.most.commonly.associated.with.your.primary.health.condition.or.underlying.health.conditions...Please.select.all.that.apply.'
q7_final_response <- "X.43"

q7_general <- get_choose_all(raw_data_general, q.name = q7, f.response = q7_final_response)
q7_bask <- get_choose_all(raw_data_bask, q.name = q7, f.response = q7_final_response)
q7_botanist <- get_choose_all(raw_data_botanist, q.name = q7, f.response = q7_final_response)
q7_hr <- get_choose_all(raw_data_hr, q.name = q7, f.response = q7_final_response)

q7_all <- rbind(q7_general, q7_bask, q7_botanist, q7_hr) %>%
  tidy_choose_all()

q7_n <- length(unique(q7_all$id))
```

```{r}
# Manipulate data into a graphable format
q7_plot <-
  q7_all %>%
  group_by(chosen) %>%
  summarize(count = n()) %>%
  mutate(percent_all = count / sum(count)) %>%
  mutate(percent_responded = count / q7_n)
```

```{r}
# Plot with percents and response counts
r <- 
  ggplot(q7_plot, aes(x = reorder(chosen, count), y = percent_responded)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  geom_text(aes(label= paste(round(percent_responded,2), count, sep = "***")))
r
```

```{r}
# Save graph as PNG, plot data as csv, and all question data including response IDs as csv (save question n and N at end of plot file as "_x.x")
ggsave(filename = 'q7_condition_symptoms.png', plot = r, device = 'png')

write.csv(q7_plot, 'q7_condition_symptoms_565.csv', row.names = FALSE)

write.csv(q7_all, 'q7_condition_symptoms_ids.csv', row.names = FALSE)
```
