---
title: "q91 'What is the highest degree or level of school you have completed? (If you're currently enrolled in school, please indicate the highest degree you have received.)' National Veterans"
author: "DJ"
date: "1/6/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
# Load libraries
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
# Read in raw data from the Veterans surveys. These are the files downloaded from survey monkey saved as a .csv
raw_data_general <- read.csv("data/general.csv", stringsAsFactors = FALSE)
raw_data_botanist <- read.csv("data/botanist.csv", stringsAsFactors = FALSE)
raw_data_bask <- read.csv("data/bask.csv", stringsAsFactors = FALSE)
raw_data_hr <- read.csv("data/hr.csv", stringsAsFactors = FALSE)
```

```{r}
# Pull out all responses for q91 (a single selection question) combine, then determine 'question n'
q91 <- "What.is.the.highest.degree.or.level.of.school.you.have.completed...If.you.re.currently.enrolled.in.school..please.indicate.the.highest.degree.you.haveÂ.received..Â."

q91_general <- get_single_selection(data = raw_data_general, q.name = q91)
q91_bask <- get_single_selection(data = raw_data_bask, q.name = q91)
q91_botanist <- get_single_selection(data = raw_data_botanist, q.name = q91)
q91_hr <- get_single_selection(data = raw_data_hr, q.name = q91)

q91_all <- rbind(q91_general, q91_bask, q91_botanist, q91_hr)

q91_n <- length(unique(q91_all$id))
```

```{r}
# Manipulate data into a graphable format
q91_plot <- 
  q91_all %>%
  group_by(response) %>%
  summarize(count = n()) %>%
  mutate(percent_all = count / sum(count)) %>%
  mutate(percent_responded = count / q91_n)
```

```{r}
# Plot with percents and response counts
r <- 
  ggplot(q91_plot, aes(x = reorder(response, count), y = percent_responded)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  geom_text(aes(label= paste(round(percent_responded, 2), count, sep = "***")))
r
```

```{r}
# Save graph as PNG, plot data as csv, and all question data including response IDs as csv (save question n and N at end of plot file as "_x.x")
ggsave(filename = 'q91_highest_degree.png', plot = r, device = 'png')

write.csv(q91_plot, 'q91_highest_degree_565.csv', row.names = FALSE)

write.csv(q91_all, 'q91_highest_degree_ids.csv', row.names = FALSE)
```
