---
title: "q94 'Have you ever been homeless?' National Veterans"
author: "DJ"
date: "1/6/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
# Load libraries
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
# Read in raw data from the Veterans surveys. These are the files downloaded from survey monkey saved as a .csv
raw_data_general <- read.csv("data/general.csv", stringsAsFactors = FALSE)
raw_data_botanist <- read.csv("data/botanist.csv", stringsAsFactors = FALSE)
raw_data_bask <- read.csv("data/bask.csv", stringsAsFactors = FALSE)
raw_data_hr <- read.csv("data/hr.csv", stringsAsFactors = FALSE)
```

```{r}
# Pull out all responses for q94 (a single selection question) combine, then determine 'question n'
q94 <- "Have.you.ever.been.homeless."

q94_general <- get_single_selection(data = raw_data_general, q.name = q94)
q94_bask <- get_single_selection(data = raw_data_bask, q.name = q94)
q94_botanist <- get_single_selection(data = raw_data_botanist, q.name = q94)
q94_hr <- get_single_selection(data = raw_data_hr, q.name = q94)

q94_all <- rbind(q94_general, q94_bask, q94_botanist, q94_hr)

q94_n <- length(unique(q94_all$id))
```

```{r}
# Manipulate data into a graphable format
q94_plot <- 
  q94_all %>%
  group_by(response) %>%
  summarize(count = n()) %>%
  mutate(percent_all = count / sum(count)) %>%
  mutate(percent_responded = count / q94_n)
```

```{r}
# Plot with percents and response counts
r <- 
  ggplot(q94_plot, aes(x = reorder(response, count), y = percent_responded)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  geom_text(aes(label= paste(round(percent_responded, 2), count, sep = "***")))
r
```

```{r}
# Save graph as PNG, plot data as csv, and all question data including response IDs as csv (save question n and N at end of plot file as "_x.x")
ggsave(filename = 'q94_homeless.png', plot = r, device = 'png')

write.csv(q94_plot, 'q94_homeless_565.csv', row.names = FALSE)

write.csv(q94_all, 'q94_homeless_ids.csv', row.names = FALSE)
```
