---
title: "Q67 Which VA Do You Go To (Veterans)"
runtime: shiny
output: html_document
---

```{r, message = FALSE}
# Load libraries
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
# Read in raw data from the Veterans surveys. These are the files downloaded from survey monkey saved as a .csv
raw_data_general <- read.csv("data/general_text.csv", stringsAsFactors = FALSE)
raw_data_botanist <- read.csv("data/botanist_text.csv", stringsAsFactors = FALSE)
raw_data_bask <- read.csv("data/bask_text.csv", stringsAsFactors = FALSE)
raw_data_healing_rose <- read.csv("data/healing_rose_text.csv", stringsAsFactors = FALSE)
```

```{r}
# Pull out all responses for Q6 (a single selection question) combine, then determine 'question n'
Q67 <- "Which.VA.do.you.go.to."

Q67_general <- get_single_selection(data = raw_data_general, q.name = Q67)
Q67_bask <- get_single_selection(data = raw_data_bask, q.name = Q67)
Q67_botanist <- get_single_selection(data = raw_data_botanist, q.name = Q67)
Q67_healing_rose <- get_single_selection(data = raw_data_healing_rose, q.name = Q67)

Q67_all <- rbind(Q67_general, Q67_bask, Q67_botanist, Q67_healing_rose)

number_of_people <- length(unique(Q67_all$id))
```


```{r}

ggsave(Q67_all, file = "Q67_VA_Location.png")

```

```{r}

write.csv(Q67_all, 'Q67_VA_Location.csv', row.names = FALSE)

```







