---
title: "q49 'Please rate the importance of the following aspects of cannabis products to you:' (National Veterans)"
author: "DJ"
date: "October 21, 2019"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
# Load libraries
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
# Read in raw data from the Veterans surveys. These are the files downloaded from survey monkey saved as a .csv
raw_data_general <- read.csv("data/general.csv", stringsAsFactors = FALSE)
raw_data_botanist <- read.csv("data/botanist.csv", stringsAsFactors = FALSE)
raw_data_bask <- read.csv("data/bask.csv", stringsAsFactors = FALSE)
raw_data_hr <- read.csv("data/hr.csv", stringsAsFactors = FALSE)
```

```{r}
# Pull out all responses for q49 (a choose all question), combine, turn into a tidy data format for further processing then determine 'question n'
q49 <- "Please.rate.the.importance.of.the.following.aspects.ofÂ.cannabis.products....1.being.most.important..2.being.moderatelyÂ.important..3.being.least.important.."
q49_final_response <- "X.267"

q49_general <- get_choose_all(raw_data_general, q.name = q49, f.response = q49_final_response)
q49_bask <- get_choose_all(raw_data_bask, q.name = q49, f.response = q49_final_response)
q49_botanist <- get_choose_all(raw_data_botanist, q.name = q49, f.response = q49_final_response)
q49_hr <- get_choose_all(raw_data_hr, q.name = q49, f.response = q49_final_response)

q49_all <- rbind(q49_general, q49_bask, q49_botanist, q49_hr) %>%
  tidy_choose_all()

q49_n <- length(unique(q49_all$id))
```

```{r}
# Manipulate data into a graphable format
q49_plot <-
  q49_all %>%
  group_by(chosen) %>%
  summarize(count = n()) %>%
  mutate(percent_all = count / sum(count)) %>%
  mutate(percent_responded = count / q49_n)
```

```{r}
# Plot with percents and response counts
r <- 
  ggplot(q49_plot, aes(x = reorder(chosen, count), y = percent_responded)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  geom_text(aes(label= paste(round(percent_responded,2), count, sep = "***")))

r
```

```{r}
# Save graph as PNG, plot data as csv, and all question data including response IDs as csv (save question n and N at end of plot file as "_x.x")
ggsave(filename = 'q49_cannabis_aspect_importance.png', plot = r, device = 'png')

write.csv(q49_plot, 'q49_cannabis_aspect_importance_431.csv', row.names = FALSE)

write.csv(q49_all, 'q49_cannabis_aspect_importance_ids.csv', row.names = FALSE)
```
