---
title: "q50 'How many days do you use cannabis per week? (Please select one)' National"
author: "DJ"
date: "1/5/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
# Load libraries
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
# Read in raw data from the Veterans surveys. These are the files downloaded from survey monkey saved as a .csv
raw_data_general <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
# Pull out all responses for q50 (a single selection question) combine, then determine 'question n'
q50 <- "How.many.days.do.you.use.cannabis.per.week...Please.select.one."

q50_all <- get_single_selection(data = raw_data_general, q.name = q50)

q50_n <- length(unique(q50_all$id))
```

```{r}
# Manipulate data into a graphable format
q50_plot <- 
  q50_all %>%
  group_by(response) %>%
  summarize(count = n()) %>%
  mutate(percent_all = count / sum(count)) %>%
  mutate(percent_responded = count / q50_n)
```

```{r}
# Plot with percents and response counts
r <- 
  ggplot(q50_plot, aes(x = reorder(response, count), y = percent_responded)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  geom_text(aes(label= paste(round(percent_responded, 2), count, sep = "***")))
r
```

```{r}
# Save graph as PNG, plot data as csv, and all question data including response IDs as csv (save question n and N at end of plot file as "_x.x")
ggsave(filename = 'q50_cannabis_days_per_week.png', plot = r, device = 'png')

write.csv(q50_plot, 'q50_cannabis_days_per_week_217.csv', row.names = FALSE)

write.csv(q50_all, 'q50_cannabis_days_per_week_ids.csv', row.names = FALSE)
```
