---
title: "q88 'What is your age (in years)?' (Veterans)"
author: "David Ritter"
date: "November 19, 2019"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
# Load libraries
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
# Read in raw data from the Veterans surveys. These are the files downloaded from survey monkey saved as a .csv
raw_data_general <- read.csv("data/general.csv", stringsAsFactors = FALSE)
raw_data_botanist <- read.csv("data/botanist.csv", stringsAsFactors = FALSE)
raw_data_bask <- read.csv("data/bask.csv", stringsAsFactors = FALSE)
raw_data_hr <- read.csv("data/hr.csv", stringsAsFactors = FALSE)
```

```{r}
# Pull out all responses for q88 (a single selection question), combine, then determine 'question n'
q88 <- "What.is.your.age..in.years.."

q88_general <- get_single_selection(data = raw_data_general, q.name = q88)
q88_bask <- get_single_selection(data = raw_data_bask, q.name = q88)
q88_botanist <- get_single_selection(data = raw_data_botanist, q.name = q88)
q88_hr <- get_single_selection(data = raw_data_hr, q.name = q88)

q88_all <- rbind(q88_general, q88_bask, q88_botanist, q88_hr)

number_of_people <- length(unique(q88_all$id))
```

```{r}
test <- 
  q88_all %>%
  inner_join(ma_ids, by = "id")
```

```{r}

sixty_plus <- q88_data %>% 
  filter(response %in% c("60-69", "70+"))

thirty_sixty <- q88_data %>% 
  filter(response %in% c("30-39", "40-49", "50-59"))

under_thirty <- q88_data %>% 
  filter(response %in% c("21-29"))

```

```{r}
# Manipulate data into a graphable format
q88_plot <-
  q88_all %>%
  group_by(response, ) %>%
  summarize(count = n()) %>%
  ungroup() %>%
  mutate(percent_all = count / sum(count))
```

```{r}
# Plot with percents and response counts
r <- 
  ggplot(q88_plot, aes(x = response, y = count)) +
  geom_bar(stat = 'identity') +
  geom_text(aes(label= paste(round(percent_all,2), count, sep = "***")))

r
```

```{r}
# Save graph as PNG, plot data as csv, and all question data including response IDs as csv (save question n and N at end of plot file as "_x.x")
ggsave(filename = 'q88_age.png', plot = r, device = 'png')

write.csv(q88_plot, 'q88_age_565.csv', row.names = FALSE)

write.csv(q88_all, 'q88_age_ids.csv', row.names = FALSE)
```
