---
title: "q45 'What prescription medications are you currently taking for the health conditions and symptoms you face that you are actively trying to reduce the use of by using cannabis? (Please select all that apply)' (Veterans)"
author: "David Ritter"
date: "November 19, 2019"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
# Load libraries
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
# Read in raw data from the Veterans surveys. These are the files downloaded from survey monkey saved as a .csv
raw_data_general <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q45 <- 'What.prescription.medications.are.you.currently.taking.for.the.health.conditions.and.symptoms.you.face.that.you.are.actively.trying.to.reduce.the.use.of.by.using.cannabis...Please.select.all.that.apply.'

q45_final_response <- "X.249"

q45_general <- get_choose_all(raw_data_general, q.name = q45, f.response = q45_final_response)

q45_all <- tidy_choose_all(q45_general)

q45_n <- length(unique(q45_all$id))
```

```{r}
# Filter by ma_ids generated in seperate code (vet_q98_state)
#q45_ma <-
  #q45_all %>%
  #inner_join(ma_ids, by = "id")

#q45_ma_n <- length(unique(q45_ma$id))
```

```{r}
# Manipulate data into a graphable format
q45_plot <-
  q45_all %>%
  group_by(chosen) %>%
  summarize(count = n()) %>%
  mutate(percent_all = count / sum(count)) %>%
  mutate(percent_responded = count / q45_n)
```

```{r}
# Plot with percents and response counts
r <- 
  ggplot(q45_plot, aes(x = reorder(chosen, count), y = percent_responded)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  geom_text(aes(label= paste(round(percent_responded,2), count, sep = "***")))
r
```

```{r}
# Save graph as PNG, plot data as csv, and all question data including response IDs as csv (save question n and N at end of plot file as "_x.x")
ggsave(filename = 'q45_meds_reduced_cannabis.png', plot = r, device = 'png')

write.csv(q45_plot, 'q45_meds_reduced_cannabis_144.csv', row.names = FALSE)

write.csv(q45_all, 'q45_meds_reduced_cannabis_ids.csv', row.names = FALSE)
```
