---
title: "q103 'Do you belong to any of the following veterans support organizations? (Please select all that apply)' National Veterans"
author: "DJ"
date: "1/6/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
# Load libraries
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
# Read in raw data from the Veterans surveys. These are the files downloaded from survey monkey saved as a .csv
raw_data_general <- read.csv("data/general.csv", stringsAsFactors = FALSE)
raw_data_botanist <- read.csv("data/botanist.csv", stringsAsFactors = FALSE)
raw_data_bask <- read.csv("data/bask.csv", stringsAsFactors = FALSE)
raw_data_hr <- read.csv("data/hr.csv", stringsAsFactors = FALSE)
```

```{r}
# Pull out all responses for q103 (a choose all question), combine, turn into a tidy data format for further processing then determine 'question n'
q103 <- 'Do.you.belong.to.any.of.the.following.veterans.support.organizations...Please.select.all.that.apply.'
q103_final_response <- "X.395"

q103_general <- get_choose_all(raw_data_general, q.name = q103, f.response = q103_final_response)
q103_bask <- get_choose_all(raw_data_bask, q.name = q103, f.response = q103_final_response)
q103_botanist <- get_choose_all(raw_data_botanist, q.name = q103, f.response = q103_final_response)
q103_hr <- get_choose_all(raw_data_hr, q.name = q103, f.response = q103_final_response)

q103_all <- 
  rbind(q103_general, q103_bask, q103_botanist, q103_hr) %>%
  tidy_choose_all()

q103_n <- length(unique(q103_all$id))
```

```{r}
# Manipulate data into a graphable format
q103_plot <-
  q103_all %>%
  group_by(chosen) %>%
  summarize(count = n()) %>%
  mutate(percent_all = count / sum(count)) %>%
  mutate(percent_responded = count / q103_n)
```

```{r}
# Plot with percents and response counts
r <- 
  ggplot(q103_plot, aes(x = reorder(chosen, count), y = percent_responded)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  geom_text(aes(label= paste(round(percent_responded,2), count, sep = "***")))
r
```

```{r}
# Save graph as PNG, plot data as csv, and all question data including response IDs as csv (save question n and N at end of plot file as "_x.x")
ggsave(filename = 'q103_vet_support_groups.png', plot = r, device = 'png')

write.csv(q103_plot, 'q103_vet_support_groups_562.csv', row.names = FALSE)

write.csv(q103_all, 'q103_vet_support_groups_ids.csv', row.names = FALSE)
```
