---
title: "q67 Which VA Do You Go To (Veterans)"
runtime: shiny
output: html_document
---

```{r, message = FALSE}
# Load libraries
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
# Read in raw data from the Veterans surveys. These are the files downloaded from survey monkey saved as a .csv
raw_data_general <- read.csv("data/general_nat.csv", stringsAsFactors = FALSE)
raw_data_botanist <- read.csv("data/botanist_nat.csv", stringsAsFactors = FALSE)
raw_data_bask <- read.csv("data/bask_nat.csv", stringsAsFactors = FALSE)
raw_data_healing_rose <- read.csv("data/healing_rose_nat.csv", stringsAsFactors = FALSE)
```

```{r}
# Pull out all responses for q6 (a single selection question) combine, then determine 'question n'
q67 <- "Which.VA.do.you.go.to."

q67_general <- get_single_selection(data = raw_data_general, q.name = q67)
q67_bask <- get_single_selection(data = raw_data_bask, q.name = q67)
q67_botanist <- get_single_selection(data = raw_data_botanist, q.name = q67)
q67_healing_rose <- get_single_selection(data = raw_data_healing_rose, q.name = q67)

q67_all <- rbind(q67_general, q67_bask, q67_botanist, q67_healing_rose)

number_of_people <- length(unique(q67_all$id))
```


```{r}
write.csv(q67_all, 'q67_VA_Location.csv', row.names = FALSE)


```

```{r}

write.csv(q67_all, 'q67_VA_Location.csv', row.names = FALSE)

```







