---
title: "q29 'What percentage of disability are you rated, as indicated by the Veteran's Affairs (VA)?' (MA Veterans)"
author: "David Ritter"
date: "November 19, 2019"
output: html_document
---
```{r, message = FALSE}
# Load libraries
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
# Read in raw data from the Veterans surveys. These are the files downloaded from survey monkey saved as a .csv
raw_data_general <- read.csv("data/general.csv", stringsAsFactors = FALSE)
raw_data_botanist <- read.csv("data/botanist.csv", stringsAsFactors = FALSE)
raw_data_bask <- read.csv("data/bask.csv", stringsAsFactors = FALSE)
raw_data_hr <- read.csv("data/hr.csv", stringsAsFactors = FALSE)
```

```{r}
# Pull out all responses for q98 (a single selection question) combine, then determine 'question n' (subsequent q are labeled for convenience, do not respond to survey q#)

q98 <- "What.state.in.the.US.do.you.currently.live.in."
q99 <- "What.US.State.do.you.currently.live.in."
q100 <- "Which.US.state.do.you.currently.live.in."
q101 <- "What.US.state.do.you.currently.live.in."

q98_general <- get_single_selection(data = raw_data_general, q.name = q98)
q98_bask <- get_single_selection(data = raw_data_bask, q.name = q99)
q98_botanist <- get_single_selection(data = raw_data_botanist, q.name = q100)
q98_hr <- get_single_selection(data = raw_data_hr, q.name = q101)

q98_all <- rbind(q98_general, q98_bask, q98_botanist, q98_hr)

ma_ids <- q98_all %>% 
  filter(response %in% c("Massachusetts"))

state_ma <- length(unique(ma_ids$id))
```

```{r}
# Pull out all responses for q29 (a single selection question) combine, then determine 'question n'
q29 <- "What.percentage.of.disability.are.you.rated..as.is.indicated.by.the.Veteran.s.Affairs..VA.."

q29_general <- get_single_selection(data = raw_data_general, q.name = q29)
q29_bask <- get_single_selection(data = raw_data_bask, q.name = q29)
q29_botanist <- get_single_selection(data = raw_data_botanist, q.name = q29)
q29_hr <- get_single_selection(data = raw_data_hr, q.name = q29)

q29_all <- rbind(q29_general, q29_bask, q29_botanist, q29_hr) %>%
  inner_join(ma_ids, by = "id")

q29_m_n <- length(unique(q29_all$id))
```


```{r}
histogram_object <- hist(as.numeric(q29_all$response))
histogram_object$breaks
histogram_object$counts
plot(histogram_object)
```

```{r}
ggsave(plot(histogram_object), file = "q29_Percentage_Disability.png")
```

```{r}
write.csv(q29_all, 'q29_Percentage_Disability_127.csv', row.names = FALSE)
```



