---
title: "Q45 Prescriptions Reduced Cannabis (Unfiltered) (MA Veterans)"
author: "DJ"
date: "July 29, 2019"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
# Load libraries
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
# Read in raw data from the Veterans surveys. These are the files downloaded from survey monkey saved as a .csv
raw_data_general <- read.csv("data/general_nat.csv", stringsAsFactors = FALSE)
raw_data_botanist <- read.csv("data/botanist_nat.csv", stringsAsFactors = FALSE)
raw_data_bask <- read.csv("data/bask_nat.csv", stringsAsFactors = FALSE)
raw_data_healing_rose <- read.csv("data/healing_rose_nat.csv", stringsAsFactors = FALSE)
```

```{r}
# Pull out all responses for Q45 (a choose all question), combine, turn into a tidy data format for further processing then determine 'question n'
Q45 <- 'What.prescription.medications.are.you.currently.taking.for.the.health.conditions.and.symptoms.you.face.that.you.are.actively.trying.to.reduce.the.use.of.by.using.cannabis...Please.select.all.that.apply.'
Q45_final_response <- "X.249"

Q45_general <- get_choose_all(raw_data_general, q.name = Q45, f.response = Q45_final_response)
Q45_botanist <- get_choose_all(raw_data_botanist, q.name = Q45, f.response = Q45_final_response)
Q45_healing_rose <- get_choose_all(raw_data_healing_rose, q.name = Q45, f.response = Q45_final_response)
Q45_bask <- get_choose_all(raw_data_bask, q.name = Q45, f.response = Q45_final_response)

Q45_all <- 
  rbind(Q45_general, Q45_botanist, Q45_healing_rose) %>%
  tidy_choose_all()

number_of_people <- length(unique(Q45_all$id))
```

```{r}
# Manipulate data into a graphable format
Q45_plot <-
  Q45_all %>%
  group_by(chosen) %>%
  summarize(count = n()) %>%
  mutate(percent_all = count / sum(count)) %>%
  mutate(percent_responded = count / number_of_people)
```

```{r}
# Plot with percents and response counts
r <- 
  ggplot(Q45_plot, aes(x = reorder(chosen, count), y = percent_responded)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  geom_text(aes(label= paste(round(percent_responded,2), count, sep = "***")))

r
```

```{r}
# Save graph as PNG, plot data as csv, and all question data including response IDs as csv (save question n and N at end of plot file as "_x.x")
ggsave(filename = 'vet_q45_prescriptions_reduced_cannabis_unfiltered.png', plot = r, device = 'png')

write.csv(Q45_plot, 'vet_q45_prescriptions_reduced_cannabis_unfiltered_388.csv', row.names = FALSE)

write.csv(Q45_all, 'vet_q45_prescriptions_reduced_cannabis_unfiltered_ids.csv', row.names = FALSE)
```






