---
title: "q100 'Do you think the VA should be trained in medical cannabis and allowed to recommend it for veterans?'"
author: "David Ritter"
date: "2/28/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q100 <- "Do.you.think.the.VA.should.be.trained.in.medical.cannabis.and.allowed.to.recommend.it.for.veterans."
q100_t <- "Do you think the VA should be trained in medical cannabis and allowed to recommend it for veterans?"
q100_data <- get_single_selection(data = raw_data, q.name = q100)
q100_n <- length(unique(q100_data$id))
q100_plot<- clean_single_select(q100_data)
r100 <- plot_single_select(q100_plot, q100_t, q100_n)
r100
```

```{r}
row3 <- colnames(q100_plot)
q100_plot2 <- rbind(row3, q100_plot)
names(q100_plot2) <- c("q100", q100_t, paste("n = ", q100_n))
```

```{r}
dir.create("output/q100_va_offer_cannabis")
ggsave(filename = 'output/q100_va_offer_cannabis/q100_va_offer_cannabis.png', plot = r100, device = 'png')
write.csv(q100_plot2, paste0("output/q100_va_offer_cannabis/q100_va_offer_cannabis_", q100_n,".csv"), row.names=F)
```







```{r}
qf_data <- q_data %>%
  filter(response == "Response text")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")
qf_n <- length(unique(qf_all_data$id))
q_plot <- clean_single_select_y(qf_all_data)
r <- plot_single_select_y(q_plot)
r
```

```{r}
q_plot2 <- rbind(q_plot, t)
dir.create("output/q100_va_offer_cannabis")
ggsave(filename = 'output/q100_va_offer_cannabis/q100_va_offer_cannabis.png', plot = r, device = 'png')
write.csv(q_plot2, paste0("output/q100_va_offer_cannabis/q100_va_offer_cannabis_", qf_n,".csv"), row.names=F)
```