---
title: "q14 'What are the effects of your pain? (Please select all that apply)'"
author: "David Ritter"
date: "2/29/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q14 <- 'What.are.the.effects.of.your.pain...Please.select.all.that.apply.'
q14_final_response <- "X.81"
q14_t <- "What are the effects of your pain? (Please select all that apply)"
q14_data <- get_choose_all(raw_data, q.name = q14, f.response = q14_final_response) %>%
  tidy_choose_all()
q14_n <- length(unique(q14_data$id))
q14_plot <- clean_choose_all(q14_data, q14_n)
r14 <- plot_choose_all(q14_plot, q14_t, q14_n)
r14
```

```{r}
row3 <- colnames(q14_plot)
q14_plot2 <- rbind(row3, q14_plot)
names(q14_plot2) <- c("q14", q14_t, paste("n = ", q14_n))
```

```{r}
dir.create("output/q14_pain_effects")
ggsave(filename = 'output/q14_pain_effects/q14_pain_effects.png', plot = r14, device = 'png')
write.csv(q14_plot2, paste0("output/q14_pain_effects/q14_pain_effects_", q14_n,".csv"), row.names=F)
write.csv(q14_data, 'output/q14_pain_effects/q14_pain_effects_ids.csv', row.names = FALSE)
```
