---
title: "q38 'Which health conditions do you find cannabis to be helpful in treating? (Please select all that apply)'"
author: "David Ritter"
date: "2/28/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q38 <- 'Which.health.conditions.do.you.find.cannabis.to.be.helpful.in.treating...Please.select.all.that.apply.'
q38_final_response <- "X.179"
q38_t <- "Which health conditions do you find cannabis to be helpful in treating? (Please select all that apply)"
q38_data <- get_choose_all(raw_data, q.name = q38, f.response = q38_final_response) %>%
  tidy_choose_all()
q38_n <- length(unique(q38_data$id))
q38_plot <- clean_choose_all(q38_data, q38_n)
r38 <- plot_choose_all(q38_plot, q38_t, q38_n)
r38
```

```{r}
row3 <- colnames(q38_plot)
q38_plot2 <- rbind(row3, q38_plot)
names(q38_plot2) <- c("q38", q38_t, paste("n = ", q38_n))
```

```{r}
dir.create("output/q38_conditions_cannabis")
ggsave(filename = 'output/q38_conditions_cannabis/q38_conditions_cannabis.png', plot = r38, device = 'png')
write.csv(q38_plot2, paste0("output/q38_conditions_cannabis/q38_conditions_cannabis_", q38_n,".csv"), row.names=F)
write.csv(q38_data, 'output/q38_conditions_cannabis/q38_conditions_cannabis_ids.csv', row.names = FALSE)
```







```{r}
qf_data <- q_data %>%
  filter(chosen == "Response text")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")
qf_n <- length(unique(qf_all_data$id))
qf_data <- qf_all_data[3] %>%
  group_by(chosen) %>%
  summarize(count=n()) %>%
  mutate(percent_responded = round(100*(count / qf_n), 2)) %>%
  arrange(desc(count))
```

```{r}
q_plot <- clean_choose_all_f2(qf_data)
r <- plot_choose_all_f2(q_plot)
r
```

```{r}
q_plot2 <- rbind(q_plot, t)
dir.create("output/q38_conditions_cannabis")
ggsave(filename = 'output/q38_conditions_cannabis/q38_conditions_cannabis.png', plot = r, device = 'png')
write.csv(q_plot2, paste0("output/q38_conditions_cannabis/q38_conditions_cannabis_", qf_n,".csv"), row.names=F)
write.csv(qf_all_data, 'output/q38_conditions_cannabis/q38_conditions_cannabis_ids.csv', row.names = FALSE)
```


