---
title: "q48 'What is your top preferred method (that is, favorite method) of using cannabis? (Please select one)'"
author: "David Ritter"
date: "2/28/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q48 <- "What.is.your.top.preferred.method..that.is..favorite.method..of.using.cannabis...Please.select.one."
q48_t <- "What is your top preferred method (that is, favorite method) of using cannabis? (Please select one)"
q48_data <- get_single_selection(data = raw_data, q.name = q48)
q48_n <- length(unique(q48_data$id))
q48_plot<- clean_single_select(q48_data)
r48 <- plot_single_select(q48_plot, q48_t, q48_n)
r48
```

```{r}
row3 <- colnames(q48_plot)
q48_plot2 <- rbind(row3, q48_plot)
names(q48_plot2) <- c("q48", q48_t, paste("n = ", q48_n))
```

```{r}
dir.create("output/q48_top_cannabis_method")
ggsave(filename = 'output/q48_top_cannabis_method/q48_top_cannabis_method.png', plot = r48, device = 'png')
write.csv(q48_plot2, paste0("output/q48_top_cannabis_method/q48_top_cannabis_method_", q48_n,".csv"), row.names=F)
```







```{r}
qf_data <- q_data %>%
  filter(response == "Smoke flower")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")
qf_n <- length(unique(qf_all_data$id))
q_plot <- clean_single_select_y(qf_all_data)
r <- plot_single_select_y(q_plot)
r
```

```{r}
q_plot2 <- rbind(q_plot, t)
dir.create("output/q48_top_cannabis_method")
ggsave(filename = 'output/q48_top_cannabis_method/q48_top_cannabis_method.png', plot = r, device = 'png')
write.csv(q_plot2, paste0("output/q48_top_cannabis_method/q48_top_cannabis_method_", qf_n,".csv"), row.names=F)
```
