---
title: "q55 'Do you grow your own cannabis at home?'"
author: "David Ritter"
date: "2/28/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q55 <- "Do.you.grow.your.own.cannabis.at.home."
q55_t <- "Do you grow your own cannabis at home?"
q55_data <- get_single_selection(data = raw_data, q.name = q55)
q55_n <- length(unique(q55_data$id))
q55_plot<- clean_single_select(q55_data)
r55 <- plot_single_select(q55_plot, q55_t, q55_n)
r55
```

```{r}
row3 <- colnames(q55_plot)
q55_plot2 <- rbind(row3, q55_plot)
names(q55_plot2) <- c("q55", q55_t, paste("n = ", q55_n))
```

```{r}
dir.create("output/q55_home_grow")
ggsave(filename = 'output/q55_home_grow/q55_home_grow.png', plot = r55, device = 'png')
write.csv(q55_plot2, paste0("output/q55_home_grow/q55_home_grow_", q55_n,".csv"), row.names=F)
```







```{r}
qf_data <- q_data %>%
  filter(response == "No")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")
qf_n <- length(unique(qf_all_data$id))
q_plot <- clean_single_select_y(qf_all_data)
r <- plot_single_select_y(q_plot)
r
```

```{r}
q_plot2 <- rbind(q_plot, t)
dir.create("output/q55_home_grow")
ggsave(filename = 'output/q55_home_grow/q55_home_grow.png', plot = r, device = 'png')
write.csv(q_plot2, paste0("output/q55_home_grow/q55_home_grow_", qf_n,".csv"), row.names=F)
```