---
title: "How much cannabis flower are you smoking or vaping per week (ie. grams, ounces, etc)?"
author: "David Ritter"
date: "2/28/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q62 <- 'How.much.cannabis.flower.are.you.smoking.or.vaping.per.week...i.e..grams..ounces..etc..'
q62_final_response <- "X.283"
q62_t <- "How much cannabis flower are you smoking or vaping per week (ie. grams, ounces, etc)?"
q62_data <- get_choose_all(raw_data, q.name = q62, f.response = q62_final_response)
dir.create("output/q62_smoke_vape_wkly")
```

```{r}
write.csv(q62_data, 'output/q62_smoke_vape_wkly/q62_smoke_vape_wkly_data.csv', row.names = FALSE)
```

```{r}
q62_data1 <- get_single_selection_3(q62_data, "Smoke flower") %>%
  filter(response != "") %>%
  clean_single_select()
q62_n1 <- tally(q62_data1, count)
q62_t1 <- "Flower weekly"
q62_r1 <- plot_single_select(q62_data1, q62_t1, q62_n1)
q62_r1
```

```{r}
ggsave(filename = "output/q62_smoke_vape_wkly/smoke_flower.png", plot = q62_r1, device = 'png')
write.csv(q62_data1, paste0("output/q62_smoke_vape_wkly/smoke_flower_", q62_n1, ".csv"), row.names = FALSE)
```

```{r}
q62_data2 <- get_single_selection_3(q62_data, "Vape flower") %>%
  filter(response != "") %>%
  clean_single_select()
q62_n2 <- tally(q62_data2, count)
q62_t2 <- "Vape weekly"
q62_r2 <- plot_single_select(q62_data2, q62_t2, q62_n2)
q62_r2
```

```{r}
ggsave(filename = "output/q62_smoke_vape_wkly/vape_flower.png", plot = q62_r2, device = 'png')
write.csv(q62_data2, paste0("output/q62_smoke_vape_wkly/vape_flower_", q62_n2, ".csv"), row.names = FALSE)
```

```{r}
q62_data3 <- get_single_selection_3(q62_data, "Concentrates (e.g. rosin, shatter, wax, hash, kief)") %>%
  filter(response != "") %>%
  clean_single_select()
q62_n3 <- tally(q62_data3, count)
q62_t3 <- "Concentrates weekly"
q62_r3 <- plot_single_select(q62_data3, q62_t3, q62_n3)
q62_r3
```

```{r}
ggsave(filename = "output/q62_smoke_vape_wkly/concentrates.png", plot = q62_r3, device = 'png')
write.csv(q62_data3, paste0("output/q62_smoke_vape_wkly/concentrates_", q62_n3, ".csv"), row.names = FALSE)
```

