---
title: "In an average week, how often do you use salves/topicals (e.g. creams, lotions, sprays, etc.)"
author: "David Ritter"
date: "2/25/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q64 <- 'In.an.average.week..how.often.do.you.use.salves.topicals..e.g..creams..lotions..sprays..etc...'
q64_final_response <- "X.303"
q64_t <- "In an average week, how often do you use salves/topicals (e.g. creams, lotions, sprays, etc.)"
q64_data <- get_choose_all(raw_data, q.name = q64, f.response = q64_final_response)
dir.create("output/q64_salves_topicals_wkly")
```

```{r}
q64_data1 <- get_single_selection_3(q64_data, "Salves/topicals") %>%
  filter(response != "") %>%
  clean_single_select()
q64_n1 <- tally(q64_data1, count)
q64_t1 <- "Salves/topicals"
q64_r1 <- plot_single_select(q64_data1, q64_t1, q64_n1)
q64_r1
```

```{r}
ggsave(filename = "output/q64_salves_topicals_wkly/q64_salves_topicals_wkly.png", plot = q64_r1, device = 'png')
write.csv(q64_data1, paste0("output/q64_salves_topicals_wkly/q64_salves_topicals_wkly_", q64_n1, ".csv"), row.names = FALSE)
```


