---
title: "Q66 Does your VA doctor or clinical care provider know about your medical cannabis use?"
author: "David Ritter"
date: "2/28/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q66 <- "Does.yourÂ.VA.doctor.or.clinical.care.provider.know.about.your.medical.cannabis.use."
q66_t <- "Does your VA doctor or clinical care provider know about your medical cannabis use?"
q66_data <- get_single_selection(data = raw_data, q.name = q66)
q66_n <- length(unique(q66_data$id))
q66_plot<- clean_single_select(q66_data)
r66 <- plot_single_select(q66_plot, q66_t, q66_n)
r66
```

```{r}
row3 <- colnames(q66_plot)
q66_plot2 <- rbind(row3, q66_plot)
names(q66_plot2) <- c("q66", q66_t, paste("n = ", q66_n))
```

```{r}
dir.create("output/q66_va_use_knowledge")
ggsave(filename = 'output/q66_va_use_knowledge/q66_va_use_knowledge.png', plot = r66, device = 'png')
write.csv(q66_plot2, paste0("output/q66_va_use_knowledge/q66_va_use_knowledge_", q66_n,".csv"), row.names=F)
```







```{r}
qf_data <- q_data %>%
  filter(response == "Response text")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")
qf_n <- length(unique(qf_all_data$id))
q_plot <- clean_single_select_y(qf_all_data)
r <- plot_single_select_y(q_plot)
r
```

```{r}
q_plot2 <- rbind(q_plot, t)
dir.create("output/q66_va_use_knowledge")
ggsave(filename = 'output/q66_va_use_knowledge/q66_va_use_knowledge.png', plot = r, device = 'png')
write.csv(q_plot2, paste0("output/q66_va_use_knowledge/q66_va_use_knowledge_", qf_n,".csv"), row.names=F)
```
