---
title: "q74 'What was the highest pay grade/rank achieved at the time of formal discharge?'"
author: "David Ritter"
date: "2/28/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q74 <- "What.was.the.highest.pay.grade.rank.achieved.at.the.time.of.formal.discharge."
q74_t <- "What was the highest pay grade/rank achieved at the time of formal discharge?"
q74_data <- get_single_selection(data = raw_data, q.name = q74)
q74_n <- length(unique(q74_data$id))
q74_plot<- clean_single_select(q74_data)
r74 <- plot_single_select(q74_plot, q74_t, q74_n)
```

```{r}
row3 <- colnames(q74_plot)
q74_plot2 <- rbind(row3, q74_plot)
names(q74_plot2) <- c("q74", q74_t, paste("n = ", q74_n))
```

```{r}
dir.create("output/q74_top_military_rank")
write.csv(q74_plot2, paste0("output/q74_top_military_rank/q74_top_military_rank_", q74_n,".csv"), row.names=F)
```







```{r}
qf_data <- q_data %>%
  filter(response == "Response text")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")

qf_n <- length(unique(qf_all_data$id))
```

```{r}
q_plot <- clean_single_select_f(qf_all_data)
r <- plot_single_select_f(q_plot)
r
```

```{r}
q_plot2 <- rbind(q_plot, t)
dir.create("output/q74_top_military_rank")
ggsave(filename = 'output/q74_top_military_rank/q74_top_military_rank.png', plot = r, device = 'png')
write.csv(q_plot2, paste0("output/q74_top_military_rank/q74_top_military_rank_", qf_n,".csv"), row.names=F)
```