---
title: "Q29 Percentage Disability (Healing Rose)"
author: "DJ"
date: "August 8, 2019"
output: html_document
---
```{r, message = FALSE}
# Load libraries
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
# Read in raw data from the Healing Rose surveys. These are the files downloaded from survey monkey saved as a .csv
raw_data_healing_rose <- read.csv("data/healing_rose_nat.csv", stringsAsFactors = FALSE)
```

```{r}
# Pull out all responses for Q29 (a single selection question) combine, then determine 'question n'
Q29 <- "What.percentage.of.disability.are.you.rated..as.is.indicated.by.the.Veteran.s.Affairs..VA.."

Q29_healing_rose <- get_single_selection(data = raw_data_healing_rose, q.name = Q29)

Q29_all <- rbind(Q29_healing_rose)

number_of_people <- length(unique(Q29_all$id))
```


```{r}
histogram_object <- hist(as.numeric(Q29_all$response))
histogram_object$breaks
histogram_object$counts
plot(histogram_object)
```

```{r}
ggsave(plot(histogram_object), file = "hr_Q29_Percentage_Disability.png")
```

```{r}
write.csv(Q29_all, 'hr_Q29_Percentage_Disability_3.csv', row.names = FALSE)
```



