---
title: "q15 Anxiety Scales"
author: "David Ritter"
date: "2/16/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
# Load libraries
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q <- "If.you.checked.offÂ.ï..anyï..problems..howÂ.difficult.have.these.problems.made.it.for.you.to.do.your.work..take.care.of.things.at.home..or.get.along.with.other.people."

q_data <- get_single_selection(data = raw_data, q.name = q)

q_n <- length(unique(q_data$id))
```

```{r}
#OPTIONAL: Filter one response, then move to process qf_data in the code of the other question being analyzed
qf_data <- filter(q_data, response == "Fair")
```

```{r}
#Pass q_data to clean_data to create q_plot. Then pass q_plot through clean_plot to produce plot.
q_plot<- clean_single_select(q_data)

plot_single_select(q_plot) +
  labs(title = "Question Text", subtitle = q_n)
```

```{r}
ggsave(filename = 'q#_qtext.png', plot = r, device = 'png')

write.csv(q_plot, 'q#_qtext_##.csv', row.names = FALSE)

write.csv(q_data, 'q#_qtext_ids.csv', row.names = FALSE)
```


```{r}
#OPTIONAL FILTERING!!!
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")

q_n <- length(unique(qf_all_data$id))
```

```{r}
#Pass q_data to clean_data to create q_plot. Then pass q_plot through clean_plot to produce plot.
q_plot <- clean_single_select(qf_all_data)

r <- plot_single_select(q_plot) +
  labs(title = "Question Text", subtitle = q_n)
r
```

```{r}
ggsave(filename = 'q#_qtext.png', plot = r, device = 'png')

write.csv(q_plot, 'q#_qtext_##.csv', row.names = FALSE)

write.csv(q_data, 'q#_qtext_ids.csv', row.names = FALSE)
```
