---
title: "Template code for choose-all questions and filtering"
author: "David Ritter"
date: "2/16/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
# Load libraries
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q <- 'Which.of.the.following.health.conditions.do.you.face.and.or.have.been.diagnosed.with...Please.select.all.that.apply.'
q_final_response <- "X.25"

q_data <- get_choose_all(raw_data, q.name = q, f.response = q_final_response) %>%
  tidy_choose_all()

q_n <- length(unique(q_data$id))
```

```{r}
#OPTIONAL Filter one response, then move to process qf_data in the code of the other question being analyzed
qf_data <- filter(q_data, chosen == "Anxiety")
```

```{r}
#Pass q_data to clean_data to create q_plot. Then pass q_plot through clean_plot to produce plot.
q_plot<- clean_choose_all(q_data)

r <- plot_choose_all(q_plot) +
  labs(title = "Question text", subtitle = q_n)
r
```

```{r}
# Save graph as PNG, plot data as csv, and all question data including response IDs as csv (save question n and N at end of plot file as "_x.x")
ggsave(filename = 'q#_qtext.png', plot = r, device = 'png')

write.csv(q_plot, 'q#_qtext_XX.csv', row.names = FALSE)

write.csv(q_data, 'q#_qtext_ids.csv', row.names = FALSE)
```

```{r}
#OPTIONAL FILTERING!!!  Filter out responses from non-selected IDs. Run after step that generates q_data.
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")

q_n <- length(unique(qf_all_data$id))
```

```{r}
#OPTIONAL FILTERING!!!
q_plot<- clean_choose_all(qf_all_data)

r <- plot_choose_all(q_plot) +
  labs(title = "Which health conditions do you find cannabis to be helpful in treating? (Please select all that apply)", subtitle = q_n)
r
```

```{r}
# Save graph as PNG, plot data as csv, and all question data including response IDs as csv (save question n and N at end of plot file as "_x.x")
ggsave(filename = 'q#_qtext.png', plot = r, device = 'png')

write.csv(q_plot, 'q#_qtext_XX.csv', row.names = FALSE)

write.csv(qf_all_data, 'q#_qtext_ids.csv', row.names = FALSE)
```
