---
title: "q78 'Were you exposed to workplace hazards including loud noises from firearms/factories/etc, chemicals, exposed to burn pits during war, or working hazardous environments that could impair any of your five senses and clinical health?' National Veterans"
author: "DJ"
date: "1/6/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
# Load libraries
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
# Read in raw data from the Veterans surveys. These are the files downloaded from survey monkey saved as a .csv
raw_data_general <- read.csv("data/general.csv", stringsAsFactors = FALSE)
raw_data_botanist <- read.csv("data/botanist.csv", stringsAsFactors = FALSE)
raw_data_bask <- read.csv("data/bask.csv", stringsAsFactors = FALSE)
raw_data_hr <- read.csv("data/hr.csv", stringsAsFactors = FALSE)
```

```{r}
# Pull out all responses for q78 (a single selection question) combine, then determine 'question n'
q78 <- "Were.you.exposed.to.workplace.hazards.including.loud.noises.from.firearms.factories.etc..chemicals..exposed.to.burn.pits.during.war..or.working.hazardous.environments.that.could.impair.any.of.your.five.senses.and.clinical.health."

q78_general <- get_single_selection(data = raw_data_general, q.name = q78)
q78_bask <- get_single_selection(data = raw_data_bask, q.name = q78)
q78_botanist <- get_single_selection(data = raw_data_botanist, q.name = q78)
q78_hr <- get_single_selection(data = raw_data_hr, q.name = q78)

q78_all <- rbind(q78_general, q78_bask, q78_botanist, q78_hr)

q78_n <- length(unique(q78_all$id))
```

```{r}
# Manipulate data into a graphable format
q78_plot <- 
  q78_all %>%
  group_by(response) %>%
  summarize(count = n()) %>%
  mutate(percent_all = count / sum(count)) %>%
  mutate(percent_responded = count / q78_n)
```

```{r}
# Plot with percents and response counts
r <- 
  ggplot(q78_plot, aes(x = reorder(response, count), y = percent_responded)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  geom_text(aes(label= paste(round(percent_responded, 2), count, sep = "***")))
r
```

```{r}
# Save graph as PNG, plot data as csv, and all question data including response IDs as csv (save question n and N at end of plot file as "_x.x")
ggsave(filename = 'q78_workplace_hazards.png', plot = r, device = 'png')

write.csv(q78_plot, 'q78_workplace_hazards_199.csv', row.names = FALSE)

write.csv(q78_all, 'q78_workplace_hazards_ids.csv', row.names = FALSE)
```
