---
title: "q104 'Would you be willing to let your anonymous results be re-shared with other researchers to use in future data analysis and publications?' National Veterans"
author: "DJ"
date: "1/6/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
# Load libraries
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
# Read in raw data from the Veterans surveys. These are the files downloaded from survey monkey saved as a .csv
raw_data_general <- read.csv("data/general.csv", stringsAsFactors = FALSE)
raw_data_botanist <- read.csv("data/botanist.csv", stringsAsFactors = FALSE)
raw_data_bask <- read.csv("data/bask.csv", stringsAsFactors = FALSE)
raw_data_hr <- read.csv("data/hr.csv", stringsAsFactors = FALSE)
```

```{r}
# Pull out all responses for q104 (a single selection question) combine, then determine 'question n'
q104 <- "Would.you.be.willing.to.let.your.anonymous.results.be.re.shared.with.other.researchers.to.use.in.future.data.analysis.and.publications."

q104_general <- get_single_selection(data = raw_data_general, q.name = q104)
q104_bask <- get_single_selection(data = raw_data_bask, q.name = q104)
q104_botanist <- get_single_selection(data = raw_data_botanist, q.name = q104)
q104_hr <- get_single_selection(data = raw_data_hr, q.name = q104)

q104_all <- rbind(q104_general, q104_bask, q104_botanist, q104_hr)

q104_n <- length(unique(q104_all$id))
```

```{r}
# Manipulate data into a graphable format
q104_plot <- 
  q104_all %>%
  group_by(response) %>%
  summarize(count = n()) %>%
  mutate(percent_all = count / sum(count)) %>%
  mutate(percent_responded = count / q104_n)
```

```{r}
# Plot with percents and response counts
r <- 
  ggplot(q104_plot, aes(x = reorder(response, count), y = percent_responded)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  geom_text(aes(label= paste(round(percent_responded, 2), count, sep = "***")))
r
```

```{r}
# Save graph as PNG, plot data as csv, and all question data including response IDs as csv (save question n and N at end of plot file as "_x.x")
ggsave(filename = 'q104_share_results.png', plot = r, device = 'png')

write.csv(q104_plot, 'q104_share_results_201.csv', row.names = FALSE)

write.csv(q104_all, 'q104_share_results_ids.csv', row.names = FALSE)
```

