---
title: "q46 'Please rate the severity of the side effects you have faced with prescription medications compared to cannabis treatments:' (Veterans)"
author: "David Ritter"
date: "November 19, 2019"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
# Load libraries
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
# Read in raw data from the Veterans surveys. These are the files downloaded from survey monkey saved as a .csv
raw_data_general <- read.csv("data/general.csv", stringsAsFactors = FALSE)
raw_data_botanist <- read.csv("data/botanist.csv", stringsAsFactors = FALSE)
raw_data_bask <- read.csv("data/bask.csv", stringsAsFactors = FALSE)
raw_data_hr <- read.csv("data/hr.csv", stringsAsFactors = FALSE)
```

```{r}
# Pull out all responses for q46 (a single selection question) combine, then determine 'question n'
q46 <- "Please.rate.the.severity.of.the.side.effects.you.have.faced.with.prescription.medications.compared.to.cannabis.treatments."

q46_general <- get_single_selection(data = raw_data_general, q.name = q46)
q46_bask <- get_single_selection(data = raw_data_bask, q.name = q46)
q46_botanist <- get_single_selection(data = raw_data_botanist, q.name = q46)
q46_hr <- get_single_selection(data = raw_data_hr, q.name = q46)

q46_all <- rbind(q46_general, q46_bask, q46_botanist, q46_hr)

q46_n <- length(unique(q46_all$id))
```

```{r}
# Manipulate data into a graphable format
q46_plot <- 
  q46_all %>%
  group_by(response) %>%
  summarize(count = n()) %>%
  mutate(percent_all = count / sum(count)) %>%
  mutate(percent_responded = count / q46_n)
```

```{r}
# Plot with percents and response counts
r <- 
  ggplot(q46_plot, aes(x = reorder(response, count), y = percent_responded)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  geom_text(aes(label= paste(round(percent_responded, 2), count, sep = "***")))

r
```

```{r}
# Save graph as PNG, plot data as csv, and all question data including response IDs as csv (save question n and N at end of plot file as "_x.x")
ggsave(filename = 'q46_side_effects_cannabis_vs_med.png', plot = r, device = 'png')

write.csv(q46_plot, 'q46_side_effects_cannabis_vs_med_150.csv', row.names = FALSE)

write.csv(q46_all, 'q46_side_effects_cannabis_vs_med.csv', row.names = FALSE)
```
