---
title: "q43 'How do you feel cannabis has helped your daily life?' (Veterans)"
author: "David Ritter"
date: "November 19, 2019"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
# Load libraries
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
# Read in raw data from the Veterans surveys. These are the files downloaded from survey monkey saved as a .csv
raw_data_general <- read.csv("data/general.csv", stringsAsFactors = FALSE)
raw_data_botanist <- read.csv("data/botanist.csv", stringsAsFactors = FALSE)
raw_data_bask <- read.csv("data/bask.csv", stringsAsFactors = FALSE)
raw_data_hr <- read.csv("data/hr.csv", stringsAsFactors = FALSE)
```

```{r}
# Pull out all responses for q43 (a single selection question) combine, then determine 'question n'
q43 <- "How.do.you.feel.cannabis.has.helped.your.daily.life.Thinking.about.how.you.feel.TODAY.compared.to.the.BEGINNING.of.your.use.of.cannabis.to.treat.your.primary.medical.condition..."

q44 <- "How.do.you.feel.cannabis.has.helped.your.daily.life.Thinking.about.how.you.feelÂ.TODAYÂ.compared.to.theÂ.BEGINNINGÂ.of.your.use.of.cannabis.to.treat.your.primary.medical.condition..."

q43_general <- get_single_selection(data = raw_data_general, q.name = q44)
q43_bask <- get_single_selection(data = raw_data_bask, q.name = q44)
q43_botanist <- get_single_selection(data = raw_data_botanist, q.name = q44)
q43_hr <- get_single_selection(data = raw_data_hr, q.name = q44)

q43_all <- rbind(q43_general, q43_bask, q43_botanist, q43_hr)

q43_n <- length(unique(q43_all$id))
```

```{r}
# Manipulate data into a graphable format
q43_plot <- 
  q43_all %>%
  group_by(response) %>%
  summarize(count = n()) %>%
  mutate(percent_all = count / sum(count)) %>%
  mutate(percent_responded = count / q43_n)
```

```{r}
# Plot with percents and response counts
r <- 
  ggplot(q43_plot, aes(x = reorder(response, count), y = percent_responded)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  geom_text(aes(label= paste(round(percent_responded, 2), count, sep = "***")))

r
```

```{r}
# Save graph as PNG, plot data as csv, and all question data including response IDs as csv (save question n and N at end of plot file as "_x.x")
ggsave(filename = 'q43_cannabis_daily_qol.png', plot = r, device = 'png')

write.csv(q43_plot, 'q43_cannabis_daily_qol_564.csv', row.names = FALSE)

write.csv(q43_all, 'q43_cannabis_daily_qol_ids.csv', row.names = FALSE)
```