---
title: "q33 'On average, how much do you pay (in US dollars) for your medications on a monthly basis out of pocket?' (Veterans)"
author: "David Ritter"
date: "November 19, 2019"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
# Load libraries
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper0.R")
```

```{r}
# Read in raw data from the Veterans surveys. These are the files downloaded from survey monkey saved as a .csv
raw_data_general <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
# Pull out all responses for q33 (a single selection question) combine, then determine 'question n'
q33 <- "On.average..how.much.do.you.pay..in.US.dollars..for.your.medications.on.a.monthly.basis.out.of.pocket."

q33_all <- get_single_selection(data = raw_data_general, q.name = q33)

q33_n <- length(unique(q33_all$id))
```

```{r}
histogram_object <- hist(as.numeric(all_data$response))
histogram_object$breaks = c(0, 200, 400, 600, 800, 1000, 1200, 1400)
histogram_object$counts
plot(histogram_object)
```

```{r}
# Save all question data including response IDs as csv (save question n and N at end of file as "_x.x")
write.csv(q33_all, 'q33_med_cost_monthly_144.csv', row.names = FALSE)

```
