---
title: "q70 'Where do you get your information to make informed decisions about cannabis products? (Please select all that apply)' (Veterans)"
author: "David Ritter"
date: "November 19, 2019"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
# Load libraries
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
# Read in raw data from the Veterans surveys. These are the files downloaded from survey monkey saved as a .csv
raw_data_general <- read.csv("data/general_nat.csv", stringsAsFactors = FALSE)
raw_data_botanist <- read.csv("data/botanist_nat.csv", stringsAsFactors = FALSE)
raw_data_bask <- read.csv("data/bask_nat.csv", stringsAsFactors = FALSE)
raw_data_hr <- read.csv("data/hr_nat.csv", stringsAsFactors = FALSE)
```

```{r}
# Pull out all responses for q70 (a choose all question), combine, turn into a tidy data format for further processing then determine 'question n'
q70 <- "Where.do.you.get.your.information.to.make.informed.decisions.about.cannabis.products...Please.select.all.that.apply."
q70_general_f <- "X.322"
q70_botanist_f <- "X.322"
q70_bask_f <- "X.322"
q70_hr_f <- "X.322"

q70_general <- get_choose_all(raw_data_general, q.name = q70, f.response = q70_general_f)
q70_bask <- get_choose_all(raw_data_bask, q.name = q70, f.response = q70_bask_f)
q70_botanist <- get_choose_all(raw_data_botanist, q.name = q70, f.response = q70_botanist_f)
q70_hr <- get_choose_all(raw_data_hr, q.name = q70, f.response = q70_hr_f)

q70_all <- rbind(q70_general, q70_bask, q70_botanist, q70_hr) %>%
  tidy_choose_all()

number_of_people <- length(unique(q70_all$id))
```

```{r}
# Manipulate data into a graphable format
q70_plot <-
  q70_all %>%
  group_by(chosen) %>%
  summarize(count = n()) %>%
  mutate(percent_all = count / sum(count)) %>%
  mutate(percent_responded = count / number_of_people)
```

```{r}
# Plot with percents and response counts
r <- 
  ggplot(q70_plot, aes(x = reorder(chosen, count), y = percent_responded)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  geom_text(aes(label= paste(round(percent_responded,2), count, sep = "***")))

r
```

```{r}
# Save graph as PNG, plot data as csv, and all question data including response IDs as csv (save question n and N at end of plot file as "_x.x")
ggsave(filename = 'q70_cannabis_info.png', plot = r, device = 'png')

write.csv(q70_plot, 'q70_cannabis_info_183.csv', row.names = FALSE)

write.csv(q70_all, 'q70_cannabis_info_ids.csv', row.names = FALSE)
```
