---
title: "q2 reasons"
author: "DJ"
date: "2/22/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
# Load libraries
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
# Read in raw data from the Veterans surveys. These are the files downloaded from survey monkey saved as a .csv
raw_data_bask <- read.csv("data/bask_only.csv", stringsAsFactors = FALSE)
```

```{r}
# Pull out all responses for q72 (a single selection question) combine, then determine 'question n'
q2 <- "What.were.the.reasons.you.selected.the.products.you.last.purchased...Please.select.all.that.apply."
q2_final_response <- "X.341"

q2_all <- get_choose_all(raw_data_bask, q.name = q2, f.response = q2_final_response) %>%
  tidy_choose_all()

q2_n <- length(unique(q2_all$id))
```

```{r}
# Manipulate data into a graphable format
q2_plot <-
  q2_all %>%
  group_by(chosen) %>%
  summarize(count = n()) %>%
  mutate(percent_all = count / sum(count)) %>%
  mutate(percent_responded = count / q2_n)
```

```{r}
# Plot with percents and response counts
r <- 
  ggplot(q2_plot, aes(x = reorder(chosen, count), y = percent_responded)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  geom_text(aes(label= paste(round(percent_responded,2), count, sep = "***")))
r
```


```{r}
# Save graph as PNG, plot data as csv, and all question data including response IDs as csv (save question n and N at end of plot file as "_x.x")
ggsave(filename = 'q2_reasons.png', plot = r, device = 'png')

write.csv(q2_plot, 'q2_reasons_32.csv', row.names = FALSE)

write.csv(q2_all, 'q2_reasons_ids.csv', row.names = FALSE)
```

