---
title: "Products for Symptoms (Botanist)"
author: "DJ"
date: "August 8, 2019"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
# Load libraries
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
# Read in raw data from the Veterans surveys. These are the files downloaded from survey monkey saved as a .csv
raw_data_botanist <- read.csv("data/bask_nat.csv", stringsAsFactors = FALSE)

```

```{r}
# Pull out all responses for Q5 (a choose all question), combine, turn into a tidy data format for further processing then determine 'question n'
Q5 <- "What.isÂ.the.average.daily.dose.for.you.to.see.a.benefit.for.your.recreation.or.health.condition.or.symptom...for.smokingÂ.please.note.how.many.puffs.per.day..edibles.and.tinctures..please.use.mg.per.day."
Q5_final_response <- "X.1385"

Q5_botanist <- get_choose_all(raw_data_botanist, q.name = Q5, f.response = Q5_final_response)

Q5_all <- 
  rbind(Q5_botanist) %>%
  tidy_choose_all()

number_of_people <- length(unique(Q5_botanist$id))
```

```{r}
# Manipulate data into a graphable format
Q5_plot <-
  Q5_all %>%
  group_by(chosen) %>%
  summarize(count = n()) %>%
  mutate(percent_all = count / sum(count)) %>%
  mutate(percent_responded = count / number_of_people)
```

```{r}
# Plot with percents and response counts
r <- 
  ggplot(Q5_plot, aes(x = reorder(chosen, count), y = percent_responded)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  geom_text(aes(label= paste(round(percent_responded,2), count, sep = "***")))

r
```

```{r}
# Save graph as PNG, plot data as csv, and all question data including response IDs as csv (save question n and N at end of plot file as "_x.x")
ggsave(filename = 'baskt_test_reasons_purchased.png', plot = r, device = 'png')

write.csv(Q5_botanist, 'bask_test_reasons_purchased_20.csv', row.names = FALSE)

write.csv(Q5_all, 'bask_test_reasons_purchased_ids.csv', row.names = FALSE)
```
