---
title: "Q10 'Are you actively trying to reduce your prescription medication intake using cannabis? Please select all that apply.' (OCCP)"
author: "David Ritter"
date: "November 19, 2019"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
# Load libraries
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
# Read in raw data from the OCCP survey. These are the files downloaded from survey monkey saved as a .csv
raw_data_occp <- read.csv("data/occp.csv", stringsAsFactors = FALSE)
```

```{r}
# Pull out all responses for Q10 (a choose all question), combine, turn into a tidy data format for further processing then determine 'question n'
Q10 <- 'Are.you.actively.trying.to.reduce.your.prescription.medication.intake.using.cannabis..Please.select.all.that.apply.'
Q10_final_response <- "X.66"

Q10_all <- get_choose_all(raw_data_occp, q.name = Q10, f.response = Q10_final_response)
Q10_clean <- tidy_choose_all(Q10_all)

Q10_responses <- length(unique(Q10_all$id))
```

```{r}
# Filter those not reducing prescriptions with cannabis
Q10_reduced <- Q10_clean %>% 
  filter(response %in% c("Not actively trying to reduce medication intake"))
Q10_reduced_responses <- length(unique(Q10_reduced$id))
```

```{r}
# Manipulate data into a graphable format
Q10_plot <-
  Q10_clean %>%
  group_by(chosen) %>%
  summarize(count = n()) %>%
  mutate(percent_all = count / sum(count)) %>%
  mutate(percent_responded = count / Q10_responses)
```

```{r}
# Plot with percents and response counts
r <- 
  ggplot(Q10_plot, aes(x = reorder(chosen, count), y = percent_responded)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  geom_text(aes(label= paste(round(percent_responded,2), count, sep = "***")))

r
```

```{r}
# Save graph as PNG, plot data as csv, and all question data including response IDs as csv (save question n and N at end of plot file as "_x.x")
ggsave(filename = 'q10_prescriptions_reduced_cannabis.png', plot = r, device = 'png')

write.csv(Q10_plot, 'q10_prescriptions_reduced_cannabis_1288.csv', row.names = FALSE)

write.csv(Q10_clean, 'q10_prescriptions_reduced_cannabis_ids.csv', row.names = FALSE)
```