---
title: "q11 'What is your highest level of pain (what is the highest level of pain you feel?)'"
author: "David Ritter"
date: "2/25/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q11 <- "What.is.yourÂ.highest.level.of.pain..what.is.the.highest.level.of.pain.you.feel.."
q11_t <- "What is your highest level of pain (what is the highest level of pain you feel?)"
q11_data <- get_single_selection_0(data = raw_data, q.name = q11) %>%
  filter(response != "")
q11_n <- length(unique(q11_data$id))
q11_mean_data <- as.numeric(as.character(q11_data$response))
q11_mean <- mean(q11_mean_data) %>%
  round(2) %>%
  print()
q11_plot<- clean_single_select(q11_data)
r11 <- plot_single_select_0(q11_plot, q11_t, q11_n, q11_mean)
r11
```

```{r}
row3 <- colnames(q11_plot)
q11_plot2 <- rbind(row3, q11_plot)
names(q11_plot2) <- c("q11", q11_t, paste("n = ", q11_n, paste(" avg = ", q11_mean)))
```

```{r}
dir.create("output/q11_highest_pain")
ggsave(filename = 'output/q11_highest_pain/q11_highest_pain.png', plot = r11, device = 'png')
write.csv(q11_plot2, paste0("output/q11_highest_pain/q11_highest_pain_", q11_n,".csv"), row.names=F)
write.csv(q11_data, 'output/q11_highest_pain/q11_highest_pain_ids.csv', row.names = FALSE)
```