---
title: "q12 'If you had to live with some pain, what level of pain would be acceptable?'"
author: "David Ritter"
date: "2/28/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q12 <- "If.you.had.to.live.with.some.pain..what.level.of.pain.would.be.acceptable."
q12_t <- "If you had to live with some pain, what level of pain would be acceptable?"
q12_data <- get_single_selection_0(data = raw_data, q.name = q12) %>%
  filter(response != "")
q12_n <- length(unique(q12_data$id))
q12_mean_data <- as.numeric(as.character(q12_data$response))
q12_mean <- mean(q12_mean_data) %>%
  round(3) %>%
  print()
q12_plot<- clean_single_select(q12_data)
r12 <- plot_single_select_0(q12_plot, q12_t, q12_n, q12_mean)
r12
```

```{r}
row3 <- colnames(q12_plot)
q12_plot2 <- rbind(row3, q12_plot)
names(q12_plot2) <- c("q12", q12_t, paste("n = ", q12_n, paste(" avg = ", q12_mean)))
```

```{r}
dir.create("output/q12_acceptable_pain")
ggsave(filename = 'output/q12_acceptable_pain/q12_acceptable_pain.png', plot = r12, device = 'png')
write.csv(q12_plot2, paste0("output/q12_acceptable_pain/q12_acceptable_pain_", q12_n,".csv"), row.names=F)
write.csv(q12_data, 'output/q12_acceptable_pain/q12_acceptable_pain_ids.csv', row.names = FALSE)
```
