---
title: "q32 'Where/how do you get your medications?'"
author: "David Ritter"
date: "2/28/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q32 <- "Where.how.do.you.get.your.medications."
q32_t <- "Where/how do you get your medications?"
q32_data <- get_single_selection(data = raw_data, q.name = q32)
q32_n <- length(unique(q32_data$id))
q32_plot<- clean_single_select(q32_data)
r32 <- plot_single_select(q32_plot, q32_t, q32_n)
r32
```

```{r}
row3 <- colnames(q32_plot)
q32_plot2 <- rbind(row3, q32_plot)
names(q32_plot2) <- c("q32", q32_t, paste("n = ", q32_n))
```

```{r}
dir.create("output/q32_medication_sourcing")
ggsave(filename = 'output/q32_medication_sourcing/q32_medication_sourcing.png', plot = r32, device = 'png')
write.csv(q32_plot2, paste0("output/q32_medication_sourcing/q32_medication_sourcing_", q32_n,".csv"), row.names=F)
```







```{r}
qf_data <- q_data %>%
  filter(response == "Response text")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")
qf_n <- length(unique(qf_all_data$id))
q_plot <- clean_single_select_y(qf_all_data)
r <- plot_single_select_y(q_plot)
r
```

```{r}
q_plot2 <- rbind(q_plot, t)
dir.create("output/q32_medication_sourcing")
ggsave(filename = 'output/q32_medication_sourcing/q32_medication_sourcing.png', plot = r, device = 'png')
write.csv(q_plot2, paste0("output/q32_medication_sourcing/q32_medication_sourcing_", qf_n,".csv"), row.names=F)
```