---
title: "q34 'Do you seek supportive mental health services, counseling, or other therapy within or outside of the VA?'"
author: "David Ritter"
date: "2/28/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q34 <- "Do.you.seek.supportive.mental.health.services..counseling..or.other.therapy.within.or.outside.of.the.VA."
q34_t <- "Do you seek supportive mental health services, counseling, or other therapy within or outside of the VA?"
q34_data <- get_single_selection(data = raw_data, q.name = q34)
q34_n <- length(unique(q34_data$id))
q34_plot<- clean_single_select(q34_data)
r34 <- plot_single_select(q34_plot, q34_t, q34_n)
r34
```

```{r}
row3 <- colnames(q34_plot)
q34_plot2 <- rbind(row3, q34_plot)
names(q34_plot2) <- c("q34", q34_t, paste("n = ", q34_n))
```

```{r}
dir.create("output/q34_mental_health_services")
ggsave(filename = 'output/q34_mental_health_services/q34_mental_health_services.png', plot = r34, device = 'png')
write.csv(q34_plot2, paste0("output/q34_mental_health_services/q34_mental_health_services_", q34_n,".csv"), row.names=F)
```







```{r}
qf_data <- q_data %>%
  filter(response == "Response text")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")
qf_n <- length(unique(qf_all_data$id))
q_plot <- clean_single_select_y(qf_all_data)
r <- plot_single_select_y(q_plot)
r
```

```{r}
q_plot2 <- rbind(q_plot, t)
dir.create("output/q34_mental_health_services")
ggsave(filename = 'output/q34_mental_health_services/q34_mental_health_services.png', plot = r, device = 'png')
write.csv(q_plot2, paste0("output/q34_mental_health_services/q34_mental_health_services_", qf_n,".csv"), row.names=F)
```
