---
title: "q61 'Do you face any of the following barriers for you to consume cannabis (Please select all that apply)'"
author: "David Ritter"
date: "2/28/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q61 <- 'Do.you.face.any.of.the.following.barriers.for.you.to.consume.cannabis...Please.select.all.that.apply.'
q61_final_response <- "X.279"
q61_t <- "Do you face any of the following barriers for you to consume cannabis (Please select all that apply)"
q61_data <- get_choose_all(raw_data, q.name = q61, f.response = q61_final_response) %>%
  tidy_choose_all()
q61_n <- length(unique(q61_data$id))
q61_plot <- clean_choose_all(q61_data, q61_n)
r61 <- plot_choose_all(q61_plot, q61_t, q61_n)
r61
```

```{r}
row3 <- colnames(q61_plot)
q61_plot2 <- rbind(row3, q61_plot)
names(q61_plot2) <- c("q61", q61_t, paste("n = ", q61_n))
```

```{r}
dir.create("output/q61_barriers")
ggsave(filename = 'output/q61_barriers/q61_barriers.png', plot = r61, device = 'png')
write.csv(q61_plot2, paste0("output/q61_barriers/q61_barriers_", q61_n,".csv"), row.names=F)
write.csv(q61_data, 'output/q61_barriers/q61_barriers_ids.csv', row.names = FALSE)
```




```{r}
qf_data <- q_data %>%
  filter(chosen == "Money to purchase products")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")
qf_n <- length(unique(qf_all_data$id))
qf_data <- qf_all_data[3] %>%
  group_by(chosen) %>%
  summarize(count=n()) %>%
  mutate(percent_responded = round(100*(count / qf_n), 2)) %>%
  arrange(desc(count))
```

```{r}
q61_plot <- clean_choose_all_f2(qf_data)
r <- plot_choose_all_f2(q61_plot)
r
```

```{r}
q61_plot2 <- rbind(q61_plot, t)
dir.create("output/q61_barriers")
ggsave(filename = 'output/q61_barriers/q61_barriers.png', plot = r, device = 'png')
write.csv(q61_plot2, paste0("output/q61_barriers/q61_barriers_", qf_n,".csv"), row.names=F)
write.csv(qf_all_data, 'output/q61_barriers/q61_barriers_ids.csv', row.names = FALSE)
```
