---
title: "q7 'Which of the following symptoms are most commonly associated with your primary health condition or underlying health conditions? (Please select all that apply)'"
author: "David Ritter"
date: "2/28/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q7 <- 'Which.of.the.following.symptoms.are.most.commonly.associated.with.your.primary.health.condition.or.underlying.health.conditions...Please.select.all.that.apply.'
q7_final_response <- "X.43"
q7_t <- "Which of the following symptoms are most commonly associated with your primary health condition or underlying health conditions? (Please select all that apply)"
q7_data <- get_choose_all(raw_data, q.name = q7, f.response = q7_final_response) %>%
  tidy_choose_all()
q7_n <- length(unique(q7_data$id))
q7_plot <- clean_choose_all(q7_data, q7_n)
r7 <- plot_choose_all(q7_plot, q7_t, q7_n)
r7
```

```{r}
row3 <- colnames(q7_plot)
q7_plot2 <- rbind(row3, q7_plot)
names(q7_plot2) <- c("q7", q7_t, paste("n = ", q7_n))
```

```{r}
dir.create("output/q7_symptoms")
ggsave(filename = 'output/q7_symptoms/q7_symptoms.png', plot = r7, device = 'png')
write.csv(q7_plot2, paste0("output/q7_symptoms/q7_symptoms_", q7_n,".csv"), row.names=F)
write.csv(q7_data, 'output/q7_symptoms/q7_symptoms_ids.csv', row.names = FALSE)
```






```{r}
qf_data <- q_data %>%
  filter(chosen == "Response text")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")
qf_n <- length(unique(qf_all_data$id))
qf_data <- qf_all_data[3] %>%
  group_by(chosen) %>%
  summarize(count=n()) %>%
  mutate(percent_responded = round(100*(count / qf_n), 2)) %>%
  arrange(desc(count))
q_plot <- clean_choose_all_f2(qf_data)
r <- plot_choose_all_f2(q_plot)
r
```

```{r}
q_plot2 <- rbind(q_plot, t)
dir.create("output/q7_symptoms")
ggsave(filename = 'output/q7_symptoms/q7_symptoms.png', plot = r, device = 'png')
write.csv(q_plot2, paste0("output/q7_symptoms/q7_symptoms_", qf_n,".csv"), row.names=F)
write.csv(qf_all_data, 'output/q7_symptoms/q7_symptoms_ids.csv', row.names = FALSE)
```

