---
title: "q92 'What is your marital status?'"
author: "David Ritter"
date: "2/28/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q92 <- "What.is.your.marital.status."
q92_t <- "What is your marital status?"
q92_data <- get_single_selection(data = raw_data, q.name = q92)
q92_n <- length(unique(q92_data$id))
q92_plot<- clean_single_select(q92_data)
r92 <- plot_single_select(q92_plot, q92_t, q92_n)
r92
```

```{r}
row3 <- colnames(q92_plot)
q92_plot2 <- rbind(row3, q92_plot)
names(q92_plot2) <- c("q92", q92_t, paste("n = ", q92_n))
```

```{r}
dir.create("output/q92_marital_status")
ggsave(filename = 'output/q92_marital_status/q92_marital_status.png', plot = r92, device = 'png')
write.csv(q92_plot2, paste0("output/q92_marital_status/q92_marital_status_", q92_n,".csv"), row.names=F)
```







```{r}
qf_data <- q_data %>%
  filter(response == "Response text")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")
qf_n <- length(unique(qf_all_data$id))
q_plot <- clean_single_select_y(qf_all_data)
r <- plot_single_select_y(q_plot)
r
```

```{r}
q_plot2 <- rbind(q_plot, t)
dir.create("output/q92_marital_status")
ggsave(filename = 'output/q92_marital_status/q92_marital_status.png', plot = r, device = 'png')
write.csv(q_plot2, paste0("output/q92_marital_status/q92_marital_status_", qf_n,".csv"), row.names=F)
```