---
title: "q94 'Have you ever been homeless?'"
author: "David Ritter"
date: "2/28/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q94 <- "Have.you.ever.been.homeless."
q94_t <- "Have you ever been homeless?"
q94_data <- get_single_selection(data = raw_data, q.name = q94)
q94_n <- length(unique(q94_data$id))
q94_plot<- clean_single_select(q94_data)
r94 <- plot_single_select(q94_plot, q94_t, q94_n)
r94
```

```{r}
row3 <- colnames(q94_plot)
q94_plot2 <- rbind(row3, q94_plot)
names(q94_plot2) <- c("q94", q94_t, paste("n = ", q94_n))
```

```{r}
dir.create("output/q94_homeless")
ggsave(filename = 'output/q94_homeless/q94_homeless.png', plot = r94, device = 'png')
write.csv(q94_plot2, paste0("output/q94_homeless/q94_homeless_", q94_n,".csv"), row.names=F)
```







```{r}
qf_data <- q_data %>%
  filter(response == "Response text")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")
qf_n <- length(unique(qf_all_data$id))
q_plot <- clean_single_select_y(qf_all_data)
r <- plot_single_select_y(q_plot)
r
```

```{r}
q_plot2 <- rbind(q_plot, t)
dir.create("output/q94_homeless")
ggsave(filename = 'output/q94_homeless/q94_homeless.png', plot = r, device = 'png')
write.csv(q_plot2, paste0("output/q94_homeless/q94_homeless_", qf_n,".csv"), row.names=F)
```