---
title: "q97 'Do you consider yourself to be any of the following?'"
author: "David Ritter"
date: "2/28/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
```

```{r}
q97 <- 'Do.you.consider.yourself.to.be.any.of.the.following.'
q97_t <- "Do you consider yourself to be any of the following?"
q97_data <- get_single_selection(data = raw_data, q.name = q97)
q97_n <- length(unique(q97_data$id))
q97_plot<- clean_single_select(q97_data)
r97 <- plot_single_select(q97_plot, q97_t, q97_n)
r97
```

```{r}
row3 <- colnames(q97_plot)
q97_plot2 <- rbind(row3, q97_plot)
names(q97_plot2) <- c("q97", q97_t, paste("n = ", q97_n))
```

```{r}
dir.create("output/q97_sexuality")
ggsave(filename = 'output/q97_sexuality/q97_sexuality.png', plot = r97, device = 'png')
write.csv(q97_plot2, paste0("output/q97_sexuality/q97_sexuality_", q97_n,".csv"), row.names=F)
```






```{r}
qf_data <- q_data %>%
  filter(response == "Response text")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")
qf_n <- length(unique(qf_all_data$id))
q_plot <- clean_single_select_y(qf_all_data)
r <- plot_single_select_y(q_plot)
r
```

```{r}
q_plot2 <- rbind(q_plot, t)
dir.create("output/q97_sexuality")
ggsave(filename = 'output/q97_sexuality/q97_sexuality.png', plot = r, device = 'png')
write.csv(q_plot2, paste0("output/q97_sexuality/q97_sexuality_", qf_n,".csv"), row.names=F)
```