---
title: "Code Chucks"
author: "DJ"
date: "2/18/2020"
output: html_document
---
# Clean and plot single select data
```{r}
q_plot<- clean_single_select(q_data)
r <- plot_single_select(q_plot)
r
```

# Filtering section for single select

```{r}
qf_data <- q_data %>%
  filter(response == "Response text")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")

qf_n <- length(unique(qf_all_data$id))
```

```{r}
q_plot <- clean_single_select_f(qf_all_data)
r <- plot_single_select_f(q_plot)
r
```

```{r}
ggsave(filename = 'q#_file_name.png', plot = r, device = 'png')
write.csv(q_plot, 'q#_file_name_n#.csv', row.names = FALSE)
```

# Clean and plot choose all questions.

```{r}
q_plot <- clean_choose_all(q_data)
r <- plot_choose_all(q_plot)
r
```


# Filtering section for choose all questions

```{r}
qf_data <- q_data %>%
  filter(chosen == "Response text")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")

qf_n <- length(unique(qf_all_data$id))
```

```{r}
q_plot <- clean_choose_all_f(qf_all_data)
r <- plot_choose_all_f(q_plot)
r
```

```{r}
ggsave(filename = 'q#_file_name.png', plot = r, device = 'png')
write.csv(q_plot, 'q#_file_name_n#.csv', row.names = FALSE)
write.csv(qf_data, 'q#_file_name_ids.csv', row.names = FALSE)
```

