---
title: "q4 'How would you rate your quality of health today?'"
author: "David Ritter"
date: "2/20/2020"
output: html_document
runtime: shiny
---

```{r, message = FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
source("helper.R")
```

```{r}
raw_data <- read.csv("data/master.csv", stringsAsFactors = FALSE)
 
q <- "How.would.you.rate.your.quality.of.health.today."
q2 <-'Which.of.the.following.health.conditions.do.you.face.and.or.have.been.diagnosed.with...Please.select.all.that.apply.'
  
less_raw_data <- 
    raw_data %>%
    select(response1 = q, response2 = q2) %>%
    slice(2:nrow(.)) %>%
    filter(response2 > 0)

filtered_data <-
  less_raw_data %>%
  filter(response1 == "Fair")
  






#q_data <- %>%
  #as.data.frame() %>%
  #filter(raw_data$How.would.you.rate.your.quality.of.health.today., response == "Fair") %>%
  
```

```{r}
q <- "How.would.you.rate.your.quality.of.health.today."
t <- "How would you rate your quality of health today?"
q_data <- get_single_selection(data = raw_data, q.name = q)
q_n <- length(unique(q_data$id))
q_plot<- clean_single_select(less_raw_data)
r <- plot_single_select(q_plot)
r
```

```{r}
ggsave(filename = 'output/q4_health_quality.png', plot = r, device = 'png')
write.csv(q_plot, 'output/q4_health_quality_144.csv', row.names = FALSE)
```

```{r}
qf_data <- q_data %>%
  filter(response == "Fair")
```

```{r}
qf_all_data <- 
  qf_data %>%
  inner_join(q_data, by = "id")
qf_n <- length(unique(qf_all_data$id))
q_plot <- clean_single_select_y(qf_all_data)
r <- plot_single_select_y(q_plot)
r
```

```{r}
ggsave(filename = 'output/q4_health_quality.png', plot = r, device = 'png')
write.csv(q_plot, 'output/q4_health_quality_232.csv', row.names = FALSE)
```
